### ISSUE TITLE
All local databases that are auto-downloaded should have version checking

### ISSUE THREAD

**Issue by dkoslicki** [RTXteam/RTX#1001]
Eg. for local COHD instance, there should be a mechanism that checks if the local SQlite database is the same as the one on the production server.

**Comment by chunyuma** [comment]
The local COHD database was updated and the `COHDIndex` script should be able to check if its local database on PC is the same as the one on the `arax.rtx.ai` server. If not, it will automatically delete the old one and download the new one.

**Comment by dkoslicki** [comment]
Fantastic! Thanks for the quick fix @chunyuma! As a friendly reminder, please remember to reference relevant issue numbers in commits (so the changes/commits are tied to the issues)

**Comment by amykglen** [comment]
question about how your versioning method works, @chunyuma: do you have to update the code every time a new version of the database is released? I noticed you seem to have hardcoded `latest_version` and `old_version_database` variables:
https://github.com/RTXteam/RTX/blob/8dfa8a79cbe2d270a022054f0d810400510b81dc/code/ARAX/KnowledgeSources/COHD_local/scripts/COHDIndex.py#L31
https://github.com/RTXteam/RTX/blob/8dfa8a79cbe2d270a022054f0d810400510b81dc/code/ARAX/KnowledgeSources/COHD_local/scripts/COHDIndex.py#L60

**Comment by chunyuma** [comment]
@amykglen, yes, you're right. This is actually not a smart method. Do you have a better idea to do this?

**Comment by amykglen** [comment]
hmm... instead of using version numbers, I wonder if it would be possible to somehow just check the timestamp of the remote file, and download it only if it's more recent than the timestamp on the local file?

**Comment by amykglen** [comment]
I think Eric and/or David also had the idea to add a table to each database that contains the version number. but I'm not sure how we could check that version number remotely without actually downloading the database first(?)

**Comment by chunyuma** [comment]
> hmm... instead of using version numbers, I wonder if it would be possible to somehow just check the timestamp of the remote file, and download it only if it's more recent than the timestamp on the local file?

I actually thought of this method which tries to check the timestamp. But it seems not reasonable that we re-download the same file just because its local timestamp is far different from that of the remote file. For COHD database, I might need to modify `COHDIndex.py` a little bit each time when I need to create a new version of the database since some datasets required to construct the database are stored locally. So I think it is not a nuisance to change the version number as well.

> I think Eric and/or David also had the idea to add a table to each database that contains the version number. but I'm not sure how we could check that version number remotely without actually downloading the database first(?)

For this idea, if we do this, we might create a new database which only stores the version number of other databases (e.g. `COHD`, `fastNGD` and etc.). This database can be stored somewhere on certain server and be checked each time if we need to use other databases. But this seems also not a smarter method than directly hardcoding the original script like I did for `COHD`. Actually I have no idea how to automatically update the version number without modifying any scripts.

**Comment by chunyuma** [comment]
@amykglen, it is actually easy to compare the timestamp of a local file and a remote file by using some python commands like
`os.system('ssh ubuntu@arax.rtx.ai "stat -c %Y ~/COHDdata/COHDdatabase_v1.0.db"')` which can return the last modification time of a remote file.

**Comment by amykglen** [comment]
nice, thanks! I think that will work just fine at least for the fastNGD database, since I don't ever need to modify the remote copy until I'm replacing it with a new version.

**Comment by amykglen** [comment]
ok, I went with the timestamp method for ngd - I used the command you posted, @chunyuma. (thanks!) code is [here](https://github.com/RTXteam/RTX/blob/25bb43ec7889be893561bfd0973f3013797ee311/code/ARAX/ARAXQuery/Overlay/compute_ngd.py#L183-L199), if you're curious.

tested and pushed to `master`.

**Comment by chunyuma** [comment]
I think we should be able to close this issue.
