### ISSUE TITLE
KG2.2.0 provided_by a list, but not really?

### ISSUE THREAD

**Issue by dkoslicki** [RTXteam/RTX#1005]
Note this edge on http://kg2endpoint.rtx.ai:7474/browser/:
```
<id>:11720285
edge_label:subclass_of
negated:False
object:DOID:682
provided_by:OBO:doid.owl,DOID:doid.owl   #<----
publications:[]
publications_info:{}
relation:http://www.w3.org/2000/01/rdf-schema#subClassOfrelation_curie:rdfs:subClassOf
simplified_edge_label:subclass_of
simplified_relation:https://w3id.org/biolink/vocab/subclass_of
simplified_relation_curie:biolink:subclass_of
subject:DOID:3933
update_date:2020-07-21 21:04:17 GMT
```
And note that `provided_by` seems to be a list-like entity, but appears to be more of a string with comma delimiters. Is this intended?

**Comment by amykglen** [comment]
I've noticed this too, but I think it may just be a display issue in the neo4j browser, because the JSON view shows a normal looking list:

<img width="410" alt="Screen Shot 2020-08-07 at 7 39 17 PM" src="https://user-images.githubusercontent.com/49423686/89700765-b55b6e80-d8e5-11ea-83e5-e2db800402a0.png">

**Comment by dkoslicki** [comment]
Oh nice! Thanks for the quick response @amykglen! Guess it's a non-issue, so closing

**Comment by saramsey** [comment]
Thanks @amykglen
