### ISSUE TITLE
merge_graphs.py doesn't work if the "optional" argument kgFileOrphanEdges is omitted

### ISSUE THREAD

**Issue by saramsey** [RTXteam/RTX#1026]
```
(kg2-venv) ubuntu@ip-172-31-0-169:~/kg2-build$ python ~/kg2-code/merge_graphs.py --kgFiles kg2-chembl-SAVE.json, test.json
usage: merge_graphs.py [-h] [--test] [--kgFiles KGFILES [KGFILES ...]]
                       [--kgFileOrphanEdges [KGFILEORPHANEDGES]]
                       outputFile
merge_graphs.py: error: the following arguments are required: outputFile
```

**Comment by kvarforl** [comment]
I actually think this is just an ordering issue, if I understand correctly.
`python kg2-code/merge_graphs.py test_output.json --kgFiles kg2-chembl-SAVE.json`
works just fine.
 
I always assumed conventionally that positional arguments should precede optional arguments, but I'm not sure how official that is.  
Anyway, the command in the comment above doesn't work because --kgFiles consumes a variable number of arguments, so the parser doesn't know how to distinguish test.json as the output file without the implicit stop of the second optional argument --kgFileOrphanEdges.

@saramsey I can open a new issue for updating the ordering of arguments in the build scripts to follow my possibly made up convention, or we can just leave it be. either way, I think this issue could probably be closed. What are your thoughts?

**Comment by saramsey** [comment]
Fixed. I made the output file an "option" `--outputFile` and I made the input files a positional argument.
