### ISSUE TITLE
Erythropoietin nodes in KG2 with strange category_labels ('disease', 'phenotypic_feature'..)

### ISSUE THREAD

**Issue by amykglen** [RTXteam/RTX#1045]
discovered this issue in #1044 

out of the many nodes for erythropoietin in kg2-3-1:
```
match (n) where toLower(n.name)="erythropoietin" return n.id, n.name, n.category_label, n.provided_by order by n.category_label
```

n.id | n.name | n.category_label | n.provided_by
-- | -- | -- | --
"CHEBI:81579" | "Erythropoietin" | "chemical_substance" | "OBO:chebi.owl"
"EFO:0003233" | "erythropoietin" | "chemical_substance" | "EFO:efo.owl"
"GTPI:4921" | "ERYTHROPOIETIN" | "chemical_substance" | "GTPI_source"
"UMLS:C4693552" | "Erythropoietin" | "disease" | "identifiers_org_registry:umls"
"DRUGBANK:DB00016" | "Erythropoietin" | "drug" | "umls_source:DRUGBANK"
"SNOMED:83042003" | "Erythropoietin" | "drug" | "umls_source:SNOMEDCT"
"HGNC:3415" | "erythropoietin" | "gene" | "umls_source:HGNC"
"ORPHANET:470286" | "erythropoietin" | "gene" | "ORPHANET:"
"NCBIGene:2056" | "erythropoietin" | "gene" | "identifiers_org_registry:ncbigene"
"UMLS:C1366564" | "Erythropoietin" | "genomic_entity" | "identifiers_org_registry:umls"
"KEGG:C18200" | "Erythropoietin" | "metabolite" | "identifiers_org_registry:kegg.compound"
"PathWhiz.ProteinComplex:7956" | "Erythropoietin" | "molecular_entity" | "PathWhiz:"
"PathWhiz.ProteinComplex:12664" | "Erythropoietin" | "molecular_entity" | "PathWhiz:"
"PathWhiz.ProteinComplex:12228" | "Erythropoietin" | "molecular_entity" | "PathWhiz:"
"PathWhiz.ProteinComplex:12446" | "Erythropoietin" | "molecular_entity" | "PathWhiz:"
"UMLS:C0014822" | "Erythropoietin" | "named_thing" | "identifiers_org_registry:umls"
"ATC:B03XA01" | "erythropoietin" | "named_thing" | "umls_source:ATC"
"UMLS:C4256163" | "Erythropoietin" | "named_thing" | "identifiers_org_registry:umls"
"UMLS:C4256161" | "Erythropoietin" | "named_thing" | "identifiers_org_registry:umls"
"UMLS:C4256162" | "Erythropoietin" | "named_thing" | "identifiers_org_registry:umls"
"MESH:D004921" | "Erythropoietin" | "named_thing" | "umls_source:MSH"
"UMLS:C2976467" | "Erythropoietin" | "named_thing" | "identifiers_org_registry:umls"
"UMLS:C4693956" | "Erythropoietin" | "named_thing" | "identifiers_org_registry:umls"
"OMIM:133170" | "Erythropoietin" | "phenotypic_feature" | "umls_source:OMIM"
"CPT:82668" | "Erythropoietin" | "procedure" | "umls_source:CPT"
"LOINC:MTHU004935" | "Erythropoietin" | "procedure" | "umls_source:LNC"
"LOINC:LP15554-6" | "Erythropoietin" | "procedure" | "umls_source:LNC"
"NCIT:C20429" | "Erythropoietin" | "protein" | "umls_source:NCI"
"PR:000007141" | "erythropoietin" | "protein" | "OBO:go/extensions/go-plus.owl"
"CHEMBL.TARGET:CHEMBL5837" | "Erythropoietin" | "protein" | "identifiers_org_registry:chembl"

there are a few that have perplexing `category_label`s:

n.id | n.name | n.category_label | n.provided_by
-- | -- | -- | --
"UMLS:C4693552" | "Erythropoietin" | "disease" | "identifiers_org_registry:umls"
"OMIM:133170" | "Erythropoietin" | "phenotypic_feature" | "umls_source:OMIM"
"CPT:82668" | "Erythropoietin" | "procedure" | "umls_source:CPT"
"LOINC:MTHU004935" | "Erythropoietin" | "procedure" | "umls_source:LNC"
"LOINC:LP15554-6" | "Erythropoietin" | "procedure" | "umls_source:LNC"

not sure if those are actually what are reported in the upstream knowledge sources, or if they might be due to an error/oversight during ingestion?

looking at the upstream source data a bit:

* LOINC:MTHU004935: http://purl.bioontology.org/ontology/LNC/MTHU004935 - I'm seeing TUI types of T125 (chemical substance), T116 (protein), and T121 (chemical substance)
* same for LOINC:LP15554-6 http://purl.bioontology.org/ontology/LNC/LP15554-6 (T125, T116, T121)

**Comment by saramsey** [comment]
OK, so I'm pretty sure this (1) a bug and (2) this is coming from the `T047` UMLS semantic type ("disease") annotation for `OMIM:133170` in `umls-omim.ttl`. I also think this bug is related to #762, for which @ericawood has committed a fix (2bd4cc8 and a45d231). We will carefully check build `KG2.3.2` to see if those two commits fix this issue.

**Comment by ericawood** [comment]
In `KG2.3.4`, the entry for UMLS:C4693552 is below: (table of `UMLS` prefixed nodes below as those were largely the ones that #762 addressed)

While some are now better than `named_thing`, `UMLS:C4693552` still has the strange `disease` label.

n.id | n.name | n.category_label | n.provided_by
-- | -- | -- | --
"UMLS:C4693956" | "Erythropoietin" | "biological_entity" | "identifiers_org_registry:umls"
"UMLS:C4693552" | "Erythropoietin" | "disease" | "identifiers_org_registry:umls"
"UMLS:C1366564" | "Erythropoietin" | "genomic_entity" | "identifiers_org_registry:umls"
"UMLS:C0014822" | "Erythropoietin" | "molecular_entity" | "identifiers_org_registry:umls"
"UMLS:C4256163" | "Erythropoietin" | "molecular_entity" | "identifiers_org_registry:umls"
"UMLS:C4256161" | "Erythropoietin" | "molecular_entity" | "identifiers_org_registry:umls"
"UMLS:C4256162" | "Erythropoietin" | "molecular_entity" | "identifiers_org_registry:umls"
"UMLS:C2976467" | "Erythropoietin" | "molecular_entity" | "identifiers_org_registry:umls"

Unless `OMIM:133170` has multiple TUIs and no category label, it will not be fixed by #762. The other strange ones listed in your table above @amykglen were also not fixed. We may want to reconsider when the TUI derived category is given to a node so that it occurs in more cases.

n.id | n.name | n.category_label | n.provided_by
-- | -- | -- | --
"OMIM:133170" | "Erythropoietin" | "phenotypic_feature" | "umls_source:OMIM"
"CPT:82668" | "Erythropoietin" | "procedure" | "umls_source:CPT"
"LOINC:MTHU004935" | "Erythropoietin" | "procedure" | "umls_source:LNC"
"LOINC:LP15554-6" | "Erythropoietin" | "procedure" | "umls_source:LNC"

**Comment by kvarforl** [comment]
As of KG2.3.5, the weird `disease` label is gone:

n.id | n.name | n.category_label | n.provided_by
-- | -- | -- | --
"UMLS:C4693552" | "Erythropoietin" | "named_thing" | "identifiers_org_registry:umls"

but the other strange labels mentioned are still there.

n.id | n.name | n.category_label | n.provided_by
-- | -- | -- | --
"OMIM:133170" | "Erythropoietin" | "phenotypic_feature" | "umls_source:OMIM"
"CPT:82668" | "Erythropoietin" | "procedure" | "umls_source:CPT"
"LOINC:MTHU004935" | "Erythropoietin" | "procedure" | "umls_source:LNC"
"LOINC:LP15554-6" | "Erythropoietin" | "procedure" | "umls_source:LNC"

**Comment by saramsey** [comment]
All clean in KG2.5.1, I think?

<img width="907" alt="Screen Shot 2021-02-01 at 1 30 45 PM" src="https://user-images.githubusercontent.com/5562107/106520540-cef30280-6491-11eb-9b9a-406fa4428afa.png">
