### ISSUE TITLE
ways to enable concurrent drug-disease score prediction?

### ISSUE THREAD

**Issue by saramsey** [RTXteam/RTX#1059]
I'm summarizing here today's discussion with DMK, AG, EWD and others about the issue that the scikit-learn object for the trained RF model for drug-disease prediction takes like 20 GB of RAM. So, if multiple ARAX processes are doing drug-disease prediction at once, we could exhaust system RAM. 

Possible approaches?

1. **Option 1** Amy suggests systematically pre-generating scores and caching above-threshold (like, top 0.1% or whatever) scores. Benefit is that we could store the significant scores in an indexed filed-based data store (HDF5 or pickledb or whatever) or in a shared memory data structure. David and Chunyu have already been thinking about this, and have procured a big server for this purpose. Downside is (of course) we have to regenerate the predictions each time the model updates.

2. **Option 2** Eric pointed out that we could have a *predictor service*, which I suppose would be single-process so we have only one copy of the RF model object in memory on the ARAX server. It seems like it *may* be possible to do this in python 3.8 using the `multiprocessing`  package, specifically, the `Server process` feature. 
https://docs.python.org/3/library/multiprocessing.html
There is some chatter on the internet that more complex classes don't work with this Server Process feature of the multiprocessing package, so who knows. The predictor service would of course have to handle requests one-at-a-time, but that may be sufficient for our needs for a while. Result caching could still be used with this option, of course.

3. **Option 3** Implement a predictor service in another language. If **Option 2** is doable in python, then it is not clear what Option 3 buys us, except that in principle it could be completely multithreaded/multiprocess since the RF model object is (according to DMK) stateless. This would enable multiple totally independent ARAX processes to be doing RF prediction on the same underlying RF model object at the *same time*, without needing N copies of the RF model object. Languages discussed were Rust, C, Scala, and Clojure.

Folks, please weigh in with corrections or comments.

**Comment by edeutsch** [comment]
Thanks, very nice summary. I would only add an idea for option 2.5 is to implement caching and batching on top of option 2 as well. If realistically 90%+ of requests will be to the same 100,000 pairs, one can easily implement batching and caching such that a repeated query that hits previously requested probabilities can return a batch of 2000 pairs in < 0.01 seconds.

Also, should we document the resolution?
I think I tentatively put up a little hand wiggle for 2/2.5
But then I think we decided that option 1 would solve our problem at some point in the future
So no action just yet?
Or the action is to plan on @chunyuma doing option 1, and 2 and 3 are not needed?

**Comment by chunyuma** [comment]
Thanks for your options @saramsey and @edeutsch. Perhaps we might need more than 20 GB of RAM to read the trained RF model into the memory. The current trained RF model which is based on the `old` KG2 and the 'old' `mychem` training data  has the size of 1.4 GB. The new RF model I'm going to rebuild is based on the canonicalized kg2 and much more training data, which increases the size of the model. So it seems like we only can choose the option1.

But the good news is that since the new model we're going to rebuild is based on the canonicalized kg2 which is much smaller than the 'old' KG2 and I also removed 1) the nodes which are both ‘drug’ and ‘disease’; 2) the nodes with type including ‘drug’ or ‘disease’ != preferred_type and 3) all edges directly connecting both ‘drug’ and disease, the final graph used to rebuild the RF model has just 35,504,539 edges and 2,485,322 nodes. So it should be faster than before to generate the predictions based on the certain threshold and save them in indexed filed-based data format. 

Since I'm now still working on issue [994](https://github.com/RTXteam/RTX/issues/994) to figure out the main reason that causes the suspiciously overfitting result, I can't tell how big the final model will be.

**Comment by dkoslicki** [comment]
Closing as #994 and #1061
