### ISSUE TITLE
set up a t2.micro instance to be our central RTXConfiguration server?

### ISSUE THREAD

**Issue by saramsey** [RTXteam/RTX#1066]
Because we may sunset `arax.rtx.ai` (instead using `arax.ncats.io`) for cost reasons at some point, and since I don't think we want our global SSH config server to be on the NCATS-provided instance (better to have it under our control), I propose that I set up a t2.micro instance (cost is negligible) and have it be our RTXConfiguration server. What do folks think?  I can copy the authorized_keys file from /home/rtxconfig on `arax.rtx.ai` so no one should have to do a key exchange. But each person would have to do a one-time `ssh` into the new instance as user `rtxconfig`, to put the new instance's IP address into their `known_hosts` file.

**Comment by edeutsch** [comment]
This is fine with me. I don't see a problem with using arax.ncats.io either. Seems like less to manage to consolidate on one server. whatever is fine with me.

**Comment by amykglen** [comment]
I like the idea. would it also make sense to put the master copies of our various local databases on there, too? (e.g., `node_synonymizer.sqlite`, `curie_to_pmids.sqlite`, etc.) if we did, then developers could run ARAX code without needing access to `arax.ncats.io`. otherwise I think everyone would still need to have proper permissions to download them from `arax.ncats.io`.

**Comment by kvarforl** [comment]
@saramsey what's the status of this issue? I see a t2.micro instance called `araxconfig.rtx.ai` in `us-east-2`. does this mean its done and able to be closed?

**Comment by saramsey** [comment]
yes, thank you @kvarforl
