### ISSUE TITLE
Expose DSL parameters, what is default, optional, mutually exclusive, required, etc

### ISSUE THREAD

**Issue by dkoslicki** [RTXteam/RTX#1080]
Currently the dependencies between parameters is not as structured as the other pieces of the DSL (like the `describe_me`) and are just local variables (like [here](https://github.com/RTXteam/RTX/blob/master/code/ARAX/ARAXQuery/ARAX_overlay.py#L285-L290)). We should make this more scrape-able.

From Amy:
>Seems like making our parameter documentation more structured in general would be a great thing (e.g., for each parameter, list whether it is required vs. optional, its default, its possible values, and its dependencies in a structured/uniform way..)

Goal: Make a `.describe_parameters()` for each DSL command.

I'm assigning everyone who I recall being responsible for some DSL command. Feel free to add/remove.

Perhaps after someone makes a first crack at it, we can all implement the `.describe_parameters()` in all the same way (as is done with `.describe_me()`.

**Comment by edeutsch** [comment]
I was grousing about the lack of clarity when this was started long ago. I have a few ideas on how it could be better. I suggest a structure like this (using add_qnode() as an example):
```
allowable_parameters = {
    'id': { 
        'is_required': false,
        'examples': [ 'n00', 'n01' ],
        'default': 'n00',
        'type': 'string',
        'description': 'Any string that is unique among all QNode id fields, with recommended format n00, n01, n02, etc.',
        },
    'curie': {
        'is_required': false,
        'examples': [ 'DOID:9281', '[UniProtKB:P12345,UniProtKB:Q54321]' ],
        'type': 'string',
        'description': 'Any compact URI (CURIE) (e.g. DOID:9281) (May also be a list like [UniProtKB:P12345,UniProtKB:Q54321])',
        },
    'name': {
        'is_required': false,
        'examples': [ 'hypertension', 'insulin' ],
        'type': 'string',
        'description': 'Any name of a bioentity that will be resolved into a CURIE if possible or result in an error if not (e.g. hypertension, insulin)',
        },
    'type': {
        'is_required': false,
        'examples': [ 'protein', 'chemical_substance', 'disease' ],
        'type': 'string',
        'description': 'Any valid Translator bioentity type (e.g. protein, chemical_substance, disease)',
        },
    'is_set': {
        'is_required': false,
        'enum': [ 'true', 'false' ],
        'examples': [ 'true', 'false' ],
        'default': 'false',
        'type': 'boolean',
        'description': 'If set to true, this QNode represents a set of nodes that are all in common between the two other linked QNodes'
        },
}
```

What do you think?

**Comment by dkoslicki** [comment]
I like it! @edeutsch , any thoughts on how we handle:

1. One of `id`, `curie`, `name`, or `type` is required
2. Some arguments are mutually exclusive (eg. `paired_concept_frequency` and `observed_expected_ratio` in `overlay(action=overlay_clinical_info)`
3. Some arguments are only valid when others are invoked (eg. `COHD_method` in `expand` only valid if `kp=COHD`)

**Comment by edeutsch** [comment]
I am inclined to just mention such constraints in the description and write code to produce a nice error message when violated rather than trying to capture it in the allowable_parameters.

One can imagine:
1. "require_one_of": [ "id", "curie", "name", "type" ] but I suppose that would need to be in some parent construct
2. "cannot_cooccur_with": [ "paired_concept_frequency", "observed_expected_ratio" ]
3. "requires_key_value": "kp=COHD"
But this is getting pretty complicated IMO

**Comment by isbluis** [comment]
I was thinking along similar lines; the logic and dependencies might get a tad complicated, especially if parameters in one DSL command also influence a different one, e.g. an undeclared node id:
```
add_qnode(name=acetaminophen, id=n0)
add_qnode(type=protein, id=n1)
add_qedge(source_id=n0, target_id=n2, id=e0)
```

Perhaps the first thing that should happen when submitting a DSL is to have a (new?) mechanism to evaluate all statements and return a list of error messages, if any. This would also benefit non-UI submitted DSLs and prevent an error from happening minutes/hours into computation.

**Comment by edeutsch** [comment]
yeah, I pondered this while designing the parser. This already happens for pure syntax problems. But doesn't happen for semantic problems. For add_qnode()/add_qedge() it's no problem because they get run at the top and therefore errors are flagged with no delay.

But you're right that semantic errors below the first expand() may only get encountered after substantial work has been done. This is potentially unpleasant, but trying to compensate for it is not easy.

The most elegant solution I could think of is to implement a validate_only=true flag for all components like overlay() etc. where that code would inspect all of it parameters and generate errors if anything seemed ungood (which it already does anyway), but then return before doing any actual work. ARAX_query could then take two passes through the DSL. The first with validate_only=true and then second with false. The first pass would just make sure that everything seemed basically okay by passing the commands that will be run through all their respective modules for a quick check before doing the whole program for real.

I still think that's the best way, but seemed a little complicated for version 1.

But maybe if we decide to go back and add the advanced allowable_parameters{} to all components as above, everyone can also implement validate_only=true for the approach described above.

Does that seem sensible?

**Comment by dkoslicki** [comment]
Conclusion from AHM: we are to replace `allowable_parameters` with a structured form proposed by Eric [here](https://github.com/RTXteam/RTX/issues/1080#issuecomment-698576075). This means each of us (@amykglen `expand`, @dkoslicki @finnagin `overlay` and `filter`, etc.) will need to update the DSL methods in `ARAX/ARAXQuery/*.py`.

@dkoslicki to update the auto-gen documentation updater

**Comment by edeutsch** [comment]
After discussing and trying out various scenarios with @amykglen this is what we recommend:

High level YAMLish overview:
```
command_definition:
    dsl_command
    description
    mutually_exclusive_params
    parameters:
        <parameter_name>
            is_required
            examples[]
            default
            type
            enum
            description
```

and one specific example from add_qnode:
```
        command_definition = {
            'dsl_command': 'add_qnode()',
            'description': """The `add_qnode` method adds an additional QNode to the QueryGraph in the Message object. Currently
                when a curie or name is specified, this method will only return success if a matching node is found in the KG1/KG2 KGNodeIndex."""
            'mutually_exclusive_params': {'paired_concept_frequency', 'observed_expected_ratio', 'chi_square'},
            'parameters': {
                'id': { 
                    'is_required': false,
                    'examples': [ 'n00', 'n01' ],
                    'default': 'n00',
                    'type': 'string',
                    'description': 'Any string that is unique among all QNode id fields, with recommended format n00, n01, n02, etc.',
                    },
                'curie': {
                    'is_required': false,
                    'examples': [ 'DOID:9281', '[UniProtKB:P12345,UniProtKB:Q54321]' ],
                    'type': 'string',
                    'description': 'Any compact URI (CURIE) (e.g. DOID:9281) (May also be a list like [UniProtKB:P12345,UniProtKB:Q54321])',
                    },
                'name': {
                    'is_required': false,
                    'examples': [ 'hypertension', 'insulin' ],
                    'type': 'string',
                    'description': 'Any name of a bioentity that will be resolved into a CURIE if possible or result in an error if not (e.g. hypertension, insulin)',
                    },
                'type': {
                    'is_required': false,
                    'examples': [ 'protein', 'chemical_substance', 'disease' ],
                    'type': 'string',
                    'description': 'Any valid Translator bioentity type (e.g. protein, chemical_substance, disease)',
                    },
                'is_set': {
                    'is_required': false,
                    'enum': [ 'true', 'false' ],
                    'examples': [ 'true', 'false' ],
                    'default': 'false',
                    'type': 'boolean',
                    'description': 'If set to true, this QNode represents a set of nodes that are all in common between the two other linked QNodes'
                    },                }
            }
            return command_definition
```

As is currently the case, when describe=true, the function would return a structure like the above.
@dkoslicki 's autodocumentation would need to be adjusted to use the new structure
@isbluis 's auto DSL helper would need to adjust to use the new structure.

We thought that we would just preserve the current behavior where overlay returns different command_definitions based on the action=value, rather than making one huge structure that encapsulates all the various scenarios all in one structure. but we weren't sure that was the right decision or not.

Give it a try and see if that works for you. Post comments/suggestions/refinements

**Comment by edeutsch** [comment]
and one more time without the syntax errors:
```
        command_definition = {
            'dsl_command': 'add_qnode()',
            'description': """The `add_qnode` method adds an additional QNode to the QueryGraph in the Message object. Currently
                when a curie or name is specified, this method will only return success if a matching node is found in the KG1/KG2 KGNodeIndex.""",
            'parameters': {
                'id': { 
                    'is_required': False,
                    'examples': [ 'n00', 'n01' ],
                    'default': 'n00',
                    'type': 'string',
                    'description': 'Any string that is unique among all QNode id fields, with recommended format n00, n01, n02, etc.',
                    },
                'curie': {
                    'is_required': False,
                    'examples': [ 'DOID:9281', '[UniProtKB:P12345,UniProtKB:Q54321]' ],
                    'type': 'string',
                    'description': 'Any compact URI (CURIE) (e.g. DOID:9281) (May also be a list like [UniProtKB:P12345,UniProtKB:Q54321])',
                    },
                'name': {
                    'is_required': False,
                    'examples': [ 'hypertension', 'insulin' ],
                    'type': 'string',
                    'description': 'Any name of a bioentity that will be resolved into a CURIE if possible or result in an error if not (e.g. hypertension, insulin)',
                    },
                'type': {
                    'is_required': False,
                    'examples': [ 'protein', 'chemical_substance', 'disease' ],
                    'type': 'string',
                    'description': 'Any valid Translator bioentity type (e.g. protein, chemical_substance, disease)',
                    },
                'is_set': {
                    'is_required': False,
                    'enum': [ 'true', 'false' ],
                    'examples': [ 'true', 'false' ],
                    'default': 'false',
                    'type': 'boolean',
                    'description': 'If set to true, this QNode represents a set of nodes that are all in common between the two other linked QNodes'
                    },
            }
        }
```

**Comment by edeutsch** [comment]
ARAXMessenger updated with the new design in `master`. Not really tested since required updates to the documentation generator and DSL builder generator. Let me know if you think the design should be altered.

**Comment by amykglen** [comment]
ok, I updated `expand` to use this new structure - it went pretty well! (changes are in a branch called `issue1080` for now.) a few notes:

1. I realized it may be helpful to list a `min` and `max` for numeric parameters (instead of `enum`). here's an example of such a parameter:
```
"COHD_method_percentile": {
    "is_required": False,
    "examples": ["paired_concept_freq", "chi_square"],
    "min": 0,
    "max": 100,
    "default": 99,
    "type": "integer",
    "description": """What percentile to use as a cut-off/threshold for the specified COHD method."""
}
```
which means the revised yaml-ish overview would look like:
```
command_definition:
    dsl_command
    description
    mutually_exclusive_params
    parameters:
        <parameter_name>
            is_required
            examples[]
            default
            type
            enum
            min
            max
            description
```
we don't have to include this of course, but I do think it would be useful (and we have a decent number of numeric parameters between expand/overlay/filter).

2. sometimes the possible choices (`enum`) for a parameter depend on the contents of the query graph/knowledge graph (e.g., `edge_id` in `expand` could be set to any of the edge IDs in the QG), but I don't think we can access `message` contents with our current set up for documentation...(?) for now, I just omitted `enum` for such situations.. at least with `expand`, this seems like a pretty minor issue.. so I'd say we needn't worry about addressing it for now..
3. @edeutsch and I discussed this today, but as a head's up for others (@dkoslicki): I switched `expand`'s documentation to the sort of `action=` paradigm used in `overlay`/`filter`, except with `kp=` instead of `action=`. I realized that the `kp` parameter in `expand` has kind of become analogous to `action` in `overlay`, in that, depending on what `kp` is chosen, only a portion of `expand`'s other parameters are valid. and also in that there is (sometimes quite rich) information specific to each of `expand`'s KPs that would be useful to document. though if anyone objects to this I'm happy to revert it.

**Comment by isbluis** [comment]
As an update on this, the UI in my dev area now picks up `default` and `is_required` values (and ignores `type` and `examples`).

Currently only `create_message()`, `add_qnode()`, and `add_qedge()` have the updated command_definition structure.  My script that generates the JSON that drives the UI can deal with old and new `describe_me()` versions, so the enhanced logic and values will be available for the rest of the commands once those definitions are updated.

Of note, some commands have markdown that is designed to render in table form.  Perhaps we need a separate definition for these do they don't show up funny in the UI?  e.g.  `overlay(action=fisher_exact_test)`

https://arax.rtx.ai/devLM/index.html

**Comment by dkoslicki** [comment]
Note to self: for `overlay(action=fisher_exact_test)` just remove the Markdown in the description.

**Comment by dkoslicki** [comment]
DMK todo: make a `short_description` to fix the aforementioned UI display issue with markdown

**Comment by dkoslicki** [comment]
Revised, revised yaml-ish format for the dicts:
command_definition:
    dsl_command
    description
    brief_description
    mutually_exclusive_params
    parameters:
        <parameter_name>
            is_required
            examples[]
            default
            type
            enum
            min
            max
            description

**Comment by edeutsch** [comment]
and just to correct the mistake I made originally, mutually_exclusive_params and enum should be lists:

```
    dsl_command
    description
    brief_description
    mutually_exclusive_params[]
    parameters:
        <parameter_name>
            is_required
            examples[]
            default
            type
            enum[]
            min
            max
            description
```

**Comment by dkoslicki** [comment]
@finnagin feel free to do the overlay() DSL commands too

**Comment by dkoslicki** [comment]
Is this in a state that can be merged into master?

**Comment by finnagin** [comment]
I think there will be a couple of tweaks necessary after merging master into issue1080 but other than that I think it is ready. @amykglen and @edeutsch now that `document_dsl_commands.py` has been updated and the documentation generated does all of your documentation look correct? If so I think we can go ahead and merge with master.

**Comment by edeutsch** [comment]
seems fine to me!

**Comment by amykglen** [comment]
looks good to me too!

**Comment by finnagin** [comment]
I've merged into master and all of the tests seem to be passing. I'm going to add a needs test on production flag and then if everything looks good with the UI etc I think we can close this one out

**Comment by isbluis** [comment]
I am on leave this week, but will try to squeeze in the necessary changes to test the UI.   Thanks!

**Comment by isbluis** [comment]
Hi @finnagin , @amykglen , @dkoslicki .
I notice that a few commands have boolean-like parameters, though they are specified as `string`; namely:
```
overlay(action=overlay_clinical_info)
-  paired_concept_frequency  
-  observed_expected_ratio
-  chi_square

filter_kg(action=remove_edges_by_type)
filter_kg(action=remove_edges_by_attribute)
filter_kg(action=remove_edges_by_property)
-  remove_connected_nodes

filter_kg(action=remove_edges_by_stats)
-  top
-  remove_connected_nodes

filter_results(action=sort_by_edge_attribute)
filter_results(action=sort_by_node_attribute)
filter_results(action=limit_number_of_results)
filter_results(action=sort_by_edge_count)
filter_results(action=sort_by_node_count)
-  prune_kg

```

It seems that some take any of [ `true`, `false`, `True`, `False`, `t`, `f`, `T`, and `F` ] as valid inputs.

Would it make sense to harmonize them with other ARAX components and define them strictly as `boolean`, with [ `true`, `false` ] as the only valid values?

Either is fine by me; the main consequence for GUI users will be that they would see a true/false menu instead of a string input box. Alternatively, I could add special logic to deal with these parameters to override the input type.

Thanks!

**Comment by edeutsch** [comment]
As a somewhat peripheral note, the current ActionsParser does not know anything about what data types arguments should be, and therefore all arguments are returned as strings. it is up to the individual components to validate their input and bark if it is not valid. And convert the strings to a different datatype as desired.

We could change that behavior if that is desirable. Until the change entertained in this thread is/was made, that was not even possible. but now it could be. although not easily.

I will also wrinkle my nose at "chi_square" et al. being a boolean, since one would expect "chi_square" to be a float. I think the argument would be better named "return_chi_square" or some such that would imply a boolean a bit more strongly.

**Comment by isbluis** [comment]
You can see a snapshot of the current state of the UI at:
https://arax.ncats.io/devLM/index.html

Some minor corrections might be needed, but otherwise looking good.

**Comment by finnagin** [comment]
@isbluis I'll change those to be marked as boolean. If it is marked as boolean can [ true, false, True, False, t, f, T, and F ] all be valid inputs and the GUI still display a true/false menu?

Awesome! looks like the brief descriptions are displaying properly.

**Comment by edeutsch** [comment]
The cost/benefit ratio may be too high, but it may be a nice touch for for add_qnode() and add_qedge() to allow selection of the types from the data that you already fetch for the graph builder.

**Comment by isbluis** [comment]
A few comments:

---
- Since for `overlay(action=overlay_clinical_info)` the following (boolean) values are mutually exclusive (i.e. only one can be true or an error is thrown):
```
-  paired_concept_frequency  
-  observed_expected_ratio
-  chi_square
```
Would it make more sense to replace these three parameters with an optional string parameter named `method` (or something like that) with possible values [ `paired_concept_frequency`, `observed_expected_ratio`, `chi_square `], @edeutsch , @finnagin ?   Also easy to add more if functionality expands in future.
_Note that this is already being done for the `COHD_method` parameter for `expand(kp=COHD)`._

---
- The true/false menu is a good idea, @finnagin ; I have added an override in my code to replace whatever is in the `enum` with [ `true`, `false`] when `type == boolean`, and thus display only a true/false menu.
See live demo at:  https://arax.ncats.io/devLM/index.html --> _filter_results(action=sort_by_node_count)_

Two things to note:
1. If the _default_ value is something other than [true, false], it will not show up or be pre-selected on the UI
2. Would be nice if **all** components of ARAXi had the same range of values for boolean types -- otherwise I believe is somewhat confusing to an outside user if, say `add_qnode(is_set=T)` does not work.  I personally like the short-hand version options, but not all components support this.

---
- Note that for `filter_kg(action=remove_edges_by_stats)`, the default values for `threshold`, `top`, and `direction` are context-dependent, but this is not easily parsable by the UI (and in the case of `threshold`, it prefills with an odd value).  Not sure what the best solution is at the moment.

---
- I actually think that the cost/benefit is small, @edeutsch : nice to have the allowable values displayed to cut down on user error / typos, and as you mention, the data are already on the page anyway.  I would suggest a special data type of something like `ARAXnode` / `ARAXedge` (or something like that) instead of `string`.  That way my code does not have to look for special cases, and it can also be used in other commands, e.g. `filter_kg(action=remove_nodes_by_type)`
See live demo at:  https://arax.ncats.io/devLM/index.html --> _add_qnode()_

---
- Last idea: should we attempt to hook up auto-complete to some/all of the string fields...?

**Comment by edeutsch** [comment]
okay, great, I changed the types to ARAXnode and ARAXedge as suggested. And removed the default value for is_set

**Comment by finnagin** [comment]
@isbluis For `remove_edges_by_stats` I think the best solution would be to default to setting `threshold`, `top`, and `direction` to just not being included and someone can add manually if they want. Since in most cases it will handle everything automatically.

@dkoslicki Any thoughts on Luis' proposed change to `overlay(action=overlay_clinical_info)` to instead of having a few true/false parameters that are mutually exclusive we instead have a `method` parameter that takes strings for each method type?

**Comment by isbluis** [comment]
@edeutsch Great, thanks!  Though I am not sure that removing the default for `is_set` is necessary, since it does _default_ to `false`?
Also, for _ARAXedge_, is the full list of valid types in the `predicates` call?  How about those special types, like `N1` etc?

@finnagin @edeutsch For those parameters, should we add some flag that tells the UI to skip them?  Maybe something like a `UI_display` = [`true`, `false`] ?  
Of course I can always add special logic to skip these, if that seems better/easier.
Either way, should we still somehow list them as available/advanced parameters somewhere on the UI?

**Comment by isbluis** [comment]
Should the `node_type` parameters for `filter_kg(action=remove_nodes_by_type)`, `filter_kg(action=remove_orphaned_nodes)`, and `filter_results(action=sort_by_node_attribute)` be set to the new `ARAXnode` type (instead of `string`) ? 

This has the effect of displaying a pull-down menu with the known/valid node types (instead of having the user mis/type it).

**Comment by edeutsch** [comment]
> Great, thanks! Though I am not sure that removing the default for is_set is necessary, since it does default to false?

So I removed the default value under the impression that means it won't then show up every time. The issue is: when I last used the interface (did not test today), I would always get stuff like:

add_qnode(curie=DOID:123,is_set=false)

But is_set is a pretty obscure parameter that very rarely needs to specified. And is clutters up the DSL to always show is_set=false when 99% of add_qnode() lines are is_set=false.

The only time I want is_set to be shown is when it's true! (or if the user wants to specify it I guess).
So it would be ideal if the user doesn't specify anything, then it is not written into the DSL (and add_qnode() treats this as false). while if the user actively picks true or false, then it is injected into to the DSL.

What do you think?

**Comment by isbluis** [comment]
@edeutsch Yes, that makes perfect sense, and it is the way it now works in my dev area with these most recent changes. Thanks!

**Comment by isbluis** [comment]
Thinking about this a little more, it means that all parameters that have a `default` value will see that parameter set when submitting the DSL command, as you point out.  Would it be preferable to not pass the value at all if it is the same as the default?  I can see it being a little confusing either way, say in the case when someone actually selects `false` on the drop-down menu.  Any strong opinions on this?

**Comment by finnagin** [comment]
@isbluis I like that idea. I'll add a `UI_display` field and set it to `false`. Probably good to assume `UI_display` is set to `true` if not included as not all parameters will have the `UI_display` field.

I also like the idea of listing these as advanced options in the UI.

**Comment by isbluis** [comment]
@finnagin Great!  I have added the latest version to my dev area, including hiding these advanced parameters.

I also wonder if the `direction` parameter within the various `sort_by_X_Y` methods in `filter_results` should have an `enum` of all possible values [`ascending` , `a` , `descending` , `d` ]  Or are there more?  This would create a drop-down menu for the UI, which might be nice.

**Comment by dkoslicki** [comment]
Conclusions from the mini-hackathon:
1. Every DSL command accepts true, false, True, False, t, f, T, and F 
2. For overlay_clinical_info, add a COHD_method option with the three options chi_square, etc.

**Comment by dkoslicki** [comment]
Has been running on production with no issues, so closing. @isbluis feel free to object if you're still on this one
