### ISSUE TITLE
add a "store=json" option to the return statement in the DSL

### ISSUE THREAD

**Issue by saramsey** [RTXteam/RTX#1094]
We were having some issues with storing large messages, and as a (possibly temporary) work-around, the idea has been proposed to have a `store=json` option to store the message as a JSON file (with a UUID in the filename) in a subdirectory that is sym-linked under the Apache2 DocumentRoot directory (which would make the JSON message file retrievable with a HTTP GET). This idea was discussed with @edeutsch and @dkoslicki and then implemented in several hacks to `ARAX_query.py`, and then tested locally (with the new test case '9999' in ARAX_query.py) and then pushed to `arax.rtx.ai` in the `/test` area for integration testing.

TODO: fix the `https://arax.rtx.ai` server URL which is now hard-coded on line 54 of the module; this won't work if/when we try to deploy the updated ARAX_query.py to arax.ncats.io, without a code change.

**Comment by saramsey** [comment]
tagging @amykglen to make her aware of this issue

**Comment by saramsey** [comment]
One possible tweak would be to add the file suffix `.json` to the file that is created, to automatically set the appropriate MIME type.

**Comment by saramsey** [comment]
Also, in b2b1b6a, I neglected to call `message.debug` to log a message about "storing message" in the `store=true` branch of the code. That should probably be fixed. Just noting it here.

**Comment by saramsey** [comment]
Thank you @amykglen for b2b1b6a

**Comment by amykglen** [comment]
no problem! added the `.json` suffix in 8a65307

**Comment by saramsey** [comment]
@amykglen:  is it OK to delete the `issue1094` branch?

**Comment by amykglen** [comment]
yes! good thinking.

**Comment by edeutsch** [comment]
I have backed out the patch and implemented local filesystem storage of messages so that everything should operate the way it did before. The storage of messages to disk should now be transparent.

They get stored to RTX/data/responses/
which gets created automatically if necessary.

For a while I've left it in that store=json works identically as store=true, just in case there is some legacy stuff.
It is rolled out to all areas (production, beta, etc.)
Not as well tested as it should be probably, but seems to work.
Let me know if you encounter issues.

**Comment by edeutsch** [comment]
okay to full remove all store=json functionality and close this issue?

**Comment by saramsey** [comment]
ok with me. @amykglen is it OK with you?

**Comment by amykglen** [comment]
yep, sounds good to me!

**Comment by edeutsch** [comment]
removal of final remnants pushed to master.
