### ISSUE TITLE
Further speedups to NGD

### ISSUE THREAD

**Issue by dkoslicki** [RTXteam/RTX#1096]
I noticed that lots of NGD calls using eUtils are for the same bioentity (like in that case, GPI wt Allele) and result in nan's. As such, I suspect that the single count frequency of GPI wt Allele is 0, and so can't hope to have a non-nan NGD. Perhaps a quick work around to this is: for every node in the KG, don't run any NGD computation if the single count frequency is zero. This will cut down on the failed O(n^2) calls that need to be made

eg. 

![](https://lh3.googleusercontent.com/-ILbm9rBNMME/X3umqmzdiaI/AAAAAAAAASY/NPPbK8Ckjuc_GA4qVFl5m3ZP0LamTv6MACK8BGAsYHg/s0/2020-10-05.png)

(ignore the error at the bottom)

**Comment by amykglen** [comment]
noting this here since it's relevant to this issue: we decided on Oct. 5 to let go of the 'fallback' NGD method (and only use the fastNGD method) in `overlay`'s `compute_ngd`, since coverage for fastNGD is quite high now (in the 95%+ range - and out of those fastNGD misses, the fallback method tends to return NaN for quite a few (hard to estimate, but maybe 30-50%)).

so the output seen above isn't currently reproducible. (and this issue may no longer be relevant?)

**Comment by finnagin** [comment]
@dkoslicki Is this issue still relevant since Amy let go of the 'fallback' NGD method in favor of only using the fastNGD method?

**Comment by dkoslicki** [comment]
Same comment as #1097: low priority, but we can keep it in the back of our minds in case the 95% hit rate of FastNGD ever drops.

**Comment by dkoslicki** [comment]
Closing since FastNGD appears to be fast enough
