### ISSUE TITLE
Create a function to check and download all databases which is always called when ARAX queries are run

### ISSUE THREAD

**Issue by chunyuma** [RTXteam/RTX#1099]
Hi all, right now we have multiple databases (fastNGD, Graph.sqlite, COHD database, node_synonymizer.sqlite and so on). For KG2.3.4, we collect all databases in `/data/orangeboard/databases/KG2.3.4/` on `arax.rtx.ai` server. I have an idea to create a function to check and download the databases from this directory once any databases are updated. But this function should be put in somewhere that is always called when ARAX queries are run (regardless of what specific commands are used). Do you have any suggestions for this idea?

**Comment by amykglen** [comment]
nice idea to centralize storage/downloading of these databases. my thought is maybe the method would belong somewhere in `ARAX_query.py`? though I don't know that module nor the rest of ARAX's 'set up' sort of code all that well. I'm sure @edeutsch has insight!

**Comment by edeutsch** [comment]
sure, a call out to such a checking function could be done in ARAX_Query around line 144.

Although I wonder, is there a need to do the check with every query?

Or is it perhaps better to perform the check and upgrade when the system launches? which would then be around line 57.

**Comment by saramsey** [comment]
Hi Chunyu, thank you for proposing this interesting idea. I think centralizing our data stores on the ARAX system is a _very_ good idea. Putting them (to the extent possible) somewhere under the `/data` file system (so they do not bloat the root filesystem inside the Docker container)--as you suggest--is also a _very_ good idea. It is unclear to me (as I have not checked the wiki lately) who--or what--creates this subdirectory and who depends on the contents of it. But if this makes it easier to copy these required data stores in order to set up a test installation of ARAX, it seems like progress!

I am unsure about the wisdom of using the KG2 semantic version in the subdirectory name, versus just having a generic directory (e.g., `/data/arax-databases`) with a text file inside the directory with the KG2 version number inside the text file. Having the version number in the subdirectory name will make deployment instructions more complex, right?

**Comment by saramsey** [comment]
What will be the mechanism to automatically determine if some database file has been updated?  File modification timestamp?  Surely not an MD5 hash (right?).

**Comment by chunyuma** [comment]
It seems like this issue has been solved. Is it ok for me to close it?

**Comment by finnagin** [comment]
Yeah this can be closed. Thanks for checking!
