### ISSUE TITLE
Remove workflow for simple lookup

### ISSUE THREAD

**Issue by dkoslicki** [RTXteam/RTX#1108]
[this workflow](https://github.com/RTXteam/RTX/blob/master/code/ARAX/ARAXQuery/ARAX_query_graph_interpreter_templates.yaml#L99-L115) should revert to the simple lookup

**Comment by dkoslicki** [comment]
Note that it matched to this template even thought the edge type was specified. Is this intended behavior @edeutsch? I had intended this template to only match when the edge type was _unspecified_.

**Comment by edeutsch** [comment]
The short answer is yes.

The long answer is that the query_graph_interpreter always uses the *closest* template, even if it's not a perfect match. This would be the closest match.

But also, the current functionality does not support a distinction between
    e00()
and
    e00(type)
and
    e00(type=contraindicated_for)
which sounds like what you want? You want there to be a different DSL depending on whether the user specifies a type or not? and then while we're at it, also allow specific types. One can already do this with *nodes*, but support for that has not been extended to edges. Not hard to add I suspect. Shall I do that?

The issue is, do we want to be able to run different DSL depending on these three different scenarios?
As currently with nodes, you wouldn't be required to write different DSL for these if you didn't want to, and the QGI would select the closest template based on what's available.

**Comment by dkoslicki** [comment]
Correct: it would be good to distinguish between 
e00()
and 
e00(type)
and 
e00(type=<something specific>)

i.e. if the user/ARS is being specific and wants a simple lookup (what drugs are `indicated`_for disease X), then we should return that to them with nothing extra. If no edge relation is specified, then we want a different DSL to decorate it so we can rank the results in some sort of meaningful way (eg. higher ranked=treats, lower ranked=causes)

**Comment by edeutsch** [comment]
okay, I have pushed to `master` code that should take care of this, adding support for edge type templating. As part of this commit, I made drug treats disease a simple lookup, and drug ? disease the complex query. I think we agreed on this, but I'm not sure. Please correct if not.

**Comment by dkoslicki** [comment]
@edeutsch I think that's correct, thanks for the fix!
