### ISSUE TITLE
One test in latest master codebase is failing

### ISSUE THREAD

**Issue by edeutsch** [RTXteam/RTX#1133]
One test failure in `master` in test_query_by_query_graph_2:
```
   def test_query_by_query_graph_2():
        query = { "message": { "query_graph": { "edges": [
                    { "id": "qg2", "source_id": "qg1", "target_id": "qg0", "type": "physically_interacts_with" }
                ],
                "nodes": [
                    { "id": "qg0", "name": "acetaminophen", "curie": "CHEMBL.COMPOUND:CHEMBL112", "type": "chemical_substance" },
                    { "id": "qg1", "name": None, "desc": "Generic protein", "curie": None, "type": "protein" }
                ] } } }
        araxq = ARAXQuery()
        result = araxq.query(query)
        print(result.show())
        assert result.status == 'OK'
        message = araxq.message
>       assert message.n_results == 32
E       assert 50 == 32
```

Perhaps an issue of moving from KG1 as default to KG2 as default.
Maybe switch assert to 50? Or maybe a more nuanced fix?

**Comment by amykglen** [comment]
yeah, agree it seems to be due to moving from KG1 to KG2 as the default. 

I didn't write this test, but I'd suggest just changing it to `assert message.n_results >= 32`, since we know there should be at least as many answers as KG1 provided, but then we won't have to keep adjusting the range as KG2 provides more and more answers over time (or the default result cut-off of 50 is changed).

**Comment by edeutsch** [comment]
okay, I went ahead and committed `assert message.n_results >= 32`. Please feel free to correct if that doesn't seem right.
