### ISSUE TITLE
Some nodes appear to be miscategorized as genes

### ISSUE THREAD

**Issue by MarkDWilliams** [RTXteam/RTX#1167]
In running this query:
```
{
  "message": {
    "query_graph": {
      "edges": [
        {
          "id": "e0",
          "source_id": "n0",
          "target_id": "n1"
        },
        {
          "id": "e1",
          "source_id": "n1",
          "target_id": "n2"
        }
      ],
      "nodes": [
        {
          "curie": "CHEBI:5062",
          "id": "n0"
        },
        {
          "id": "n1",
          "type":"gene"
        },
        {
          "id":"n2",
          "curie":"MONDO:0005339"
        }
      ]
    }
  }
}
```
I got the following results:
https://ars.transltr.io/ars/api/messages/f3630ade-2c56-4184-91cd-a4dd6ff1edc5
It appears that Unipolar Depression (MONDO:0005263), Polycystic Ovarian Syndrome (MONDO:0008487), Prostate Cancer (MONDO:0008315), and Losartan (CHEMBL.COMPOUND:CHEMBL191) are incorrectly categorized as genes.

**Comment by MarkDWilliams** [comment]
To clarify, this is not currently a blocking issue for our work, but I thought I'd let y'all know about it.

**Comment by saramsey** [comment]
OK, looking into this. KG2.3.5 seems to have `MONDO:0008315` as a `biolink:Disease` so my thinking is that there could be an issue downstream of KG2. @amykglen can you please check KG2c?

<img width="588" alt="Screen Shot 2020-12-15 at 10 30 36 AM" src="https://user-images.githubusercontent.com/5562107/102256805-b10d1680-3ec0-11eb-9fe4-c6bdfdc22458.png">

**Comment by edeutsch** [comment]
Hi Mark, thanks for reporting. We've been following up on some similar issues as well.
See #1044 for the Losartan example.

There are several sources of these, one is:
https://github.com/TranslatorSRI/NodeNormalization/issues/36

and here's another, specifically on the Losartan one:
https://github.com/TranslatorSRI/NodeNormalization/issues/38

If you have any ability to nudge progress on these @MarkDWilliams that would be great!

**Comment by amykglen** [comment]
as for the MONDO:0008315 (prostate cancer) example, it looks like one of the equivalent curies the NodeSynonymizer gives is a gene, which is why that concept is being returned when querying for genes.

these are the KG2.3.4 nodes coalesced to form MONDO:0008315 in KG2c:
```
match (n) where n.id in ["UMLS:C1415693", "HGNC:5143", "UMLS:C0376358", "HP:0012125", "LOINC:LA15688-7", "UMLS:C1739135", "MEDDRA:10066489", "MEDDRA:10060862", "UMLS:C0007112", "MEDDRA:10001186", "MESH:D011471", "UMLS:C4722327", "UMLS:C2931456", "MESH:C537243", "UMLS:C4722328", "NCIT:C7378", "NCIT:C103817", "NCIT:C2919", "OMIM:601518", "OMIM:176807", "OMIM:MTHU017418", "PDQ:CDR0000038782", "SNOMED:399068003", "SNOMED:399490008", "SNOMED:715412008", "MONDO:0008315", "ORPHANET:1331", "EFO:0000673", "MONDO:0011098", "MONDO:0023122", "MONDO:0005082", "DOID:10283", "DOID:2526"] return n.id, n.category_label, n.name, n.iri
```

n.id | n.category_label | n.name | n.iri
-- | -- | -- | --
"UMLS:C1415693" | "genomic_entity" | "hereditary prostate cancer 1" | "https://identifiers.org/umls:C1415693"
"HGNC:5143" | "gene" | "hereditary prostate cancer 1" | "https://identifiers.org/hgnc:5143"
"UMLS:C0376358" | "disease" | "Malignant tumor of prostate" | "https://identifiers.org/umls:C0376358"
"HP:0012125" | "phenotypic_feature" | "Prostate cancer" | "http://purl.obolibrary.org/obo/HP_0012125"
"LOINC:LA15688-7" | "procedure" | "Prostate cancer" | "http://purl.bioontology.org/ontology/LNC/LA15688-7"
"UMLS:C1739135" | "disease" | "Progression of prostate cancer" | "https://identifiers.org/umls:C1739135"
"MEDDRA:10066489" | "named_thing" | "Progression of prostate cancer" | "http://purl.bioontology.org/ontology/MEDDRA/10066489"
"MEDDRA:10060862" | "disease" | "Prostate cancer" | "http://purl.bioontology.org/ontology/MEDDRA/10060862"
"UMLS:C0007112" | "disease" | "Adenocarcinoma of prostate" | "https://identifiers.org/umls:C0007112"
"MEDDRA:10001186" | "named_thing" | "Adenocarcinoma of prostate" | "http://purl.bioontology.org/ontology/MEDDRA/10001186"
"MESH:D011471" | "named_thing" | "Prostatic Neoplasms" | "http://purl.bioontology.org/ontology/MESH/D011471"
"UMLS:C4722327" | "disease" | "Prostate cancer, hereditary, 1" | "https://identifiers.org/umls:C4722327"
"UMLS:C2931456" | "disease" | "Familial prostate cancer" | "https://identifiers.org/umls:C2931456"
"MESH:C537243" | "named_thing" | "Prostate cancer, familial" | "http://purl.bioontology.org/ontology/MESH/C537243"
"UMLS:C4722328" | "disease" | "Hereditary Prostate Carcinoma" | "https://identifiers.org/umls:C4722328"
"NCIT:C7378" | "disease" | "Malignant Prostate Neoplasm" | "https://identifiers.org/ncit:C7378"
"NCIT:C103817" | "disease" | "Hereditary Prostate Carcinoma" | "https://identifiers.org/ncit:C103817"
"NCIT:C2919" | "disease" | "Prostate Adenocarcinoma" | "https://identifiers.org/ncit:C2919"
"OMIM:601518" | "phenotypic_feature" | "Prostate cancer, hereditary, 1" | "http://purl.obolibrary.org/obo/OMIM_601518"
"OMIM:176807" | "phenotypic_feature" | "Prostate cancer" | "http://purl.obolibrary.org/obo/OMIM_176807"
"OMIM:MTHU017418" | "phenotypic_feature" | "Prostate cancer" | "http://purl.obolibrary.org/obo/OMIM_MTHU017418"
"PDQ:CDR0000038782" | "named_thing" | "prostate cancer" | "http://purl.bioontology.org/ontology/PDQ/CDR0000038782"
"SNOMED:399068003" | "disease" | "Malignant tumor of prostate" | "http://purl.bioontology.org/ontology/SNOMEDCT/399068003"
"SNOMED:399490008" | "disease" | "Adenocarcinoma of prostate" | "http://purl.bioontology.org/ontology/SNOMEDCT/399490008"
"SNOMED:715412008" | "disease" | "Familial prostate cancer" | "http://purl.bioontology.org/ontology/SNOMEDCT/715412008"
"MONDO:0008315" | "disease" | "prostate cancer" | "http://purl.obolibrary.org/obo/MONDO_0008315"
"ORPHANET:1331" | "disease" | "Familial prostate cancer" | "http://purl.bioontology.org/ontology/ORDO/1331"
"EFO:0000673" | "disease" | "prostate adenocarcinoma" | "http://purl.bioontology.org/ontology/EFO/0000673"
"MONDO:0011098" | "disease" | "prostate cancer, hereditary, 1" | "http://purl.obolibrary.org/obo/MONDO_0011098"
"MONDO:0023122" | "disease" | "familial prostate carcinoma" | "http://purl.obolibrary.org/obo/MONDO_0023122"
"MONDO:0005082" | "disease" | "prostate adenocarcinoma" | "http://purl.obolibrary.org/obo/MONDO_0005082"
"DOID:10283" | "disease" | "prostate cancer" | "http://purl.obolibrary.org/obo/DOID_10283"
"DOID:2526" | "disease" | "prostate adenocarcinoma" | "http://purl.obolibrary.org/obo/DOID_2526"

**Comment by edeutsch** [comment]
It's a similar story for Polycystic Ovarian Syndrome.
There's a HGNC name in KG2 naming the gene after the disease:
```
HGNC:8741	polycystic ovary syndrome 1	gene
```
It is also withdrawn:
https://www.genenames.org/data/gene-symbol-report/#!/hgnc_id/8741

I can add in some specific exceptions to avoid these, but I wonder if maybe excluding "withdrawn" HGNC curies from KG2 might be a good solution, if it is feasible? (or update their names with WITHDRAWN if that seems better, although I don't think it is)

**Comment by sstemann** [comment]
waiting on https://github.com/TranslatorSRI/NodeNormalization/issues/38

**Comment by amykglen** [comment]
with the rollout of KG2.6.7.1, the results for @MarkDWilliams' original query appear fixed - none of the four reported conflations are present and the results appear strictly gene/protein-like.

results are here: https://arax.ncats.io/?r=16949 (query adapted for TRAPI 1.1)

feel free to close this issue @MarkDWilliams, if this looks good to you.

**Comment by finnagin** [comment]
Closing as this appears to be fixed.
