### ISSUE TITLE
Not include withdrawn HGNCs?

### ISSUE THREAD

**Issue by edeutsch** [RTXteam/RTX#1170]
Following on issue #1167, we decided it would be advantageous (probably) to *exclude* HGNCs that are "withdrawn" such as:

https://www.genenames.org/data/gene-symbol-report/#!/hgnc_id/8741

The question is: can we/should we exclude from KG2.4.1+ all HGNCs that are "withdrawn"?

**Comment by dkoslicki** [comment]
I vote yes: exclude all HGNCs that are `withdrawn`

**Comment by kvarforl** [comment]
Okay so we currently ingest HGNC through UMLS, and the [UMLS representation](https://www.nlm.nih.gov/research/umls/sourcereleasedocs/current/HGNC/sourcerepresentation.html) doesn't include the HGNC status, which is unfortunate.
![image](https://user-images.githubusercontent.com/39020520/102556554-66d59200-4086-11eb-8b77-a7b1ba097e83.png)

This means that there isn't a simple way of determining which HGNC nodes are withdrawn, so they are hard to throw out.

**Comment by kvarforl** [comment]
On the bright side, the nodes with locus type "phenotype" are all withdrawn, so that can be used to get rid of 569 withdrawn nodes
![image](https://user-images.githubusercontent.com/39020520/102556887-32160a80-4087-11eb-8d18-24c73b17cd5f.png)

(im basing this assumption off searching [HGNC](https://www.genenames.org/tools/search/#!/genes?query=) with a blank query, looking at the number of phenotype matches in the side bar (569), filtering by "withdrawn", and comparing that number again (still 569). The curator note also says "HGNC no longer maintain symbols for phenotypes. Please visit OMIM for further information about this locus.")

**Comment by edeutsch** [comment]
I wonder if a query to mygene.info might easily identify those that are withdrawn? I don't know the answer, but just wondering.

**Comment by kvarforl** [comment]
Putting a note here to remind my future self that the changes for this are in PR #1172,  which is blocked by an issue with owltools/ ontobio. Links to the ontobio issue are in the PR.

**Comment by saramsey** [comment]
> Putting a note here to remind my future self that the changes for this are in PR #1172, which is blocked by an issue with owltools/ ontobio. Links to the ontobio issue are in the PR.

Thank you for cross-referencing the PR here. Also I will cross-reference the ontobio issue:  https://github.com/biolink/ontobio/issues/507

**Comment by saramsey** [comment]
Thank you @kvarforl and @ericawood !

**Comment by ericawood** [comment]
This appears to be fixed in `KG2.6.0`, though it is a bit hard to test:

`match (n {id: 'HGNC:8741'}) return n` returns no records

`match (n) where split(n.id, ':')[0]="HGNC" return count(n)`
`KG2.5.2` count(n) | `KG2.6.0` count(n) | difference
--|--|--
41675|41111|564
