### ISSUE TITLE
Refactor reasoning code for new KG

### ISSUE THREAD

**Issue by dkoslicki** [RTXteam/RTX#119]
@saramsey As we discussed on the Monday call, let's begin the process of updating the code for the new KG and get ready to push it to production. To get started, I will need:
1. db location of the new KG (eg. ``rtx.ncats.io:7474/db/data``)
2. bolt location of the new KG (eg. ``rtx.ncats.io:7687``)
3. Summary of changes (so I can ``sed`` replace the code)

**Comment by saramsey** [comment]
Hi David,

OK, per your request in GitHub #119, I have installed the current KG in 

/mnt/data/rtxdev

on rtx.ncats.io (see screen capture below; we now have 85,511 nodes in the KG and five million relationships). This Neo4j database is served by the Neo4j server in the “DEV” docker container.  From the *outside* of the instance, you can access it at:

http://rtx.ncats.io:7574

from the web browser, make **SURE** to override the bolt port number and specify 7787 (else you will get the production database).

From the standpoint of your code running inside the DEV docker container, you can access the database like this:

	http://localhost:7474
	bolt://localhost:7687

(note that we use “7687” from inside the Docker container).

As for the KG schema, I have no new updates since the last batch of sed commands that I sent to you.

Steve

![screen shot 2018-05-08 at 2 09 06 pm](https://user-images.githubusercontent.com/5562107/39783560-59fe1f4a-52ca-11e8-8278-e46a49428408.png)
![screen shot 2018-05-08 at 2 04 42 pm](https://user-images.githubusercontent.com/5562107/39783561-5a12cb98-52ca-11e8-9863-618338cd5e00.png)

**Comment by dkoslicki** [comment]
Problem on Q5:
```python
python3 QuestionAnsweringTestSuite.py -q Q5 -p /home/dkoslicki/Dropbox/Repositories/RTX/VE3/bin/python3 -r /dev/fd/0
ERROR on question: what are the phenotypes of the disease adult medulloblastoma
The most similar question I can answer is: what are the phenotypes of the disease $disease But I found: "Multiple terms found for disease: ['DOID:3864', 'DOID:4']"
multiple_terms
```

**Comment by dkoslicki** [comment]
Q12 tested and fixed. Resuming tests this afternoon.

**Comment by dkoslicki** [comment]
All questions passing
