### ISSUE TITLE
SmartAPI registered endpoint returning error

### ISSUE THREAD

**Issue by MarkDWilliams** [RTXteam/RTX#1191]
When I try to run the example query provided in the SmartAPI documentation, it seems to return an error.  Am I making a user error, or is there an issue with the service/registered metadata?

https://smart-api.info/ui/fd006b0be2774dde2dca18dd9d1005cd#/query/query

**Comment by edeutsch** [comment]
It looks like this is because the example values for Message are missing, I think? Will fix try to fix this.

**Comment by edeutsch** [comment]
@MarkDWilliams I've tried to puzzle through this but don't really have it working.
- I refreshed the schema at SmartAPI to the latest, so that's fine
- If you go to our site https://arax.ncats.io/devED/api/arax/v1.0/ui/#/query/query and [Try it out] and [Execute], it works fine
- But if you go to the SmartAPI site https://smart-api.info/ui/fd006b0be2774dde2dca18dd9d1005cd#/query/query and [Try it out] and [Execute], it fails. the most immediate cause is apparently because this page is using this as the request URL: https://smart-api.info/devED/api/arax/v1.0/query?bypass_cache=false . This is obviously not the right hostname. In our JSON definition, it clearly defines our server, not that one. So I am at a loss here. I think this is a question for a SmartAPI expert. It is working for others?

**Comment by edeutsch** [comment]
hmm, I tried a few more things and I think I understand the problem but not how to fix it. Although our input YAML defines the hostname, the output JSON that SmartAPI slurps in has the hostname neatly excised. Why is that?? the input YAML is:
servers:
- url: https://arax.ncats.io/devED/api/arax/v1.0
but then the output JSON is:
"servers": [ {"url":"/devED/api/arax/v1.0" } ]

It is not clear how to fix that at the moment. Ideas welcome. Will keep fussing with it.

**Comment by edeutsch** [comment]
Well, after a truly horrifying hack in connexion/apis/flask_api.py I think I have it working. @MarkDWilliams Let me know if it works for you now. I will surely be arrested for this.

**Comment by MarkDWilliams** [comment]
Don't worry, I'm no snitch haha.  Everything looks good on my end.  Thanks for looking in on this.  Side note, not sure on git etiquette.  Issue appears to be resolved as far as I'm concerned, but I don't know if it's proper to Close with comment on someone else's repo.

**Comment by edeutsch** [comment]
Far be it for me to advise on etiquette, but it seems like a good practice for the issue opener to close it when the issue is resolved to their satisfaction.

**Comment by MarkDWilliams** [comment]
Sounds good; closing the ticket.  Thank you for the assistance.
