### ISSUE TITLE
connect diseases to Gene Ontology terms

### ISSUE THREAD

**Issue by saramsey** [RTXteam/RTX#122]
this supersedes #75

**Comment by saramsey** [comment]
From Chris Mungall (this was very helpful!): 

> We have curated linkages between MONDO and GO. These are generally conservative and "obvious". See https://github.com/biolink/biolink-api/issues/177 for methods to fetch these (basically with scigraph or direct neo4j you have to traverse the is-a yourself, is that true everyone?)
> 
> Note: it's of course possible to use other statistical methods to derive likely associations, but these yield a lot of noise

**Comment by saramsey** [comment]
Update:  I am generating (on rtxsteve.saramsey.org) a new KG that includes the entire Gene Ontology and including disease->GO links per the request by @dkoslicki .

**Comment by dkoslicki** [comment]
@saramsey So I see diseases now have outgoing edges to cellular_component, but there are no outgoing edges from cellular_component to non-cellular component. Does the KS you're using for this include any out-going relationships cellular_process --> non_cellular_process?

**Comment by dkoslicki** [comment]
i.e. the following returns nothing:
```
match (n:cellular_component)-[r]->(t) where t:protein or t:pathway or t:disease or t:microRNA or t:anatomical_entity or t:chemical_substance or t:molecular_function or t:phenotypic_feature return distinct type(r) limit 10
```

**Comment by saramsey** [comment]
Why does the edge direction matter?  I understood that you are not doing subgraph discovery on the directed KG but rather on the un-directed KG

I am generating a bunch more edges from protein->cellular_component, in any event.  But there is no situation in which I envision there being an outgoing edge from cellular component.

**Comment by saramsey** [comment]
I'll make a stronger statement. Edge direction must be interpreted with care. For many (probably most) directed predicate types, it doesn't imply direction of causation.

**Comment by dkoslicki** [comment]
Yeah, my question was probably imprecise. I was attempting to come up with a solution to the following: Since cellular_component is an ontology (right?), there aren't any undirected paths (:disease)-[]-(:cellular_component)-[]-(:disease), they all look like (:disease)-[]-(:cellular_component)-[:subclass_of]*repeat n>2 times - (:disease). For example, looking at myopathy, the shortest way I can connect it to another disease through cellular_component is via 4 hops:
![cellular_component_myopathy](https://user-images.githubusercontent.com/6362936/39951031-f722b69c-553a-11e8-87c5-0469c03fb478.png)
I was hoping there was a way I could "leave the cellular component ontology more quickly". Hence my desire for other edge types to/from cellular component nodes.

**Comment by dkoslicki** [comment]
And your comments about edge direction are well taken. Pretty much nowhere in the code do I take edge direction into consideration.

**Comment by saramsey** [comment]
![screen shot 2018-05-21 at 2 45 16 pm](https://user-images.githubusercontent.com/5562107/40331543-98fc3d22-5d05-11e8-9c96-7cc935bac477.png)
