### ISSUE TITLE
How to decide which KP to expand?

### ISSUE THREAD

**Issue by edeutsch** [RTXteam/RTX#1236]
We mused about this before, but it seems like it is becoming more and more relevant.
A flaw in the current QueryGraphInterpreter setup is that it doesn't have intelligence to decide which KP to expand on. So it always says KG2.
But I'm thinking we should set the QueryGraphInterpreter YAML to NOT specify which KP, and then let Expand decide on a edge-by-edge basis which KPs it will hit. Based on an internal /predicates like map of all our KPs.

Can Expand essentially already do that? Or close? Or should QGI do this step?

**Comment by amykglen** [comment]
yeah, totally agree we need some sort of map that dictates what kind of qedge should be sent to which KP. and I like the idea of having `expand` be the one to decide which KP to use. it's not set up to do that already, though I don't think it would be too complicated.

maybe this map could be compiled in an automated fashion based on all our KPs' `/predicates` endpoints? or perhaps we'd want to do some tailoring of it?

**Comment by dkoslicki** [comment]
Yeah, hopefully the `/predicates` endpoint will help. One thing to note: there will be multiple KPs that can fulfill the same predicate. I would vote for hitting _all_ endpoints that can handle that predicate, and uniquifying results after that (based on curies or the like).

**Comment by amykglen** [comment]
@edeutsch - here's what I've got for external KP APIs:
```
{
        "GeneticsKP": "https://translator.broadinstitute.org/genetics_data_provider",
        "MolePro": "https://translator.broadinstitute.org/molepro/trapi/v1.0",
        "BTE": "https://api.bte.ncats.io/v1"
}
```
the only other one we might want is COHD - I think the the COHD expand submodule doesn't hit up any API, but maybe using their /predicates endpoint would still be of use? I'm not familiar enough with `COHDQuerier` to know off the top of my head (i.e., can it answer queries for everything COHD itself can? do we invent our own edge types or use the ones COHD does? not sure.. @dkoslicki / @chunyuma?)

**Comment by amykglen** [comment]
first step for this could be to add a method to `expand` that takes in a one-hop query graph and returns a list of all the KPs capable of answering it (according to info in the KPs' `/predicates` endpoint - maybe precomputed and combined into one big internal map, as Eric suggested)

then tweaking `expand` to loop through this list of KPs and ask each to answer the given one-hop QG should be pretty straightforward.

we could try this out and see how time-intensive queries end up being, and go from there

**Comment by dkoslicki** [comment]
And we may need to make a decision about whether we hit all KPs that can satisfy a one hop query, or just one of them (in some prioritized list?). I lean towards hitting all KPs that can satisfy a query

**Comment by amykglen** [comment]
tagging @kvarforl here as she's going to help with this one :)

**Comment by dkoslicki** [comment]
And just a note about how this will be useful: during the standup call today (3/19), Mark used the following query:
```
{
  "edges": {
    "N1": {
      "object": "n1",
      "predicate": "biolink:has_normalized_google_distance_with",
      "relation": "N1",
      "subject": "n0"
    },
    "e01": {
      "object": "n1",
      "predicate": [
        "biolink:correlated_with"
      ],
      "subject": "n0"
    }
  },
  "nodes": {
    "n0": {
      "category": [
        "biolink:Disease"
      ],
      "id": [
        "MONDO:0004979"
      ],
      "is_set": false
    },
    "n1": {
      "category": [
        "biolink:ChemicalSubstance"
      ],
      "is_set": false
    }
  }
}
```
This was meant to test integration with ICEES and COHD since they mainly have the `corellated_with` predicate. Thankfully, monarch has that predicate too, since we didn’t actually hit ICEES or COHD for this call but did get a few results.

**Comment by kvarforl** [comment]
Excited to help! Here are my thoughts as to how to go about this (with questions intermixed 😄 ). Posting as a reference for chatting with amy (no action required from others)

- first, I don't know how to query the `/predicates` endpoint of the kps. is there an example somewhere?
  - after this, construct a large internal map will look something like `{“predicate_triple” : [kp, kp, kp]}`. or perhaps `{kp: set(available_predicate_triples)}` would be better?
- Add a method as amy suggested that takes in a one-hop query graph and returns a list of all the KPs capable of answering it
- perhaps store in a local dictionary `qedge_to_kp_map = {“qedge_key”: [kp, kp, kp]}` ?
- Then adjust the code around  https://github.com/RTXteam/RTX/blob/2300b9f9e985cd6ccbf127a195bcd73544e54fdc/code/ARAX/ARAXQuery/ARAX_expander.py#L318  to also iterate through `qedge_to_kp_map` and  change `kp_to_use` accordingly.

**Comment by kvarforl** [comment]
Okay, I've taken a stab at this! 

As of now, I didn't do any precomputing of the predicates responses, and I also didn't reformat them (not super sure why I thought reformatting them was neccessary in my previous comment, haha). If we do find that the API call is too slow, we could just store the predicates responses in a map and it would be easy to iterate through that instead.
I also haven't addressed the KPs that don't have predicates endpoints yet.

I'm sure this could be optimized, but you've gotta walk before you can run sometimes 😅 

Please also note that this is horrifyingly untested, as my dev environment is not at all set up. Perhaps @amykglen and I can meet up later in the week to go over it?

**Comment by amykglen** [comment]
thanks so much @kvarforl! this is awesome. re: your question here:
https://github.com/RTXteam/RTX/blob/85bf82b41194659dca59f37b58735ee9cd053d02/code/ARAX/ARAXQuery/ARAX_expander.py#L1004-L1005
I think you could get this from the class variable `self.command_definitions` (the keys in that dictionary are all of the KPs `expand` can use):
https://github.com/RTXteam/RTX/blob/85bf82b41194659dca59f37b58735ee9cd053d02/code/ARAX/ARAXQuery/ARAX_expander.py#L68-L83
(this is what I've been trying to use as the 'master' list of KPs)

**Comment by kvarforl** [comment]
@amykglen woo! Thanks for your help, I'll make this change soon.

Things left to do/fix:

- Add faux predicate endpoints for non-api kps that we use
- Handle QGs with no categories specified and/or no predicates specified

**Comment by kvarforl** [comment]
Okay, I added an attempt at handling QG's where the subject list, object list, and/or predicate list (and hopefully any combination thereof) is empty.

Basically, if the subject list is empty, it gets set to be all possible subjects from the predicates response. Same thing for objects. For predicates, I just added a boolean called `any_predicate` that is True if no predicates are specified, and False otherwise.

@amykglen would you mind helping me test again? something in my environment still isn't set up correctly; I get an error when trying to run the expand tests. :)

**Comment by amykglen** [comment]
nice, it's looking good from my end! (and sorry about your environment, hah 😅 I can help with that) for some reason `requests` was producing stale data (still with the `biolink:biolink` issue), but switching to `urllib.request` fixed that for whatever reason, so I pushed that change... 

it seems like the empty category/predicate handling is working pretty well, although I suppose one more complicating factor is that not all KPs will answer queries where no categories and/or predicates are specified. I've tried to keep a record of who will answer what in that regard [here](https://github.com/RTXteam/RTX/blob/master/code/ARAX/ARAXQuery/Expand/expand_utilities.py#L243-L258) (since it isn't captured in TRAPI anywhere). so maybe we'll need to inspect that as well? as right now, for example, the method says that GeneticsKP can answer queries involving None categories, but it actually won't respond with anything if you were to send such a query graph to it (so this is resulting in an error currently).

@edeutsch - just want to make sure it's correct that TRAPI doesn't provide a place to indicate whether a KP can accept None for `QNode.category` or `QEdge.predicate`? and are there any changes coming related to this in TRAPI 1.1?

**Comment by edeutsch** [comment]
> nice, it's looking good from my end! (and sorry about your environment, hah 😅 I can help with that) for some reason requests was producing stale data (still with the biolink:biolink issue), but switching to urllib.request fixed that for whatever reason, so I pushed that change...

#1328 ?!

**Comment by edeutsch** [comment]
> edeutsch - just want to make sure it's correct that TRAPI doesn't provide a place to indicate whether a KP can accept None for QNode.category or QEdge.predicate? and are there any changes coming related to this in TRAPI 1.1?

This is correct. But this is a very good point, and I will bring this in front of the TRAPI WG tomorrow and beyond so that we can sort this out.

**Comment by amykglen** [comment]
@kvarforl - I also started creating a new ['Director' class](https://github.com/RTXteam/RTX/blob/issue1236/code/ARAX/ARAXQuery/Expand/director.py) in Expand that I think we should probably move your work into (there was some discussion today about this issue at the mini-hackathon and it seems like having a separate class here is a good way to go). the general idea is that this class has a couple primary methods:
1. one for creating its giant meta map of all of the KPs' `predicates/` info (which should be cached in some fashion, and periodically automatically updated)
2. and another that takes in a single-hop query graph and uses the precomputed meta map to figure out which KPs can answer it

I left some TODOs in there where I think your work would go in - feel free to move it over there whenever. :)

**Comment by amykglen** [comment]
> This is correct. But this is a very good point, and I will bring this in front of the TRAPI WG tomorrow and beyond so that we can sort this out.

got it. thanks!

> #1328 ?!

hah, yeah, I was suspicious of that too - maybe there's a smart way to get past that problem but in this case I thought it seemed easier to just switch libraries!

**Comment by kvarforl** [comment]
Okay, I moved the functions over to the director class!

I also added endpoints for COHD and CHP to the map in `expand_utilities.py`: https://github.com/RTXteam/RTX/blob/20d4bbc03d9a42b1c84ade36b11f6dd39d17eb8d/code/ARAX/ARAXQuery/Expand/expand_utilities.py#L407-L416

Both have `/predicates` endpoints, so I figured we should use them. @amykglen will this cause problems elsewhere in the code? 

This leaves hardcoding of predicates info for DTD and NGD. I assumed we would ignore KG1 in hopes that we can phase it all the way out soon.

For NGD, I was thinking we could just use KG2's predicates info since (i think!) that database is built off of KG2? but I'm not wholly sure that's how that works, so someone better informed should let me know :)

**Comment by kvarforl** [comment]
@dkoslicki What predicate triples does DTD accept? If there is a faux predicates endpoint somewhere, can you point me to it? If not, a list of accepted triples would be very helpful :)

**Comment by dkoslicki** [comment]
@kvarforl There is no endpoint since it's an in-house tool. The predicates it accepts are `biolink:treats` and `biolink:treated_by`

**Comment by kvarforl** [comment]
@dkoslicki thanks!! What node categories does it accept for subjects? (My guess is Drug and ChemicalSubstance, but not sure)
 What about node categories for objects? Just Disease?

**Comment by amykglen** [comment]
> For NGD, I was thinking we could just use KG2's predicates info since (i think!) that database is built off of KG2? but I'm not wholly sure that's how that works, so someone better informed should let me know :)

@kvarforl - yep, I think that makes a ton of sense for NGD!

and everything else in your [comment](https://github.com/RTXteam/RTX/issues/1236#issuecomment-813567422) makes sense to me too. thanks!

**Comment by edeutsch** [comment]
> > For NGD, I was thinking we could just use KG2's predicates info since (i think!) that database is built off of KG2? but I'm not wholly sure that's how that works, so someone better informed should let me know :)
> 
> @kvarforl - yep, I think that makes a ton of sense for NGD!
> 
> and everything else in your [comment](https://github.com/RTXteam/RTX/issues/1236#issuecomment-813567422) makes sense to me too. thanks!

I probably should know about this, but I confess I don't: are we now able to Expand based purely on NGD? Is there a database of pre-computed top relationships? I recall we mused about this like a year ago, but I don't recall how it ended up. I would think all the predicates in NGD expansion would be just something bland like "associated_with" if not our made-up "biolink:has_normalized_google_distance_with"

**Comment by amykglen** [comment]
> I probably should know about this, but I confess I don't: are we now able to Expand based purely on NGD? Is there a database of pre-computed top relationships? I recall we mused about this like a year ago, but I don't recall how it ended up. I would think all the predicates in NGD expansion would be just something bland like "associated_with" if not our made-up "biolink:has_normalized_google_distance_with"

ah, that's true, I forgot that the only accepted predicate should be some simple thing like you suggest. but the accepted node categories will be the same as for KG2. 

yeah, we can expand using ngd (in some capacity) - the issue for that was #975. it doesn't use a database of pre-computed relationships at the moment; it's currently limited to connections in KG2. so it first looks for neighbors of the input node in KG2, and then computes ngd between that node and all its neighbors, and drops those with an NGD worse than a particular value.

**Comment by kvarforl** [comment]
> > I probably should know about this, but I confess I don't: are we now able to Expand based purely on NGD? Is there a database of pre-computed top relationships? I recall we mused about this like a year ago, but I don't recall how it ended up. I would think all the predicates in NGD expansion would be just something bland like "associated_with" if not our made-up "biolink:has_normalized_google_distance_with"
> 
> ah, that's true, I forgot that the only accepted predicate should be some simple thing like you suggest. but the accepted node categories will be the same as for KG2.

Just for extra confirmation: the "predicates" map  for NGD should have all possible subject categories and object categories from KG2C predicates response, and then `biolink:related_to` for the actual predicate?

**Comment by amykglen** [comment]
yeah, I think that's right about the subject/object categories, and I think maybe a discussion needs to be had about what predicates it should accept. I'd say for now, as a placeholder, we could say it accepts either `biolink:has_normalized_google_distance_with` or no predicate (for all subject/object combinations).

**Comment by amykglen** [comment]
@dkoslicki / @chunyuma: does this look like an accurate representation of what DTD's `/predicates` info should look like?
```
{
  "biolink:Drug":{
    "biolink:Disease":[
      "biolink:treats",
      "biolink:treated_by"
    ],
    "biolink:PhenotypicFeature":[
      "biolink:treats",
      "biolink:treated_by"
    ],
    "biolink:DiseaseOrPhenotypicFeature":[
      "biolink:treats",
      "biolink:treated_by"
    ]
  },
  "biolink:ChemicalSubstance":{
    "biolink:Disease":[
      "biolink:treats",
      "biolink:treated_by"
    ],
    "biolink:PhenotypicFeature":[
      "biolink:treats",
      "biolink:treated_by"
    ],
    "biolink:DiseaseOrPhenotypicFeature":[
      "biolink:treats",
      "biolink:treated_by"
    ]
  },
  "biolink:Disease":{
    "biolink:Drug":[
      "biolink:treats",
      "biolink:treated_by"
    ],
    "biolink:ChemicalSubstance":[
      "biolink:treats",
      "biolink:treated_by"
    ]
  },
  "biolink:PhenotypicFeature":{
    "biolink:Drug":[
      "biolink:treats",
      "biolink:treated_by"
    ],
    "biolink:ChemicalSubstance":[
      "biolink:treats",
      "biolink:treated_by"
    ]
  },
  "biolink:DiseaseOrPhenotypicFeature":{
    "biolink:Drug":[
      "biolink:treats",
      "biolink:treated_by"
    ],
    "biolink:ChemicalSubstance":[
      "biolink:treats",
      "biolink:treated_by"
    ]
  }
}

```

**Comment by chunyuma** [comment]
@amykglen, I think these DTD's predicates info are correct for me.

**Comment by amykglen** [comment]
@chunyuma - can CHP Expand and COHD Expand answer all the kinds of queries specified at their `/predicates` endpoints?

CHP: http://chp.thayer.dartmouth.edu/predicates/
COHD: http://tr-kp-clinical.ncats.io/api/predicates

**Comment by chunyuma** [comment]
Hi @amykglen,

For CHP, CHP expander can only answer `biolink:Gene-biolink:pairs_with-biolink:Drug` or `biolink:Drug-biolink:pairs_with-biolink:Gene` because CHP client currently can only answer one `biolink:Disease` which is `MONDO:0007254` and one `biolink:PhenotypicFeature` which is `EFO:0008007`. So they are default setting.

For COHD, COHD expander can only answer all predicates except for the predicates associated with `biolink:PopulationOfIndividualOrganisms` and `biolink:Procedure`

**Comment by amykglen** [comment]
got it - thanks @chunyuma!

ok, just merged changes for this issue into `master`. big thanks to @kvarforl for her help here! 🥳 

summary of how the preliminary system works is:
* if you don't tell expand which KP to use, it will select some KPs itself (all 8 of our KPs - local and API - are candidates)
* it creates/maintains its own local `meta_map.json` file with info from all KPs' `/predicates` endpoints (upon running a query, if the file hasn't been updated for >=24 hours, it goes through and refreshes it. this doesn't take long at all.)
* it uses that file to figure out who's capable of answering a given one-hop query (and also does a little bit more filtering on top of that; like considering who can support batch queries)
* it hits up all the selected KPs in parallel and will timeout (and log a warning) in a somewhat intelligent way if a KP is taking too long

this is more of a starting place - plenty that could be improved upon and we'll surely need to 'fine-tune' the heuristics for choosing KPs as we start to see what's working best, but should at least be better than what we currently do! (and hopefully doesn't slow things down _too_ much, due to the relatively strict timeouts and parallelism. 🙂)

**Comment by edeutsch** [comment]
The latest `master` is rolled out to test. (not other deployment)
All tests pass. Example works on UI.
Try some additional tests.
If we're all happy, I can roll out to all deployments

**Comment by edeutsch** [comment]
hmm, I wonder if it could some weird interaction between threads and multiprocessing? During active GUI queries there are two active threads. Where in the code is that red arrow?

**Comment by amykglen** [comment]
it corresponds to this:

https://github.com/RTXteam/RTX/blob/ea2658f05b63a1fd23d7f5a7c78ff063ebae6fef/code/ARAX/ARAXQuery/ARAX_expander.py#L346-L349

(so basically the `expand_edge()` function)

**Comment by amykglen** [comment]
ok, believe I figured out the missing log messages thing (fix is in `master`). it was just that processes were being given _copies_ of Expand's main `response` object (duh), but I wasn't merging them into the main `response` upon completion. (so I guess the 'real-time' log messages in the UI won't be quite real-time during this part of expand, unfortunately... unless I got fancy and figured out how to share state between processes, or switched to `threading` and use locks I guess..)

as for why the live stream of messages when running `pytest -v -s` _does_ include all of the child process messages anyway as they're happening, that seems quite mysterious/magical to me (but very nice).

**Comment by edeutsch** [comment]
terrific! I thought about that but discounted it. I always have to go through great contortions to deepcopy such things for that to happen, I didn't think it could possibly do that on its own. Do you suppose it is the "[ ] for" construction that does that or the multiprocessing part that does the deepcopies?

**Comment by amykglen** [comment]
hah, yeah, I think `multiprocessing` copies everything: https://stackoverflow.com/a/5983362

**Comment by edeutsch** [comment]
ah yeah, I shoulda known that. thanks for the link. So now you just do the response merge at the end I assume. I suppose to achieve real-time updates you'd need to switch to threading as you say, but that is a lot more complex. But fun when you finally get it to work.

**Comment by amykglen** [comment]
this is seeming pretty stable in testing on production - figuring it makes sense to close this issue and write up any improvements/tweaks in separate issues as they arise? will close, but if anyone objects, feel free to reopen..
