### ISSUE TITLE
Drug, but DTD model doesn’t think so

### ISSUE THREAD

**Issue by dkoslicki** [RTXteam/RTX#1240]
For umls:C1171279 (Neulasta, a drug), the synonymizer says it’s a `molecular_entity,drug`, but the DTD model errors out saying it’s not a drug. Don’t know if this is a DTD problem or a node synonymizer problem, so tagging @chunyuma, @amykglen, and @edeutsch .

**Comment by chunyuma** [comment]
The DTD model is built based on the canonical node type. Even though it might have other types belong to `drug`, the DTD model will not consider it as `drug`.

**Comment by dkoslicki** [comment]
Ah, I see. Let’s make a note in the future to have the DTD model work on any node that has a synonym that is drug. That way, actual drugs like Neulasta will have predictions for them. I’ll close this issue, but let’s make sure the next iteration of the model does this.

**Comment by chunyuma** [comment]
I'll reopen this question because I'm rebuilding the DTD model based on KG2.5.1C. Since it is quite time-consuming for rebuilding the DTD model and the DTD database, we have to make a final decision how to process this problem before I start to rebuild anything. 

We have to have a thorough discussion If we need to include any nodes that has a synonym that is drug. How actual this will be? This is also associated with training data collection. umls:C1171279 (Neulasta, a drug) might be a specific case. I hope we can also investigate if other nodes that have `drug` or `chemicalsubstance` are really a drug.

**Comment by chunyuma** [comment]
I think I have ever asked this question to @edeutsch. @edeutsch said that we can't 100% sure the accuracy. It is not sure then I don't want to include them to introduce the potential biases to the model.

**Comment by chunyuma** [comment]
In the version of KG2.5.1c, by using DSL `match (n:`biolink:NamedThing`) where "biolink:Drug" in n.all_categories return count(distinct n.id)`, you will find that there are 14700 nodes that have this situation. Please note that in this case, we haven't considered `biolink:ChemicalSubstance` yet.

**Comment by chunyuma** [comment]
I think the main question is that if we consider any nodes having a synonym that is drug are `drug`, then why not NodeSynonymizer moves them to the group with preferred type that is `biolink:Drug`. Perhaps @edeutsch can help to answer this question.

**Comment by edeutsch** [comment]
I don't really know the answer here. The relationships between different nodes and types and very complex. I know the NodeSynonymizer needs to be better. But I'm generally not familiar enough with the various imports into KG2 to know what is considered reliable and what is not. We could probably come up with heuristics that can help categorize thing better.

In this case, if a cluster has an RXNORM: and is classified as a drug, are we pretty sure this is really a drug? SRI Node Normalizer knows nothing about the two CURIEs that are associated with this drug. The UMLS and RXNORM are linked because they share the same name, neither is in SRI Node Normalizer. The reason this group gets called a molecular_entity is just a matter of chance really. Additional rules could be applied to make drug outrank molecular_entity for example.

**Comment by chunyuma** [comment]
OK, based on discussion with @dkoslicki, the current solution for this is that we keep using our previous rule to collect the training data and train the DTD model (only consider the `preferred_type` with `drug` or `chemicalsubstance` and `disease` or `phenotypic_feature` or `diseaseorphenotypic_feature`). But for the `expand(kp=DTD)` which is evaluation, I would let it not check the type of input query nodes. In other words, it will allow to calculate the probability of any two nodes with any types.

For the DTD database (pre-calculating the probability), I can consider any nodes which has a synonym that is `drug` or `chemicalsubstance` as drug and `disease` or `phenotypic_feature` or `diseaseorphenotypic_feature` as disease. But since this will dramatically increase the number of drug and disease, the rebuilding time of DTD database will also be increased (originally we need two weeks, so I guess it might need more than 3 week once we consider more nodes.)
