### ISSUE TITLE
Why does node `UMLS:C0030660`  not have the semantic type?

### ISSUE THREAD

**Issue by saramsey** [RTXteam/RTX#1244]
UMLS CUI nodes are supposed to have their semantic type annotated in the description field, but for some reason, `UMLS:C0030660` does not:
```
{
  "iri": "https://identifiers.org/umls:C0030660",
  "category_label": "disease",
  "deprecated": "False",
  "name": "Pathological process",
  "description": "A biologic function or a process having an abnormal or deleterious effect at the subcellular, cellular, multicellular, or organismal level.; The abnormal mechanisms and forms involved in the dysfunctions of tissues and organs.",
  "provided_by": "identifiers_org_registry:umls",
  "id": "UMLS:C0030660",
  "category": "biolink:Disease",
  "update_date": "2017"
}
```

**Comment by saramsey** [comment]
For some reason, my suspicion immediately goes towards the dictionary merging code

**Comment by ericawood** [comment]
From what I've found so far, the problem is not the dictionary merging code. `UMLS:C0030660` is brought in through MTH and NCI (though it appears that it might also come in with MSH and SNOWMED... more on this later). However, with NCI, it has the ID `NCIT:C16956`. In the nodes part of `multi_ont_to_json_kg.py`, the two are linked and their descriptions are added together. However, the semantic type identifier within the description field isn't added until the edges portion of the code based on a TUI edge. `UMLS:C0030660` (the way it appears in MTH) DOESN'T have a TUI. `NCIT:C16956` DOES have a TUI (log entry edited for clarity):
```
Predicate Curie: UMLS:has_sty
Subject Node: NCIT:C16956
Object Node: UMLS_STY:T046
Subject Description Pre-Line-998: A biologic function or a process having an abnormal or deleterious effect at the subcellular, cellular, multicellular, or organismal level.
Subject Description: A biologic function or a process having an abnormal or deleterious effect at the subcellular, cellular, multicellular, or organismal level.; UMLS Semantic Type:          UMLS_STY:T046
```

I don't have the same thing for `UMLS:C0030660` to show from my debugging log.

These are the same nodes. But, they look different in Neo4j:
```
{
  "iri": "https://identifiers.org/ncit:C16956",
  "category_label": "biological_process",
  "deprecated": "False",
  "name": "Pathologic Process",
  "description": "A biologic function or a process having an abnormal or deleterious effect at the subcellular, cellular, multicellular, or organismal level.; UMLS Semantic Type: UMLS_STY:T046",
  "provided_by": "umls_source:NCI",
  "id": "NCIT:C16956",
  "category": "biolink:BiologicalProcess",
  "update_date": "2019"
}
```

```
{
  "iri": "https://identifiers.org/umls:C0030660",
  "category_label": "disease",
  "deprecated": "False",
  "name": "Pathological process",
  "description": "A biologic function or a process having an abnormal or deleterious effect at the subcellular, cellular, multicellular, or organismal level.; The abnormal mechanisms and forms involved in the dysfunctions of tissues and organs.",
  "provided_by": "identifiers_org_registry:umls",
  "id": "UMLS:C0030660",
  "category": "biolink:Disease",
  "update_date": "2017"
}
```

Quite frankly, I'm unsure how to fix this because it's a problem with the data. Do you have any thoughts @saramsey?

**Comment by saramsey** [comment]
Thank you @ericawood. I'm not sure what else we can do. But I appreciate your looking into this. I am going to close this out as won'tfix.
