### ISSUE TITLE
ETL miRBase

### ISSUE THREAD

**Issue by kvarforl** [RTXteam/RTX#1247]

**Comment by saramsey** [comment]
Thank you @kvarforl

**Comment by ericawood** [comment]
I've started the miRBase ETL. However, on browsing their site, I noticed that, while they claim to do releases about every [6 months](http://mirbase.org/help/FAQs.shtml#How%20often%20do%20you%20update%20miRBase?), they haven't released a new download since 2018 and the release before that was 2015 (check out their FTP, sorted by Last Modified at [ftp://mirbase.org/pub/mirbase/](ftp://mirbase.org/pub/mirbase/)).
@saramsey Is this updated enough for us?

**Comment by saramsey** [comment]
> I've started the miRBase ETL. However, on browsing their site, I noticed that, while they claim to do releases about every [6 months](http://mirbase.org/help/FAQs.shtml#How%20often%20do%20you%20update%20miRBase?), they haven't released a new download since 2018 and the release before that was 2015 (check out their FTP, sorted by Last Modified at ftp://mirbase.org/pub/mirbase/).
> @saramsey Is this updated enough for us?

I think so, assuming (1) there isn't another obvious alternative; (2) the ETL is not too hard.

Thanks for bringing this up.

**Comment by ericawood** [comment]
miRBase appears to be present in `KG2.6.0`:

`match (n) where split(n.id, ':')[0]="miRBase" return count(n)`
![image](https://user-images.githubusercontent.com/36611732/115939305-92acbe00-a452-11eb-8822-49ca77d06642.png)
