### ISSUE TITLE
Some gene curies are missing in KG2.5.1

### ISSUE THREAD

**Issue by chunyuma** [RTXteam/RTX#1260]
Hi @saramsey and @kvarforl,

I'm working on issue #1122 and I found that there a few gene curies provided in Connections Hypothesis Provider (CHP) which don't show up in KG2.5.1. 

Below is the gene list for these missing gene curies:

```
ENSEMBL:ENSG00000254414
ENSEMBL:ENSG00000258941
ENSEMBL:ENSG00000252791
ENSEMBL:ENSG00000187695
ENSEMBL:ENSG00000221961
ENSEMBL:ENSG00000223659
ENSEMBL:ENSG00000263775
ENSEMBL:ENSG00000258838
ENSEMBL:ENSG00000241341
ENSEMBL:ENSG00000269948
```

**Comment by edeutsch** [comment]
a (perhaps) semi-related set of questions that rattle around in my head:
- do all of our nodes in KG2 have at least one edge?
- Do we expect to have *all* members of a set (say ENSG*s) in KG2, or just the ones for which we have edges?
- Would it be useful to have all members of a set of identifiers even if there are no available edges for them?

**Comment by ericawood** [comment]
@chunyuma I searched all of those identifiers on the ENSEMBL website. They have all been retired. Some are now mapped to a different identifier, but not all. I suspect they're not in `KG2.5.1` because it should use the latest version of ENSEMBL.
`ENSEMBL:ENSG00000254414`:
![image](https://user-images.githubusercontent.com/36611732/107733682-718c5c00-6cb0-11eb-84cf-b44660e5fc51.png)

`ENSEMBL:ENSG00000258941`
![image](https://user-images.githubusercontent.com/36611732/107733701-7e10b480-6cb0-11eb-8cbb-9db19a7420a4.png)

`ENSEMBL:ENSG00000252791`:
![image](https://user-images.githubusercontent.com/36611732/107733795-b6b08e00-6cb0-11eb-914d-19b4387389f2.png)

`ENSEMBL:ENSG00000187695`:
![image](https://user-images.githubusercontent.com/36611732/107733818-c92ac780-6cb0-11eb-96e9-4d79019a67c0.png)

`ENSEMBL:ENSG00000221961`:
![image](https://user-images.githubusercontent.com/36611732/107733844-d6e04d00-6cb0-11eb-90bd-31bcc9376e48.png)

`ENSEMBL:ENSG00000223659`:
![image](https://user-images.githubusercontent.com/36611732/107733889-f0819480-6cb0-11eb-962e-223eff4aa8fc.png)

`ENSEMBL:ENSG00000263775`:
![image](https://user-images.githubusercontent.com/36611732/107733914-fecfb080-6cb0-11eb-9a18-af78acd997a5.png)

`ENSEMBL:ENSG00000258838`:
![image](https://user-images.githubusercontent.com/36611732/107733931-0db66300-6cb1-11eb-83ef-b1bbff481a81.png)

`ENSEMBL:ENSG00000241341`:
![image](https://user-images.githubusercontent.com/36611732/107733954-1c9d1580-6cb1-11eb-9f67-19b1c9213dd0.png)

`ENSEMBL:ENSG00000269948`
![image](https://user-images.githubusercontent.com/36611732/107733983-2e7eb880-6cb1-11eb-96c2-b1035753dfee.png)

**Comment by chunyuma** [comment]
Ah, I see. Thanks @ericawood! Perhaps I should contact CHP team to update other data. 

@edeutsch, can I close this issue? Or I should let it open for your questions?

**Comment by edeutsch** [comment]
Fine to close. I will just continue to wonder.
