### ISSUE TITLE
rename the TSV export of KG2 "kg2-tsvs.tar.gz" instead of "kg2-tsvs-medikanren-YYYYMMDD.tar.gz"

### ISSUE THREAD

**Issue by saramsey** [RTXteam/RTX#1262]
This is a partial solution for TranslatorPM issue 52; see RTX issue #1129 for discussion thread and commits related to a more durable and systematic solution.

**Comment by saramsey** [comment]
There is nothing particularly medikanren-specific about the export file format, and having the ISO-8601 date in the filename makes it more problematic to have a durable URL if we are hosting from an S3 bucket. 

This issue also includes removing the ISO-8601 date part of the filename for the "indexes" mediKanren tarball.

**Comment by saramsey** [comment]
Fixing this in the `RTX/code/kg2/mediKanren/README.md` instructions and in the files currently hosted on S3. Since team Unsecret Agent already has URLs pointing to those ISO-8601-named files, I won't touch those, but will copy them. In the future, we'll just host tarballs named generically without the ISO date.

**Comment by kvarforl** [comment]
I'm wondering if this should be reverted to include medikanren in the name again for clarity's sake, since the Kg2 api is live and serves the purpose of making kg2 accessible to other translator teams.

I say this because we have another tsv tarball, called `kg2-tsv-for-neo4j.tar.gz`, that gets pushed to the private S3 bucket, `rtx-kg2`. Since there are different TSV tarballs in more than one place on S3, and since they are in two distinct formats, I think it would be more helpful for people who are joining the team if each tarball was named more specifically.

Thoughts, @saramsey ?

**Comment by saramsey** [comment]
> I'm wondering if this should be reverted to include medikanren in the name again for clarity's sake, since the Kg2 api is live and serves the purpose of making kg2 accessible to other translator teams.
> 
> I say this because we have another tsv tarball, called `kg2-tsv-for-neo4j.tar.gz`, that gets pushed to the private S3 bucket, `rtx-kg2`. Since there are different TSV tarballs in more than one place on S3, and since they are in two distinct formats, I think it would be more helpful for people who are joining the team if each tarball was named more specifically.
> 
> Thoughts, @saramsey ?

Good thinking. We definitely want to disambiguate the two non-equivalent TSV files. Yeah, let's reinstate the "-medikanren" part of the filename (but we are still not putting ISO date in the filename, correct?).
