### ISSUE TITLE
How much similarity reasoning can ARAX do?

### ISSUE THREAD

**Issue by edeutsch** [RTXteam/RTX#1268]
There is a rather nice summary of some basic reasoning that Chris B is proposing that *KPs* do. I'm wondering how much of this can ARAX even do? and how does it do it? Can we document that here? (or elsewhere?)

KPs that implement the Translator Reasoner API must perform the following kinds of reasoning in answering queries:
   1. Making identifiers more specific, e.g. responding to a query involving an entity with information related to a subclass of that entity.
   2. Making categories in a query more specific. e.g. responding to a query for a Named Thing with a particular ChemicalSubstance.
   3. Making predicates more specific, e.g. responding to a query for “affects expression of” with an edge with predicate “increases expression of”.
   4. Inverting predicates. e.g. responding to a query with predicate P with an edge whose predicate is the inverse of P.  

(from PR 28 over at https://github.com/NCATSTranslator/TranslatorArchitecture, intentionally not linked)

**Comment by amykglen** [comment]
an update of what's been done so far here:
1. not done yet
2. this one is done thanks to @edeutsch's `expanded_categories` in the node synonymizer, which are now used as Neo4j node labels in KG2c (these are also now reflected in KG2's `/predicates` endpoint)
3. not done yet
4. this is done and fully functional, although perhaps could see some performance improvements (it currently just parses the biolink model yaml file, but imagine there's a better tool for that.. and perhaps we want to switch to only looking in KG2 for the one from each pair that KG2 decides to use, rather than both..)
    - right now this returns edges _as they are_ in KG2c (doesn't modify them to match the query graph or anything). I like this way better :), but looks like this is being voted on in Architecture, so this may need to be updated at some point.

**Comment by edeutsch** [comment]
this is fantastic! This is a huge ask for everyone and I think we're way ahead of the game here. Thank you!

**Comment by amykglen** [comment]
alright, KP reasoning requirement 3) is now done and working on production.

an example: https://arax.ncats.io/?r=6982. it asks for `biolink:interacts_with` and the results include `biolink:physically_interacts_with` and `biolink:molecularly_interacts_with` edges. (previously this query returned a no results error.)

so that just leaves requirement 4) (subclass_of stuff) - have made good progress on that one, though a little bit of a hurdle there (#1367).

**Comment by edeutsch** [comment]
This is terrific! This will help tremendously in returning more and better results.

One thing I notice in the results linked above: in the first result, there are two biolink:physically_interacts_with edges, from two different sources.

Is it desirable to have two edges of the same predicate?
I suppose the answer is yes if we somehow want to encode attributes that are specific to one source or another.

**Comment by amykglen** [comment]
yeah, edges with the same subject/object/predicate are merged in KG2c (their provided_bys are merged into one list), but in that example, those edges go in different directions (so they have different subjects/objects), so that's why they appear separately...

**Comment by amykglen** [comment]
closing this issue since all four KP reasoning requirements were implemented some time ago
