### ISSUE TITLE
Should we do something about unsightly descriptions?

### ISSUE THREAD

**Issue by edeutsch** [RTXteam/RTX#1300]
It seems like for many nodes, especially UniProtKB, the description field is a dumping ground for a huge about of perhaps machine parsable information. When displayed in the UI, a rather nice definition is often followed by yards of spewage that is less than user-friendly. Should we address this? Should it even go in the description in the first place? Should the UI suppress this ECO code-ridden bit? Should it be parsed into something nicer? Or fine, good enough, leave it?

![image](https://user-images.githubusercontent.com/12707718/111409504-4f617180-8694-11eb-9f98-5dd515a8e6a1.png)

**Comment by saramsey** [comment]
I note that we are already parsing the PMIDs out of the `description` field

<img width="1081" alt="Screen Shot 2021-03-16 at 8 18 11 PM" src="https://user-images.githubusercontent.com/5562107/111409740-c7c83280-8694-11eb-8c8c-8523b3cfd94d.png">

At some point we could probably parse the `CATALYTIC ACTIVITY` section into structured edges and such, but it looks like it will not be easy because they use free-text descriptions like `NADPH--hemoprotein reductase` instead of controlled vocabulary identifiers in the reaction components (logged as #1301, just now).  As for the ECO codes, there is already an issue on this (#647).

**Comment by saramsey** [comment]
I favor trying to pull out specific subsets of structured data from the `description` field as we are able (and as there is motivation) to do so, but not proactively nuking them.

**Comment by isbluis** [comment]
Hi @saramsey .  Yes, this is exactly what I started to do, but have found that there are other delimiters that I should consider -- especially in the case where the description is the result of multiple sources (e.g. UniprotKB, NCBIgene, etc).

So far I have found `-!-` , `;;` (double semi-colons) , and `---` (triple dashes) .  I believe some of these are inserted during ETL.  Do you know if there are others to add to this list?

This does help make it a little more readable (at the often small expense of making the page longer).

To see this in my dev vs current, follow these links, open any result, and click on a node to see the description:
https://arax.ncats.io/devLM/?r=4757  <-- with some parsing
https://arax.ncats.io/?r=4757  <-- current production

As always, any and all suggestions welcome!

**Comment by finnagin** [comment]
Closing as this is no longer an issue. 

query with CYP1A2: https://arax.ncats.io/?r=36231
