### ISSUE TITLE
Generate slim versions of DTD and COHD databases

### ISSUE THREAD

**Issue by finnagin** [RTXteam/RTX#1304]
- [x] Write script to get list of curries used in the test suite for dtd and cohd queries
- [x] Write a script which takes a list of curies and a path to a pre-existing cohd/dtd database and generates a slim version of that database only containing rows including the inputted curies
- [x] Generate the slim databases for KG 2.3.4 and store them in the same directory on arax.ncats.io as the original databases.
- [x] Test that the new slim databases are enough to successfully pass all tests

**Comment by chunyuma** [comment]
Hi @finnagin, I've already generated the slim version for DTD and COHD database for kg2.3.4 and stored them on `/data/orangeboard/databases/KG2.3.4`. 

<img width="768" alt="Screen Shot 2021-03-21 at 8 22 55 PM" src="https://user-images.githubusercontent.com/20031672/111926511-713b6980-8a83-11eb-86b6-18facaf53e65.png">

The script used for generating these databases is [here](https://github.com/RTXteam/RTX/blob/master/code/ARAX/ARAXQuery/Overlay/GraphSage_train/py_scripts/generate_slim_databases.py).

All these slim databases pass all tests in `test_ARAX_expand.py`, `test_ARAX_overlay.py` and `test_ARAX_workflows.py

`.

**Comment by finnagin** [comment]
Awesome, thanks @chunyuma !

Just ran everthing in Travis and it looks like everything is passing except test_DTD_expand_1

I get the following error:
```
2021-03-22T20:03:44.263425 ERROR: [UnknownError] Internal Error encountered connecting to the local graph database file while expanding edges with kp=DTD.

2021-03-22T20:03:44.263446 DEBUG: [] Processing query results for edge e0 by using DTD model

2021-03-22T20:03:44.264505 ERROR: [UncaughtARAXiError] An uncaught error occurred: 'DTDQuerier' object has no attribute 'pred': ['Traceback (most recent call last):\n', 
'  File "/home/travis/build/rtx-travis-tester/RTX/code/ARAX/test/../ARAXQuery/ARAX_query.py", line 592, in execute_processing_plan\n    expander.apply(response, action[\'parameters\'], mode=mode)\n', 
'  File "/home/travis/build/rtx-travis-tester/RTX/code/ARAX/test/../ARAXQuery/ARAX_expander.py", line 342, in apply\n    query_graph, use_synonyms, mode, log)\n', 
'  File "/home/travis/build/rtx-travis-tester/RTX/code/ARAX/test/../ARAXQuery/ARAX_expander.py", line 447, in _expand_edge\n    answer_kg, edge_to_nodes_map = kp_querier.answer_one_hop_query(edge_query_graph)\n', 
'  File "/home/travis/build/rtx-travis-tester/RTX/code/ARAX/test/../ARAXQuery/Expand/DTD_querier.py", line 141, in answer_one_hop_query\n    final_kg, edge_to_nodes_map = self._answer_query_using_DTD_model(query_graph, log)\n', 
'  File "/home/travis/build/rtx-travis-tester/RTX/code/ARAX/test/../ARAXQuery/Expand/DTD_querier.py", line 568, in _answer_query_using_DTD_model\n    probability = self.pred.prob_single(converted_source_curie, converted_target_curie)\n', 
"AttributeError: 'DTDQuerier' object has no attribute 'pred'
"]
```

**Comment by chunyuma** [comment]
Hi @finnagin, it's weird since I just ran it on `master` branch but didn't get this error. Could you please try running it on `master` branch on your side to see if this error still exists? The error you reported doesn't make sense because I just checked the `DTD_querier.py` script and the `DTDQuerier ` should have `pred ` (Please see [here](https://github.com/RTXteam/RTX/blob/4f8503855c36c293ab876572a58b9643a7d948cc/code/ARAX/ARAXQuery/Expand/DTD_querier.py#L93)).

**Comment by finnagin** [comment]
Just tried a git pull and still getting the same error: https://travis-ci.com/github/rtx-travis-tester/RTX/builds/220883293

Looks like something is going wrong when it trys to run that line you linked since that error in the except section is included as well:
```
- 2021-03-23T01:08:46.092559 ERROR: [EOFError] Traceback (most recent call last):

  File "/home/travis/build/rtx-travis-tester/RTX/code/ARAX/test/../ARAXQuery/Expand/DTD_querier.py", line 127, in answer_one_hop_query

    self.pred = predictor(model_file=self.pkl_file, use_prob_db=False)

  File "/home/travis/build/rtx-travis-tester/RTX/code/ARAX/test/../ARAXQuery/Overlay/predictor/predictor.py", line 34, in __init__

    self.model = joblib.load(model_file)

  File "/home/travis/virtualenv/python3.7.6/lib/python3.7/site-packages/joblib/numpy_pickle.py", line 585, in load

    obj = _unpickle(fobj, filename, mmap_mode)

  File "/home/travis/virtualenv/python3.7.6/lib/python3.7/site-packages/joblib/numpy_pickle.py", line 504, in _unpickle

    obj = unpickler.load()

  File "/opt/python/3.7.6/lib/python3.7/pickle.py", line 1086, in load

    raise EOFError

EOFError

  - 2021-03-23T01:08:46.092628 ERROR: [UnknownError] Internal Error encountered connecting to the local LogModel.pkl file while expanding edges with kp=DTD.

  - 2021-03-23T01:08:46.092705 ERROR: [AttributeError] Traceback (most recent call last):

  File "/home/travis/build/rtx-travis-tester/RTX/code/ARAX/test/../ARAXQuery/Expand/DTD_querier.py", line 134, in answer_one_hop_query

    self.pred.import_file(None, graph_database=self.db_file)

AttributeError: 'DTDQuerier' object has no attribute 'pred'
```

I'm going to try and poke around a bit more and see if I can recreate this error locally instead of just on the travis side

**Comment by chunyuma** [comment]
Hi @finnagin, is it ok to close this issue?

**Comment by finnagin** [comment]
Yeah I think so

**Comment by finnagin** [comment]
Reopening to generate new slim databases after the 2.5.2 rollout

**Comment by finnagin** [comment]
@chunyuma I'm going to try and do this myself but I might ask for help if I need it. 

I'm also thinking of slightly changing this script to pull the COHD and DTD file locations from RTXConfiguration and have it do both at once.

**Comment by chunyuma** [comment]
@finnagin, sure, I'm happy to help for this.

Regarding the generation of new slim databases for kg2.5.2, we can simply complete it by running [this](https://github.com/RTXteam/RTX/blob/master/code/ARAX/ARAXQuery/Overlay/GraphSage_train/py_scripts/generate_slim_databases.py) script. But we have to use the correct version of `NodeSynonymizer` [here](https://github.com/RTXteam/RTX/blob/b83b0ca5d978ae9b08042f9b6dc5524ac01051b7/code/ARAX/ARAXQuery/Overlay/GraphSage_train/py_scripts/generate_slim_databases.py#L14).  

A few things about running this script:
1. This script currently has to run twice, separately for DTD and COHD by setting what database you want to run [here](https://github.com/RTXteam/RTX/blob/b83b0ca5d978ae9b08042f9b6dc5524ac01051b7/code/ARAX/ARAXQuery/Overlay/GraphSage_train/py_scripts/generate_slim_databases.py#L17). Also, you have to modify its corresponding input files. 
2. Regarding your thought to pull the COHD and DTD file locations from RTXConfiguration, please notice that currently for the generation of the slim DTD embedding database (`GRAPH_slim.sqlite`), I didn't generate it from `GRAPH.sqlite` but from the `map.txt` and `rel_max.emb.gz`. But these two files have already been removed from the automatic download list since they are not the required files for run ARAX. So if you want to pull the locations from RTXConfiguration, I think we have to modify the script to let `GRAPH_slim.sqlite` be built from `GRAPH.sqlite`.

**Comment by finnagin** [comment]
Oh that makes sense I guess that wouldn't work then. I was just thinking it might make sense to make it as streamlined as possible with the hopes of automating it (or push button) whenever we switch the databases in configv2.json. 

I might running this just for COHD since that is the biggest one and see if that is enough. COHD is already completely updated for 2.5.2 correct?

**Comment by chunyuma** [comment]
@finnagin, it should work for making it as streamlined as possible with automation by just simply do a few modifications for the script. I can try for this.

**Comment by finnagin** [comment]
@chunyuma Yeah that makes sense about not having complete automation since those will be hard-coded in. If you have the bandwidth and already have an idea of how to do it that would be great! Otherwise I can work on it if you don't have time. 

Also, I was thinking one other nice addition would be if instead of the output file name being hard-coded in just take the input file name and replace the `.<file_extention>` with `_slim.<file_extention>` that way it will be updated correctly every time the input file is changed.

**Comment by chunyuma** [comment]
@finnagin, yes, I have an idea for this and can work for it. 

For your new idea, we can have a talk in today's mini-hackathon.

**Comment by chunyuma** [comment]
Hi @finnagin, has this issue been solved? Can I close this issue?

**Comment by finnagin** [comment]
Yes, sorry meant to close this as soon as all the tests were passing. Closing now.
