### ISSUE TITLE
Potential Caching Issue With ARAX/ARS Result Loading

### ISSUE THREAD

**Issue by MarkDWilliams** [RTXteam/RTX#1317]
When loading results from the ARS into the ARAX interface and using a "top-level" PK, meaning one that contains children for each of the registered services' responses, if this is done while the ARS is in a partially done state (e.g. Some, but not all services have responded.  Some services are either still in "Running" state or haven't been invoked yet), it seems that ARAX caches the partially done set of responses with the PK.  After this happens, loading the same PK after it has completed on the ARS side still shows the initial, partially done result set.  Is it possible to change this caching behavior?  Are any changes needed on the ARS side to assist?

Thanks,
Mark

**Comment by isbluis** [comment]
@edeutsch : is this an API caching issue or mine/GUI?

**Comment by edeutsch** [comment]
I originally assumed this was an ARS issue, but after thinking it through, it could well be an ARAX server caching problem. I didn't intentionally cache these, but we have requests_cache enabled for other components in the system, and I'm suspecting that the server is indeed caching these. requests_cache is neat because it intercepts calls to requests and implements caching fairly invisibly. But the downside may be that it caches even when you didn't intend it. I'll try to figure out how to turn off requests caching for a particular class or object. Unless anyone out there already knows?

**Comment by edeutsch** [comment]
@MarkDWilliams I have deployed what I think should be a fix for this, but I don't have a test. Would you test or report if it happens again?
