### ISSUE TITLE
Some KG2-5-2 edges have an invalid predicate of 'biolink:synonym'

### ISSUE THREAD

**Issue by amykglen** [RTXteam/RTX#1345]
thanks to @chunyuma , I noticed that there appear to be about 50,000 edges in KG2-5-2 with the predicate `biolink:synonym`:

```
MATCH p=()-[r:`biolink:synonym`]->() RETURN count(distinct r)
```

but `biolink:synonym` doesn't appear to be a valid predicate according to the biolink model? should these be `biolink:same_as` instead?

**Comment by saramsey** [comment]
I think in some cases it should probably be `biolink:related_to` (see `HASANCESTRO`). Hi @kvarforl can you investigate?

**Comment by saramsey** [comment]
What say you, KG2 team?  do you think we can get this bug squashed before the 2.5.3 build?

**Comment by chunyuma** [comment]
Thanks @amykglen to generate this issue. As @saramsey said, perhaps they should be `biolink:related_to` rather than `biolink:synonym`. 

Here is one example:
I queried `match (n)-[r]-(m) where n.id='RXNORM:1053143' and m.id='RXNORM:8091' and r.predicate='biolink:synonym' return n.id, n.name, m.id, m.name, r.predicate` in kg2.5.2


n.id | n.name | m.id | m.name | r.predicate
-- | -- | -- | -- | --
"RXNORM:1053143" | "Stye" | "RXNORM:8091" | "Petrolatum" | "biolink:synonym"

The petrolatum  seems to be a treatment for stye based on [this](https://www.verywellhealth.com/how-styes-are-treated-5095601) blog rather than synonym .

**Comment by kvarforl** [comment]
Yep! Looking into it now. 
```
MATCH p=()-[r:`biolink:synonym`]->() RETURN distinct r.provided_by, count(*)
```

r.provided_by | count(*)
-- | --
["umls_source:RXNORM"] | 48926
["EFO:efo.owl"] | 9
["OBO:genepio.owl"] | 1

All of the RXNORM ones can be fixed by changing this entry in `predicate-remap.yaml`:https://github.com/RTXteam/RTX/blob/237f8d845ab558e66f5b8fbdb73af88e2f47e5e2/code/kg2/predicate-remap.yaml#L3937-L3940

I'll track the other 10 down as well; pretty sure they can be similarly fixed.

Also noting to myself to check if this snuck past the validation script or if the model just got updated since the last build :)

**Comment by kvarforl** [comment]
Also noting that RXNORM is yet another victim of trying to assign all nodes from a source to one category and not quite succeeding 😢 

Adapted slightly from Chunyu's query:
```
match (n)-[r]-(m) where n.id='RXNORM:1053143' and m.id='RXNORM:8091' and r.predicate='biolink:synonym' return n.id, n.name, n.category, m.id, m.name, m.category
```

n.id | n.name | n.category | m.id | m.name | m.category
-- | -- | -- | -- | -- | --
"RXNORM:1053143" | "Stye" | "biolink:Drug" | "RXNORM:8091" | "Petrolatum" | "biolink:Drug"


has Stye listed as a drug, which I think is likely not super optimal. Tagging @ericawood  so they are aware

**Comment by kvarforl** [comment]
I think for RXNORM I am going to go with `biolink:same_as` for the `has_tradename` relations, based on [this](https://www.nlm.nih.gov/research/umls/rxnorm/sourcereleasedocs/rxnorm.html):
<img width="975" alt="image" src="https://user-images.githubusercontent.com/39020520/113645299-767be500-963b-11eb-80e9-60ace310db2c.png">
Re:Chunyu, I think Stye is the name of an eyedrop brand with the ingredient [petrolatum](https://www.stye.com/stye-sterile-lubricant-eye-ointment#tab3) :)

**Comment by chunyuma** [comment]
Thanks @kvarforl. It makes sense that Style is the name of an eyedrop brand with the ingredient petrolatum. I think the issue might be because the nodesynonymizer clustered it with `MONDO:0005800` which is `biolink:Disease`.

```
{
  "iri": "http://purl.obolibrary.org/obo/MONDO_0005800",
  "expanded_categories": [
    "biolink:BiologicalEntity",
    "biolink:Disease",
    "biolink:DiseaseOrPhenotypicFeature",
    "biolink:NamedThing",
    "biolink:PhenotypicFeature"
  ],
  "name": "hordeolum",
  "description": "An acute, localized swelling of the eyelid that may be external or internal and usually is a pyogenic (typically staphylococcal) infection or abscess.",
  "equivalent_curies": [
    "DOID:9909",
    "EFO:0007315",
    "HP:0010606",
    "MEDDRA:10020377",
    "MEDDRA:10042269",
    "MESH:D006726",
    "MONDO:0005800",
    "NCIT:C118722",
    "RXNORM:1053143",
    "SNOMED:397513003",
    "UMLS:C0019917",
    "UMLS:C2961551",
    "UMLS:C4280376"
  ],
  "id": "MONDO:0005800",
  "category": "biolink:Disease",
  "all_names": [
    "Hordeolum",
    "Stye",
    "hordeolum"
  ],
  "all_categories": [
    "biolink:ChemicalSubstance",
    "biolink:Disease",
    "biolink:Drug",
    "biolink:NamedThing",
    "biolink:PhenotypicFeature"
  ],
  "publications": [
    "http://en.wikipedia.org/wiki/hordeolum",
    "https://www.merckmanuals.com/professional/eye-disorders/eyelid-and-lacrimal-disorders/chalazion-and-hordeolum-stye"
  ]
}
```

So there is a link with `biolink:synonym` between `biolink:Disease` and `biolink:Drug` in kg2c-5-2, which doesn't make sense.



n.id | n.name | m.id | m.name | r.predicate
-- | -- | -- | -- | --
"MONDO:0005800" | "hordeolum" | "CHEMBL.COMPOUND:CHEMBL2108555" | "PETROLATUM" | "biolink:synonym"

**Comment by saramsey** [comment]
> Re:Chunyu, I think Stye is the name of an eyedrop brand with the ingredient [petrolatum](https://www.stye.com/stye-sterile-lubricant-eye-ointment#tab3) :)

Based on looking at this bioontology page
https://bioportal.bioontology.org/ontologies/RXNORM?p=classes&conceptid=1053143

I concur with @kvarforl, though it was reasonable to suppose it *might* represent the ophthalmic condition, "stye". Thank you @chunyuma and @kvarforl for your help!

**Comment by edeutsch** [comment]
Shall I put in an exception? I can forcibly rename RXNORM:1053143 to "Stye ointment" or "Stye(TM)" or something similar and that will prevent the NodeSynonymizer from assuming that Stye the brand name is a stye the malady. Yar?

**Comment by edeutsch** [comment]
(The manual exception is just for NodeSynonymizer purposes, not the KG)

**Comment by chunyuma** [comment]
> Shall I put in an exception? I can forcibly rename RXNORM:1053143 to "Stye ointment" or "Stye(TM)" or something similar and that will prevent the NodeSynonymizer from assuming that Stye the brand name is a stye the malady. Yar?

I would support this method.

**Comment by edeutsch** [comment]
okay, pushed a line to Exceptions.txt to rename it to Stye(TM)
