### ISSUE TITLE
Revisit rule for filling out the ARAX node 'category'?

### ISSUE THREAD

**Issue by amykglen** [RTXteam/RTX#1360]
a while back the group decided that it would be best to set `Node.category` to the same category of the qnode it's fulfilling (if one was provided). this seems reasonable when each qnode has a single category, but now that `QNode.category` can be a list, does this still make sense?

for example, for this query:
```
{
      "edges": {
        "e01": {
          "object": "n1",
          "predicate": ["biolink:treated_by", "biolink:treats"],
          "subject": "n0"
        }
      },
      "nodes": {
        "n0": {
          "category": ["biolink:Disease", "biolink:Drug", "biolink:Pathway"],
          "id": ["OMIM:246300", "DRUGBANK:DB00002"]
        },
        "n1": {
          "category": ["biolink:Drug", "biolink:Disease","biolink:ChemicalSubstance"]
        }
      }
    }
```
the first result contains:
![Screen Shot 2021-04-09 at 1 47 14 PM](https://user-images.githubusercontent.com/49423686/114239137-8563df80-993a-11eb-8f89-4ea5a2f73bee.png)

you can see the category of this node matches the category provided for qnode n1, but I'm not sure that's ideal here. might it be better to just use the 'preferred' category from the syonymizer as the `Node.category`? or maybe the `expanded_categories`?

**Comment by edeutsch** [comment]
Good question, but I don't know. I tried to open a related topic awhile ago:
https://github.com/NCATSTranslator/ReasonerAPI/issues/224
I tried to resolve it with a sensible rule yesterday, but there was substantial pushback (because it's pretty inconsequential, so of course it's a huge controversy).

I would cast my vote as "Until there is some consensus at the Translator level, we probably shouldn't fret about it, because different groups will do it differently. I like setting it to the preferred category is best. But I don't feel strongly. And I don't think it matters much. It is bound to the QNode so there should be no confusion about it even if different than the QNode category(ies). So let's call it what we think it is, irrespective of what the client called it." But that could change if there is ever Translator-wide standardization of this question. I hesitate to bring it up because there will be an hour of squabbling.

**Comment by amykglen** [comment]
ah, I see. yeah, I agree with you - I think using the preferred category would be simplest. and we could adapt later if there were ever standardization on this.

**Comment by amykglen** [comment]
I believe @dkoslicki was a proponent of forcing it to match the qnode.category. would you have concerns if we switched to just using the preferred category, @dkoslicki?

**Comment by finnagin** [comment]
@amykglen @edeutsch is this still relevant?

**Comment by dkoslicki** [comment]
From 9/30 AHM: use the most specific category available (i.e. if I ask for a NamedThing and get back a ChemicalEntity, leave the category as ChemicalEntity, don't substitute NamedThing)

**Comment by amykglen** [comment]
ah, fyi, this issue was why we began forcing categories to match the QG: https://github.com/RTXteam/RTX/issues/987

**Comment by amykglen** [comment]
ok, this has been adjusted in `master` and I verified it's working as expected on arax.ci.transltr.io.

while we agreed we don't want to force `Node.categories` to match `QNode.categories` anymore, I don't think we agreed on precisely what we should put in `Node.categories` going forward instead (e.g., the 'preferred' category according to the synonymizer, the list of all categories for that node, or something else). I made it so that it's essentially the intersection of the node's full categories list with the QNode categories' descendants (and conflations).

so for Calcitonin (Result 3) in our [standard acetaminophen query](https://arax.ci.transltr.io/?r=66276) (`Acetaminophen--physically_interacts_with--Protein`), Node.categories is now:
```
[biolink:Gene, biolink:Protein]
```
vs. if we used only the preferred category it would be:
```
[biolink:BiologicalEntity]
```
or if we used the full category list it would be:
```
[biolink:NamedThing, biolink:ChemicalEntity, biolink:Gene, biolink:BiologicalEntity, biolink:Protein, biolink:MolecularEntity, biolink:Drug, biolink:SmallMolecule]
```

does that seem reasonable to people? (i.e., go with the first approach listed above)
