### ISSUE TITLE
Qnodes distinct, or not?

### ISSUE THREAD

**Issue by dkoslicki** [RTXteam/RTX#1373]
Trying out this query (similar to the one in #1370 , but with intermediate node category pinned to make it run faster):
```
add_qnode(key=N0,id=chembl.compound:CHEMBL787)
add_qnode(key=N1,category=biolink:Protein)
add_qedge(key=E0,subject=N0,object=N1,predicate=biolink:physically_interacts_with)
add_qnode(key=N2,category=biolink:ChemicalSubstance)
add_qedge(key=E2,subject=N1,object=N2)
expand()
overlay(action=compute_ngd,default_value=inf,virtual_relation_label=V1,subject_qnode_key=N0,object_qnode_key=N1)
overlay(action=compute_ngd,default_value=inf,virtual_relation_label=V2,subject_qnode_key=N1,object_qnode_key=N2)
overlay(action=compute_ngd,default_value=inf,virtual_relation_label=V3,subject_qnode_key=N0,object_qnode_key=N2)
overlay(action=compute_jaccard,start_node_key=N0,intermediate_node_key=N1,end_node_key=N2,virtual_relation_label=VJ)
resultify()
filter_results(action=limit_number_of_results,max_results=100,prune_kg=true)
```
I discovered that Qnode N0 and N2 were not necessarily distinct. Take a look at the results https://arax.ncats.io/?r=7176 and note that CHEMBL787 (Montelukast) satisfies both N0 and N2, which introduces the self loops due to the NGD and jaccard between N0 and N2. The point of this query was “find me drugs that target similar proteins to Montelukast” so kind of silly to answer that with Montelukast!

Is there any case where we do want this to happen? Or should we put some logic in `expand` to keep this from happening? I would favor the latter.

Tagging @amykglen @saramsey and @edeutsch in case some/all want to chime in.

**Comment by saramsey** [comment]
Interesting!  Thank you for bringing this up, @dkoslicki.  To the extent that this DSL is supposed to be the ARAXi translation of the user intent "find me drugs that are similar to Montelukast in terms of biomedical literature semantic similarity (pubmed abstract NGD similarity) or target-target protein semantic similarity (bibliographic coupling, Jaccard index), then yes, I agree... returning Montelukast is probably not what the user wanted.

More generally, for any kind of "find stuff that is similar to X" user intent, we probably don't ever want to return X. I mean, X~X (tilde denoting similarity) is kind of axiomatic, right?  (i think it's called something fancy like the "reflexive axiom"?).

**Comment by dkoslicki** [comment]
Exactly, I can't think of a case when a user asks about X and wants to see X returned. Is there some way to make `expand` not allow X to satisfy subsequent qnodes? @amykglen might know

**Comment by amykglen** [comment]
yeah, agree it definitely seems silly to answer a question about X with X. I'm not sure that expand would be the best place to filter out such answers though. for a couple reasons:
1. I don't think we want a _general_ rule that a given node can only fulfill one qnode, because, as one example, in queries like `(n0: disease {DOID:14330})--(n1: protein)--(n2: drug)--(n3: protein)`, there would be proteins that fulfill both qnode n1 _and_ n3, but I think that's desired here. in other words, I think we specifically would only want to filter out answers where the 'target' node of an answer is the same as the 'input' qnode.
2. figuring out what the 'target' node of a query is isn't super easy (or always possible? especially not for `expand`, which may be told to expand an incomplete QG), but I think resultify gives this its best shot when it tries to figure out the 'essence' of a result (i.e., it identifies which qnode in the QG is likely the 'target' qnode.) so maybe resultify should have a rule to throw out results where the 'essence' node is the same as the 'input' qnode's curie? although, figuring out what the 'input' qnode is isn't always easy either (since multiple qnodes can have curies specified), plus things get more complex once we consider the fact that qnodes may (and often do, for the KG2 API) have _lists_ of curies :). maybe this throwing out of results should happen only if one qnode in the QG has a (single) curie specified, and the 'essence' node in a result matches that 'input' qnode's curie? that would resolve the situation @dkoslicki reported but hopefully without resulting in other unintended consequences...

**Comment by amykglen** [comment]
though, thinking about it more, if we decide to say that we don't want DOID:14330 fulfilling n2 in these kinds of queries (not positive if we would or wouldn't want that):
```
(n0: disease {DOID:14330})--(n1: protein)--(n2: disease)--(n3: drug)
(n0: disease {DOID:14330})--(n1: protein)--(n2: phenotypic_feature)--(n3: drug)
```
then maybe we _could_ just have a simple rule in expand where if there's a qnode in the QG with a single curie, then that curie can't fulfill any qnode except that one that it's on.

(so far I haven't thought of any examples other than the ones shown above where this might be detrimental..)

**Comment by dkoslicki** [comment]
@amykglen That’s sort of what I was thinking: if you pin/specify a qnode with a curie (or name), then it shouldn’t satisfy any other qnodes. Eg. In your two examples, if a use really wanted `(n2:disease|phenotypic_feature{DOID:14330})--(n3:drug)` they could just specify that instead of requiring the first hop through a protein. Does that sound reasonable?

**Comment by amykglen** [comment]
ah, nice, hah (I think the title of the issue made me think something more general was being proposed). yep, that seems reasonable enough to me!

and do you think this rule should apply regardless of whether the 'pinned' qnode has a list of curies vs. a single curie? (I'm figuring yes, but just checking..)

**Comment by dkoslicki** [comment]
:) correct: single curie or list of them! If the user put something in/started somewhere, we shouldn't return that as an answer

**Comment by amykglen** [comment]
ok, changes for this are in `master` - will verify on production/test after the next roll out.

**Comment by edeutsch** [comment]
@amykglen latest `master` is now rolled out to all deployments

**Comment by dkoslicki** [comment]
Just tried it out, and apparently it’s still the same, unfortunately: https://arax.ncats.io/?r=7627

**Comment by amykglen** [comment]
huh, very strange - the test I added for this passes and seems valid... ah! it's that I forgot to canonicalize curies in the QG prior to comparing to nodes in the KG...  ok, fix is in `master`.

**Comment by amykglen** [comment]
looks like this is working properly now: https://arax.ncats.io/?r=7781. (no montelukast in the results)

**Comment by dkoslicki** [comment]
Awesome! Looks to be fixed. Closing
