### ISSUE TITLE
Results not displayed in rank order

### ISSUE THREAD

**Issue by dkoslicki** [RTXteam/RTX#1390]
Don't know if this is a UI issue, or a `ranker` issue, but check out the results of https://arax.ncats.io/?r=7546. Note how the 1.0 confidence result is not on the top.

**Comment by edeutsch** [comment]
The UI just displays the results as they come from the server. It does not re-sort them. So I think it is an issue with the ranker. It looks like it is just that the first result is out of order. I'm guessing that it just comes back from the server that way. Maybe a bug in this statement:
```
filter_results(action=sort_by_edge_attribute, edge_attribute=jaccard_index, direction=descending, max_results=15)
```
Hmm, I just ran the DSL again, and the result is a again slightly different. The first row is again out of place:
https://arax.ncats.io/?r=7550

I suspect there is a bug in some final sorting mechanism in ranker?
@finnagin ?

**Comment by finnagin** [comment]
@dkoslicki if I look at the DSL for that query it looks like the last command is to sort by the jaccard index:
```
filter_results(action=sort_by_edge_attribute, edge_attribute=jaccard_index, direction=descending, max_results=15)
```

If you look at the one jaccard index edge connecting Parkinson disease with the drug it looks like it is correctly sorted by the jaccard index. 

However, since confidences are calculated by taking all the scores into account (and not just the jaccard index) they are not matched to this sorting and thus appear out of order.

**Comment by edeutsch** [comment]
ha, of course, I should have seen that!
so, it is operating as designed.

**Comment by finnagin** [comment]
Yeah, I believe so. I don't think filter_results is supposed to overwrite the confidence values in the results when resorting them correct?

**Comment by dkoslicki** [comment]
Ah ha! Clearly I did not read the DSL close enough. I guess this is a non-issue. And correct, `filter` should not touch the confidence values.
