### ISSUE TITLE
concerning number of edges dropped from KG2.6.0?

### ISSUE THREAD

**Issue by kvarforl** [RTXteam/RTX#1400]
Thanks to @ericawood's awesome new script that reports changes in edge numbers between builds, we can be notified when the content of kg2 changes substantially!

Here is the output for KG2.6.0 (keep in mind, we've dropped including KG1)

```
 64 There are no edges from DOID:doid.owl in this build. There were 8799 in the previous build.
 65 There are no edges from GO:go-plus.owl in this build. There were 352059 in the previous build.
 66 There are no edges from GeneProf: in this build. There were 128276 in the previous build.
 67 There are no edges from MyChem: in this build. There were 25955 in the previous build.
 68 There was a significant drop in edges from OBO:mondo.owl in this build. The count dropped from 317034 to 14    0901
 69 There was a significant drop in edges from OBO:nbo.owl in this build. The count dropped from 7402 to 5842
 70 There are no edges from OMIM: in this build. There were 5769 in the previous build.
 71 There are no edges from PC2: in this build. There were 823712 in the previous build.
 72 There are no edges from UMLS_STY: in this build. There were 14604 in the previous build.
 73 There was a significant drop in edges from identifiers_org_registry:chembl.compound in this build. The coun    t dropped from 118197 to 63272
 74 There was a significant drop in edges from identifiers_org_registry:reactome in this build. The count dropp    ed from 845743 to 153717
 75 There was a significant drop in edges from identifiers_org_registry:uniprot in this build. The count droppe    d from 140490 to 96319
 76 There are no edges from miRGate: in this build. There were 336068 in the previous build.
 77 There are no edges from monarch.biolink: in this build. There were 1105698 in the previous build.
 78 There are no edges from monarch.scigraph: in this build. There were 15031 in the previous build.
 79 There are no edges from pharos: in this build. There were 13936 in the previous build.
```

Posting this issue to confirm that none of these were unintended before releasing KG2.6.0.

**Comment by saramsey** [comment]
Hmm, my biggest concern is that we lost `GO:go-plus.owl` edges. That is worth investigating.  Also `DOID:doid.owl`.

The loss of edges from `GeneProf`, `PC2`, `miRGate`, `monarch.biolink`,  `monarch.scigraph`, `MyChem`, and `pharos` is expected.

**Comment by saramsey** [comment]
Oh also, I think we should investigate the big drop in MONDO edges.

**Comment by saramsey** [comment]
Can we look at what node CURIE IDs had the biggest drop in counts, in 2.6.0 vs. 2.5.2?

**Comment by saramsey** [comment]
Thank you for bringing this issue to my attention.

**Comment by saramsey** [comment]
One option to consider, if folks are really clamoring for 2.6.0, is to put KG1 back in, for the 2.6.0 build. Then we could investigate the disappearing-edges syndrome for the 2.6.1 build?

**Comment by kvarforl** [comment]
yep! I was thinking of standing up the graph that we have in neo4j so it's easier to compare / investigate. Just deciding which endpoint to use (I can't recall if kg2.5.0 endpoint is being used for anything important right now; otherwise I'll just step on it)

**Comment by saramsey** [comment]
From this command:
```
ssh ubuntu@araxconfig.rtx.ai
sudo su - araxconfig
cat configv2.json
```
it looks like we are on 2.5.2, right, @amykglen ?

**Comment by kvarforl** [comment]
Great! The build is up at http://kg2endpoint2.rtx.ai:7474/browser/ for debugging: I'll message in slack once I've added the cname and fixed the versioning and identified / addressed any other bugs that pop up :)

**Comment by kvarforl** [comment]
here is a chunky table of the differences in node counts between kg2.5.2 and kg2.6.0:

Kg2.5.2 n.provided_by | kg2.6.0 n.provided_by | Kg2.5.2 count | Kg2.6.0 count | Difference
-- | -- | -- | -- | --
"OMIM:" | - | 9 | 0 | Not present in KG2.6.0
"HP:hp.owl" | - | 2 | 0 | Not present in KG2.6.0
"DOID:doid.owl" | - | 7 | 0 | Not present in KG2.6.0
"UMLS_STY:" | "UMLS_STY:" | 21932 | 129 | -21803
"OBO:mondo.owl" | "OBO:mondo.owl" | 42437 | 21785 | -20652
"OBO:pr.owl" | "OBO:pr.owl" | 295832 | 288104 | -7728
"umls_source:HGNC" | "umls_source:HGNC" | 41665 | 41095 | -570
"identifiers_org_registry:umls" | "identifiers_org_registry:umls" | 3548265 | 3547714 | -551
"identifiers_org_registry:uniprot" | "identifiers_org_registry:uniprot" | 27061 | 26513 | -548
"OBO:cl.owl" | "OBO:cl.owl" | 1048 | 798 | -250
"OBO:uberon/ext.owl" | "OBO:uberon/ext.owl" | 12559 | 12342 | -217
"umls_source:RXNORM" | "umls_source:RXNORM" | 108937 | 108937 | 0
"umls_source:OMIM" | "umls_source:OMIM" | 111589 | 111589 | 0
"umls_source:NDFRT" | "umls_source:NDFRT" | 1 | 1 | 0
"umls_source:NCBITAXON" | "umls_source:NCBITAXON" | 1776515 | 1776515 | 0
"umls_source:LNC" | "umls_source:LNC" | 260727 | 260727 | 0
"umls_source:ICD10CM" | "umls_source:ICD10CM" | 84684 | 84684 | 0
"umls_source:ICD10AE" | "umls_source:ICD10AE" | 1 | 1 | 0
"umls_source:ICD10" | "umls_source:ICD10" | 12319 | 12319 | 0
"umls_source:HCPT" | "umls_source:HCPT" | 44 | 44 | 0
"umls_source:HCPCS" | "umls_source:HCPCS" | 6968 | 6968 | 0
"umls_source:CPT" | "umls_source:CPT" | 14335 | 14335 | 0
"identifiers_org_registry:ttd.target" | "identifiers_org_registry:ttd.target" | 7147 | 7147 | 0
"identifiers_org_registry:smpdb" | "identifiers_org_registry:smpdb" | 110217 | 110217 | 0
"identifiers_org_registry:hmdb" | "identifiers_org_registry:hmdb" | 10001 | 10001 | 0
"identifiers_org_registry:drugbank" | "identifiers_org_registry:drugbank" | 6009 | 6009 | 0
"UNICHEM_source:" | "UNICHEM_source:" | 1 | 1 | 0
"SEMMEDDB:" | "SEMMEDDB:" | 38 | 38 | 0
"RTX:" | "RTX:" | 1 | 1 | 0
"REPODB:" | "REPODB:" | 1 | 1 | 0
"PathWhiz:" | "PathWhiz:" | 373744 | 373744 | 0
"OBO:ddanat.owl" | "OBO:ddanat.owl" | 70 | 70 | 0
"OBO:ehdaa2.owl" | "OBO:ehdaa2.owl" | 2658 | 2659 | 1
"OBO:bspo.owl" | "OBO:bspo.owl" | 169 | 170 | 1
"umls_source:DRUGBANK" | "umls_source:DRUGBANK" | 7560 | 7562 | 2
"umls_source:ICD10PCS" | "umls_source:ICD10PCS" | 189500 | 189503 | 3
"umls_source:ATC" | "umls_source:ATC" | 6332 | 6335 | 3
"umls_source:MED-RT" | "umls_source:MED-RT" | 674 | 680 | 6
"ORPHANET:" | "ORPHANET:" | 8103 | 8109 | 6
"umls_source:NDDF" | "umls_source:NDDF" | 29983 | 29990 | 7
"umls_source:ICD9CM" | "umls_source:ICD9CM" | 22407 | 22414 | 7
"OBO:ro.owl" | "OBO:ro.owl" | 462 | 471 | 9
"OBO:pato.owl" | "OBO:pato.owl" | 2132 | 2142 | 10
"OBO:bfo.owl" | "OBO:bfo.owl" | 36 | 51 | 15
"biolink_download_source:biolink-model.owl.ttl" | "biolink_download_source:biolink-model.owl.ttl" | 737 | 754 | 17
"umls_source:PDQ" | "umls_source:PDQ" | 13321 | 13342 | 21
"OBO:nbo.owl" | "OBO:nbo.owl" | 761 | 782 | 21
"umls_source:VANDF" | "umls_source:VANDF" | 28474 | 28496 | 22
"umls_source:HPO" | "umls_source:HPO" | 14571 | 14593 | 22
"umls_source:MEDLINEPLUS" | "umls_source:MEDLINEPLUS" | 273 | 298 | 25
"umls_source:GO" | "umls_source:GO" | 45007 | 45033 | 26
"OBO:fma.owl" | "OBO:fma.owl" | 563 | 660 | 97
"OBO:ino.owl" | "OBO:ino.owl" | 187 | 295 | 108
"umls_source:MSH" | "umls_source:MSH" | 298353 | 298495 | 142
"OBO:ncbitaxon/subsets/taxslim.owl" | "OBO:ncbitaxon/subsets/taxslim.owl" | 3377 | 3616 | 239
"umls_source:FMA" | "umls_source:FMA" | 104267 | 104529 | 262
"umls_source:MEDDRA" | "umls_source:MEDDRA" | 73629 | 73943 | 314
"identifiers_org_registry:ensembl" | "identifiers_org_registry:ensembl" | 67668 | 67993 | 325
"umls_source:PSY" | "umls_source:PSY" | 7582 | 7969 | 387
"identifiers_org_registry:ncbigene" | "identifiers_org_registry:ncbigene" | 61629 | 62035 | 406
"OBO:hp.owl" | "OBO:hp.owl" | 1544 | 2188 | 644
"OBO:genepio.owl" | "OBO:genepio.owl" | 1268 | 2050 | 782
"OBO:go/extensions/go-plus.owl" | "OBO:go/extensions/go-plus.owl" | 12155 | 12957 | 802
"umls_source:HL7" | "umls_source:HL7" | 5694 | 6594 | 900
"OBO:mi.owl" | "OBO:mi.owl" | 20 | 1485 | 1465
"OBO:foodon.owl" | "OBO:foodon.owl" | 23421 | 24912 | 1491
"umls_source:MTH" | "umls_source:MTH" | 59404 | 61576 | 2172
"umls_source:SNOMEDCT" | "umls_source:SNOMEDCT" | 356874 | 359358 | 2484
"EFO:efo.owl" | "EFO:efo.owl" | 19117 | 22317 | 3200
"OBO:doid.owl" | "OBO:doid.owl" | 6950 | 14356 | 7406
"umls_source:NCI" | "umls_source:NCI" | 137449 | 147265 | 9816
"OBO:chebi.owl" | "OBO:chebi.owl" | 144486 | 156123 | 11637
"identifiers_org_registry:reactome" | "identifiers_org_registry:reactome" | 2215 | 67306 | 65091
"identifiers_org_registry:chembl.compound" | "identifiers_org_registry:chembl.compound" | 1893015 | 1976191 | 83176

I made this using cypher queries and a spreadsheet. a negative number in the difference column means that kg2.6.0 has that many fewer nodes than kg2.5.2

**Comment by edeutsch** [comment]
Nice, thanks!

It is worth annotating some of the major discrepancies for posterity? I find myself wondering why we "lost" half our MONDOs. Probably a good reason, but I wonder if a sentence explaining the the major discrepancies would be useful?

**Comment by kvarforl** [comment]
Yeah I think understanding why is definitely a good move! I'll look into it and report back.

**Comment by ericawood** [comment]
From what I can tell so far, this is actually okay. Those were the `provided_by` fields that changed. However, MONDO, DOID, and go-plus.owl had two different `provided_by` names that were being given to those nodes. See below the examples from the KG1 ETL. Note that those are equivalent to the "missing" edge's `provided_by` names. Then note below, from the report file, how there are still MONDO, DOID, and go-plus.owl edges in KG2.
https://github.com/RTXteam/RTX/blob/b43a8bd920793c2c6cfe7cce19f10ae505ac3171/code/kg2/rtx_kg1_neo4j_to_kg_json.py#L39
https://github.com/RTXteam/RTX/blob/b43a8bd920793c2c6cfe7cce19f10ae505ac3171/code/kg2/rtx_kg1_neo4j_to_kg_json.py#L47
https://github.com/RTXteam/RTX/blob/b43a8bd920793c2c6cfe7cce19f10ae505ac3171/code/kg2/rtx_kg1_neo4j_to_kg_json.py#L54
https://github.com/RTXteam/RTX/blob/b43a8bd920793c2c6cfe7cce19f10ae505ac3171/code/kg2/rtx_kg1_neo4j_to_kg_json.py#L34
https://github.com/RTXteam/RTX/blob/b43a8bd920793c2c6cfe7cce19f10ae505ac3171/code/kg2/rtx_kg1_neo4j_to_kg_json.py#L51

```
      "number_of_edges_by_source": {
          "DGIdb:": 71054,
          "DisGeNET:": 345237,
          "DrugCentral:": 233473,
          "EFO:efo.owl": 104307,
          "JensenLab:": 718090,
          "OBO:bfo.owl": 34,
          "OBO:bspo.owl": 364,
          "OBO:chebi.owl": 290465,
          "OBO:cl.owl": 26728,
          "OBO:ddanat.owl": 351,
          "OBO:doid.owl": 35084,
          "OBO:ehdaa2.owl": 13113,
          "OBO:fma.owl": 119686,
          "OBO:foodon.owl": 37638,
          "OBO:genepio.owl": 7035,
          "OBO:go/extensions/go-plus.owl": 177386,
          "OBO:hp.owl": 45897,
          "OBO:ino.owl": 430,
          "OBO:mi.owl": 1540,
          "OBO:mondo.owl": 140901,
```
Finally, please look to this table for changes in the node prefixes. It is possible that the changes seen in @kvarforl's table (thank you!) above are due to differences in the merge of the `provided_by` field between builds.

Node Prefix|KG2.6.2 Node Count|KG2.6.0 Node Count|Change|
--|--|--|--|
UMLS|3616968|3616859|-109|
CHEMBL.COMPOUND|1879220|1961462|82242|
NCBITaxon|1780643|1780894|251|
SNOMED|359521|359357|-164|
MESH|298547|298494|-53|
LOINC|260726|260726|0|
PR|217574|230226|12652|
ICD10PCS|189502|189502|0|
PathWhiz.Reaction|175039|175039|0|
NCIT|147265|147264|-1|
CHEBI|144488|156110|11622|
OMIM|111699|111589|-110|
PathWhiz|110217|110217|0|
SMPDB|110216|110216|0|
RXNORM|108936|108936|0|
FMA|105189|105189|0|
ICD10|97044|97001|-43|
PathWhiz.Compound|78599|78599|0|
MEDDRA|73942|73942|0|
ENSEMBL|67777|68031|254|
NCBIGene|67008|67414|406|
GO|50336|50541|205|
HGNC|41675|41111|-564|
NDDF|29989|29989|0|
VANDF|28495|28495|0|
UniProtKB|27060|26512|-548|
MONDO|24145|24490|345|
FOODON|22996|23445|449|
ICD9|22413|22413|0|
KEGG|18182|0|-18182|
MGI|16846|16879|33|
AraPort|15919|0|-15919|
HP|15341|16180|839|
UBERON|15281|15468|187|
CPT|14377|14377|0|
ORPHANET|14369|14320|-49|
DRUGBANK|13569|13569|0|
PDQ|13341|13341|0|
DOID|12646|13177|531|
CHEMBL.TARGET|12478|13378|900|
EFO|10977|11261|284|
HMDB|10000|10000|0|
PathWhiz.ProteinComplex|8882|8882|0|
RGD|8114|8146|32|
PSY|7968|7968|0|
ttd.target|7147|7147|0|
HCPCS|6967|6967|0|
ATC|6333|6333|0|
sgd|5938|0|-5938|
GARD|5814|0|-5814|
PomBase|5124|5124|0|
dictybase.gene|4540|4546|6|
wb|4479|4541|62|
ecogene|4018|4045|27|
FBgn|3954|3973|19|
ZFIN|3318|3367|49|
PATO|2792|2807|15|
medgen|2582|0|-2582|
EHDAA2|2473|2473|0|
CL|2438|2520|82|
SO|2435|383|-2052|
REACT|2215|67305|65090|
OBO|1633|2462|829|
OMOP|1590|0|-1590|
MI|1566|1566|0|
CHEMBL.MECHANISM|1316|1350|34|
GENEPIO|1105|1105|0|
NBO|929|929|0|
SYMP|848|847|-1|
GAZ|823|823|0|
biolink|736|753|17|
RO|659|659|0|
OncoTree|556|0|-556|
CGNC|552|551|-1|
ENVO|532|554|22|
OMIMPS|472|0|-472|
PO|456|472|16|
CLO|429|429|0|
PathWhiz.Bound|416|416|0|
PathWhiz.ElementCollection|340|340|0|
HANCESTRO|304|312|8|
EnsemblGenomes|278|351|73|
PathWhiz.NucleicAcid|251|251|0|
OBI|212|211|-1|
BSPO|196|196|0|
UO|180|214|34|
DDANAT|136|136|0|
AEO|135|135|0|
UMLS_STY|128|128|0|
OBA|126|126|0|
MOD|120|126|6|
FBbt|111|111|0|
BTO|78|78|0|
MPATH|77|75|-2|
IAO|76|77|1|
ECTO|63|162|99|
BFO|57|57|0|
EO|52|52|0|
CARO|50|50|0|
ARO|50|50|0|
SEMMEDDB|38|38|0|
IDO|36|36|0|
STATO|36|36|0|
ZFA|35|35|0|
FAO|33|112|79|
TRANS|32|32|0|
umls_source|31|31|0|
OIO|31|31|0|
UBPROP|31|31|0|
OPL|30|30|0|
GENO|25|31|6|
SIO|20|20|0|
OMIT|18|18|0|
dc|15|15|0|
ECO|15|15|0|
MF|13|13|0|
GOREL|12|12|0|
PCO|12|12|0|
CP|9|9|0|
dbpedia|9|9|0|
ECOCORE|9|38|29|
PECO|9|9|0|
CHMO|8|8|0|
ERO|7|7|0|
identifiers_org_registry|7|10|3|
OGMS|6|6|0|
skos|6|6|0|
MFOMD|6|6|0|
doap|5|5|0|
PW|5|5|0|
NPO|4|0|-4|
GEO|4|4|0|
rdfs|3|4|1|
foaf|3|3|0|
BAO|3|3|0|
MP|3|3|0|
ExO|3|5|2|
owl|2|10|8|
dcterms|2|2|0|
OBOREL|2|0|-2|
TO|2|2|0|
MA|2|2|0|
WD|2|0|-2|
EDAM|2|2|0|
VCARD|2|2|0|
biolink_download_source|1|1|0|
UPHENO|1|1|0|
FBdv|1|1|0|
OBAN|1|1|0|
ZEA|1|1|0|
CEPH|1|2|1|
MFOEM|1|1|0|
OGG|1|1|0|
ICO|1|1|0|
MMO|1|1|0|
EPO|1|1|0|
CVDO|1|1|0|
VT|1|1|0|
FIX|1|1|0|
XCO|1|1|0|
OMP|1|1|0|
TypOn|1|1|0|
OMIABIS|1|1|0|
FLU|1|1|0|
OMRSE|1|1|0|
NCRO|1|1|0|
OAE|1|1|0|
UNICHEM_source|1|1|0|
REPODB|1|1|0|
AQTLTrait|1|0|-1|
RTX|1|1|0|
DrugCentral|0|4643|4643|
miRBase|0|1917|1917|
JensenLab|0|1|1|
DisGeNET|0|1|1|

**Comment by saramsey** [comment]
OK, so the big negative is KEGG; we should discuss what to do about that.

Also, OMIMPS; I wonder if "OMIMPS" is for a type of OMIM concept/record, maybe a phenotype or something?

AraPort is for arabidopsis, a plant, and SGD is for yeast; I think we can ignore those. Also I think we can ignore OncoTree.

**Comment by saramsey** [comment]
Wait, should the left column be labeled "2.5.2 count" rather than "2.6.2 count"?

**Comment by kvarforl** [comment]
@saramsey Yes, I think the column was mislabeled! I went ahead and fixed it. Thanks @ericawood for your sluething! 

@saramsey I agree that KEGG is something that we are missing, but I don't think it's necessarily from a mistake in the kg2.6.0 build. shall I press on with the post setup tasks and releasing it, or do we need to somehow add kegg back in and rebuild?

**Comment by kvarforl** [comment]
Thanks to Erica's work, some KEGG nodes are back in KG2.6.1: 
```
match (n) where n.id starts with "KEGG" return count(*)
```
shows that there are 18782 kegg nodes.

**Comment by kvarforl** [comment]
I think this issue has essentially been subsumed by #1421... okay to close?
