### ISSUE TITLE
ARAX failed on tomorrow's standup

### ISSUE THREAD

**Issue by edeutsch** [RTXteam/RTX#1403]
It looks like ARAX failed on tomorrow's standup.
f5f704e4-feb0-43af-ae6d-75905ea35a7c
![image](https://user-images.githubusercontent.com/12707718/115791354-23b16580-a37d-11eb-9c1e-e9f96837b6f9.png)

I'm thinking this is due to our intentional conflation of diseases and phenotypes.
But maybe it's more subtle than that. It would be useful if @amykglen could examine what went wrong with this query:

```
{
  "edges": {
    "e01": {
      "object": "n1",
      "subject": "n0"
    },
    "e02": {
      "object": "n2",
      "subject": "n1"
    }
  },
  "nodes": {
    "n0": {
      "category": "biolink:Disease",
      "id": "MONDO:0005812"
    },
    "n1": {
      "category": "biolink:PhenotypicFeature"
    },
    "n2": {
      "category": "biolink:Disease"
    }
  }
}
```

**Comment by dkoslicki** [comment]
Yeah, I have poked at that quite a bit, and can’t seem to find what’s going wrong. It’s always edge e02, no matter the direction, the identifiers, etc.

**Comment by dkoslicki** [comment]
Works with KG1:
```
add_qnode(key=n0,name=influenza)
add_qnode(key=n1,category=biolink:PhenotypicFeature)
add_qnode(key=n2,category=biolink:Disease)
add_qedge(subject=n0, object=n1, key=e0)
add_qedge(subject=n1, object=n2, key=e1)
expand(kp=ARAX/KG1)
resultify()
filter_results(action=limit_number_of_results, max_results=30)
```
But returns ~5K n2 nodes before filtering (not surprising)

**Comment by edeutsch** [comment]
I'll note in passing that this is exactly the kind of query where we want n1 to have is_set = true.
As of yesterday it was forcing that. But today it's not anymore.
Maybe I should take @amykglen 's suggestion to actively disable that forcing if both sides are pinned to a CURIE.

**Comment by dkoslicki** [comment]
Good point @edeutsch , and agreed about wanting is_set here (if we got any results)

**Comment by amykglen** [comment]
ah, think I figured it out - it was my mistake, relating to #1373. fix is in `master` and will need to be rolled out to the KG2 API.

**Comment by amykglen** [comment]
actually, there may be one other piece needed for the fix. looking into it..

**Comment by amykglen** [comment]
ok, never mind. think we're good to go. will verify after `master` is rolled out to the KG2 endpoint.

**Comment by edeutsch** [comment]
current state of master rolled out to all deployments.
I also re-instatated the is_set forcing cuz I think we want that for this query.
I will try to get a better fix in based on @amykglen suggestion soonish.

**Comment by amykglen** [comment]
alright, well the query now produces results! (about 55k nodes, 900k edges): https://arax.ncats.io/?r=7774

though, as a side note, sadly it took a while for the KG2 API to respond with answers for the second hop (7.5 minutes). it wasn't the `expand` portion of the KG2 API's work that took so long though (that was about 30 seconds). check out the 7-minute gap between these two messages at the very end of processing:

![Screen Shot 2021-04-22 at 6 11 25 PM](https://user-images.githubusercontent.com/49423686/115803716-50be4200-a396-11eb-97a9-be2cf64e0f31.png)

(I would post a link so you can check out that query for yourself, but it broke the browser since results aren't filtered on the KG2 endpoint, so no URL to share.)

**Comment by dkoslicki** [comment]
Besides the performance issue, looks good to me. Thanks all! (@amykglen @edeutsch for your help!)

**Comment by amykglen** [comment]
also, fyi - I didn't see this error in my testing of #1373 because it's kind of tricky to test how changes will impact the KG2 API prior to code actually being rolled out there (since ARAX always calls that endpoint, and the sort of 'recursive' Expand call makes things a little intricate) - but I improved `expand`'s 'force_local' mechanism just now (in 3dc531c and ab43797), so I think such issues should be caught in testing going forward..

**Comment by edeutsch** [comment]
aha, good idea, yes, I was thinking that the two-component system makes it harder to test.
