### ISSUE TITLE
KG2.6.1 node synonymizer issue with acetaminophen

### ISSUE THREAD

**Issue by amykglen** [RTXteam/RTX#1423]
so I built a new synonymizer from KG2.6.1 and then used it to build a KG2c from KG2.6.1 

the  KG2.6.1c is hosted at http://kg2canonicalized.rtx.ai:7474/browser/ 
and the synonymizer is at `/translator/data/orangeboard/databases/KG2.6.1/node_synonymizer.sqlite`

but at first glance, things seem a bit off... for example, there's no node with the `id` CHEMBL.COMPOUND:CHEMBL112 (acetaminophen) in KG2c... instead, the id for the node that CHEMBL.COMPOUND:CHEMBL112 is an equivalent curie for has the name 'histamine', the`id` FMA:61806, and over 4,000 equivalent curies.

I confirmed that the synonymizer seems to contain this strangeness (e.g., do `python3 node_synonymizer.py --lookup=acetaminophen`)

acetaminophen happened to be the first node I checked - don't know if issues are more extensive than this

but thinking we should hold off building downstream databases until @edeutsch has a chance to assess the situation. fyi, this is how the synonymizer was built: https://github.com/RTXteam/RTX/blob/master/code/kg2/canonicalized/build-synonymizer.sh

**Comment by edeutsch** [comment]
Holy Helga Hufflepuff! 4000 equivalent nodes! I will investigate.

**Comment by edeutsch** [comment]
@amykglen would you be able to put the 2.6.1 kg2_equivalencies.tsv kg2_node_info.tsv kg2_synonyms.json files in the databases/KG2.6.1 folder so I can test against those?

**Comment by amykglen** [comment]
sure! they're in there now.

**Comment by edeutsch** [comment]
First off, this problem is huge and pervasive. Huge groups of similar things are being coalesced into clusters where they shouldn't be. I'm able to vastly reduce and perhaps fix the problem by using the kg2_equivalencies.tsv from 2.5.2.

i.e. using kg2_node_info.tsv from 2.6.1 and kg2_equivalencies.tsv from 2.6.1 leads to huge overclustering
but using kg2_node_info.tsv from 2.6.1 and kg2_equivalencies.tsv from 2.5.2 seems to be vastly better and maybe completely fine.

I'm still trying to pinpoint some examples of what's wrong with kg2_equivalencies.tsv from 2.6.1 but I thought I'd post this in case someone has ideas about what may be the problem, while I still have some hair left.

**Comment by edeutsch** [comment]
Tylenol, Ofirmev, Mapap, Pharbetol, FeverAll, Tactinal, these are all good additions!

But Vicodin, Xolox, Percocet are Acetaminophen PLUS something else (oxycodone)

It almost seems like in the expansion of same_as, there are many more equivalent names (which is good) but then there are a whole lot of drugs that are being called same_as X when in fact X is just one of the consituents. 

This has the effect of merging aceteminophen with all drugs that *contain* acetaminophen, and in turn all drugs that contain chemical substances that are sometimes mixed with acetaminophen. That's how we got to 4000!

This is not limited to acetaminophen. this is a hugely pervasive issue.

**Comment by kvarforl** [comment]
Ah yikes! My first thought is that this might be related to #1345. I'm just on my phone right now so I can't look into it thoroughly, but I will be able to do so in a couple of hours and report back here! Thanks for the report :)

**Comment by ericawood** [comment]
Posting this for later consideration (from `KG2.6.1`):
![image](https://user-images.githubusercontent.com/36611732/116758173-60f0a580-a9c4-11eb-9d0d-246be1778a9c.png)

**Comment by edeutsch** [comment]
>Ah yikes! My first thought is that this might be related to #1345. I'm just on my phone right now so I can't look into it thoroughly, but I will be able to do so in a couple of hours and report back here! Thanks for the report :)

aha yes, sounds very likely, from here:
https://github.com/RTXteam/RTX/issues/1345#issuecomment-813756161

![image](https://user-images.githubusercontent.com/12707718/116757893-dc9e2280-a9c3-11eb-9601-1c6be57f4d76.png)

I did not notice it at the time, but "Advil Sinus Congestion and Pain" is NOT just a trade name for ibuprofen, it is a trade name for a product that *contains* ibuprofen.
 "Advil Sinus Congestion and Pain" is Ibuprofen 200mg + phenylephrine HCI 10mg

If RXNORM doesn't distinguish between trade name for exact drug vs. trade name of something that contains exact drug, that would be sad. And then it shouldn't be same_as. Need to look at a bunch of examples, I suppose. I hope there's a way to distinguish!

**Comment by kvarforl** [comment]
Okay, definitely agreed that RXNORM mapping is the problem. However, after looking into the documentation, I'm not seeing a clear / obvious way to distinguish the `has_tradename` relationships that are for exact drug vs. trade name of something that contains exact drug. 

All of the examples that I can find seem to show the intent of providing tradenames for exact drugs only, but, as demonstrated above, that does not seem to be the case.

For reference, I looked at this page of [relationship types](https://www.nlm.nih.gov/research/umls/rxnorm/docs/appendix1.html) in RXNORM (here is a link to the [term types](https://www.nlm.nih.gov/research/umls/rxnorm/docs/appendix5.html) mentioned)

RXNREL RXCUI2 TTY | RELA | RXNREL RXCUI1 TTY | Example with Strings
-- | -- | -- | --
Generic Pack | has_tradename | Brand Name Pack | '{24  (Acetaminophen 500 MG / Diphenhydramine Hydrochloride 25 MG Oral  Tablet) / 50 (Acetaminophen 500 MG Oral Tablet) } Pack' has_tradename  '{24 (Acetaminophen 500 MG / Diphenhydramine Hydrochloride 25 MG Oral  Tablet [Tylenol PM]) / 50 (Acetaminophen 500 MG Oral Tablet [Tylenol]) }  Pack [Tylenol Extra Strength Day and Night Pack]'
Ingredient | has_tradename | Brandname | 'Acetaminophen' has_tradename 'Tylenol'
Semantic Clinical Drug | has_tradename | Semantic Branded Drug | 'Acetaminophen 325 MG Oral Tablet' has_tradename 'Acetaminophen 325 MG Oral Tablet [Tylenol]'
Semantic Clinical Drug Component | has_tradename | Semantic Branded Drug Component | 'Acetaminophen 325 MG' has_tradename 'Acetaminophen 325 MG [Tylenol]'
Semantic Clinical Drug Form | has_tradename | Semantic Branded Drug Form| 'Acetaminophen Oral Tablet' has_tradename 'Acetaminophen Oral Tablet [Tylenol]'
Semantic Clinical Dose Form Group | has_tradename | Semantic Branded Dose Form Group | 'Acetaminophen Pills' has_tradename 'Tylenol Pills'

The most suspicious one is the one that connects Ingredient to Brand name, though the example seems fine. Even if we decided to opt out of including those ones, the "types" from this table aren't abundantly apparent in the ingested .ttl file.

So essentially, it's a bit of a stumper for me for now. A simple solution (though not a good one) would be to change the relationship mapping from #1345 to something other than `same_as` and partially rebuild for 2.6.2 (which should hopefully take a few hours instead of a few days).

@ericawood  I would love a second pair of eyes to see if i'm missing something obvious!

@amykglen @edeutsch I'm assuming this is a blocker for rolling out kg2.6.1, and as such a kg2.6.2 with these edges omitted would be desirable soon? let us know :)

**Comment by edeutsch** [comment]
> Okay, definitely agreed that RXNORM mapping is the problem. However, after looking into the documentation, I'm not seeing a clear / obvious way to distinguish the `has_tradename` relationships that are for exact drug vs. trade name of something that contains exact drug.

boo RXNORM!

> So essentially, it's a bit of a stumper for me for now. A simple solution (though not a good one) would be to change the relationship mapping from #1345 to something other than `same_as` and partially rebuild for 2.6.2 (which should hopefully take a few hours instead of a few days).

looks like it should be same_as_or_a_part_of

> @ericawood I would love a second pair of eyes to see if i'm missing something obvious!
> 
> @amykglen @edeutsch I'm assuming this is a blocker for rolling out kg2.6.1, and as such a kg2.6.2 with these edges omitted would be desirable soon? let us know :)

yes please. KG2.6.1 as is not usable unless I:
a) have NodeSynonymizer ignore all equivalencies as encoded in kg2_equivalencies.tsv (same_as plus some other things?)
b) build NodeSynonymizer with the kg2_equivalencies.tsv from KG2.5.2
which are options.

but a fixed KG2.6.2 does seem preferable to me.

**Comment by kvarforl** [comment]
something interesting to note is that the Biolink model has `RXNORM:has_tradename` as a narrow mapping for the node property `synonym` [L542-L567](https://github.com/biolink/biolink-model/blob/04a4fbb9d1d64784c29df4fc2a951df1a30bfe2e/biolink-model.yaml#L542-L567), though with a "needs review?" comment. 

Does the node synonymizer use the synonym's list in canonicalizing as well? I suppose sticking everything in there instead is somewhat dodging the point that the `has_tradename` relationship is not indicative of synonymousness. 
Until I can find a way to disguish what should be "same as" vs "part of", I will likely map them all to "part of" as a temporary solution.

**Comment by edeutsch** [comment]
> something interesting to note is that the Biolink model has `RXNORM:has_tradename` as a narrow mapping for the node property `synonym` [L542-L567](https://github.com/biolink/biolink-model/blob/04a4fbb9d1d64784c29df4fc2a951df1a30bfe2e/biolink-model.yaml#L542-L567), though with a "needs review?" comment.

would be great if you can get a not that this is definitely always true.

> Does the node synonymizer use the synonym's list in canonicalizing as well?

It does not currently, no. It seemed like such a huge list that it might get us until more trouble.

> I suppose sticking everything in there instead is somewhat dodging the point that the `has_tradename` relationship is not indicative of synonymousness.

yeah. I don't think putting it in synonyms is a good idea.

> Until I can find a way to disguish what should be "same as" vs "part of", I will likely map them all to "part of" as a temporary solution.

if same_as_or_a_part_of is not an option, then part_of seems like the best alternative. Technically there are inactive ingredients in Advil mixed in with ibuprofen as well, making the idea of part_of quite reasonable in all cases.

**Comment by kvarforl** [comment]
Okay, hopefully this should be better in kg2.6.2 now:
```
match p=(n{id:"RXNORM:161"})-[]-(m{id:"RXNORM:128793"}) return p
```
<img width="681" alt="image" src="https://user-images.githubusercontent.com/39020520/116800972-a099b900-aaba-11eb-86a7-dec402070939.png">

Let me know if it is not resolved once the synonymizer is built!

**Comment by edeutsch** [comment]
Great, thanks! I don't have what I need to test, I rely on @amykglen to provide the files I need. But maybe @amykglen can just go ahead and try to run the NodeSynonymizer and KG2C build process and see how it goes?

**Comment by amykglen** [comment]
sounds good to me! will do so and let you know.

**Comment by amykglen** [comment]
so the KG2.6.3c build is underway, and I can see that the acetaminophen node in the KG2.6.3 synonymizer appears normal! 🎉  

so I'll go ahead and close this issue. thanks @kvarforl and @ericawood for such quick fixes!!
