### ISSUE TITLE
Make FET work even when Expand uses external KPs?

### ISSUE THREAD

**Issue by amykglen** [RTXteam/RTX#1438]
I noticed that this query (on https://arax.ncats.io/NewFmt):
```
add_qnode(name=acetaminophen, categories=biolink:ChemicalSubstance, key=n0)
add_qnode(categories=biolink:Protein, key=n1)
add_qedge(subject=n0, object=n1, key=e0)
expand(edge_key=e0)
overlay(action=fisher_exact_test,subject_qnode_key=n0,virtual_relation_label=F1,object_qnode_key=n1,filter_type=top_n,value=10)
resultify()
```
produces the error:
```
Only KG1 or KG2 or KG2C is allowable to calculate the Fisher's exact test temporally
```
is this restriction something that we're planning to lift at some point? if we want to use FET in #1387 (as is currently the plan), I think it will probably be important for it to work even with non-RTX KPs, since `expand` often uses such KPs these days.

but I don't know all the specifics of how FET works. if I recall correctly, this restriction is because we don't have the total entity counts by category for external KPs. would it be possible to just always use KG2c's total entity counts? maybe it wouldn't be 100% accurate, but perhaps 'good enough'?

**Comment by chunyuma** [comment]
Hi @amykglen, it seems like right now [these](https://github.com/RTXteam/RTX/blob/19d1ee3662f86d9ec00673f18327e086e15c841c/code/ARAX/ARAXQuery/Expand/expand_utilities.py#L430-L439) external KPs (except for COHD, DTD and NGD) are available in `expand`, right? Should they all be included in FET? The reason why currently I only allow KG1 and KG2 is because we have to know four types of count in these KPs for FET calculation. Here is an example to show what I need to know for a given KP expand:

Let's say (nodeA: categoryA)-[r:predicateXX]-(nodeB: categoryB) --> expand(kp=XX, predicates=XX)

To calculate FET probability, I have to know:
1) how many nodeBs are expanded with kp=XX in knowledge graph?
2) how many nodeAs are connected to each node B in knowledge graph?
2) how many nodeAs connected to nodeB with predicateXX are categoryA in kpXX?
3) how many nodes with categoryA are in kpXX?

I'm not sure if we can have all these counts for all these external KPs? Can we also build a pre-count database like `kg2c_v1.2_KG2.5.2.sqlite` for other external KPs? Otherwise we might also need to use DSL query to count these values if we want to include other KPs. Also, if we can still use KG2c's entity counts for other external KPs, it should be easy to include these external KPs in FET.

**Comment by amykglen** [comment]
ah, I see. thanks for the nice explanation! 

so is it only items 3 and 4 that rely on counts from the KP? and if so, would it be possible to use KG2c for items 3 _and_ 4, regardless of which KP the nodes came from? KG2c will have different neighbor counts than other KPs of course, but KG2c is pretty comprehensive, so maybe it could work ok most of the time?

it seems to me that it might be really difficult to get neighbor counts and total entity by category counts for external KPs, and I believe the BTE team said it's flat out not possible to do that for BTE, since they don't have an underlying database (their nodes/edges are all gathered on the fly from other sources).

**Comment by chunyuma** [comment]
> is it only items 3 and 4 that rely on counts from the KP? 

Yes, only 3 and 4 are based on the KP. Item 1 and 2 are based on the knowledge graph.

I think currently if we want to include other external KPs in FET, we have two choices:

1) For item 3 and 4, we still rely on the count from KG2c although this might cause a little discrepancy.

2) I can query DSL within FET to get the count of 3 and 4 items. The advantage might be more accurate but the shortcoming might be running slower than 1). But one thing I want to point out is that for `kg2c` KP, even though currently we have a pre-computed database (eg. `kg2c_v1.2_KG2.5.2.sqlite`), we might also need to use DSL query if the users query with `expand(kp=XXX, predicates=biolink:XXXX)`. 

I'm not sure which one might be better but I would prefer the second one.

**Comment by amykglen** [comment]
got it. I would vote for option 1 - I think there would be major speed/performance issues with option 2 (like we see when using the DSL approach with our own KPs).

> we might also need to use DSL query if the users query with expand(kp=XXX, predicates=biolink:XXXX).

are you referring to the fact that the DSL method is still used if a `rel_edge_key` is specified for FET? if so, this is something we can change pretty easily - the first round of KG2c's neighbor counts didn't include a breakdown by predicate just because I didn't realize you needed that, but we can easily precompute those as well. (whether they go in the KG2c sqlite or are exposed on Plover.)

**Comment by amykglen** [comment]
ok, great. I'll figure out a way so you can have the counts by predicate as well!

> If a user queried expand(kp=ARAX/KG1, predicate=biolink:XXX), this predicate might only exist in KG1 rather than KG2. So if I query the kg2c sqlite database, this count might be 0 and it might cause the negative value.

that makes sense - although I think we shouldn't worry about this for KG1 since KG1 will soon be deprecated (you could continue to use the DSL method for KG1 if you want).

though I think it's possible this situation could arise with external KPs too, so it might be smart to have some special handling for this case (e.g., maybe it means you calculate FET ignoring the predicate in this case, or maybe there's some other way to handle these that makes more sense).

**Comment by chunyuma** [comment]
@amykglen, I think I've solved this issue by using RTX-KG2 for FET calculation when the external KGPs are called. For the issue which causes the negative value in FET calculation (the queried predicate only exists in KG1 or other external KPs), the associated nodes would be skipped. Currently, I think this is the best way to solve this problem. 

@amykglen, if you agree, can we close this issue?

**Comment by amykglen** [comment]
awesome, yes, closing now, thanks!
