### ISSUE TITLE
Make add_qnode() and add_qedge() enforce unique qnode/qedge keys

### ISSUE THREAD

**Issue by amykglen** [RTXteam/RTX#1439]
this isn't high priority, but I think it'd be nice if `add_qnode()` and `add_qedge()` prevented you from adding a qnode/qedge to the QG if it uses a key that already exists in QG.nodes/QG.edges

I often find myself accidentally adding two qedges with the same key in DSL (due to copying errors), and it generally results in a weird downstream error that doesn't make it obvious went wrong...

here's a recent example, courtesy of @dkoslicki 🙂   (two qedge's have the key `e02`): 
```
add_qnode(key=n0,category=biolink:Gene)
add_qnode(key=n1,id=CHEBI:45783,category=biolink:ChemicalSubstance)
add_qnode(key=n2,id=MONDO:0005301,category=biolink:Disease)
add_qedge(key=e01,subject=n0,object=n1,predicate=biolink:related_to)
add_qedge(key=e02,subject=n0,object=n2,predicate=biolink:related_to)
expand()
resultify()
add_qnode(key=n3,category=biolink:ChemicalSubstance)
add_qedge(key=e02,subject=n0,object=n3,predicate=biolink:related_to)
expand(edge_key=e02,continue_if_no_results=false,enforce_directionality=false,use_synonyms=true)
resultify()
filter_results(action=limit_number_of_results,max_results=50,prune_kg=true)
```
this results in: `ERROR: [InvalidQG]    Required portion of QG is disconnected. This is not allowed.` during the second `expand` step.

**Comment by edeutsch** [comment]
fixed in NewFmt and deployed

test_ARAX_messenger.py::test_add_qnode_duplicate_key PASSED                                                                                                                                              test_ARAX_messenger.py::test_add_qedge_duplicate_key PASSED

the above DSL (after conversion to TRAPI 1.1) now produces:
2021-05-15T06:39:09.890196 ERROR: Duplicate key 'e02' specified when trying to create a new QEdge

**Comment by amykglen** [comment]
awesome! closing
