### ISSUE TITLE
master -> NewFmt merge conflict

### ISSUE THREAD

**Issue by finnagin** [RTXteam/RTX#1440]
The following merge conflict happened in index.html when I merged the most recent master uspdates into NewFmt:

```
<<<<<<< HEAD
<div class="statushead">TRAPI 1.1</div>
<div id="topnotice" class="status">
  <h3 style="display:inline-block;">This is the interface based on <b>TRAPI 1.1</b>.</h3> Click <a href="/">here to go to the TRAPI 1.0-based interface</a>
</div><br><br>

=======
<div style="border-left-color:#c40;" class="statushead error">TRAPI 1.1</div>
<div class="status">
  <h3 style="display:inline-block;">This is the interface based on <b>TRAPI 1.1</b>. Click <a href="/">here to go to the TRAPI 1.0-based interface</a></h3>
</div><br><br>


>>>>>>> master
```

This is how I fixed it:

```
<div style="border-left-color:#c40;" class="statushead error">TRAPI 1.1</div>
<div class="status">
  <h3 style="display:inline-block;">This is the interface based on <b>TRAPI 1.1</b>. Click <a href="/">here to go to the TRAPI 1.0-based interface</a></h3>
</div><br><br>
```

Is this correct?

**Comment by edeutsch** [comment]
master and NewFmt should be different in this case, because one is TRAPI 1.0 and one is TRAPI 1.1. But it seems like you're concerned about div class differences? I don't know. Tagging @isbluis for help because he would know. I suppose going forward we *don't* want to have these be merged. we want them different. how can we do that? Maybe we need to have two files and a sym link in the deployment?

**Comment by isbluis** [comment]
Hi @finnagin .  These should not be merged because as @edeutsch mentioned, they are supposed to be different.

![image](https://user-images.githubusercontent.com/37852256/117586446-1d392280-b0cd-11eb-9f89-d14803932d9a.png)

![image](https://user-images.githubusercontent.com/37852256/117586544-a81a1d00-b0cd-11eb-9df1-57f411d1784f.png)

i.e. the more red/angry message should be if on TRAPI 1.0, but not on 1.1
These differences are not as obvious with the latest merge/fix.

Is it possible to skip/not merge this file?   Otherwise we will need to put special logic.

Thanks!

**Comment by finnagin** [comment]
Sure! I had already made the merge but I reverted the file to the state from right before the merge and committed that as a new change. Important to note is this means that if we merge NewFmt into master the index.html file in NewFmt will replace the one in master without conflict. I think this may be what we want but I figured I should mention it here just in case.

**Comment by isbluis** [comment]
Great, thank you @finnagin !  And duly noted.  I believe we'll just go back to having no banner after we are set on 1.1, so shouldn't be an issue.

**Comment by finnagin** [comment]
I think this issue can be closed.
