### ISSUE TITLE
A number of druggable genes present in KG2C-5-2 but not KG2C-6-3

### ISSUE THREAD

**Issue by dkoslicki** [RTXteam/RTX#1453]
eg: `match (n{id:"UMLS:C1413064"}) return n` *CACNA1S*

`match (n{id:"UMLS:C1336679"}) return n` *TSHR*

Compare the results on http://kg2c-6-3.rtx.ai:7474/browser/ vs http://kg2c-5-2.rtx.ai:7474/browser/. The CURIES were pulled from the `Synonyms` UI tool.

Note this is not a problem on the non `C` versions of the graphs.

**Comment by amykglen** [comment]
looks like maybe they just have different 'preferred' curies in KG2c-6-3? (MONDO instead of UMLS)

both of these return an answer in KG2c-6-3:
```
match (n) where "UMLS:C1413064" in n.equivalent_curies return n
```
```
match (n) where "UMLS:C1336679" in n.equivalent_curies return n
```
(the UI synonyms tool is based on the KG2.5.2 synonymizer, so it wouldn't necessarily give you the right preferred curies for KG2.6.3)

**Comment by amykglen** [comment]
although it doesn't seem good that both of these nodes are instances of gene/disease conflation in KG2.6.3. I thought 2.6.3 was supposed to be improved in that regard? so these nodes actually wouldn't be returned for gene queries, since their `expanded_categories` contains only disease-like things..
