### ISSUE TITLE
Strange overlay NGD behavior (computing self-edges)

### ISSUE THREAD

**Issue by amykglen** [RTXteam/RTX#1457]
this query is erroring out for me in resultify on NewFmt:
```
{
  "nodes": {
    "n00": {
      "categories": [
        "biolink:Gene"
      ],
      "is_set": false
    },
    "n01": {
      "ids": [
        "MONDO:0018177"
      ],
      "categories": [
        "biolink:Disease"
      ],
      "is_set": false
    }
  },
  "edges": {
    "e00": {
      "subject": "n00",
      "object": "n01",
      "exclude": false
    }
  }
}
```
and in trying to trace what's going wrong, I found it seems that overlay NGD is trying to compute NGD from n00 nodes to themselves? here's a bit from the log to see what I mean:
```
2021-05-11T21:09:52.482806 DEBUG: Computing NGD
2021-05-11T21:09:52.487981 INFO: Computing the normalized Google distance: weighting edges based on subject/object node co-occurrence frequency in PubMed abstracts
2021-05-11T21:09:52.493873 DEBUG: Narrowing down n00--n00 node pairs to overlay
2021-05-11T21:09:52.837615 DEBUG: Identified 978 node pairs to overlay (with help of resultify)
2021-05-11T21:09:52.850660 DEBUG: Canonicalizing curies of relevant nodes using NodeSynonymizer
2021-05-11T21:09:59.820824 DEBUG: Extracting PMID lists from sqlite database for relevant nodes
2021-05-11T21:10:08.019940 DEBUG: Looping through 978 node pairs and calculating NGD values
2021-05-11T21:10:08.083670 DEBUG: 476 publications found for edge (UniProtKB:P28370)-[]-(UniProtKB:P28370) limiting to 30...
2021-05-11T21:10:08.094528 DEBUG: 95 publications found for edge (UniProtKB:Q8N488)-[]-(UniProtKB:Q8N488) limiting to 30...
2021-05-11T21:10:08.095737 DEBUG: 5754 publications found for edge (UniProtKB:P10721)-[]-(UniProtKB:P10721) limiting to 30...
2021-05-11T21:10:08.104437 DEBUG: 949 publications found for edge (UniProtKB:P51677)-[]-(UniProtKB:P51677) limiting to 30...
2021-05-11T21:10:08.110849 DEBUG: 86 publications found for edge (UniProtKB:O43424)-[]-(UniProtKB:O43424) limiting to 30...
```
not sure why it's trying to overlay `n00--n00` edges vs. `n00--n01` edges..

**Comment by amykglen** [comment]
worth noting that this also appears to happen on the TRAPI 1.0 endpoint (tries to overlay n00-n00 edges). the equivalent QG is:
```
{
  "nodes": {
    "n00": {
      "category": "biolink:Gene",
      "is_set": false
    },
    "n01": {
      "id": "MONDO:0018177",
      "category": "biolink:Disease",
      "is_set": false
    }
  },
  "edges": {
    "e00": {
      "subject": "n00",
      "object": "n01",
      "exclude": false
    }
  }
}
```

**Comment by dkoslicki** [comment]
@finnagin and @amykglen so this is quite weird: if you remove the zero (`n00->n0`, etc.) and use:
```
{
  "nodes": {
    "n0": {
      "category": "biolink:Gene",
      "is_set": false
    },
    "n1": {
      "id": "MONDO:0018177",
      "category": "biolink:Disease",
      "is_set": false
    }
  },
  "edges": {
    "e0": {
      "subject": "n0",
      "object": "n1",
      "exclude": false
    }
  }
}
```
then it completes without issue. Similarly, using `n000` makes it work just fine:
```
{
  "nodes": {
    "n000": {
      "category": "biolink:Gene",
      "is_set": false
    },
    "n001": {
      "id": "MONDO:0018177",
      "category": "biolink:Disease",
      "is_set": false
    }
  },
  "edges": {
    "e000": {
      "subject": "n000",
      "object": "n001",
      "exclude": false
    }
  }
}
```
And while it does appear that NGD is doing self loop stuff (probably a nested `for` loop without considering both iterations on the same CURIE) as @amykglen saw (eg. `2021-05-12T03:23:04.670001 DEBUG: 87 publications found for edge (UniProtKB:Q9HC78)-[]-(UniProtKB:Q9HC78) limiting to 30...`), it appears that the error happens right after resultify is to be called:
```
2021-05-12T03:23:04.806726 INFO: Processing action 'resultify' with parameters {'': 'true'}
2021-05-12T03:23:04.806784 DEBUG: Applying Resultifier to Message with parameters {'': 'true'}
2021-05-12T03:23:04.980637 ERROR: 'n00'  #<---- This odd error
2021-05-12T03:23:04.984852 DEBUG: Cleaning up the KG to remove nodes not used in the results
```

**Comment by dkoslicki** [comment]
There appear to be only 4 usages of `self.response.error` in `ARAX_resultify.py`, so perhaps adding more verbose text to the two error strings that don't have verbose text (eg. ` self.response.error(str(e))`) might be a way to figure out what is going on.

But it doesn't settle well with me that most of the uses of `n00` are in tests, save for the query graph interpreter. Hope it isn't something odd happening with that.

**Comment by amykglen** [comment]
yep, I'll plan to fix resultify as well. I think it's the NGD self-edges that are throwing it off... (and about the logging - I think when Steve wrote resultify he wanted to keep the main resultify function pure so he didn't use `self.response.error` in there, but I've been thinking of changing that paradigm..)

**Comment by finnagin** [comment]
Looks like the self loop is coming from the query graph interpreter.

When I print `new_araxi_commands` from [line 184](https://github.com/RTXteam/RTX/blob/68f341bb1d20ec2f08a5913ae23418a38538838f/code/ARAX/ARAXQuery/ARAX_query_graph_interpreter.py#L184) I get the following:

```
['expand()', 'overlay(action=compute_ngd, virtual_relation_label=N1, subject_qnode_key=n00, object_qnode_key=n00)', 'resultify()', 'filter_results(action=limit_number_of_results, max_results=100)']
```

However when I print out the template araxi commands from [line 163](https://github.com/RTXteam/RTX/blob/68f341bb1d20ec2f08a5913ae23418a38538838f/code/ARAX/ARAXQuery/ARAX_query_graph_interpreter.py#L163) I get the following:
```
ARAXI COMMANDS: ['expand()', 'overlay(action=compute_ngd, virtual_relation_label=N1, subject_qnode_key=n00, object_qnode_key=n01)', 'resultify()', 'filter_results(action=limit_number_of_results, max_results=100)']
```

which has the correct n00 and n01. So it looks like the issue is happening in the loop between [lines 166 and 181](https://github.com/RTXteam/RTX/blob/68f341bb1d20ec2f08a5913ae23418a38538838f/code/ARAX/ARAXQuery/ARAX_query_graph_interpreter.py#L166-L181). Looks to me like it might be happening on [line 172](https://github.com/RTXteam/RTX/blob/68f341bb1d20ec2f08a5913ae23418a38538838f/code/ARAX/ARAXQuery/ARAX_query_graph_interpreter.py#L172)

Not sure if relevant but from the log it looks like it is using the following template:
```
2021-05-12T00:34:14.085144 DEBUG: [] The QueryGraph reference template is: n00(ids)-e00()-n01(categories=biolink:Gene)
```

**Comment by finnagin** [comment]
Oh I think I figured it out. And I know why it only happens when we use n00 but not n0 or n000. If you look at [lines 170-173](https://github.com/RTXteam/RTX/blob/68f341bb1d20ec2f08a5913ae23418a38538838f/code/ARAX/ARAXQuery/ARAX_query_graph_interpreter.py#L170-L173) it loops through the template araxi command and replaces the templates node names with the supplied node names. My guess is it is mapping n00 to n01 so first it replaces all instances of n00 with n01. Next it moves to the next node which it has mapped n01 to n00 so it then replaces all instaces of n01 with n00 but since we just replaced n00 with n01 those now get replaced with n00. 

I.E. it goes like this:
'overlay(action=compute_ngd, virtual_relation_label=N1, subject_qnode_key=n00, object_qnode_key=n01)'
-> (replace n00 with n01)
'overlay(action=compute_ngd, virtual_relation_label=N1, subject_qnode_key=n01, object_qnode_key=n01)'
-> (replace n01 with n00)
'overlay(action=compute_ngd, virtual_relation_label=N1, subject_qnode_key=n00, object_qnode_key=n00)'

The problem seems to be that we use a sequential find & replace on the command on node ids that might be used in query_graphs. Maybe to fix we could use ids like 'PLEASE_DONT_USE_THIS_NODE_ID_PLEASE_PLEASE_PLEASE_n01' or use some special characters line '%$&!no1%$&!' we don't think people will use in node ids. Or we could do some sort of find and replace function that replaces both at the same time only looping through the string once.

**Comment by finnagin** [comment]
Tagging @edeutsch in case you have thoughts on how we should go about fixing this.

**Comment by dkoslicki** [comment]
I personally like the idea of `PLEASE_DONT_USE_THIS_NODE_ID_PLEASE_PLEASE_PLEASE_n01`:D

**Comment by edeutsch** [comment]
I opted for something a little less boisterous than `PLEASE_DONT_USE_THIS_NODE_ID_PLEASE_PLEASE_PLEASE_n01`, but effectively the same

deployed to v1.1 NewFmt

**Comment by amykglen** [comment]
awesome - verified it seems to be working on arax.ncats.io/NewFmt! closing
