### ISSUE TITLE
Change Arax Interface to New ARS URL

### ISSUE THREAD

**Issue by MarkDWilliams** [RTXteam/RTX#1495]
It seems we are nearing the end of our deployment of the ARS with ITRB and now have a running instance that we would like to start using and testing against.  Is it possible to change the ARAX interface to point at https://ars.ci.transltr.io/ which is be 1.1 TRAPI?

**Comment by edeutsch** [comment]
Hi @MarkDWilliams I have switched our test instance to use this new host, you can test it at:
https://arax.ncats.io/test/

I tried to test with a PK from a recent stand up:
91a60bea-cbe7-40c9-be24-ef1a2f604b93

but I'm getting a 404.
I'm guessing that this is because that PK is on ars-dev and they're not shared to ars.ci, assuming that PKs are host specific.
This could cause some awkwardness.
It's also possible that I botched something.
Do you want to test at:
https://arax.ncats.io/test/
?
I suspect if I roll this out to our main production URL, then the PKs won't work for others any more.

**Comment by edeutsch** [comment]
I could potentially change the code to try both servers for a while, ars.ci as well as ars-dev
i.e. try ars.ci but if that gives a 404, then try ars-dev

**Comment by MarkDWilliams** [comment]
Eric, thanks.  I'll send a few queries this afternoon and test it out.  You are correct that PKs are not shared across dev and CI environments, though PKs from prod are accessible through the CI instance (though they would all be 1.0 queries as we haven't started really using the CI instance)

**Comment by finnagin** [comment]
@edeutsch are we okay to close this one?

**Comment by edeutsch** [comment]
okay to close.
