### ISSUE TITLE
Should we check our KP answers?

### ISSUE THREAD

**Issue by edeutsch** [RTXteam/RTX#1496]
It seems like for the last several weeks on standups and hackathons (although I don't attend most of them so maybe I'm confused) we keep seeing that BTE is ignoring edge predicate information and just returns all edges, and they keep saying they're working on it, but it doesn't seem to be getting fixed. And it seems to be affecting ARAX in that I presume ARAX asks BTE for certain predicates but it gets different irrelevant predicates?

Would it be sensible to add logic in ARAX such that when it asks a KP for some answers, that is checks to make sure the predicates are what we asked for and potentially discards answers that are not right?

Or do we think we should just trust our KPs not to return bogus results?

**Comment by dkoslicki** [comment]
The (canceled) standup today `https://github.com/NCATSTranslator/testing/issues/79` doe make it seem like we want to check KP answers. As mentioned in slack, at least look for consistency with the QG and throw out stuff that isn't. @amykglen is this an `expand` thing, or a post-`expand` thing?

**Comment by amykglen** [comment]
I think in an ideal world we could just trust the KPs, but indeed it seems we can't (at this stage at least). :)

I think it would probably makes sense to have it be an `expand` thing to add these checks.

however, I'm not totally sure how to detect the problem in that standup query (`https://github.com/NCATSTranslator/testing/issues/79`) where MolePro isn't obeying qnode `n1`'s curie. I think it's not as simple as looking to see if the curie of each node matches its qnode's curie, since I think a KP could technically return subclasses of the `n1` curie as well, and we wouldn't necessarily know what are valid/invalid subclasses. 

for example, if a query is like `(n0: insulin)--(n1: diabetes)`, I think a KP could return answers that look something like `(n0: insulin)-[treats]-(n1: type 1 diabetes)`, `(n0: insulin)-[associated with]-(n1: type 2 diabetes)`, etc... so there would be multiple `n1` nodes in the KG with curies that differ from qnode `n1`'s, but technically they're valid.

and one potential problem with predicate/category validation is that if a KP selectively uses some conflations of categories or predicates, like RTX-KG2 does (for protein/drug, phenotype/disease, etc.), then we might throw out their answer because its category/predicate doesn't align with what was asked, even though the KP actually intended to return it.

**Comment by edeutsch** [comment]
yes, I think I agree. It would be a lot more complicated than I originally thought.

I think I suggest that we don't take any action until next week.
This will be discussed on Tuesday at the standup and then perhaps at the Arch call.
I think our position could be that we sent a query to a KP and got an answer that was not the answer to our question and ran with it.
Vlado admitted that MolePro ignores QNode.ids for the *object* node.
I think that deserves a yellow card, if not a red card!

I think this brings up two important issues for the Architecture committee:
1) To what degree should ARAs trust the responses from KPs?
2) To what degree is it imperative that KPs (and ARAs) be sure that they fully understand the question (and return an error if they don't)?

In the TRAPI calls, I pushed fairly hard that KPs/ARAs should be obligated to examine all properties that were given to them in a QGRaph, and if they cannot understand or handle everything, that should yield an error. I was surprised at the pushback. Seems like lots of people felt that it was okay to just answer whatever you can (thereby returning an answer to a question that is different than was asked!) At the moment, this is stipulated as being okay, to my dismay.

Tuesday will be interesting.

**Comment by amykglen** [comment]
sounds good to me. definitely agree that KPs/ARAs should not return anything if they don't understand/support the question being asked!

I suppose if a KP/ARA _understands_ the question but chooses to answer it slightly differently, that may be ok... but responding with something when they straight up don't understand the question seems very undesirable to me.

**Comment by finnagin** [comment]
Closing as this is no longer an issue.
