### ISSUE TITLE
Why do we return fewer results than COHD?

### ISSUE THREAD

**Issue by edeutsch** [RTXteam/RTX#1498]
This came up at today's mini-hackathon:
https://arax.ncats.io/?source=ARS&id=7c8d4771-cbdb-4e71-84bc-33fb65e068cb

Why is ARAX returning fewer results than COHD, given that some of our results are from COHD?
I was unable to answer

**Comment by saramsey** [comment]
Maybe we are doing FET on COHD data and the "COHD" KP is not?  IDK.  Paging @dkoslicki @finnagin @chunyuma

**Comment by saramsey** [comment]
Other possibility-- lossy identifier translation?

**Comment by chunyuma** [comment]
I think the reason might be associated with [this](https://github.com/RTXteam/RTX/issues/1430#issuecomment-832228421). Basically, even though we did use COHD database, the `concept_ids` we used might be different from what they used in COHD API/KP. The `concept_ids` we used are based on the athena website by mapping all synonyms of a query curie to the ids in Athena website.

**Comment by chunyuma** [comment]
Hi @edeutsch, I don't understand what is the problem in issue 28 that NCATS is asking. But if this issue is associated with the fewer COHD results returned ARAX than what COHD returned, I think the problem should be due to the OMOP IDs that we used don't match with what COHD used. Like I said in the previous post, [here](https://github.com/RTXteam/RTX/issues/1430#issuecomment-832228421) is an example. In this example, COHD considers `MONDO:0014007` as basal ganglia disease while we considers `MONDO:0014007` as `Aicardi-Goutieres syndrome 6`.

What COHD API returns:
```
"MONDO:0014007": {
          "attributes": [
            {
              "name": "omop_concept_id",
              "source": "OMOP",
              "type": "EDAM:data_1087",
              "value": "OMOP:378144"
            },
            {
              "name": "omop_concept_name",
              "source": "OMOP",
              "type": "EDAM:data_2339",
              "value": "Disorder of basal ganglia"
            },
            {
              "name": "omop_domain",
              "source": "OMOP",
              "type": "EDAM:data_0967",
              "value": "Condition"
            }
          ],
          "category": [
            "biolink:DiseaseOrPhenotypicFeature"
          ],
          "name": "basal ganglia disease"
        }
```
What ARAX returns:
![Screen Shot 2021-06-14 at 1 50 55 PM](https://user-images.githubusercontent.com/20031672/121936411-97397880-cd17-11eb-927f-9e520ad51786.png)

So, I'm not sure if there is something wrong with COHD labeling when we think our label is correct. Perhaps we might need people from COHD team to take a look at this issue.

Two solutions to solve this issue:
1. We can ask COHD team to get a copy of OMOP id mapping file that that they used (This might be the most straightforward method that we can always keep the same results as COHD)
2.  Solving the label mismatch issue mentioned above.

**Comment by edeutsch** [comment]
Thanks for the quick response, @chunyuma , I don't quite understand what you mean with the OMOP ids.

Would you see if you can verify that your guess is correct for the query that NCATS cites? so, from the OP:
https://arax.ncats.io/?source=ARS&id=7c8d4771-cbdb-4e71-84bc-33fb65e068cb
You'll find that for that query COHD returns 71 results, while ARAX returns 12 results.
the relevant portion of the ARAX log perhaps is:
![image](https://user-images.githubusercontent.com/12707718/121943395-63a22280-cd06-11eb-84f4-988b7a5c4b6b.png)
So it seems that we only got 12 nodes and edges back. Rather an 71 back.

As a specific example, their (COHD's) second answer is "poisoning" MONDO:0029000
But "poisoning" is nowhere in our results. Even though "poisoning" MONDO:0029000 is a concept in our system.

Does this point to your proposed solutions 1 or 2? I confess I just don't understand them enough to see if it does.

thanks!

**Comment by chunyuma** [comment]
It seems like this issue is also associated with some internal operations of `expand`.

Hi @amykglen, based on the query from https://arax.ncats.io/?source=ARS&id=7c8d4771-cbdb-4e71-84bc-33fb65e068cb, I tried to query ARAX via the following commands:

```
"add_qnode(ids=SNOMEDCT:197358007, key=n0)",
"add_qnode(categories=biolink:DiseaseOrPhenotypicFeature, key=n1)",
"add_qedge(subject=n0, object=n1, key=e0, predicates=biolink:related_to)",
"add_qedge(subject=n0, object=n1, key=e1, predicates=biolink:has_normalized_google_distance_with)",
"expand(kp=COHD)"
```
 I found that the query graph sent to `COHD_querier.py` doesn't have the curie `MONDO:0029000`. Is it because we request `predicates=biolink:related_to` and `predicates=biolink:has_normalized_google_distance_with`?

**Comment by chunyuma** [comment]
Hi @amykglen,

Based on the query from https://arax.ncats.io/?source=ARS&id=7c8d4771-cbdb-4e71-84bc-33fb65e068cb, I tried to query ARAX with the following commands:

```
  "add_qnode(ids=SNOMEDCT:197358007, key=n0)",
  "add_qnode(categories=biolink:DiseaseOrPhenotypicFeature, key=n1)",
  "add_qedge(subject=n0, object=n1, key=e0, predicates=biolink:related_to)",
  "add_qedge(subject=n0, object=n1, key=e1, predicates=biolink:has_normalized_google_distance_with)",
  "expand(kp=COHD)"
```

However, I found that in [this](https://github.com/RTXteam/RTX/blob/d08a4b50a2c3ad5e3935b02a05845b90aebf5919/code/ARAX/ARAXQuery/Expand/COHD_querier.py#L871) line, `qg.nodes[qnode_key]` doesn't return `MONDO:0029000` for that specific example @edeutsch is asking. I'm wondering if this is due to the constraints of `predicates=biolink:related_to` and `predicates=biolink:has_normalized_google_distance_with` in `add_qedge`. 

### For `e0`
```
2021-06-14T17:04:53.928037 DEBUG: [] Processing query results for edge e0 by using paired concept frequency
2021-06-14T17:04:53.928069 INFO: [] Getting the OMOP id for n0
{'categories': ['biolink:DiseaseOrPhenotypicFeature',
                'biolink:Disease',
                'biolink:PhenotypicFeature'],
 'constraints': None,
 'ids': ['SNOMEDCT:197358007'],
 'is_set': False,
 'option_group_id': None}
```

### For `e1`
```
2021-06-14T17:04:53.956550 DEBUG: [] Processing query results for edge e1 by using paired concept frequency
2021-06-14T17:04:53.956570 INFO: [] Getting the OMOP id for n0
{'categories': ['biolink:DiseaseOrPhenotypicFeature',
                'biolink:Disease',
                'biolink:PhenotypicFeature'],
 'constraints': None,
 'ids': ['SNOMEDCT:197358007'],
 'is_set': False,
 'option_group_id': None}
2021-06-14T17:04:53.956980 INFO: [] Getting the OMOP id for n1
{'categories': ['biolink:DiseaseOrPhenotypicFeature',
                'biolink:Disease',
                'biolink:PhenotypicFeature'],
 'constraints': None,
 'ids': ['UMLS:C0579140',
         'UMLS:C0578533',
         'UMLS:C0947846',
         'MONDO:0002254',
         'MONDO:0000001',
         'UMLS:C1320355',
         'UMLS:C1333803',
         'UMLS:C0426686',
         'MONDO:0024505',
         'UMLS:C0947747',
         'UMLS:C3661974',
         'UMLS:C0851731'],
 'is_set': False,
 'option_group_id': None}
```

**Comment by edeutsch** [comment]
thanks @chunyuma 
Note that
```
add_qedge(subject=n0, object=n1, key=e1, predicates=biolink:has_normalized_google_distance_with)
```
is not part of the original query. This is a "virtual edge" added by our system.
so this should be excluded in this sleuthing.

thanks!

**Comment by chunyuma** [comment]
> is not part of the original query. This is a "virtual edge" added by our system.

thanks for pointing this out. But this makes me confuse about the original query. Based on https://arax.ncats.io/?source=ARS&id=7c8d4771-cbdb-4e71-84bc-33fb65e068cb, I found the json format of the query graph is below:

```
{
  "edges": {
    "N1": {
      "object": "n1",
      "predicates": [
        "biolink:has_normalized_google_distance_with"
      ],
      "relation": "N1",
      "subject": "n0"
    },
    "e0": {
      "object": "n1",
      "predicates": [
        "biolink:correlated_with"
      ],
      "subject": "n0"
    }
  },
  "nodes": {
    "n0": {
      "ids": [
        "SNOMEDCT:197358007"
      ],
      "is_set": false
    },
    "n1": {
      "categories": [
        "biolink:DiseaseOrPhenotypicFeature"
      ],
      "is_set": false
    }
  }
}
```

So, if `biolink:has_normalized_google_distance_with` should be excluded, what is the real query that ARAX used?

**Comment by dkoslicki** [comment]
@chunyuma this edge is a result of the query graph interpreter [here](https://github.com/RTXteam/RTX/blob/master/code/ARAX/ARAXQuery/ARAX_query_graph_interpreter_templates.yaml). In short, it adds an ARAXi command like `overlay(action=compute_ngd, virtual_relation_label=N1, subject_qnode_key=n00, object_qnode_key=n01)`. The query graph is then modified/added to in order for `resultify` to know what to do with those virtual edges. See the docs [here](https://github.com/RTXteam/RTX/blob/master/code/ARAX/Documentation/DSL_Documentation.md#overlayactioncompute_ngd) which explains the `N1` labeled edge.

**Comment by edeutsch** [comment]
> So, if biolink:has_normalized_google_distance_with should be excluded, what is the real query that ARAX used?

everything *except* edge N1

**Comment by chunyuma** [comment]
Ah, I see. Thanks @dkoslicki and @edeutsch.

So if `N1` is an example added to `ARAX_overlay`, I think the original query should be like:
```
  "add_qnode(ids=SNOMEDCT:197358007, key=n0)",
  "add_qnode(categories=biolink:DiseaseOrPhenotypicFeature, key=n1)",
  "add_qedge(subject=n0, object=n1, key=e0, predicates= biolink:correlated_with)",
  "expand(kp=COHD)"
```

Bases on this query, I think I found the reason why our system returns fewer results than COHD. It is due to the parameter `COHD_method_percentile `. Below is its description:

```
COHD_method_percentile
What percentile to use as a cut-off/threshold for the specified COHD method.

Acceptable input types: integer.

This is not a required parameter and may be omitted.

95 and 80 are examples of valid inputs.

The values for this parameter can range from a minimum value of 0 to a maximum value of 100.

If not specified the default input will be 99.
```

The default is 99 percentile. However, `MONDO:0029000` is not within 99 percentile. If we set:

```
      "add_qnode(ids=SNOMEDCT:197358007, key=n0)",
      "add_qnode(categories=biolink:DiseaseOrPhenotypicFeature, key=n1)",
      "add_qedge(subject=n0, object=n1, key=e0, predicates= biolink:correlated_with)",
      "expand(kp=COHD, COHD_method_percentile=98)"
```

We can see that ARAX will return `MONDO:0029000`. If we set `COHD_method_percentile` to 0, we might get the total 71 back as what COHD returns.

**Comment by edeutsch** [comment]
aha, excellent, that seems like the right answer, thank you!

Before I provide an answer to NCATS explaining that we filter our results at 99, the question for our team is:

is this (default 99) the desired behavior? Or should we adjust our approach when querying COHD? such that if this query is repeated after change, then we end up with more than 12 results?

**Comment by chunyuma** [comment]
It is hard to determine an appropriate cutoff. But 99 might be too stringent. I think 90 or 95 might be more suitable.

**Comment by edeutsch** [comment]
I'm thinking top N where N ~ 100 seems like a better default approach than limiting by percentile 99, but I know barely anything about COHD

Why not report lower percentiles? And report them as a numerical value that can be used for ranking?

Is something with an 89 in COHD worse than what comes out of SEMMEDDB? I don't know.

**Comment by chunyuma** [comment]
> I'm thinking top N where N ~ 100 seems like a better default approach than limiting by percentile 99, but I know barely anything about COHD

@edeutsch, sorry for late reply! I thinking your suggestions. I think both `top N` filtering method or `percentile` filtering method should work for COHD filtering. Currently, based on `percentile` method, this is how it does:

For a case like `MONDO:XXXXX` -- relation -- biolink:Disease:

1. The `expand(kp=COHD)` first finds all concept ids of `MONDO:XXXXX` that stored in our local COHD database
2. Based on these concept ids, it will extract the `chiSquare`, `obsExpRatio`, `relativeFrequency`(default)  information of all concept id pairs associated with these given concept ids provided by COHD. 
3. Based on the returned `relativeFrequency` information of all concepts id pairs, it chooses the 99 percentiles as default and consider them as high-quality results. 

[Here](https://github.com/RTXteam/RTX/issues/974#issuecomment-668744533) has some distribution graphs I drew before. Based on these distribution graphs, for different curies, 99 percentile might vary (some will return much more results than other). So perhaps top N might be more stable.

**Comment by edeutsch** [comment]
Decision call: just filter top 1000

**Comment by chunyuma** [comment]
The `expand` scripts for COHD edge expansion have been changed by replacing `percentile` with `top_n`. I checked the associated tests and they all pass. So I guess this issue can be closed, @edeutsch?

**Comment by chunyuma** [comment]
@edeutsch agrees to close this issue by asking him at minihackathon.
