### ISSUE TITLE
Which what?

### ISSUE THREAD

**Issue by edeutsch** [RTXteam/RTX#155]
One of my favorite test questions for months has been:
What proteins does acetaminophen target?
For various reasons, I thought I'd switch it to use proper grammar:
Which proteins does acetaminophen target?

But this question yields a response:
The most similar question I can answer is: What drugs target proteins associated with $disease But I was unable to fill the following parameters: ['disease']

hmm.

**Comment by dkoslicki** [comment]
The code now deals with "which" and "what" for this (and some other) question types. Do you think I should change the restated question template too? For some other question types, it's not abundantly clear to me if "what" or "which" is preferable.

**Comment by edeutsch** [comment]
I'm no grammar expert, but I think most of them really should be "Which"

I'm thinking that if either "which" or "what" seem to work, it should probably be "which".

I was going to fix all those in case there might be some grammar pedants looking at them, but started with one and the wheels came off.

**Comment by dkoslicki** [comment]
You should be able to edit the ``Questions.tsv`` file to make any changes you wish: second column being the restated question template, in the third column add a single quote string using "which" instead of "what". This may be a good task for the Ohio students to do at the hackathon, as I don't consider it a high-priority item atm. They would then need to re-build the autocomplete dictionary to pick of these new question statements. I can close this issue and open a new one to that effect if you like (thinking of making a "hackathon" tag so we can direct them to that given no other tasks for them to do).

**Comment by dkoslicki** [comment]
Ancient, not relevant? Closing unless objections.
