### ISSUE TITLE
SemMedDB/PubMed NGD needs updating

### ISSUE THREAD

**Issue by dkoslicki** [RTXteam/RTX#1551]
In [this query](https://arax.ncats.io/?r=15499):
```
add_qnode(ids=CHEMBL.COMPOUND:CHEMBL1428, key=n0)
add_qnode(key=n1)
add_qnode(ids=MONDO:0005301, key=n2)
add_qedge(subject=n0, object=n1, key=e0)
add_qedge(subject=n1, object=n2, key=e1)
expand()
overlay(action=compute_ngd, virtual_relation_label=N1, subject_qnode_key=n0, object_qnode_key=n2)
resultify()
filter_results(action=limit_number_of_results, max_results=30)
```
One would expect a non-zero NGD on the NGD edge `N1` due to this paper: https://pubmed.ncbi.nlm.nih.gov/32293054/ but it currently is not. Is a refresh of FastNGD in order?

**Comment by finnagin** [comment]
Yeah might be if we haven't in a while.

@amykglen could you help walk me through how I would go about refreshing the FastNGD database with new PubMed data?

**Comment by amykglen** [comment]
sure! there is actually a README at: https://github.com/RTXteam/RTX/blob/master/code/ARAX/ARAXQuery/Overlay/ngd/README.md

it's admittedly not very detailed (was intended as a start, to be improved when I had more time), but with your knowledge might be enough. 

you'll want to do the `--full` build since you want to grab the new PubMed data (which the script extracts from your PubMed XML files and puts into the intermediary `conceptnames_to_pmids.db`).

I typically use the `ngdbuild.rtx.ai` instance, though since you're doing a 'full' build, there shouldn't be any particular artifacts on there you need.

**Comment by finnagin** [comment]
Thanks! I'll work through this and ping you if I get stuck.

**Comment by finnagin** [comment]
For the pubmed xml file do you mean these files? https://www.nlm.nih.gov/databases/download/pubmed_medline.html

Or some other set of files?

**Comment by amykglen** [comment]
sounds good!

yeah, exactly - the "Baseline" files: https://ftp.ncbi.nlm.nih.gov/pubmed/baseline/

(and any additions to the README are welcome!)

**Comment by dkoslicki** [comment]
@finnagin Please do update the README with a detailed, step-by-step walkthrough of what you do in order to rebuild this. Would be much appreciated

**Comment by dkoslicki** [comment]
This is now part of KG2 build process, so closing
