### ISSUE TITLE
Keeping the edges separate?

### ISSUE THREAD

**Issue by edeutsch** [RTXteam/RTX#1559]
this is a rule that is going into the Translator Architecture policies.
https://togithub.com/NCATSTranslator/TranslatorArchitecture/pull/56/files

Are we doing this already?

Any concerns?

Okay to approve?

**Comment by saramsey** [comment]
In the KG2 build process, if there are two edges with the same subject, object, and predicate, they will get merged into a single edge. This is because there is a fair bit of repetition among the ontologies, at least, in the way that we are loading them into the KG2 build system. There is a reason why `provided_by` is a list, right?  So we can capture that multiple sources asserted a given triple? Maybe it doesn't matter in practice, because this architecture requirement is about KPs, and not KSs.

**Comment by saramsey** [comment]
Paging @ericawood for their take

**Comment by saramsey** [comment]
I forgot to add-- thank you for the heads-up

**Comment by amykglen** [comment]
it looks like these rules only apply to ARAs, right @edeutsch? I don't see any rules about what KPs are supposed to do... (in which case I think KG2/c are fine as is..)

**Comment by amykglen** [comment]
and to clarify - yes, ARAX already does this (keeps edges from different KPs separate, even if they have the same subject/predicate/object).

**Comment by edeutsch** [comment]
Yes, correct these rules only apply to ARAs. At least that is how it is stated, and also my understanding.

**Comment by finnagin** [comment]
Closing as this looks to be resolved
