### ISSUE TITLE
COHD API returning more information than the local copy has

### ISSUE THREAD

**Issue by dkoslicki** [RTXteam/RTX#1574]
Take a look at https://arax.ncats.io/?source=ARS&id=ac397d4b-12eb-4526-beee-11f00d12104f
The [ARAX results](https://arax.ncats.io/?r=16266)  have edges that look like:

```
attribute_type_id: | EDAM:data_0951
original_attribute_name: | paired_concept_frequency
value_url: | http://cohd.smart-api.info/
value: | 0.00499

attribute_source: | infores:arax-reasoner-ara
attribute_type_id: | biolink:knowledge_source
description: | The Clinical Data Provider (COHD), accessed via a local ARAX copy.
value_type_id: | biolink:InformationResource
value: | infores:cohd
 
attribute_source: | infores:arax-reasoner-ara
attribute_type_id: | biolink:aggregator_knowledge_source
value_type_id: | biolink:InformationResource
value: | infores:arax-reasoner-ara
```
while the [COHD API results](https://arax.ncats.io/?source=ARS&id=6529ce68-d65a-4fcc-9283-5fc8ca01d5b4) has edges with the following information:
```
attribute_source: | infores:cohd
-- | --
attribute_type_id: | biolink:original_knowledge_source
value_type_id: | biolink:InformationResource
value_url: | http://cohd.io/api/query
value: | infores:cohd
 
attribute_source: | infores:cohd
attribute_type_id: | biolink:supporting_data_source
value_type_id: | biolink:InformationResource
value_url: | http://cohd.io/api/
value: | infores:cohd
 
attribute_source: | infores:cohd
attribute_type_id: | biolink:p_value
description: | Chi-square p-value, unadjusted. http://cohd.io/about.html
original_attribute_name: | p-value
value_type_id: | EDAM:data_1669
value_url: | http://edamontology.org/data_1669
value: | no value!
 
attribute_source: | infores:cohd
attribute_type_id: | biolink:p_value
description: | Chi-square p-value, Bonferonni adjusted by number of pairs of concepts. http://cohd.io/about.html
original_attribute_name: | p-value adjusted
value_type_id: | EDAM:data_1669
value_url: | http://edamontology.org/data_1669
value: | no value!
 
attribute_source: | infores:cohd
attribute_type_id: | biolink:has_evidence
description: | Observed-expected frequency ratio. http://cohd.io/about.html
original_attribute_name: | ln_ratio
value_type_id: | EDAM:data_1772
value: | 5.2976174620800185
 
attribute_source: | infores:cohd
attribute_type_id: | biolink:has_confidence_level
description: | Observed-expected frequency ratio 0.99% confidence interval
original_attribute_name: | ln_ratio_confidence_interval
value_type_id: | EDAM:data_0951
value: | 5.2616641324834065.332660553093865
 
attribute_source: | infores:cohd
attribute_type_id: | biolink:has_evidence
description: | Relative frequency, relative to the subject node. http://cohd.io/about.html
original_attribute_name: | relative_frequency_subject
value_type_id: | EDAM:data_1772
value: | 0.9771096686026648
 
attribute_source: | infores:cohd
attribute_type_id: | biolink:has_confidence_level
description: | Relative frequency (subject) 0.99% confidence interval
original_attribute_name: | relative_freq_subject_confidence_interval
value_type_id: | EDAM:data_0951
value: | 0.91046089539104611.0486193061128157
 
attribute_source: | infores:cohd
attribute_type_id: | biolink:has_evidence
description: | Relative frequency, relative to the object node. http://cohd.io/about.html
original_attribute_name: | relative_frequency_object
value_type_id: | EDAM:data_1772
value: | 1.0133459312625488
 
attribute_source: | infores:cohd
attribute_type_id: | biolink:has_confidence_level
description: | Relative frequency (object) 0.99% confidence interval
original_attribute_name: | relative_freq_object_confidence_interval
value_type_id: | EDAM:data_0951
value: | 0.94367802987116631.0881704628949302
 
attribute_source: | infores:cohd
attribute_type_id: | biolink:has_count
description: | Observed concept count between the pair of subject and object nodes
original_attribute_name: | concept_pair_count
value_type_id: | EDAM:data_0006
value: | 8580
 
attribute_source: | infores:cohd
attribute_type_id: | biolink:has_count
description: | Observed concept count of the subject node
original_attribute_name: | concept_count_subject
value_type_id: | EDAM:data_0006
value: | 8781
 
attribute_source: | infores:cohd
attribute_type_id: | biolink:has_count
description: | Observed concept count of the object node
original_attribute_name: | concept_count_object
value_type_id: | EDAM:data_0006
value: | 8467
 
attribute_source: | infores:cohd
attribute_type_id: | EDAM:operation_3438
description: | Calculated expected count of concept pair. For ln_ratio. http://cohd.io/about.html
original_attribute_name: | expected_count
value_type_id: | EDAM:operation_3438
value: | 42.93003641176124
 
attribute_source: | infores:cohd
attribute_type_id: | biolink:provided_by
description: | Dataset ID within COHD
original_attribute_name: | dataset_id
value_type_id: | EDAM:data_1048
value: | 3
```

December Demo C will want to take advantage of this information. Can we do the same with our local copy?

**Comment by chunyuma** [comment]
Hi @dkoslicki, perhaps we can do the same thing with our local copy. Actually, there are more information in the local copy of cohd database that we didn't return (since we don't know what information we need). I guess the ARAX results were generated by `expand()` without specifying kp. So be default, when it called `kp=cohd`, it only ran `expand(kp=cohd, COHD_method='paired_concept_freq')` and thus it only returned `paired_concept_frequency` information. Perhaps we can set the default `expand(kp=cohd)` to something like `expand(kp=cohd, COHD_method='all')` which can return more information.

But if we want to return the exactly same information as COHD api returns, it might involve a few problems:

1. In the local copy, it doesn't contain the `confidence level` information. So I guess we have to calculate by ourselves. We have to take one of COHD api results and figure out how COHD team calculates these statistics (since they have three dataset, I don't know if the mean value which is used to calculate the confidence level is calculated from only one datasets or three datasets). If COHD team can tell us about this, that will be great. Otherwise, i might need to take some time to figure it out.
2. Regarding `Observed concept count of the object node` and `Observed concept count of the subject node`, we might get different values because the OMOP ids we used might be different from them. Currently, the omop ids of a specific curie in our side are from the mapping of all its synonym identifiers to Athena. And each OMOP id might have a `count` value. So if a curie has multiple OMOP ids, it might have multiple `count` value. In this case, do we sum them up as its final count? I don't know if this is correct.

**Comment by chunyuma** [comment]
Hi @dkoslicki, as for setting one more option `all` to expand(COHD_method), it seems like there is a problem. As I said in the last post, one curie might have multiple OMOP ids (however, COHD API seems to have one-on-one mapping between curie and OMOP id) which might also cause confusion if we want to return all information for a pair of subject curie and object curie. 

Here is a simple example: assume subject curie has two OMOP ids (e.g. 990029, 981807) and object curie has one OMOP id (e.g. 8507). Then they will have two possible OMOP id pairs (e.g. (25, 100) or (25,100)). We need to map these OMOP id pairs to the COHD local copy to access the corresponding information (how the pair info is stored in COHD local database):

```
dataset_id      concept_id_1    concept_id_2    concept_count   concept_prevalence      chi_square_t    chi_square_p    expected_count  ln_ratio        rel_freq_1      rel_freq_2
1       8507    955372  6       3.351148e-06    6.983689e-01    4.033323e-01    4.631562e+00    2.588652e-01    7.959006e-06    5.454545e-01
1       8507    985786  7       3.909673e-06    4.141921e-01    5.198494e-01    8.421023e+00    -1.848211e-01   9.285507e-06    3.500000e-01
1       8507    990029  7       3.909673e-06    2.040442e+00    1.531652e-01    1.052628e+01    -4.079647e-01   9.285507e-06    2.800000e-01
1       8507    924939  8       4.468198e-06    3.635890e-02    8.487762e-01    8.421023e+00    -5.128973e-02   1.061201e-05    4.000000e-01
1       8507    974677  8       4.468198e-06    2.014034e+00    1.558505e-01    5.473665e+00    3.794932e-01    1.061201e-05    6.153846e-01
1       8507    981807  8       4.468198e-06    8.018260e+00    4.630804e-03    1.684205e+01    -7.444369e-01   1.061201e-05    2.000000e-01
1       8507    993183  9       5.026723e-06    4.798856e+00    2.847864e-02    1.557889e+01    -5.486923e-01   1.193851e-05    2.432432e-01
1       8507    915663  10      5.585247e-06    2.247318e+00    1.338462e-01    1.431574e+01    -3.587744e-01   1.326501e-05    2.941176e-01
1       8507    929956  10      5.585247e-06    1.415989e-01    7.066966e-01    1.094733e+01    -9.051045e-02   1.326501e-05    3.846154e-01
1       8507    939259  10      5.585247e-06    8.364711e+00    3.825775e-03    1.978940e+01    -6.825615e-01   1.326501e-05    2.127660e-01
1       8507    948695  10      5.585247e-06    2.247318e+00    1.338462e-01    1.431574e+01    -3.587744e-01   1.326501e-05    2.941176e-01
1       8507    902430  11      6.143772e-06    9.911184e+00    1.642774e-03    2.231571e+01    -7.073956e-01   1.459151e-05    2.075472e-01
1       8507    915669  11      6.143772e-06    5.281292e+00    2.155574e-02    1.852625e+01    -5.212934e-01   1.459151e-05    2.500000e-01
1       8507    937793  11      6.143772e-06    3.640015e-01    5.462922e-01    1.263153e+01    -1.383011e-01   1.459151e-05    3.666667e-01
1       8507    940097  11      6.143772e-06    1.041651e+00    3.074377e-01    1.389469e+01    -2.336113e-01   1.459151e-05    3.333333e-01
1       8507    974166  11      6.143772e-06    9.130674e-02    7.625224e-01    1.178943e+01    -6.930824e-02   1.459151e-05    3.928571e-01
1       8507    997997  11      6.143772e-06    6.000871e+00    1.429882e-02    6.315767e+00    5.548461e-01    1.459151e-05    7.333333e-01
1       8507    904546  12      6.702297e-06    6.061480e-02    8.055268e-01    1.136838e+01    5.407078e-02    1.591801e-05    4.444444e-01
```

If we assign the lowest `chi-square p-value` as the final returned p-value and the largest `ln_ratio` as the infal returned `ln_ratio`. They might come from different OMOP id pairs. Therefore, their corresponding `concept_count`, `rel_freq_1`, `rel_freq_2` might be also from different OMOP id pairs. If we also sum up the `concept_count` and take the largest `rel_freq_1` and `rel_freq_2`. The final returned information might be a combination of the information of different OMOP id pairs. I don't know if it doesn't matter because this might cause confusion. You might find the mismatched information (e.g. ln_ratio != ln( expected_count ); expected_count != Count_1_and_2 * num_patients / (Count_1 * Count_2)).

I'm thinking if we should return the COHD API result by using `slow_mode` if the user chooses `expand(COHD_method='all')`.

**Comment by dkoslicki** [comment]
Ah, I see. We could theoretically tally up the counts ourselves (with the sum, as you say), and then update the new expected_count, and ln( expected_count), calculate a new chi_square value, etc. Given how slow the COHD API is, I wonder if this would be more efficient.

Stepping back though, it would be good to know if this one-to-many relationship with OMOP ids is due things like `ibuprofen 10mg`, `ibuprofen 15mg`, etc. In that case, the summing/recalculating approach would make sense. If it's something like (as in the table above) `OMOP 955372, ethanol` and `OMOP 985786 Ketoconazole` being synonomyzed, then there is a more significant issue at hand.

**Comment by chunyuma** [comment]
ok, now using `expand(kp=COHD, COHD_method=all)` can return the COHD information as close as what COHD API returns except for `adjusted p-value` and `confidence interval`.

**Comment by chunyuma** [comment]
@dkoslicki, can we close this issue now? I think this issue should be solved by using `expand(kp=COHD, COHD_method=all)`.

**Comment by dkoslicki** [comment]
Confirmed working in prod: https://arax.ncats.io/?r=24404 Closing (Thanks @chunyuma!)
