### ISSUE TITLE
ARAX is making edges that point in both directions Workflow A.8

### ISSUE THREAD

**Issue by edeutsch** [RTXteam/RTX#1611]
Apologies if there's already an issue for this, but this came up at the Translator mini-hackathon this morning and I was not able to muster a good answer:

https://github.com/NCATSTranslator/minihackathons/issues/214

ideas?

**Comment by amykglen** [comment]
ah, yeah, I think this will be addressed with #1527 - shall I prioritize that issue?

**Comment by edeutsch** [comment]
I really don't know how severe it is, seems like a minor issue to me. But since it comes up in the mini-hackathons, we will be asked about in a week again I suspect.

**Comment by amykglen** [comment]
status of this issue for the record: its deployment is tied to roll-out of a new KG2 version, so expected to occur within the next couple weeks.

**Comment by amykglen** [comment]
are we good to close this one, @edeutsch? (I see you commented in https://togithub.com/NCATSTranslator/minihackathons/issues/214)

also, just a heads up for everyone: ARAX doesn't always ignore qedge direction now - it only does for symmetric predicates. I did put a special exception in place for `biolink:treats`, since a mistake is easy to detect in that case (i.e., Expand will flip `treats` qedges that seem to be going in the wrong direction and issue a warning), but all other asymmetric predicates are now sensitive to which qnode is the subject vs. object.

**Comment by edeutsch** [comment]
super, yes, thanks! closing.
