### ISSUE TITLE
Should Ranker consider publications from sources other than SEMMEDDB?

### ISSUE THREAD

**Issue by amykglen** [RTXteam/RTX#1628]
the ranker currently computes some sort of score based on the number of publications that SEMMEDDB edges have.

is there a reason why that score is only calculated for SEMMEDDB edges, and not for edges from other knowledge sources?

there are some other KG2 knowledge sources that provide publications and some of our other KPs also sometimes provide publications.

**Comment by finnagin** [comment]
So currently the publication ranking just downranks the SEMMEDDB edges with a few publications while leaving the score the same for SEMMEDDB edges with many publications. I think if we stated adding a ranking for other knowledge sources publications we might want to do it on a per knowledge source bases an SEMMEDDB likely has to be downranked much more aggressively than say a curated knowledge source since it is generated  using nlp. 

@amykglen so you happen to know what other knowledge sourced provide publications?

**Comment by finnagin** [comment]
Adding @dkoslicki is case he had any thoughts on this.

**Comment by dkoslicki** [comment]
@finnagin is it the case that the node property name for SEMMEDDB and non-SEMMEDDB publications the same? If so, can you verify that the ranker is using that when accounting for publications?

**Comment by dkoslicki** [comment]
@finnagin bump ^^

**Comment by finnagin** [comment]
Yeah the attribute name is the same it is `biolink:publications`. Though that is an edge attribute not a node property. It identifies semeddb edges by a  the value `infores:semmeddb` for the the edge attribute `biolink:knowledge_source`.

**Comment by dkoslicki** [comment]
Or right, of course it's an edge property. How about changing the ranker to do the simplest approach first: 

A) just union the counts of all the publications, regardless of knowledge source (so treating non-semmeddb edges as if they were).

A more nuanced approach would be to B) gather the list of non-semmeddb knowledge sources that have publications and make custom sigmoids for each. 

So Finn, can you go with approach A and put approach B as something to discuss during an AHM?

**Comment by finnagin** [comment]
Sure, I can do that. Should make the change now in master or put it in a branch and merge after the relay?

**Comment by dkoslicki** [comment]
Still TODO
