### ISSUE TITLE
Q11 example not working

### ISSUE THREAD

**Issue by edeutsch** [RTXteam/RTX#164]
Q11: What microRNAs are expressed in the retina?
gets restated as:
What genes are expressed in retina?

and then that question gets answered. which is the same as Q8.

Fix? or remove from example questions?

**Comment by edeutsch** [comment]
Q15 and Q22 are in the same boat. The translator interprets microRNAs as something else.

**Comment by dkoslicki** [comment]
Remove from example questions (haven't come up with a way to handle microRNAs, since it's not an english word and ``nltk`` doesn't like it. Eric, can you remove from QuestionExamples.tsv (I don't know if prepending a line with ``#`` will do it or not, and I don't want to break your parsing of that file).

**Comment by edeutsch** [comment]
Prepending a # should work, but the official way is to turn column 2 into false. This means it is masked until such a time as we can find a good answer.

But note that the example for Q6 does work:
What micrornas control the expression of G6PD?

This seems to be parsed correctly and returns what seems to be microRNAs.

So I could comment out all microRNA questions *except* Q6?
Or does a working Q6 provide a hint on how the others could be fixed?

**Comment by dkoslicki** [comment]
Fixed due to progress in #170. So no need to comment this one out. Closing
