### ISSUE TITLE
Expander stop sending redundant curies to KPs?

### ISSUE THREAD

**Issue by edeutsch** [RTXteam/RTX#1674]
Part of the discussion today at the Translator mini-hackathon centered around the timeouts and one conclusion seemed to be that ARAX should not be sending redundant queries to the KPs since this is unnecessary and slows them down. They all professed to be doing node normalization. The idea was that this may be why they are timing out because we send them lots of curies. Here's one screen grab of an example (although not the one we were looking at:
![image](https://user-images.githubusercontent.com/12707718/134555396-b67bad0c-81ab-4a95-a076-a2c954b8344a.png)
We send 1 curies to RTX-KG2, but 7 or 8 curies to the others.
There was at least some contention that if one sends just the original curies to these KPs, then they resturn answers well before the timeout.
Here they're taking quite a long time to process those multiple CURIEs:
![image](https://user-images.githubusercontent.com/12707718/134555611-b9cf9c99-4e1e-4aad-a3d0-825d9fc62c6e.png)
In this case, most but not all meet the 30 second deadline, but sometimes they don't?

**Comment by edeutsch** [comment]
I suppose the idea is that we are now at a point where it would be better for KPs to fail because we send them 1 CURIE that they claim to support but don't do so properly rather than send them a whole raft of equivalent CURIEs and they timeout dealing with the set. Here's a repro query:
```
{
  "edges": {
    "e01": {
      "exclude": false,
      "object": "n1",
      "predicates": [
        "biolink:related_to"
      ],
      "subject": "n0"
    }
  },
  "nodes": {
    "n0": {
      "categories": [
        "biolink:Gene"
      ],
      "is_set": true
    },
    "n1": {
      "categories": [
        "biolink:ChemicalEntity"
      ],
      "ids": [
        "CHEBI:45783"
      ],
      "is_set": false
    }
  }
}
```
although I know there's a better one out there, but I can't find it.

**Comment by amykglen** [comment]
noting for the record: I briefly investigated doing this recently but immediately ran into an issue with genes where it's hard to know 'which' gene (out of the curies with supported prefixes) to send, because, for instance, gene 'clusters' in the synonymizer often have multiple NCBIGene IDs in them (the mouse version, human version, rat version, etc.). most KPs will only answer the human version I think, but we'd have to be able to figure out which gene is the human one...

**Comment by edeutsch** [comment]
hmm. tricky.
Can it be designed so that if there are multiple CURIES with the same prefix, then go ahead and then those multiples? But only in that case. So in the above case, if the KP wants a CHEMBL and there's only one CHEMBL, then send that. If our synonymizer finds two CHEMBLs, well, then in that case send both.

**Comment by edeutsch** [comment]
Here's the minihackathon issue. Not much detail, but this is the same:
https://togithub.com/NCATSTranslator/minihackathons/issues/295

**Comment by amykglen** [comment]
yeah, that might resolve the majority of the problems - that's very similar to what we already do, except instead of sending only CHEMBL curies, we send all curies that have a prefix the KP says it supports (so maybe CHEMBL and CHEBI and Drugbank).

so I suppose we should just pick one supported prefix (randomly?) and send all curies with that prefix?

**Comment by edeutsch** [comment]
yes, exactly! Not sure about the "randomly" part. But I don't really have a better idea than that.

**Comment by rtroper** [comment]
As another data point on this issue, the following might be related: https://github.com/NCATSTranslator/minihackathons/issues/289

**Comment by edeutsch** [comment]
AH, that's the one I was looking for:
![image](https://user-images.githubusercontent.com/12707718/134595195-23154a1b-d713-48f6-9cc8-5f7d249ccd6c.png)
RTX-KG2 gets 1 curies and all the rest get lots.
It was thought that this might be the reason for their underperformance.
![image](https://user-images.githubusercontent.com/12707718/134595270-ee9581ba-dd06-4d1b-82a5-b29466ab0c48.png)
```

    "message": {
        "query_graph": {
            "nodes": {
                "n00": {
                    "categories": [
                        "biolink:Disease"
                    ],
                    "ids": [
                        "MONDO:0005301"
                    ],
                    "is_set": false,
                    "constraints": []
                },
                "n01": {
                    "categories": [
                        "biolink:SmallMolecule"
                    ],
                    "is_set": false,
                    "constraints": []
                }
            },
            "edges": {
                "e00": {
                    "subject": "n00",
                    "object": "n01",
                    "predicates": [
                        "biolink:has_real_world_evidence_of_association_with"
                    ],
                    "constraints": [],
                    "exclude": false
                }
            }
        }
    }
}
```

**Comment by amykglen** [comment]
alright, I pushed a change so that if a curie uses a prefix the KP says it supports for the given qnode's categories (or descendant categories), then Expand just leaves that curie as it is. but if it uses an unsupported prefix, then it will convert that curie to a prefix that the KP does recognize (may technically be transformed to more than one curie, in the event that the 'cluster' contains more than one equivalent curie with the same prefix).

the above query indeed now seems to see fewer timeouts: https://arax.ncats.io/?r=27647
<img width="924" alt="Screen Shot 2021-09-23 at 9 53 39 PM" src="https://user-images.githubusercontent.com/49423686/134620649-a38fad37-39e5-42cc-a49b-7b29c5a39ebd.png">
<img width="867" alt="Screen Shot 2021-09-23 at 9 54 14 PM" src="https://user-images.githubusercontent.com/49423686/134620656-aa43a53e-d1b0-441b-be97-700b01234fa9.png">

**Comment by edeutsch** [comment]
This looks really great! @rtroper does this seem good to you?

**Comment by rtroper** [comment]
> This looks really great! @rtroper does this seem good to you?

Thanks! Yes, this does look better. It's finishing much more quickly than before.

**Comment by edeutsch** [comment]
This seems to have helped a lot. closing.
