### ISSUE TITLE
KGNodeIndex returns OMIM:146850 for token "is"

### ISSUE THREAD

**Issue by dkoslicki** [RTXteam/RTX#172]
This isn't good since a lot of our questions include "is" (_what is the..._).
```python
KGNodeIndex.KGNodeIndex().get_curies("is")
Out[61]: ['OMIM:146850']
```

**Comment by edeutsch** [comment]
The problem is that I thought it would be a good idea to add the abbreviations of diseases if there is one. AD, ADHD, HD. Unforunately Immune Suppression is apparently abbreviated IS. Your fix seems plausible, but a better fix is probably to add in special code not to add IS or other abbreviations that are actually common words. I will implement that fix sometime. But in the mean time there is a bigger parsing problem afoot.

**Comment by dkoslicki** [comment]
Ok, we'll go with the hacky solution until post-hackathon. Closing
