### ISSUE TITLE
aiohttp.client_exceptions.ContentTypeError in RTX-KG2 on arax-backup

### ISSUE THREAD

**Issue by saramsey** [RTXteam/RTX#1729]
On https://arax-backup.rtx.ai/fork-test, when I run the following JSON query through ARAX:
```
{
  "message": {
    "query_graph": {
      "edges": {
        "e04": {
          "object": "n4",
          "predicates": [
            "biolink:related_to"
          ],
          "subject": "n2"
        }
      },
      "nodes": {
        "n2": {
          "categories": [
            "biolink:Protein",
            "biolink:Gene"
          ],
          "ids": [
            "UniProtKB:P42263",
            "UniProtKB:P49908",
            "UniProtKB:P00167",
            "UniProtKB:Q14126",
            "UniProtKB:P14923",
            "UniProtKB:Q03692",
            "UniProtKB:P51793",
            "NCBIGene:22899",
            "UniProtKB:Q30154",
            "UniProtKB:P98161",
            "UniProtKB:Q9UPQ9",
            "UniProtKB:P18505",
            "UniProtKB:Q96PV0",
            "UniProtKB:P20393",
            "UniProtKB:Q9Y6X0",
            "UniProtKB:P51686",
            "UniProtKB:Q8TAB3",
            "NCBIGene:51499",
            "UniProtKB:Q02108",
            "UniProtKB:Q99250",
            "UniProtKB:Q7L2H7",
            "UniProtKB:Q14896",
            "UniProtKB:P51649",
            "UniProtKB:P63096",
            "UniProtKB:Q8IUX4",
            "UniProtKB:Q7KZN9",
            "UniProtKB:Q92736",
            "UniProtKB:Q8IZU9",
            "UniProtKB:Q7Z589",
            "UniProtKB:Q99574",
            "UniProtKB:P35557",
            "UniProtKB:Q99959",
            "UniProtKB:Q969V4",
            "UniProtKB:Q9H2D6",
            "UniProtKB:Q12879",
            "NCBIGene:4724",
            "UniProtKB:P49639",
            "UniProtKB:Q9BXA5",
            "UniProtKB:Q9UQD0",
            "UniProtKB:Q9H5P4",
            "UniProtKB:P37023",
            "UniProtKB:Q9UI40",
            "UniProtKB:Q9H2P0",
            "UniProtKB:P58400",
            "UniProtKB:P49419",
            "UniProtKB:Q7Z6Z7",
            "NCBIGene:845",
            "UniProtKB:Q1HG43",
            "UniProtKB:Q6ZVL6",
            "UniProtKB:P17693",
            "UniProtKB:Q16650",
            "UniProtKB:Q5HYJ1",
            "UniProtKB:Q05586",
            "UniProtKB:Q14721",
            "UniProtKB:Q9P258",
            "UniProtKB:Q9UPX8",
            "UniProtKB:P23141",
            "UniProtKB:Q13061",
            "UniProtKB:P12814",
            "NCBIGene:8800",
            "NCBIGene:219578",
            "UniProtKB:Q8NFP9",
            "UniProtKB:Q8N0W4",
            "UniProtKB:P30038",
            "UniProtKB:O60281",
            "UniProtKB:Q6UB99",
            "UniProtKB:Q12809"
          ],
          "is_set": true
        },
        "n4": {
          "categories": [
            "biolink:BiologicalProcessOrActivity"
          ],
          "is_set": true
        }
      }
    }
  },
  "submitter": "infores:arax"
}
```
I get the following error:  
> 2021-11-13T22:51:20.284058 WARNING: RTX-KG2: Request threw exception after 3 seconds: <class 'aiohttp.client_exceptions.ContentTypeError'>

**Comment by saramsey** [comment]
Commit a229118 should fix the issue.

**Comment by saramsey** [comment]
This reminds me, @edeutsch should we set the `content_type` to `application/json` for the ARAX `query_controller.py` as well?

**Comment by edeutsch** [comment]
> This reminds me, @edeutsch should we set the `content_type` to `application/json` for the ARAX `query_controller.py` as well?

I rather suspect it doesn't matter that much.

But I used to have it that only the streaming mode would set the mime-type:
https://github.com/RTXteam/RTX/blob/NewFmt/code/UI/OpenAPI/python-flask-server/openapi_server/controllers/query_controller.py
Non-streaming let the Flask framework set the mime-type, which I assume was application/json
It looks like you unified everything to a single return.

The rationale for not having application/json in the streaming mode is because it is not a single json response (which is what I think application/json implies) but rather a series of objects. I was actually thinking that we should change the content-type to 'text/event-stream' (but only for the stream of course).

Looking at the code a little more closely, though, what happened to the HTTP code setting? As seen in the older version:
https://github.com/RTXteam/RTX/blob/NewFmt/code/UI/OpenAPI/python-flask-server/openapi_server/controllers/query_controller.py
Did that get removed? Or handled elsewhere? I think we want to preserve the ability to send back HTTP codes other than 200.

**Comment by edeutsch** [comment]
okay, I was a little confused by what I was seeing in various places. Currently deployed code only sets the mime-type for streaming responses, but not for non-streaming. But it appears that the code in master unifies these in a way that I'm thinking is not a good idea.

And also, it looks like the HTPP code setting logic for non-streaming responses for the code in `master` has been lost. What is the rationale for that?

I think you're right that deploying current code is master would break things.
