### ISSUE TITLE
Check example questions

### ISSUE THREAD

**Issue by dkoslicki** [RTXteam/RTX#173]
Running through all the example questions now looking for any error or classifications.

**Comment by dkoslicki** [comment]
@edeutsch @jaredroach @edeutsch All of Jared's questions are now running without error (at least on the back-end, and only for the ones marked true). Please test the UI to:
1. Populate the cache with the example questions (@edeutsch **Do you need to flush the cache on production as some of the questions will return different results?**)
2. Test for any UI bugs or things I didn't catch on a single run-through.

**Comment by edeutsch** [comment]
@dkoslicki at this point I don't want to majorly "flush the cache anymore, although I suppose I could if there was a real need. If you have reason to believe that query results may now be different, the two best options IMO are either for you to rerun the affected queries with Luis's cache switch turned OFF (that's why it's there) or for you to bump up the RTX version number and then I roll that code out to production (or dev or test) and then rerun the queries again. Since the version number is different, the cache will be bypassed because the cached result version does not match current code version. Either way is fine. Although the latter involves me, while the former does not.
