### ISSUE TITLE
error building Docker image from Dockerfile-Merged

### ISSUE THREAD

**Issue by saramsey** [RTXteam/RTX#1739]
When I try to build a Docker image from `Dockerfile-Merged`, I see this error at step 42:
```
Step 42/53 : RUN update-rc.d RTX_Complete enable
 ---> Running in d7af458ca0e2
Failed to enable unit, unit RTX_Complete.service does not exist.
```
I'm assuming this is not expected?  Or at least, not desirable?  I am unsure how to fix. I should note that Docker build carries on bravely after this, culminating with:
```
Removing intermediate container a364b672435d
 ---> a66f3931f4f2
Successfully built a66f3931f4f2
Successfully tagged arax:1.0
```

**Comment by saramsey** [comment]
Tentatively labeling "bug" but I am not really sure....

**Comment by saramsey** [comment]
Yes, I am able to run `apache2`, `RTX_OpenAPI_kg2`, and `RTX_OpenAPI_production` inside the container. So the container appears to be functional.
```
root@63db69d152e8:/etc/apache2/sites-enabled# service --status-all
 [ - ]  RTX_Complete
 [ + ]  RTX_OpenAPI_kg2
 [ + ]  RTX_OpenAPI_production
 [ - ]  apache-htcacheclean
 [ + ]  apache2
 [ - ]  dbus
 [ ? ]  hwclock.sh
 [ - ]  procps
 [ - ]  rsync
 [ - ]  unattended-upgrades
 [ - ]  x11-common
```

**Comment by saramsey** [comment]
BTW, what is `RTX_Complete`?

**Comment by edeutsch** [comment]
> 
> 
> BTW, what is `RTX_Complete`?

word autocompletion for the synonyms service.

**Comment by saramsey** [comment]
Ah, thank you

**Comment by saramsey** [comment]
Now I'm seeing this error:
```
Step 52/53 : RUN update-rc.d RTX_OpenAPI_kg2 enable
 ---> Running in 346b21007aaf
Failed to enable unit, unit RTX_OpenAPI_kg2.service does not exist.
```
I wonder if there is some kind of weird race condition?

**Comment by saramsey** [comment]
Also this error:
```
Step 37/53 : RUN update-rc.d RTX_OpenAPI_production enable
 ---> Running in 79191528d4d9
Failed to enable unit, unit RTX_OpenAPI_production.service does not exist.
```

**Comment by saramsey** [comment]
Hi @finnagin any status on this?

**Comment by finnagin** [comment]
@saramsey Not yet. I was treating this as low priority since this doesn't seem to hinder the running of the service at all. I'm not exactly sure what is the best thing to try to change here though. Should I just remove the enable line? Since it seems to spit out the error and the service runs fine anyway?

**Comment by finnagin** [comment]
I admit that I may be a little confused on what the update-rc.d enable command does. Looking at the documentation it looks like it allows it to start the service on startup but does that make sense in the context of a docker container? @edeutsch would you be able to shed some light?

**Comment by edeutsch** [comment]
My usual protocol is this:

cd RTX/code/UI/OpenAPI/python-flask-server
cp -p RTX_OpenAPI_kg2beta /etc/init.d/
cd /etc/init.d/
update-rc.d RTX_OpenAPI_kg2beta defaults


It is my understanding that when you run:

update-rc.d RTX_OpenAPI_kg2beta defaults

it creates sym links in all the different runlevel directories so that the service starts and stops as the system switches to different runlevels.

But I think you’re right that that is probably ignored/irrelevant for a docker container.
So it seems likely upon reflection that that is a useless thing to do. I started doing it because that’s what I always used to do when I install new services on a host OS. And just kept foolishly doing inside the docker container uselessly.

so you can probably skip the update-rc.d command.
Although I'm not certain.

**Comment by saramsey** [comment]
> @saramsey Not yet. I was treating this as low priority since this doesn't seem to hinder the running of the service at all. I'm not exactly sure what is the best thing to try to change here though. Should I just try removing the enable line and see if it still works? Since it seems to spit out the error and the service runs fine anyway?

Yes, if there is a way to simply silence the warning/error message on install, that works for me!
