### ISSUE TITLE
Alternative for QEdge.exclude?

### ISSUE THREAD

**Issue by edeutsch** [RTXteam/RTX#1766]
If I understand correctly, we have a QEdge.exclude property that is unique to ARAX. If I understand it correctly it allows this:

add_qnode(name=multiple sclerosis, key=n0)
add_qnode(categories=biolink:SmallMolecule, key=n1)
add_qedge(subject=n0, object=n1, key=e0)
add_qedge(subject=n0, object=n1, key=e1, predicates=biolink:contraindicated_for, exclude=true)

The meaning of this is: get me all SmallMolecules associated with multiple sclerosis, *except* for those that are contraindicated for it.
Is that right?

In discussing this proposal with the TRAPI group, it was suggested that instead of having two edges like this, it would be cleaner to have excluded be a predicate list. So instead:

add_qnode(name=multiple sclerosis, key=n0)
add_qnode(categories=biolink:SmallMolecule, key=n1)
add_qedge(subject=n0, object=n1, key=e0, excluded_predicates=[biolink:contraindicated_for])

So the QEdge.predicates would be included ones and excluded_predicates would be those to ignore.

What do you think of this?
Is it just as good?
Is it better?
Is there a flaw for what we're trying to accomplish?
Is it a fine idea for TRAPI 1.3?
Could we implement this pretty easily in Expand?

What do you think?

**Comment by saramsey** [comment]
Interesting idea. In addition to impacting Expand, would this proposal not also impact Resultify, because it would entail a change in the query graph structure? And Ranker, too, maybe?  Interestingly, from a cursory inspection of the code it doesn't appear that Ranker is currently ignoring "exclude" type qedges, so I wonder if that should be changed if we stick with the two-qedge approach; but I guess if we move to the "single qedge" approach, then it becomes a non-issue.

I feel the current two-qedge system is a bit more flexible, because you could have a query graph like this:

A[disease] <- B[gene], "biolink:related_to"
C[small molecule] -> B[gene], "biolink:related_to"
C[small module] -> A[disease], exclude "biolink:contraindicated_for"

right?  So you get no points for an edge C->A whatsoever, and furthermore, any triple of nodes for which there is C-[contraindicated_for]->A would be excluded.

**Comment by saramsey** [comment]
I'd like to get @amykglen's take on this

Also I've put it on the agenda for the 5th.

**Comment by edeutsch** [comment]
Thanks, your example is a compelling one keeping the exclude=True notation.

**Comment by amykglen** [comment]
agree with Steve's sentiment! I do think what we have provides quite different (more) functionality than the proposed `excluded_predicates`.

**Comment by saramsey** [comment]
Can we close this issue out?
