### ISSUE TITLE
biomarker_for results appear to be rubbish

### ISSUE THREAD

**Issue by dkoslicki** [RTXteam/RTX#1774]
From today's standup: https://arax.ncats.io/?r=0a0efe04-9f73-410e-89ae-1e1f9c2e658f
it appears that most/all results are just plain terrible. Things like "Rheumatologist is a biomarker for psoriatic arthritis". Unclear what the cause of this could be (since poor results are returned by KG2, BTE, etc.), but certainly seems worth investigating.

Tagging KG2 team, but feel free to un-assign as appropriate.

**Comment by dkoslicki** [comment]
Other notes:
Changing the `NamedThing` to `Protein` returns no results, but changing it to `BiologicalEntity` reveals quite a few nodes appear to be misclassified: https://arax.ncats.io/?r=35579
Eg. "diagnosis" isn't a biological entity, right?

**Comment by saramsey** [comment]
Thank you for the bug report. 

Digging into this, one thing I notice right off the bat is that we are getting (from SemMedDB) a lot of procedures being connected to diseases/conditions, via `biolink:biomarker_for`. Details in [RTX-KG2 issue 194](https://github.com/RTXteam/RTX-KG2/issues/194). So that should be an easy fix for the next KG2 build. However, that may not be the only issue with the results for the original query that was looking for biomarkers of rheumatoid arthritis. I will have to do some more digging.

**Comment by saramsey** [comment]
In fairness, we were using the mapping for `SEMMEDDB:diagnoses` to `biolink:biomarker_for` that came straight from Biolink
https://github.com/biolink/biolink-model/blob/ca93f7ebd7fd52437b23a7195b51f54d74b81d37/biolink-model.yaml#L4469

but in issue 194, you can see evidence that the Biolink model-suggested mapping is problematic.

**Comment by saramsey** [comment]
I haven't looked into the BTE results, but I note that if they are using the Biolink-suggested predicate mapping of `SEMMEDDB:diagnoses` to `biolink:biomarker_for`, then they would be affected as well.

**Comment by saramsey** [comment]
Fixed.
