### ISSUE TITLE
Query for cataracts returning kidney disease

### ISSUE THREAD

**Issue by cbizon** [RTXteam/RTX#1780]
This standup query: https://github.com/NCATSTranslator/testing/blob/main/ars-requests/not-none/1.2/cataractTreatment.json

is basically (n0:Procedure)-[treats]->(n1 "Cataract").

Querying RTXKG2 directly returns many different values for n1.  Many of them are proper subclasses of cataract (at least according to MONDO).

But there are quite a few that are not, mainly terms relating to kidney disease:
MONDO:0020642 polycystic kidney disease
MONDO:0004691 autosomal dominant polycystic kidney disease
MONDO:0002473 cystic kidney disease
MONDO:0015268 medullary sponge kidney

This causes problems for Aragon when it goes to merge answers.

**Comment by saramsey** [comment]
Here's a [reprex](https://arax.ncats.io/?r=36254) of the issue using ARAX.

**Comment by saramsey** [comment]
Thank you @cbizon for reporting this. We are on it.

**Comment by amykglen** [comment]
looks like this issue has already been fixed in KG2, and fully deployed. (e.g., on https://kg2.transltr.io/ -  I don't see anything about kindeys in KG2's response)

I'm going to close this, but please reopen if you see any issues, @cbizon!

<img width="1412" alt="Screen Shot 2023-05-03 at 3 43 02 PM" src="https://user-images.githubusercontent.com/49423686/236066740-24934e00-b6f1-48b2-9355-71e939f9edc2.png">
