### ISSUE TITLE
double-adding infores:biothings-explorer?

### ISSUE THREAD

**Issue by edeutsch** [RTXteam/RTX#1802]
I notice in one of the results of the Question of the month:
https://arax.ncats.io/?r=b3ffebd5-95a6-4cc3-8007-8dc6bf6d2a17

In the ARAX result:
https://arax.ncats.io/?r=37343

In the single returned result, I see two attributes on the edge:
![image](https://user-images.githubusercontent.com/12707718/155604360-8822af1d-2c3d-46bc-9325-33f97ee2d494.png)

![image](https://user-images.githubusercontent.com/12707718/155604431-0d0298dd-8a8e-4d8a-894d-9ca3f359866b.png)

It seems like this second attribute is unnecessary (only added if missing) and perhaps due to a bug?

**Comment by amykglen** [comment]
I was hoping this would be fixed with the latest code changes (on beta), but it looks like it wasn't: https://arax.ncats.io/beta/?r=37359

guess it's some other bug with the way Expand decides whether to add that attribute

**Comment by rcpeene** [comment]
The logic to check whether or not the kp name is already in the edge attributes after the edge is received from a kp can be found [here](https://github.com/RTXteam/RTX/blob/dd1de262d0817f7e6d2f64e5bec7d5009a3a2740/code/ARAX/ARAXQuery/Expand/trapi_querier.py#L314).

The problem seems to be that the attribute values can either be a string or a list of strings (i.e. 'value' or ['value']), so comparing the kp name to the attribute directly using the `==` operator doesn't cover the case where the kp name is ['kp_name_here']. It looks like the best fix is to change the line to the following:
`if not any(self.kp_name in attribute.value for attribute in returned_edge.attributes):`

This has been implemented and a merge request into master has been issued

**Comment by rcpeene** [comment]
The fix shown above was implemented with two typos which were preventing the bug fix from working in some cases. The bugfix was revised and changes pushed directly to master. Will have to verify this when master is rolled out next.
