### ISSUE TITLE
The time for ITRB has come!

### ISSUE THREAD

**Issue by edeutsch** [RTXteam/RTX#1824]
At this week's architecture call, we had the collective realization that it is time to get serious about ITRB! (I didn't push it, honest!)

Our task for the next week is to get our ITRB instances ship shape and switch our SmartAPI registrations to point to our ITRB instances. We will be asked to report on our status wrt ITRB deployments at next Tuesday's Architecture call!

What needs to be done to get everything buttoned up?

**Comment by finnagin** [comment]
I'll have to update the database files on the sftp server after the 2.7.5 rollout today and I'll need to update the dockerfile to setup ITRB to use the query mysql server. Then I'll need to work with ITRB to get them to pull the latest code and redeploy.

**Comment by finnagin** [comment]
Note to self: filename for identification is `config.domain` and it lives in /code

**Comment by amykglen** [comment]
I think it'd also be good to figure out which of their Plover instances their prod/test/dev KG2 instances are using. (because as far as I can tell, only their "dev" Plover works - not "prod" or "test")

**Comment by edeutsch** [comment]
> Note to self: filename for identification is `config.domain` and it lives in /code

As on now, config.domain might be this:
```
arax.ci.transltr.io
```

But I wonder if it might be better to replace this with something a little more flexible like a file called config_instance_settings.json with content like:
```
{
  "instance_name": "arax.ci.transltr.io",
  "maturity_level": "ci",
}
```

This file would be different for the 3 different ITRB instances and different on arax.ncats.io and arax-test.rtx.ai, etc. They could all share the same config_v2.json, but have this instance-specific file?

Just an idea..

**Comment by edeutsch** [comment]
> I think it'd also be good to figure out which of their Plover instances their prod/test/CI KG2 instances are using. (because as far as I can tell, only their "CI" Plover works - not "prod" or "test")

@amykglen would you pester ITRB about seeing that all three instances are running and working? The claim is that all should be working now.

**Comment by amykglen** [comment]
yep - I'll bug them!

**Comment by amykglen** [comment]
ok, so it turns out that the wrong Plover URLs are listed in [this spreadsheet](https://docs.google.com/spreadsheets/d/1Qge8SXmPhiI8xM_gBWprlWJKL_hlPEiLyefJdXJ72II/edit#gid=447123908). the correct URLs are:
```
CI: https://kg2cploverdb.ci.transltr.io
Test: https://kg2cploverdb.test.transltr.io
Prod: https://kg2cploverdb.transltr.io
```
and indeed all three of those instances appear to be working currently. (I pointed out the incorrect URLs to Kanna earlier today and he said he would update that spreadsheet.)

and some other good news: their continuous deployment seems to have worked for the first time for Plover! the CI Plover instance was automatically redeployed after my commit this morning and is now running KG2.7.5c.

the test and prod ITRB Plovers are still on KG2.7.4c. I suppose technically we shouldn't be rolling out new KG2 versions in the ITRB Plovers without updating the KG2 and ARAX ITRB instances simultaneously... in this case I don't think it should break anything to have Plover on a different KG2 version than KG2 API/ARAX, but other times it might. should I ask them to redeploy the test and prod Plovers now? or should we ask them to do that at the same time as the KG2 API/ARAX instances?

and by the way @finnagin - the master config file has now been updated like we discussed (pointing to the ITRB CI Plover), so it's good to go for the ITRB deployments.

**Comment by edeutsch** [comment]
great!
I'm thinking that it seems like a reasonable ask to request that since all the services depend on each other we'd like to update ARAX, KG2, and ProverDB all at the same time. and see what happens.

But I don't feel strongly. if you want to do them separately, that's fine, too.

**Comment by amykglen** [comment]
ok, cool - I like the idea of asking them to update them simultaneously. so maybe @finnagin and I should coordinate requesting updates

**Comment by finnagin** [comment]
Thanks @amykglen ! Yeah, I agree about asking together. For some reason these messages got buried in my inbox but glad you saw I messaged them and posted as well.

**Comment by edeutsch** [comment]
Looks like we're in pretty good shape except for the SmartAPI registration. okay to close?

**Comment by finnagin** [comment]
Yeah, I think so.
