### ISSUE TITLE
Bad conflation: disease with anatomical entity

### ISSUE THREAD

**Issue by dkoslicki** [RTXteam/RTX#1847]
See: https://arax.ncats.io/?r=44476

Via: https://arax.ncats.io/?r=44476

**Comment by amykglen** [comment]
-- just adding notes on the problem node --

UBERON:0000916 - 'abdomen'

```
{
   "attribute_source":null,
   "attribute_type_id":"biolink:category",
   "attributes":null,
   "description":"Categories of all nodes in this synonym set in RTX-KG2.",
   "original_attribute_name":null,
   "value":[
      "biolink:AnatomicalEntity",
      "biolink:InformationContentEntity",
      "biolink:NamedThing",
      "biolink:PhenotypicFeature",
      "biolink:Disease",
      "biolink:DiseaseOrPhenotypicFeature",
      "biolink:PathologicalProcess",
      "biolink:BiologicalEntity",
      "biolink:OrganismTaxon"
   ],
   "value_type_id":"metatype:Uriorcurie",
   "value_url":null
},
{
   "attribute_source":null,
   "attribute_type_id":"biolink:synonym",
   "attributes":null,
   "description":"Names of all nodes in this synonym set in RTX-KG2.",
   "original_attribute_name":null,
   "value":[
      "Abdominopelvic structure",
      "dizziness",
      "Abdominal",
      "Other peripheral vertigo",
      "Dizziness and giddiness symptoms",
      "Vertigo, Peripheral",
      "lightheadedness",
      "Abdominal Cavity",
      "Vertigo",
      "peripheral vertigo",
      "abdomen",
      "Dizziness",
      "Abdomen",
      "Vertigo, Intermittant",
      "Lightheadedness",
      "Vertigo, Brain Stem",
      "Vertigo, Essential",
      "abdominal cavity",
      "Positional Vertigo",
      "vertigo",
      "Abdominal cavity",
      "Vertigo, Constant",
      "Orthostasis",
      "giddiness, vertigo"
   ],
   "value_type_id":"metatype:String",
   "value_url":null
},
{
   "attribute_source":null,
   "attribute_type_id":"biolink:xref",
   "attributes":null,
   "description":"Identifiers of all nodes in this synonym set in RTX-KG2.",
   "original_attribute_name":null,
   "value":[
      "LOINC:LP6990-8",
      "UMLS:C0012833",
      "NCIT:C38057",
      "UMLS:C0522359",
      "OMIM:MTHU001035",
      "OMIM:MTHU046180",
      "UBERON:0003684",
      "UMLS:C0476206",
      "UMLS:C0220870",
      "UMLS:C0234757",
      "NCBITaxon:145161",
      "MESH:D034841",
      "MESH:D004244",
      "UMLS:C0155501",
      "UMLS:C0042571",
      "UMLS:C0522349",
      "NCIT:C37943",
      "NCIT:C12664",
      "UMLS:C0149746",
      "UBERON:0000916",
      "LOINC:LP35080-8",
      "LOINC:LA7428-1",
      "DOID:9847",
      "MESH:D000005",
      "SYMP:0019179",
      "FMA:9577",
      "NCIT:C25342",
      "PSY:14800",
      "LOINC:MTHU001425",
      "NCIT:C118255",
      "OMIM:MTHU000219",
      "UMLS:C0029706",
      "LOINC:LA12706-0",
      "LOINC:LP199956-6",
      "SYMP:0000610",
      "PSY:00010",
      "EFO:0009847",
      "NCIT:MPN-SAF",
      "PSY:55630",
      "UMLS:C0522351",
      "FMA:12266",
      "HP:0002321",
      "UMLS:C0751573",
      "MESH:D014717",
      "ICD9:386.19",
      "MONDO:0004900",
      "UMLS:C0476207",
      "SYMP:0000399",
      "UMLS:C0230168",
      "OMIM:MTHU018247",
      "UMLS:C0000726",
      "UMLS:C1508499"
   ],
   "value_type_id":"metatype:Nodeidentifier",
   "value_url":null
},
```

**Comment by amykglen** [comment]
it looks like this conflation has been resolved in the latest version of the new synonymizer (#2003) - that super-cluster seems to have been broken up:

Cluster for PSY:55630 (MONDO:0002317) has 35 nodes:

| id                 | category          | name                                  | in_SRI   | in_KG2pre   | is_cluster_rep   |
|:-------------------|:------------------|:--------------------------------------|:---------|:------------|:-----------------|
| DOID:2479          | Disease           | central nervous system origin vertigo | X        | X           |                  |
| HP:0002321         | Disease           | Vertigo                               | X        | X           |                  |
| ICD10:H81.4        | Disease           |                                       | X        |             |                  |
| ICD9:386.2         | Disease           | Vertigo of central origin             | X        | X           |                  |
| LOINC:LA7428-1     | PhenotypicFeature | Dizziness                             |          | X           |                  |
| MEDDRA:10013573    | Disease           |                                       | X        |             |                  |
| MEDDRA:10013580    | Disease           |                                       | X        |             |                  |
| MEDDRA:10019201    | Disease           |                                       | X        |             |                  |
| MEDDRA:10019202    | Disease           |                                       | X        |             |                  |
| MEDDRA:10019203    | Disease           |                                       | X        |             |                  |
| MEDDRA:10041619    | Disease           |                                       | X        |             |                  |
| MEDDRA:10047340    | Disease           |                                       | X        |             |                  |
| MEDDRA:10047343    | Disease           |                                       | X        |             |                  |
| MEDDRA:10047347    | Disease           |                                       | X        |             |                  |
| MEDDRA:10047349    | Disease           |                                       | X        |             |                  |
| MEDDRA:10048019    | Disease           |                                       | X        |             |                  |
| MEDDRA:10058708    | Disease           |                                       | X        |             |                  |
| MESH:D004244       | Disease           | Dizziness                             | X        | X           |                  |
| MESH:D014717       | Disease           | Vertigo                               | X        | X           |                  |
| MONDO:0002317      | Disease           | central nervous system origin vertigo | X        | X           | X                |
| NCIT:C37943        | Disease           | Dizziness                             | X        | X           |                  |
| NCIT:C38057        | Disease           | Vertigo                               | X        | X           |                  |
| PSY:14800          | PhenotypicFeature | Dizziness                             |          | X           |                  |
| PSY:55630          | PhenotypicFeature | Vertigo                               |          | X           |                  |
| SNOMEDCT:271789005 | Disease           |                                       | X        |             |                  |
| SNOMEDCT:38403006  | Disease           |                                       | X        |             |                  |
| SNOMEDCT:399090003 | Disease           |                                       | X        |             |                  |
| SNOMEDCT:399153001 | Disease           |                                       | X        |             |                  |
| SNOMEDCT:404640003 | Disease           |                                       | X        |             |                  |
| SYMP:0000399       | PhenotypicFeature | vertigo                               |          | X           |                  |
| SYMP:0000610       | PhenotypicFeature | dizziness                             |          | X           |                  |
| UMLS:C0012833      | Disease           | Dizziness                             | X        | X           |                  |
| UMLS:C0042571      | Disease           | Vertigo                               | X        | X           |                  |
| UMLS:C0155503      | Disease           | Central Nervous System Origin Vertigo | X        | X           |                  |
| UMLS:C0476206      | Disease           | Dizziness and giddiness symptoms      | X        | X           |                  |

Cluster for UMLS:C0230168 has 4 nodes:

| id            | category         | name             | in_SRI   | in_KG2pre   | is_cluster_rep   |
|:--------------|:-----------------|:-----------------|:---------|:------------|:-----------------|
| FMA:12266     | AnatomicalEntity | Abdominal cavity |          | X           |                  |
| MESH:D034841  | AnatomicalEntity | Abdominal Cavity | X        | X           |                  |
| NCIT:C12664   | AnatomicalEntity | Abdomen          | X        | X           |                  |
| UMLS:C0230168 | AnatomicalEntity | Abdominal Cavity | X        | X           | X                |

Cluster for FMA:9577 (UMLS:C0000726) has 9 nodes:

| id               | category         | name     | in_SRI   | in_KG2pre   | is_cluster_rep   |
|:-----------------|:-----------------|:---------|:---------|:------------|:-----------------|
| FMA:9577         | AnatomicalEntity | Abdomen  |          | X           |                  |
| LOINC:LA12706-0  | AnatomicalEntity | Abdomen  |          | X           |                  |
| LOINC:LP199956-6 | AnatomicalEntity | Abdomen  |          | X           |                  |
| LOINC:LP6990-8   | AnatomicalEntity | Abdomen  |          | X           |                  |
| LOINC:MTHU001425 | AnatomicalEntity | Abdomen  |          | X           |                  |
| LOINC:MTHU059270 | AnatomicalEntity | Abdomen+ |          | X           |                  |
| MESH:D000005     | AnatomicalEntity | Abdomen  | X        | X           |                  |
| PSY:00010        | AnatomicalEntity | Abdomen  |          | X           |                  |
| UMLS:C0000726    | AnatomicalEntity | Abdomen  | X        | X           | X                |

it's worth noting that the SRI's synonymization of 'abdomen' doesn't appear complete; they don't cluster UBERON:0000916 with the rest of the 'abdomen' nodes:

Cluster for UBERON:0000916 has 1 nodes:

| id             | category                 | name    | in_SRI   | in_KG2pre   | is_cluster_rep   |
|:---------------|:-------------------------|:--------|:---------|:------------|:-----------------|
| UBERON:0000916 | GrossAnatomicalStructure | abdomen | X        | X           | X                |

and I'm also not sure why they group NCIT:C12664 ('abdomen') with the 'abdominal cavity' nodes, rather than the other 'abdomen' nodes... but for now we're sticking with what the SRI says. I wrote this up in https://github.com/TranslatorSRI/NodeNormalization/issues/188

**Comment by amykglen** [comment]
looks good on test instances:

https://arax.ncats.io/devLM/?term=abdomen
https://arax.ncats.io/devLM/?term=dizziness
https://arax.ncats.io/devLM/?term=abdominal%20cavity
