### ISSUE TITLE
CHP edges?

### ISSUE THREAD

**Issue by edeutsch** [RTXteam/RTX#1856]
Hi everyone, I got a message from @GregHydeDartmouth. I'm slammed for a while and am wondering if someone else might be able to take a look into this?

I'm trying to walk through a new feature CHP has put together, but I'm seeing strange results coming back from ARAX. There is reasonably likelihood its on our side, but I'm having trouble trying to pin it down. I've put together a query relationship going from Disease->Tissue->Gene<-Drug. The edge CHP will return on is Tissue->Gene, though I don't know that I'm seeing our results be proliferated through onto the next step. You can see the flow in the ARAX results here: https://arax.ncats.io/?r=50031. According to the UI, I can see CHP returns 180 edges, but I don't see any of the genes we return being propagated forward though into the Gene<-Drug edge. To confirm my suspicions, I took the query ARAX sent us from result 50031, and sent it to CHP manually, collected our gene returns and then ran the Gene<-Drug result manually. This can be seen here: https://arax.ncats.io/?r=50032.  When a run a tissue->Gene 1 hop, these seem to be filled in by ARAX and by CHP dirrectly to the ARS as normal. As an example: https://arax.ncats.io/?r=ecac6339-f968-4945-9d8f-389a8badb960. Wondering if you had any ideas?

**Comment by dkoslicki** [comment]
@GregHydeDartmouth It's likely that the CHP results aren't showing up due to how many results there are in this query. 
I see you're using the Fisher exact test (FET) to limit the number of intermediate results, so it's possible that the CHP results are being removed since you limit it to the top 30 edges according to FET, and the query edge of interest to you has 872 edges returned from knowledge providers.

If you want to specify that _only_ CHP should be hit for that edge, then you can do something like [this query](https://gist.github.com/dkoslicki/44c3352a2b86d214e4fe104e5ab2ac47) which specifies that a certain edge should only be answered by a certain KP (in that example, e0 by COHD)

**Comment by GregHydeDartmouth** [comment]
@dkoslicki Thanks for the workflow example. I was able to create a query that only got sent to CHP on the second hop and was able to determine an issue with our node/edge bindings. For some reason we create multiple node/edge bindings. Thanks for the help!

**Comment by GregHydeDartmouth** [comment]
@dkoslicki Hi David. I'm again trying to walk through this query pipeline and I still appear to be having issues. I use the workflow as you suggest above:
```
{
    "workflow": [
        {
            "id": "fill",
            "parameters": {
                "allowlist": [
                    "infores:rtx-kg2"
                ],
                "qedge_keys": [
                    "e0"
                ]
            }
        },
        {
            "id": "fill",
            "parameters": {
                "allowlist": [
                    "infores:connections-hypothesis"
                ],
                "qedge_keys": [
                    "e1"
                ]
            }
        }
    ],
    "message": {
        "query_graph": {
            "nodes": {
                "n0": {
                    "categories": [
                        "biolink:Disease"
                    ],
                    "ids": [
                        "MONDO:0009061"
                    ]
                },
                "n1": {
                    "categories": [
                        "biolink:GrossAnatomicalStructure"
                    ]
                },
                "n2": {
                    "categories": [
                        "biolink:Gene"
                    ]
                }
            },
            "edges": {
                "e0": {
                    "subject": "n0",
                    "object": "n1",
                    "predicates": [
                        "biolink:related_to"
                    ]
                },
                "e1": {
                    "subject": "n1",
                    "object": "n2",
                    "predicates": [
                        "biolink:expresses"
                    ]
                }
            }
        }
    }
}
```
And I can't get our results to appear through ARAX. You will have to increase the ARAX timeout to a least 60 seconds for the above query to resolve. However, I still don't see our results pop up. When I send the query ARAX sends CHP:
```
{
  "message": {
    "query_graph": {
      "edges": {
        "e1": {
          "object": "n1",
          "predicates": [
            "biolink:expressed_in"
          ],
          "subject": "n2"
        }
      },
      "nodes": {
        "n1": {
          "categories": [
            "biolink:GrossAnatomicalStructure"
          ],
          "ids": [
            "UBERON:0002107",
            "UBERON:0002113",
            "UBERON:0034969",
            "UBERON:0000397",
            "UBERON:0002530",
            "UBERON:0000004",
            "UBERON:0000017",
            "UBERON:0000966",
            "UBERON:0000310",
            "UBERON:0000981",
            "UBERON:0016410",
            "UBERON:0000058",
            "UBERON:0000160",
            "UBERON:0000158",
            "UBERON:0000019",
            "UBERON:0000483",
            "UBERON:0000970",
            "UBERON:0003891",
            "UBERON:0000062",
            "UBERON:0001901",
            "UBERON:0009912",
            "UBERON:0000344",
            "UBERON:0002048",
            "UBERON:0001154",
            "UBERON:0002040",
            "UBERON:0001911"
          ],
          "is_set": True
        },
        "n2": {
          "categories": [
            "biolink:Gene",
            "biolink:Protein"
          ],
          "is_set": True
        }
      }
    }
  }
}
```
directly to the ARAS I see our results appear back from CHP and I also see the results in ARAGORN.
https://arax.ncats.io/?r=2f384c05-ed2d-41f3-9d19-fe487c19df86

Is this still a ranking issue? I noticed in the debugging messages from ARAX I see:
2022-07-05T00:34:08.415381 DEBUG: infores:connections-hypothesis: After removing self-edges, answer KG counts are: e1: 150, n1: 15, n2: 150
2022-07-05T00:34:08.415601 DEBUG: Got answers from all KPs; merging them into one KG
2022-07-05T00:34:08.415655 DEBUG: Merging answer into Message.KnowledgeGraph
2022-07-05T00:34:08.416342 DEBUG: Sending NodeSynonymizer.get_canonical_curies() a list of 1 curies
2022-07-05T00:34:09.041576 DEBUG: Got response back from NodeSynonymizer
2022-07-05T00:34:09.042284 DEBUG: Removed 0 edges fulfilling e1 from the KG because they were orphaned

though I'm not entirely sure how to interpret this.
