### ISSUE TITLE
Annotation of returned results lists

### ISSUE THREAD

**Issue by jaredroach** [RTXteam/RTX#190]
If the returned answer is a list of times, those items can be annotated, in table format. These annotations can support the logic used to return them as answers (e.g., GSEA enrichment score if it was used to decide that the protein was part of a relevant pathway to the inquiry) as well as provide useful information. So if a list of proteins is returned, they might be annotated with a Uniprot ID. If drugs are returned, they might be annotated with a human drug safety field.

- per Table C SME May 2018 Hackathon discussion and Paul Clemons

**Comment by jaredroach** [comment]
fwiw, here is a quick PERL script that can parse the JSON output and return a list of results:

use JSON::Parse qw(  json_file_to_perl);

my $decoded_json = json_file_to_perl("naproxen_target.json");
 
my @result_list = @{$decoded_json->{'result_list'}};
foreach my $value (@result_list) {
	my %hash = %{$value};
	my $text_result = $hash{'text'};
	$text_result =~ /chemical_substance (.*) involves/;
	my $actual_result = $1;
	print $actual_result,"\n";
}

exit;

**Comment by edeutsch** [comment]
thanks, that a good start. I would critique this by saying that parsing the "text" field is likely to be very fragile. It would be better to pull the information out of the node_list, although that is more complex. although it some cases maybe the text would be better. Also, you asked about fetching directly from the API (skipping the executing on the browser and cutting and pasting from dev). Below you will find a script that fetches directly from the api, parses the result and parses the results from the node_lists. It's more complicated, but hoepfully better in the long run. Note that I am currently pointing to the "devED" endpoint. This is because this code as written works for API version 0.8.0. Production is still 0.7.0 and the schema is a little different. By early next week everything will be on 0.8.0 and you can switch the endpoint away from devED. But for the next few days devED is necessary. I will check this into the an area with client examples also.

#!/usr/bin/perl

use strict;
use warnings;

use HTTP::Request;
use LWP::UserAgent;
use JSON::Parse;

my $url = 'http://rtx.ncats.io/devED/api/rtx/v1/query';
my $json = '{"query_type_id": "Q3", "terms": { "chemical_substance": "CHEMBL:CHEMBL521" } }';
my $request = HTTP::Request->new( 'POST', $url );
$request->header( 'Content-Type' => 'application/json' );
$request->content( $json );

my $lwp = LWP::UserAgent->new;
my $lwp_response = $lwp->request( $request );

my @results_list = ();

if ( $lwp_response->is_success() ) {
  my $response = JSON::Parse::parse_json($lwp_response->content());
  if ( $response->{'result_list'} ) {
    my @result_list = @{$response->{'result_list'}};
    foreach my $result (@result_list) {
      my $text_result = $result->{'text'};
      if ( $result->{result_graph} ) {
        foreach my $node ( @{$result->{result_graph}->{node_list}} ) {
          if ( $node->{type} eq 'protein' ) {
            push( @results_list, [ $node->{id}, $node->{name} ] );
          }
        }
      }
    }
  } else {
    print($response->{message}."\n")
  }

} else {
    print("ERROR: " . $lwp_response->status_line());
}

foreach my $result ( @results_list ) {
  print join("\t",@{$result})."\n";
}

**Comment by edeutsch** [comment]
Checked in the example:
https://github.com/RTXteam/RTX/blob/master/code/UI/ClientExamples/Perl/fetchIbuprofenTargets.pl

**Comment by dkoslicki** [comment]
Closing due to #788 and current list integration in UI and Reasoner Std API format
