### ISSUE TITLE
NamedThing that shouldn't be?

### ISSUE THREAD

**Issue by dkoslicki** [RTXteam/RTX#1913]
For this response: https://arax.ncats.io/?r=64936 there are entities such as MYRICETIN that show up in the [json response](https://arax.ncats.io/api/arax/v1.3/response/9c7a676c-8f48-4227-aa78-24c4709759be) as a `NamedThing` category, even though the [synonymizer](https://arax.ncats.io/?term=MYRICETIN) lists it as a `SmallMolecule` and the "attribute_type_id": "biolink:category" correctly lists it as a 
```
"value": [
                "biolink:ChemicalEntity",
                "biolink:SmallMolecule",
                "biolink:MolecularEntity",
                "biolink:Drug"
              ],
```
However, the the `categories` is given as:
```
"categories": [
            "biolink:NamedThing"
          ],
```
Anyone have an idea whey there is a mismatch between the `category` and the `categories`?

**Comment by amykglen** [comment]
yes, it's expected behavior currently - see #1360. basically it was decided early on in ARAX development that we should override each returned node's categories to match the categories that were was asked for in the QG. (note that that TRAPI property used to be called `category` rather than `categories` when issue 1360 was created)

**Comment by dkoslicki** [comment]
Thanks for clarifying Amy! I'll put this on the agenda for the next AHM to circle back to #1360

**Comment by dkoslicki** [comment]
Closing in favor of #1360
