### ISSUE TITLE
Simple one-hop DTD query takes 2.5 minutes?

### ISSUE THREAD

**Issue by amykglen** [RTXteam/RTX#1932]
I remember someone (maybe @edeutsch) mentioning this at a meeting sometime in the last few months, but it seems like when Expand uses DTD to answer queries, processing takes much longer than I thought it used to?

for instance, this query (with a single 'input' curie -- chickenpox):
```
add_qnode(ids=MONDO:0005700, key=n0)
add_qnode(categories=biolink:Drug, key=n1)
add_qedge(subject=n1, object=n0, key=e0, predicates=biolink:treats)
expand(kp=infores:arax-drug-treats-disease)
resultify()
filter_results(action=limit_number_of_results, max_results=100)
```

takes about 2.5 minutes on arax.ncats.io:
https://arax.ncats.io/?r=78839

I thought by default DTD does not run in 'slow mode', so I don't think that would be the issue?

just wondering if anything might be wrong, or if this is expected.

**Comment by edeutsch** [comment]
Yes, I mentioned this once several months ago but never followed up.

One thing I've been wondering: with the new ML creative mode drug disease database, does that make the old DTD mostly obsolete? Can the very slow calls to the old DTD be replaced with a fast lookup in the new system?

**Comment by chunyuma** [comment]
I think the reason that makes it run so slowly is due to issue #1624. For each drug-disease pair returned from the DTD database, we have to use a "for-loop" to double check if their ancestors satisfy the query category. @amykglen, is there a faster way to achieve this?

**Comment by chunyuma** [comment]
@amykglen, is it urgent for this issue? I don't have a good idea to optimize my code and plan to discuss it with you in our next mini-hackathon meeting.

**Comment by amykglen** [comment]
ah, got it - that sounds great to discuss at the next mini-hackathon. thanks @chunyuma!

**Comment by amykglen** [comment]
we should discuss this sometime soon to see if we can speed up DTD. 

I find it strange that DTD seems to be using an external web API to find ancestors of Biolink categories?

![Screen Shot 2023-01-12 at 11 15 01 AM](https://user-images.githubusercontent.com/49423686/212160324-54f9bb7a-75b0-4777-b051-4b5636dc5deb.png)

**Comment by amykglen** [comment]
if it's just needing ancestors of Biolink categories, you can use BiolinkHelper's [get_ancestors()](https://github.com/RTXteam/RTX/blob/4870fcb5856fae4634afd30880218f2c1b660583/code/ARAX/BiolinkHelper/biolink_helper.py#L39) method, which uses a cache.

**Comment by amykglen** [comment]
happy to help troubleshoot where else the slowness is coming from, @chunyuma. for instance, you could probably just get ancestors once for each node, rather than for every possible pair of drug/disease nodes? (it looks like the for loop you mentioned is over an intertools.product(), which likely means an O(n^2) situation?)

**Comment by chunyuma** [comment]
@amykglen, thanks for reporting this. It is indeed weird. I did not make DTD use any external web API. It just uses BiolinkHelper's get_ancestors function under RTX/code/ARAX/BiolinkHelper/biolink_helper (please see these [two](https://github.com/RTXteam/RTX/blob/4870fcb5856fae4634afd30880218f2c1b660583/code/ARAX/ARAXQuery/Expand/DTD_querier.py#L150-L151) lines). Please let me know whether I can download the database to local and test it locally in my side.

Regarding the slowness problem, one of the most time-consuming lines is [this](https://github.com/RTXteam/RTX/blob/4870fcb5856fae4634afd30880218f2c1b660583/code/ARAX/ARAXQuery/Expand/DTD_querier.py#L401) line. Basically, given a list of tuples (e.g., [(drug1 curie, disease1 curie, prob1), (drug2 curie, disease2 curie, prob2), ...]), what this line wants to do are:

1. filter out those tuples with probability < a given threshold
2. use node synonymizer to find all categories for each drug curie and see if either one of them meets the specific categories.

Perhaps one of the optimized solutions is: 1) Convert this list to a dataframe and then filter probability column using the given threshold; 2) request node synonymizer once for all curies instead of querying one by one.

I will try this to see if it can make it faster. Amy, if you have any better solutions, please let me know. Thanks so much!

**Comment by amykglen** [comment]
nice, those sound like good ideas! hmm, it must be one of the synonymizer calls that is querying the external web API under the hood (it looks like that error message in the above screenshot is printed by the synonymizer's get_ancestors() function)...

another thing you can do to speed up the code is only call `synonymizer.get_canonical_curies()` once and pass it _all_ node IDs you need to canonicalize, rather than calling it once for each node. (Expand always passes batches of curies to the synonymizer like that because it's much faster.)

**Comment by amykglen** [comment]
oops, sorry, I just noticed you already proposed calling the node synonymizer once for all curies. I read that wrong. great idea!

**Comment by chunyuma** [comment]
Hi @amykglen, I've modified the scripts to make "DTD expand" run faster. I did a comparison locally and found that using the new method is much faster than the old one. So it should solve this slow issue. I'm in the middle of doing pytest DTD-associated commands (e.g. "test_dtd_expand_1" in test_ARAX_expand.py). It is weird that running `DTD_slow_mode=True` in expand module gets stuck somewhere. I'm still figuring out the reason (Not sure if it is due to the high load in our server now). I will test it once more this weekend after our server is not busy.
