### ISSUE TITLE
Filter out SemMedDB edges that don't have many publications supporting them?

### ISSUE THREAD

**Issue by dkoslicki** [RTXteam/RTX#1972]
Inject an ARAXi `filter` command at the end of _every_ query that filters out those edges that have fewer than `n` PMIDs associated with it, and then removes any orphaned nodes.

Will be a touch tricky with creative mode question 1, since the xDTD paths are already computed, so would need to remove the whole path this edge is a part of, up until the in-degree of any node on this path exceeds 1.

**Comment by dkoslicki** [comment]
Alternatively, extremely downweight (via the `ranker`) any result that contains such an edge.

**Comment by amykglen** [comment]
maybe rather than downweighting the whole result, just make that edge have 0 weight? that way, when a result also includes parallel edges that are from sources _other_ than semmeddb, that result could still be ranked highly (as seems desirable)

**Comment by saramsey** [comment]
From the discussion in the Team Expander Agent all-hands meeting on 3/29, there seemed to be a consensus (?) that a practical and flexible approach would be to filter SemMedDB edges based on publication count _in the RTX-KG2 KP_, rather than in the KG2pre build process or in the KG2c build process. On a related point, Will Byrd has confirmed that Team Unsecret Agent prefers that, for the KG2pre artifact that we provide to them, _all_ SemMedDB edges to be included regardless of publication count. So if we put the filtering logic in the RTX-KG2 KP, it doesn't affect the graph used by Unsecret Agent in mediKanren and it would also enable client-specifiable preference as to the filtering threshold (which would be pretty much impossible to do if we were to pre-filter in the build process for KG2pre or KG2c).

**Comment by edeutsch** [comment]
Was anyone on the team at the SemMedDB call this morning? Apparently from 9-10a this morning there was an extended discussion about what to do about SemMedDB. I was not there.

If anyone was, can you provide a report or link to the minutes?

Or if not, maybe someone from the team should be?

**Comment by saramsey** [comment]
FYI: @edeutsch has conveyed that, from the perspective of Translator/ARS user experience, filtering out questionable SemMedDB edges is now a high priority for the consortium, as articulated by Tyler.

**Comment by edeutsch** [comment]
> Oops. I must have missed the memo on that, sorry. Would have been good to be there. Do you know if it is a recurring meeting?

I don't know. I only found out about it because several people like Tyler and Sierra were a bit late coming to the TRAPI meeting because the SemMedDB meeting ran over.

**Comment by amykglen** [comment]
FYI - it appears that the parent meeting to the SemMedDB hackathon was TAQA - there was a recap of it on the TAQA call today (some notes in the agenda for today [here](https://docs.google.com/document/d/1eWwa-sC5xxghu7SNPsXEmUvis52njpT6-2YNzjIr-vA/edit#)).

in summary, it sounds like most people tend to think a hard cut-off based on number of publications is a bit too crude, though it is easy. some new efforts have been started (by Andrew Su I think) to look at also considering 1) the UMLS hierarchy and 2) NER scores (not sure if these correspond to the 'subject_score'/'object_score' in KG2?).

it sounds like another SemMedDB hackathon will probably happen in around 3 weeks; the TAQA call is going to revisit the plan for that on April 15.

**Comment by dkoslicki** [comment]
closing in favor of #2045

**Comment by dkoslicki** [comment]
closing in favor of #2045
