### ISSUE TITLE
Direct and inferred results MUST be merged soon

### ISSUE THREAD

**Issue by edeutsch** [RTXteam/RTX#1988]
We finally tackled this issue head on in the Architecture call today:

The conclusion was:
- When a user requests knowledge_type=inferred, ARAs MUST return *both* inferred results merged with direct lookup results
- Tyler says that *all* queries from the main UI will be inferred queries
- There will be PR coming to formalize this. Objections still can be made
![image](https://user-images.githubusercontent.com/12707718/226713065-4e6d0c1f-d9aa-40d4-bf69-cd21d33db1a1.png)

**Comment by dkoslicki** [comment]
@kvnthomas98 can you work with @chunyuma to get augment the `xDTD` [code](https://github.com/RTXteam/RTX/blob/master/code/ARAX/ARAXQuery/ARAX_infer.py) (specifically, [here](https://github.com/RTXteam/RTX/blob/master/code/ARAX/ARAXQuery/ARAX_infer.py#L345)), to also include a call to [expand](https://github.com/RTXteam/RTX/blob/master/code/ARAX/ARAXQuery/ARAX_expander.py) with the query `(?:biolink:Drug|biolink:ChemicalMixture|biolink:ChemicalEntity)-[biolink:amerliorates|biolink:treats]-(<input disease>:biolink:DiseaseOrPhenotypicFeature)` and for these results only, filter out any edges (and associated drug) that originates from SemMedDB?

**Comment by dkoslicki** [comment]
Ah, yes, that does sound a lot simpler. @amykglen do you concur? I think the trick would be in the merging step in any case

**Comment by dkoslicki** [comment]
Looks like infer does call resultify:
https://github.com/RTXteam/RTX/blob/c0ed6fd32a74fe1dd0b5ea80a1b30b823e2c8cd2/code/ARAX/ARAXQuery/Infer/scripts/creativeCRG.py#L73
https://github.com/RTXteam/RTX/blob/c0ed6fd32a74fe1dd0b5ea80a1b30b823e2c8cd2/code/ARAX/ARAXQuery/Infer/scripts/infer_utilities.py#L770
But @chunyuma will know for sure

**Comment by chunyuma** [comment]
Hi @edeutsch @amykglen @dkoslicki, as you know, currently the infer results can come from two models in the creative mode: `xDTD` and `xCRG`. However, It should be fine to merge `xDTD` results into the normal direct expansion because we did pre-computation and stored the results in database so it is much faster than `xCRG` which is called on the fly. Therefore, I would not suggest merging `xCRG` into the normal direct expansion unless we also do pre-computation. 

But here is another problem: `xCRG` is not like `xDTD` that it doesn't have an RL-based model to predict the paths. It now only calls `expand` internally for this goal. So it is temporally impossible to do pre-computation. 

For Amy's questions "Resultify currently called after Infer runs?", Yes, the `ARAXResultify()` is applied to the resulting scores.

**Comment by chunyuma** [comment]
> @kvnthomas98 can you work with @chunyuma to get augment the xDTD [code](https://github.com/RTXteam/RTX/blob/master/code/ARAX/ARAXQuery/ARAX_infer.py) (specifically, [here](https://github.com/RTXteam/RTX/blob/master/code/ARAX/ARAXQuery/ARAX_infer.py#L345)), to also include a call to [expand](https://github.com/RTXteam/RTX/blob/master/code/ARAX/ARAXQuery/ARAX_expander.py) with the query (?:biolink:Drug|biolink:ChemicalMixture|biolink:ChemicalEntity)-[biolink:amerliorates|biolink:treats]-(<input disease>:biolink:DiseaseOrPhenotypicFeature) and for these results only, filter out any edges (and associated drug) that originates from SemMedDB?

There is one more thing that we might need to discuss. The edges coming from xDTD model lack of the attribute of `primary_source`. In other words, we don't know each edge is from SemMedDB. I might be able to add this information back to the model since I'm making the automatic pipeline for xDTD training. Also, I noticed previously that if we remove all edges (and associated drug) that originates from SemMedDB? Most drug-disease pairs will lack connections within 3 hops. Actually, I've already done some filtering based on NGD <=0.6 for SemMedDB edges. Do we still need to filter out all?

**Comment by dkoslicki** [comment]
@kvnthomas98 Let's prioritize this issue: during the standup call today, the program manager mentioned wanting this ASAP

**Comment by kvnthomas98** [comment]
Sure, working on it now
