### ISSUE TITLE
Some protein nodes are missing descriptions

### ISSUE THREAD

**Issue by dkoslicki** [RTXteam/RTX#20]
Eg. P08563

**Comment by dkoslicki** [comment]
Found another such node:
```
match (n) where n.name="DOID:10923" return n
```

**Comment by saramsey** [comment]
confirmed this bug in the current dev KG (in container rtxsteve on rtxdev.saramsey.org)

**Comment by saramsey** [comment]
Updated database has been pushed to http://rtxdev.saramsey.org:7674

![screen shot 2018-03-29 at 3 02 02 pm](https://user-images.githubusercontent.com/5562107/38115804-4c665bae-3362-11e8-82fc-8d98558a2ba8.png)

**Comment by saramsey** [comment]
all drugs now have descriptions:

![screen shot 2018-03-29 at 3 06 30 pm](https://user-images.githubusercontent.com/5562107/38115930-d2309768-3362-11e8-978c-ef4df2d4c001.png)

**Comment by saramsey** [comment]
Looks like 303 protein nodes lack descriptions. Not clear from a search of the code-base where these are coming from.  More investigation needed:
![screen shot 2018-03-29 at 3 09 52 pm](https://user-images.githubusercontent.com/5562107/38116043-434cbd64-3363-11e8-9fb8-d86facf01df5.png)

**Comment by dkoslicki** [comment]
Note also that some of the target edges are missing probabilities:
```
match p=(n:pharos_drug)-[t:targets]-(:uniprot_protein) return t.probability limit 10

t.probability
--
null
null
null
0.03231776208
0.00615026285
7.3254e-7
1
0.00000596881
0.00000803035
0.00000190193


```

**Comment by saramsey** [comment]
Can you give me a pair of ChEMBL ID and Uniprot ID?

-----------------------------------------------------
Stephen Ramsey
Assistant Professor, Oregon State University
* School of Electrical Engineering and Computer Science
* Department of Biomedical Sciences
208A Dryden Hall
stephen.ramsey@oregonstate.edu<mailto:stephen.ramsey@oregonstate.edu>
http://lab.saramsey.org







On Mar 29, 2018, at 3:17 PM, David Koslicki <notifications@github.com<mailto:notifications@github.com>> wrote:


Note also that some of the target edges are missing probabilities:

match p=(n:pharos_drug)-[t:targets]-(:uniprot_protein) return t.probability limit 10

t.probability
--
null
null
null
0.03231776208
0.00615026285
7.3254e-7
1
0.00000596881
0.00000803035
0.00000190193

**Comment by dkoslicki** [comment]
```
MATCH p=(s:pharos_drug)-[r:targets]->(t:uniprot_protein) where r.probability is Null return s.name, t.name, r.probability limit 10


s.name | t.name | r.probability
-- | -- | --
"CHEMBL1166" | "Q9H244" | null
"CHEMBL1166" | "Q9BQB6" | null
"CHEMBL1166" | "P03952" | null
"CHEMBL1166" | "P38435" | null
"CHEMBL1201244" | "P02708" | null
"CHEMBL1201244" | "P11230" | null
"CHEMBL1201244" | "Q07001" | null
"CHEMBL1201244" | "P08913" | null
"CHEMBL602" | "P13569" | null
"CHEMBL602" | "P37231" | null
```

**Comment by saramsey** [comment]
Yes, this is a Pharos issue (see screen cap).  Since we first attempt to get drug-target relationships using ChEMBL before attempting Pharos, not sure what else can be done here.


[cid:F794E69F-2503-471B-86CC-A856E430B859]

-----------------------------------------------------
Stephen Ramsey
Assistant Professor, Oregon State University
* School of Electrical Engineering and Computer Science
* Department of Biomedical Sciences
208A Dryden Hall
stephen.ramsey@oregonstate.edu<mailto:stephen.ramsey@oregonstate.edu>
http://lab.saramsey.org







On Apr 16, 2018, at 2:22 PM, David Koslicki <notifications@github.com<mailto:notifications@github.com>> wrote:


@saramsey<https://github.com/saramsey> Closing the loop on this issue: some of the probabilities are still not populated:

match p=(n:chemical_substance)-[t:directly_interacts_with]-(m:protein) where not exists(t.probability) return t.probability, n.description, m.description limit 100


eg edge connecting triclofos and GABRE.

If this is due to Pharos not having the info, then it's fine and we can close this issue. I just wanted to make sure it wasn't a problem with the orangeboard construction itself.

**Comment by dkoslicki** [comment]
Fair enough: let's chalk it up to a shortcoming of the KS's. Guess we can close this issue then.
