### ISSUE TITLE
Lil'Gim return proteins not in the KG

### ISSUE THREAD

**Issue by dkoslicki** [RTXteam/RTX#201]
This causes problems when trying to format the API response since I can't query the KG for things like the name, the URI, etc. Ideas for a workaround (besides adding all of UniProtKB into the KG)?

**Comment by saramsey** [comment]
example?

**Comment by saramsey** [comment]
@dkoslicki can I get a MWE for this?  It would help me to track down the issue, thanks.

**Comment by saramsey** [comment]
@dkoslicki I suppose I could modify QueryLilGIM.py so that it queries the Neo4j KG by Cypher to get a list of all protein nodes, caches this list in memory, and then uses that list as a filter.  What do you think?

**Comment by saramsey** [comment]
@flashkicker I am assigning this issue to you. The issue is that 

QuestionAnswering/QueryLilGim.py

has a method,

    query_neighbor_genes_for_gene_set_in_a_given_anatomy

which is returning genes that are *not* in the knowledge graph.  I think this method needs to be extended to provide an optional fourth argument called "allowed_proteins_filter_set". Caller would use this argument to pass a python Set of UniProt protein symbols that would be allowed to be included in the return data. Does that make sense?  If not, please let me know and I will clarify.  Thanks.

**Comment by saramsey** [comment]
@flashkicker please do some investigation on the reproducibility of this issue; @dkoslicki reports that the issue is sporadic

**Comment by saramsey** [comment]
@flashkicker can I please get an update on this issue?

**Comment by flashkicker** [comment]
@saramsey added an optional argument that takes in a tuple with uniprot_ids like this:
`new_tuple = ('Q14691', 'O75792', 'Q9Y242')
qlg.query_neighbor_genes_for_gene_set_in_a_given_anatomy("UBERON:0002384", ("UniProtKB:P12004",), new_tuple)`

Is this acceptable, or would you like me to filter the uniprot_ids in this format: `UniProtKB:Q14691`

Also, tried to use a set as the optional argument but that wasn't working very well due to it being unhashable, hence I switched to using a tuple.

**Comment by dkoslicki** [comment]
@saramsey @flashkicker I think passing a list of "allowable" proteins would be too cumbersome: we'd be passing a list of 21,810 elements (since that is how many proteins are in the KG currently). I think it would be easier to post-process the lilGIM results: run it as usual, check if each protein exists in the KG, if not, remove it from the lilGIM results. Does that make sense?

**Comment by flashkicker** [comment]
Would it possibly work if we queried the KG to retrieve all the elements in the KG and store it in a tuple and then pass that tuple as an optional argument to the `query_neighbor_genes_for_gene_set_in_a_given_anatomy` function? That would essentially filter out all uniprot_ids not in the KG and return the desired lilGIM dictionary. @dkoslicki

**Comment by dkoslicki** [comment]
Yes, it is possible to do. [This function](https://github.com/RTXteam/RTX/blob/master/code/reasoningtool/QuestionAnswering/ReasoningUtilities.py#L82) shows how to check if an individual node exists. [This function](https://github.com/RTXteam/RTX/blob/master/data/KGmetadata/dumpdata.py#L46) shows how to dump *all* nodes. You'd need to replace ``(n)`` with ``(n:proteins)`` or something similar. It's somewhat annoying to have auxiliary files floating around (and it would be way too intensive to compute it on the fly each time). Hence why I suggested post-processing.

**Comment by saramsey** [comment]
@flashkicker why does the argument need to be hashable?

**Comment by flashkicker** [comment]
When trying to pass a set as an optional parameter:
```
new_set = {'Q14691', 'O75792', 'Q9Y242'}
print(qlg.query_neighbor_genes_for_gene_set_in_a_given_anatomy("UBERON:0002384", ("UniProtKB:P12004",), new_set))
```

And with the fourth optional parameter declared like this:
```
def query_neighbor_genes_for_gene_set_in_a_given_anatomy(self,
                                                             anatomy_curie_id_str,
                                                             protein_set_curie_id_str,
                                                             allowed_proteins_filter_set=set())
```

I get the following error:
```
Traceback (most recent call last):
  File "C:/Users/Ujjval/Documents/RTX/code/reasoningtool/QuestionAnswering/QueryLilGIM.py", line 177, in <module>
    print(qlg.query_neighbor_genes_for_gene_set_in_a_given_anatomy("UBERON:0002384", ("UniProtKB:P12004",), new_set))
TypeError: unhashable type: 'set'
```

Using a tuple instead doesn't produce this error, and I can't seem to figure out the reason for it

**Comment by flashkicker** [comment]
The function query_neighbor_genes_for_gene_set_in_a_given_anatomy() in QueryLilGIM.py now returns only the genes that are in the knowledge graph.
