### ISSUE TITLE
Changes for building KG2.8.2c

### ISSUE THREAD

**Issue by sundareswarpullela** [RTXteam/RTX#2010]
**NOTE: All changes are made in the `kg2integration` branch.**

Current requested changes:

- [x] Change the edge property `knowledge_source : list` to `primary_knowledge_source : str`

**Comment by sundareswarpullela** [comment]
Hey @acevedol , I'm unable to find the node property knowledge_source . The current supported properties are
```
 {
     "nodes": {
         "id": {"type": str, "in_kg2pre": True, "in_kg2c_lite": True},
         "name": {"type": str, "in_kg2pre": True, "in_kg2c_lite": True},
         "category": {"type": str, "in_kg2pre": True, "in_kg2c_lite": True},
         "iri": {"type": str, "in_kg2pre": True, "in_kg2c_lite": False},
         "description": {"type": str, "in_kg2pre": True, "in_kg2c_lite": False},
         "all_categories": {"type": list, "in_kg2pre": False, "in_kg2c_lite": True, "use_as_labels": True},
         "publications": {"type": list, "in_kg2pre": True, "in_kg2c_lite": False},
         "equivalent_curies": {"type": list, "in_kg2pre": False, "in_kg2c_lite": False},
         "all_names": {"type": list, "in_kg2pre": False, "in_kg2c_lite": False}
     },
```
Should I add the new provided_by property of type list along with the present properties or am I supposed to replace one of the above with it?

**Comment by la89587** [comment]
If knowledge_source was not already in use in kg2c, I would just leave `provided_by` out for now. I can double check with @saramsey if this is okay.

**Comment by acevedol** [comment]
Hi Sundar, 
If `knowledge_source` was not already in use in kg2c, I would just leave provided_by out for now. I will check with @saramsey if this is okay.

**Comment by amykglen** [comment]
@sundareswarpullela - we only record `knowledge_source` on **edges** in KG2c, not nodes.

on edges, we need to change `knowledge_source` --> `primary_knowledge_source`.

we don't want to add `provided_by` to edges or nodes.

**Comment by sundareswarpullela** [comment]
The change has been made @acevedol

**Comment by amykglen** [comment]
@sundareswarpullela - not sure if this was already on your radar, but we likely also need to change how we merge edges in the KG2c build, since KG2pre no longer merges edges from the same `primary_knowledge_source`, and KG2c is no longer supposed to do that kind of edge merging either.

in other words, we will probably want to add the `primary_knowledge_source` to the KG2c edge IDs.

**Comment by sundareswarpullela** [comment]
Yes @amykglen, I'm working on it.

**Comment by amykglen** [comment]
Just a status update and an FYI for the KG2 team - I merged Sundar's code for KG2.8.2c with the new synonymizer code (in a branch called `kg2.8.2c`) and got things smoothed out; I got a test build to complete successfully and am now doing the full build! 

Wanted to note a couple changes about KG2c builds:
1. I made it a lot easier to run test builds: You don't need to set up special test KG2pre TSVs or anything anymore. Simply just run `python build_kg2c.py --test` and it will know to create test versions of the necessary input files on its own. Test builds now even include a synonymizer build and uploading of artifacts to arax-databases.rtx.ai and s3! It's always a good idea to do one of these test builds before kicking off a full build.
1. As part of updating the test build process, I also changed output file naming: Output files from test builds are no longer created with "test" in the name (i.e., `kg2c.json` for a test build is still called `kg2c.json` on buildkg2c.rtx.ai), but when they're uploaded to arax-databases.rtx.ai and s3, they do have a `_TEST` suffix tacked on (e.g., `kg2c-tsv.tar.gz_TEST`, so it's easy to distinguish them there.
1. To avoid accidentally running out of memory on buildkg2c.rtx.ai, I also changed output file naming (for both full and test builds) so that files are always given their simple, version-_independent_ names on the instance doing the build (e.g., `meta_kg.json` vs. `meta_kg_v1.0_KG2.8.2.json` on buildkg2c.rtx.ai). **But** when they're uploaded to arax-databases.rtx.ai, they are given their full version-dependent names (e.g., `meta_kg_v1.0_KG2.8.2.json`).
