### ISSUE TITLE
UI issue - "Cannot read properties of null (reading 'length')"

### ISSUE THREAD

**Issue by amykglen** [RTXteam/RTX#2032]
Eric may have already reported this issue to @isbluis, but I'll write it up here nonetheless

with TRAPI 1.4 (which has now been merged into `master`), we sometimes get this error when running queries from the UI:

![Screen Shot 2023-05-17 at 1 46 58 PM](https://github.com/RTXteam/RTX/assets/49423686/7cfe72db-1150-41db-aacb-6f7c086a2c52)

strangely, that error doesn't appear when loading an _already-stored_ response - this is the link to the response shown in the above screenshot:
https://arax.ncats.io/NewFmt/?r=138214

it doesn't show that error, but if you run the query _fresh_, it does produce the error. this is the JSON query, in case it's helpful:
```
{
   "edges": {
      "e00": {
         "subject":   "n00",
         "object":    "n01",
         "predicates": ["biolink:gene_associated_with_condition"]
      }
   },
   "nodes": {
      "n00": {
         "ids":        ["UniProtKB:P32754"]
      },
      "n01": {
         "ids":  ["MONDO:0001910"]
      }
   }
}
```

**Comment by edeutsch** [comment]
But after loading such an existing result as above, although no error is displayed, when you click on [Results] nothing is displayed, I'm guessing the same problem, just no error message.

**Comment by isbluis** [comment]
Got free WiFi!Glad to help troubleshoot if you send me error messages and/or screenshots. Error might  be due to incomplete TRAPI.  Perhaps analyses and/or support_graphs with null / zero elements?  JS console will tell you exact line number.  On May 17, 2023, at 11:04, Eric Deutsch ***@***.***> wrote:﻿
But after loading such an existing result as above, although no error is displayed, when you click on [Results] nothing is displayed, I'm guessing the same problem, just no error message.

**Comment by edeutsch** [comment]
yeah, you're right, JS code was not checking for null elements. I added some null checking and now I think it seems to work in /devED and /test and /NewFmt

**Comment by amykglen** [comment]
agree this seems to be resolved on /NewFmt and /kg2NewFmt! I'll close...
