### ISSUE TITLE
normalization issue related to "coenzyme A"

### ISSUE THREAD

**Issue by saramsey** [RTXteam/RTX#2058]
In KG2.8.3c, we have to separate nodes that I think both correspond to "coenzyme A" and should be normalized:

- first node: 
  - `id`: `PUBCHEM.COMPOUND:6816`
  - `name`: `"[[(2R,3S,4R,5R)-5-(6-aminopurin-9-yl)-4-hydroxy-3-phosphonooxyoxolan-2-yl]methoxy-hydroxyphosphoryl] [3-hydroxy-2,2-dimethyl-4-oxo-4-[[3-oxo-3-(2-sulfanylethylamino)propyl]amino]butyl] hydrogen phosphate"`
  - `equivalent_curies`: `["PathWhiz.Compound:1099", "INCHIKEY:RGJOEKWQDUBAIZ-DRCCLKDXSA-N", "PUBCHEM.COMPOUND:6816", "CHEMBL.COMPOUND:CHEMBL1623949", "KEGG.COMPOUND:C00010"], id: "PUBCHEM.COMPOUND:6816", category: "biolink:SmallMolecule"` 
  - `all_names`: `["Coenzyme A"]` 
 
- second node:
  - `id`: `PUBCHEM.COMPOUND:87642`
  - `name`: `"coenzyme A"`
  - `equivalent_curies`: `["UNII:SAA04E81UX", "RXNORM:1314344", 
"UMLS:C0009140", "DRUGBANK:DB01992", "CAS:143180-18-1", "INCHIKEY:RGJOEKWQDUBAIZ-IBOSZNHHSA-N", 
"CHEBI:15346", "HMDB:HMDB0001423", "CHEMBL.COMPOUND:CHEMBL1213327", 
"NCIT:C384", "MESH:D003065", "GTOPDB:3044", "PUBCHEM.COMPOUND:87642"]`

for more details and evidence, see https://github.com/RTXteam/RTX-KG2/issues/282

**Comment by saramsey** [comment]
@amykglen yes could you please report this issue to the SRI?  Thanks.

**Comment by amykglen** [comment]
sure, done! https://github.com/TranslatorSRI/NodeNormalization/issues/203

can we close this issue since the ARAX NodeSynonymizer is technically behaving how we intended?

**Comment by amykglen** [comment]
so it turns out those two Coenzyme A clusters differ in chirality; they have different inchi keys - see Chris B.'s response here: https://github.com/TranslatorSRI/NodeNormalization/issues/203#issuecomment-1585824197

it looks like there are a total of 3 nodes in KG2pre that were tacked onto one of these two clusters based on name only (they weren't recognized by the SRI NodeNormalizer). so unless the naming tendencies differ for those two chiral molecules, the Node Synonymizer very well may have gotten their assignments wrong..
