### ISSUE TITLE
KeyError stacktrace originating in smartapi.py

### ISSUE THREAD

**Issue by saramsey** [RTXteam/RTX#2071]
This line of code in `smartapi.py`

https://github.com/RTXteam/RTX/blob/f93f7c5352bfae3652c6525fd78bb45d9ae2b84c/code/ARAX/ARAXQuery/Expand/smartapi.py#L112

in a situation where a SmartAPI registry entry for a service is misconfigured (specifically, when the service's registry entry doesn't contain a `services` block as required), can lead to an error in `refresh_kp_info_caches`, as shown here in this excerpt from https://arax.transltr.io/api/arax/v1.4/status/logs:

```
2023-07-20T12:00:42.393426: INFO: ARAXBackgroundTasker: refresh_kp_info_caches() failed: 'servers': ['Traceback (most recent call last):\n', '  File "/mnt/data/orangeboard/production/RTX/code/UI/OpenAPI/python-flask-server/openapi_server/../../../../ARAX/ARAXQuery/ARAX_background_tasker.py", line 66, in run_tasks\n    kp_info_cacher.refresh_kp_info_caches()\n', '  File "/mnt/data/orangeboard/production/RTX/code/ARAX/ARAXQuery/Expand/kp_info_cacher.py", line 46, in refresh_kp_info_caches\n    smart_api_kp_registrations = smart_api_helper.get_all_trapi_kp_registrations(trapi_version=self.rtx_config.trapi_major_version,\n', '  File "/mnt/data/orangeboard/production/RTX/code/ARAX/ARAXQuery/Expand/smartapi.py", line 240, in get_all_trapi_kp_registrations\n    endpoints = self.get_trapi_endpoints(version=trapi_version, whitelist=whitelist, blacklist=blacklist)\n', '  File "/mnt/data/orangeboard/production/RTX/code/ARAX/ARAXQuery/Expand/smartapi.py", line 112, in get_trapi_endpoints\n    for server in hit["servers"]:\n', "KeyError: 'servers'\n"]
```

**Comment by saramsey** [comment]
Thank you @edeutsch for reporting this issue (via Slack `#deployment` channel)

**Comment by saramsey** [comment]
perhaps the code on L112 could be made a bit more robust so it doesn't lead to a stacktrace; thinking maybe printing a warning to the log about a misconfigured service, might be a good way to handle it?

**Comment by isbluis** [comment]
I added simple checking of the existence of the `servers` element; a warning is written to `stdout` if not found.
Please close when you are able to verify in production.

**Comment by edeutsch** [comment]
Great, thanks, please write the error to STDERR instead, since STDOUT is effectively invisible.

There really isn't any great way to test because it shouldn't happen and isn't happening now. But you could test by forcibly deleting the servers element from a response and watch that the code behaves appropriately.

**Comment by isbluis** [comment]
I did test by running `kp_info_cacher.py` multiple times (and checking for a made-up element as a test).  Worked fine.

I avoided STDERR since it is really not our application error, but one that comes from an outside resource.  I see it more as a warning, but glad to promote it to error.

**Comment by edeutsch** [comment]
Great, if you think it'll work better than it did before, then that's good enough.

In general with most web applications STDOUT goes back to the client and STDERR goes to the error logs. So if it shouldn't be sent to the client, send it to STDERR.

With ARAX, the system is a bit more complicated, but in general the policy is:
- If the ARAX Response object is available and the information should be stored in the logs section in the Response for the user to see, use the response.error() or response.warning() or response.info() or response.debug() methods. Sending the problem to there will BOTH put it in the response so that it can be see in the web UI AND write it to STDERR so it's visible in the error log file that sometimes gets looked at
- If the ARAX Response object is not available (as it isn't in kp_ingo_cacher.py) (or if it's not something the user should see), then send it to STDERR. You can format it however to you like, you can call it a warning or a note or an error or whatever
- Don't ever send anything to STDOUT unless it directly needs to end up with the client. it'll either mess up the JSON that the client wants back, or more usually, it will end up where no one will ever see it.

So here, it's fine to call it a warning if you like, but it has to be sent to STDERR to have any chance of being noticed.

thanks!

**Comment by isbluis** [comment]
It doesn't seem that this process ever talks back to a JSON client, but I am not that familiar with this part of the code.
Updated to send to STDERR.
Thanks!

**Comment by edeutsch** [comment]
Great, thanks, deployed!
