### ISSUE TITLE
KG2.8.4c canonicalization seems incomplete

### ISSUE THREAD

**Issue by saramsey** [RTXteam/RTX#2078]
In the KG2.8.4c Neo4j endpoint (kg2-8-4c.rtx.ai), the following Cypher command:
```
match (n {id: 'MONDO:0005015'})-[r:`biolink:close_match`]-(m) return m.name, m.id;
```
produces many obvious semantic synonyms for `MONDO:0005015` ("diabetes mellitus") that should be canonicalized to it: 
```
m.name	m.id
"Diabetes Mellitus"	"UMLS:C0011849"
"Diabetes"	"UMLS:C0011847"
"Diabetes Mellitus"	"NCIT:C2985"
"Diabetes Mellitus"	"MESH:D003920"
"Diabetes mellitus"	"ICD9:250"
"Diabetes mellitus"	"HP:0000819"
"diabetes mellitus"	"EFO:0000400"
"diabetes mellitus"	"DOID:9351"
"diabetes mellitus"	"EFO:0000400"
```
In contrast, in the KG2.8.3c Neo4j endpoint (kg2-8-3c.rtx.ai), that same query produces relatively few: 
```
m.name	m.id
"diabetic ketoacidosis"	"MONDO:0012819"
"Rare diabetes mellitus"	"ORPHANET:101952"
"Diabetes"	"OMIM:MTHU050182"
"Diabetes mellitus"	"OMIM:MTHU036798"
"Diabetes mellitus (DM)"	"LOINC:LA27539-8"
```
Was something changed with the canonicalization in KG2.8.4c?  I believe the more fragmented nature of KG2.8.4c is causing some failures of PloverDB regression tests (e.g., `PloverDB/test/test.py::test_20`).

**Comment by sundareswarpullela** [comment]
Could be an issue with poorly build synonymizer. I'm looking into it.

**Comment by amykglen** [comment]
it looks to me like the KG2.8.4 synonymizer doesn't suffer from the problem Steve reported - this is the cluster for `MONDO:0005015` in the KG2.8.4 synonymizer (I got the below table by running `python node_synonymizer.py MONDO:0005015`, after making sure my local `config_dbs.json` was pointed to the KG2.8.4 synonymizer):

Cluster for MONDO:0005015 has 17 nodes:

| id                | category   | name              |
|:------------------|:-----------|:------------------|
| DOID:9351         | Disease    | diabetes mellitus |
| EFO:0000400       | Disease    | diabetes mellitus |
| HP:0000819        | Disease    | Diabetes mellitus |
| ICD10:E08-E13     | Disease    |                   |
| ICD9:250          | Disease    | Diabetes mellitus |
| MEDDRA:10012594   | Disease    |                   |
| MEDDRA:10012601   | Disease    |                   |
| MEDDRA:10012614   | Disease    |                   |
| MESH:D003920      | Disease    | Diabetes Mellitus |
| MONDO:0005015     | Disease    | diabetes mellitus |
| NCIT:C2985        | Disease    | Diabetes Mellitus |
| PDQ:CDR0000685852 | Disease    | diabetes mellitus |
| PSY:13950         | Disease    | Diabetes          |
| PSY:13970         | Disease    | Diabetes Mellitus |
| SNOMEDCT:73211009 | Disease    |                   |
| UMLS:C0011847     | Disease    | Diabetes          |
| UMLS:C0011849     | Disease    | Diabetes Mellitus |

so this implies the issue was somewhere in the KG2c (as opposed to synonymizer) build. 

for whatever reason none of the nodes in that cluster are listed under MONDO:0005015's `equivalent_curies` property in neo4j:

<img width="1286" alt="Screen Shot 2023-08-02 at 5 41 43 PM" src="https://github.com/RTXteam/RTX/assets/49423686/b9c3f970-40d4-4f1a-bb33-43464d13a415">

that's a problem (that must have happened during the KG2c build).

were there any changes to the KG2c code recently, @sundareswarpullela?

**Comment by sundareswarpullela** [comment]
Amy and I suspect an issue with the code using the wrong or broken  synonymizer for the KG2.8.4c build. New KG2c build underway right now with the re-built synonimyzer.

**Comment by sundareswarpullela** [comment]
Neo4j with the latest KG2.8.4c is up on [kg2-8-4c.rtx.ai](http://kg2-8-4c.rtx.ai:7474/browser/). The number of non-canonicalized nodes in the latest build for the query:
```
match (n {id: 'MONDO:0005015'})-[r: `biolink:close_match`]-(m) return m.name, m.id;
```

reduced from 9 to 4. Now all 17 nodes are showing up as equivalent curies for `MONDO:0005015`.

**Comment by sundareswarpullela** [comment]
Working on getting plover up and running the tests again. But as mentioned above, initial tests seem promising. There is a significant reduction in KG2.8.4c file size as well pointing to a more completely canonicalized version.

**Comment by sundareswarpullela** [comment]
All Plover tests have now passed. Closing this issue.

**Comment by saramsey** [comment]
accidentally reopened, sorry
