### ISSUE TITLE
What are we going to do with NewFmt?

### ISSUE THREAD

**Issue by dkoslicki** [RTXteam/RTX#209]
I vaguely recall that this was/is for the proto-MVP; do we plan on eventually merging ``NewFmt`` to ``master``? What are the main steps that need to be done before this happens?

**Comment by edeutsch** [comment]
NewFmt is actually primarily for the switch from the Standard API Format version 0.7.0 to version 0.8.0. Since the format changed, there was a fair bit of code that had to change and we didn't want to break production.

We should definitely merge. But it would be helpful to pick a time when you have a little time to assist. I am not confident in my abilities to do the merge without making a hash of things. Got any time over the next couple days to be on call?
