### ISSUE TITLE
GUI gets stuck in "rendering..." state sometimes now?

### ISSUE THREAD

**Issue by edeutsch** [RTXteam/RTX#2094]
https://arax.ci.transltr.io/?r=96139275-cee2-4d1e-a215-a32a287e490d
![image](https://github.com/RTXteam/RTX/assets/12707718/4d18c1f1-7553-4f56-8dad-c6095845dccd)

Can we determine the cause of it?
It might be a ARS issue.

**Comment by isbluis** [comment]
This happens when the agent response is entirely empty (is that even considered a valid response??)
![image](https://github.com/RTXteam/RTX/assets/37852256/1f70d763-88ad-4006-8111-875d804f1b27)


I noticed this earlier this week, and has already been fixed in _devLM_:
https://arax.ncats.io/devLM/?r=96139275-cee2-4d1e-a215-a32a287e490d

**Comment by edeutsch** [comment]
ah great, then ship it!

looks like new behavior. I suspect it comes from the new 5 minute timeout they implemented. As of now, I think they made it so that if there's no response after 5 minutes, they just close it out and don't accept any more responses. And so the response is null.

Here are some examples for posterity:
https://arax.ncats.io/devLM/?r=96139275-cee2-4d1e-a215-a32a287e490d

https://ars.ci.transltr.io/ars/api/messages/96139275-cee2-4d1e-a215-a32a287e490d?trace=y

https://ars.ci.transltr.io/ars/api/messages/d41755b6-884b-44ca-a61d-f50b6284fc43

https://ars.ci.transltr.io/ars/api/messages/874e634e-ea04-4bf4-8157-74d2b218e73b

**Comment by isbluis** [comment]
Pushed the fix
