### ISSUE TITLE
Is KG2 working correctly?

### ISSUE THREAD

**Issue by edeutsch** [RTXteam/RTX#2102]
I've been having some problems with one of my smoke tests for KG2 since we upgraded and finally now trying to fix it. It's not returning expected answers.

Today when you ask production KG2 our standard Example 1 query, the results seem very strange to me. Please go to:
https://arax.ncats.io/kg2/
And issue the Example 1 JSON query: Which proteins physically interact with acetaminophen.
Usually with past KG2s we expect PTGS1 and 2 and friends.
The top hits now are ANAKINRA and GOLIMUMAB and gets weirder from there.
Is this sensible or is something off the rails here?
@saramsey

**Comment by saramsey** [comment]
This is what I am seeing right now:

<img width="656" alt="Screenshot 2023-08-16 at 7 59 26 AM" src="https://github.com/RTXteam/RTX/assets/5562107/98ae68fd-39ce-454e-bd52-1cd85bba504a">

**Comment by saramsey** [comment]
Yes, this is because the Biolink model says to map `DRUGBANK:drug-interaction` to `biolink:physically_interacts_with`. So there is, in fact, a drug-drug interaction between acetaminophen (`DRUGBANK:DB00316`) and the biologic therapeutic agent Anakinra (`DRUGBANK:DB00026`), and since the latter is a biologic, it gets tagged with a `category` label of `biolink:Protein`. I have already put in an issue with Biolink about that we cannot be mapping `DRUGBANK:drug-interaction` to `biolink:physically_interacts_with`; see https://github.com/biolink/biolink-model/issues/1371

**Comment by saramsey** [comment]
It looks better if you use `biolink:affects`

**Comment by saramsey** [comment]
The situation looks better on `kg2.test.transltr.io`. I'm going to close this out.
