### ISSUE TITLE
Multiple gene nodes with same name

### ISSUE THREAD

**Issue by dkoslicki** [RTXteam/RTX#214]
There are multiple genes with the same name, but are actually different:
```
match (n:protein{name:"PMM2"}) return n
```
eg. these all have the name PMM2, yet it returns the genes
http://www.uniprot.org/uniprot/Q59F02 (no name)
http://www.uniprot.org/uniprot/H3BV55 (an actual PMM2)
http://www.uniprot.org/uniprot/A0A0S2Z4J6 (uniprotKB duplicate gene)
http://www.uniprot.org/uniprot/H3BV34 (another duplicate).

Anybody up for reporting a bug to UniprotKB?

**Comment by edeutsch** [comment]
I know folks at UniProtKB, Swiss-Prot, and neXtProt pretty well and could help out. But they're also extraordinarily careful and you won't find bugs easily. This may be that we don't understand the situation quite right. Is the above the complete list of PMM2? The real PMM2 may be this in neXtProt:
 https://www.nextprot.org/entry/NX_O15305/
and in UniProtKB:
http://www.uniprot.org/uniprot/O15305
Notice that this one has "reviewed" status while the 4 you mention above are unreviewed entries. Remember that UniProtKB includes both Swiss-Prot (reviewed) and TrEMBL (unreviewed). For some species only a small fraction of the proteome is reviewed. But for human, the reviewing is essentially "finished", so unless you're delving into speculative research details, we probably don't want to be fussing much with unreviewed sequences. This is one reason that I was recommending neXtProt because they only have reviewed sequences and spend quite a lot more time fussing over the data since they only do human.

I'm happy to chat more about this. I'd need to learn the issues a bit better before I would go to UniProtKB claiming to have a bug.

**Comment by saramsey** [comment]
I am proceeding under the assumption that this is a bug in my code.

**Comment by edeutsch** [comment]
The quickest fix would be to reject any associations that link to a UniProt/TrEMBL protein. Only include links to reviewed UniProt/Swiss-Prot entries.

A slight refinement if we're worried about losing a little bit of valid ones is to only reject TrEMBL when Swiss-Prot entries are *also* present. If no Swiss-Prot association present, then maybe keep the TrEMBL.

I would contend that in 99% of cases, we should not add TrEMBL entries. Curiously, just now during another study I just stumbled into what seems like an important TrEMBL entry not in Swiss-Prot. I will report that one. I3L2J0

**Comment by saramsey** [comment]
fixed

![screen shot 2018-06-10 at 10 49 52 am](https://user-images.githubusercontent.com/5562107/41204647-0aea2e8a-6c9c-11e8-93fd-7d2a07353c28.png)
