### ISSUE TITLE
Why are we TRAPI validating every query response?

### ISSUE THREAD

**Issue by saramsey** [RTXteam/RTX#2159]
It was just explained to me (thanks @isbluis ) that ARAX and RTX-KG2 are TRAPI-validating (i.e., running through the reasoner validator) every query response. I am wondering why?  Given that (per @isbluis's timing results) validating the responses really increases latency (the statistic he quoted me is 5–10X, though perhaps I misunderstood the severity), why isn't this an optional thing (default off) that the user/client could turn on at their discretion?  Is this a "OSI Layer 9" 
issue?  Or could we just make it optional?   Please pardon my ignorance. I'm sure this has been discussed before but I don't recall.

**Comment by edeutsch** [comment]
I am under the impression that this is not the case. But I might be wrong.

**Comment by edeutsch** [comment]
I'm looking here: https://github.com/RTXteam/RTX/blob/8372db4d9ccf4c0fab828723b4d2fa995676dca6/code/ARAX/ARAXQuery/ARAX_query.py#L887

**Comment by edeutsch** [comment]
It depends a little on what you mean by "every query response"

**Comment by isbluis** [comment]
We validate when calling via response cache, [here](https://github.com/RTXteam/RTX/blob/8372db4d9ccf4c0fab828723b4d2fa995676dca6/code/ARAX/ResponseCache/response_cache.py#L319)

This adds quite a bit of time every time that a given response is requested.

**Comment by edeutsch** [comment]
what is true. But fresh queries are not validated.

**Comment by edeutsch** [comment]
(and note that since KG2 queries are never stored, they are never validated)

**Comment by saramsey** [comment]
OK, thank you!  Closing.

**Comment by edeutsch** [comment]
So my answer is:
- fresh queries are not validated, but all requests for previously stored are validated.
- I suppose the answer to why is:
- For development, to make sure that answers are valid TRAPI
- If we care enough to call up a previous response, we care enough to see if it's valid
- Historically many TRAPI responses (ours and others) have been invalid, and unless we showcase this, no one will ever notice and things will never get fixed.
- I attribute the fact that most TRAPI responses are valid these days is because of our relentless validation and public display of errors
- If no one can see the problems, they will never be fixed. Over-validation is a small price to pay IMO
-

**Comment by saramsey** [comment]
> So my answer is:
> 
>     * fresh queries are not validated, but all requests for previously stored are validated.
> 
>     * I suppose the answer to why is:
> 
>     * For development, to make sure that answers are valid TRAPI
> 
>     * If we care enough to call up a previous response, we care enough to see if it's valid
> 
>     * Historically many TRAPI responses (ours and others) have been invalid, and unless we showcase this, no one will ever notice and things will never get fixed.
> 
>     * I attribute the fact that most TRAPI responses are valid these days is because of our relentless validation and public display of errors
> 
>     * If no one can see the problems, they will never be fixed. Over-validation is a small price to pay IMO

Great points. Thank you.  Especially the point about (basically) "errors that are not seen will not get fixed". That is true.
