### ISSUE TITLE
Identifiers to MeSH terms

### ISSUE THREAD

**Issue by dkoslicki** [RTXteam/RTX#22]
I am trying to improve our answers to the Q2 COP's. To do this, I need the Google distance to work on all nodes in our KG. Currently, in QueryNCBIeUtils.py, there is a way to get mesh term ID's from OMIM ID's and from disease names, but I also need to get mesh term ID's from:
1. Uniprot protein identifiers (eg: P23219).
2. UBERON ID's

I don't think I need it for phenotypes since the KG descriptions are all showing up in MeSH as far as I can tell.

The need stems from the fact that currently the Google distance doesn't work on "P23219" and "Prostaglandin G/H synthase 1" (one of its synonyms), but does work for another synonym "Cyclooxygenase-1".

I tried poking around on the uniprot API, and the only way I could see to do this is to download:
https://www.uniprot.org/uniprot/P23219.xml (or https://www.uniprot.org/uniprot/P23219.txt)
and then pull off all the names and hit them with QueryNCBIeUtils.is_mesh_term. But I assume there's a much better way to do this via API call.

**Comment by dkoslicki** [comment]
@saramsey looks like something is wrong with QueryEBIOLS for some uberon's:
```python
>>>QueryEBIOLS.get_mesh_id_for_uberon_id("UBERON:0001162")
set()
```

**Comment by saramsey** [comment]
Fixed, do a git pull.

Also it looks like adding “self” to the method broke the test.  It’s a static method, so called like this:

    print(QueryEBIOLS.get_mesh_id_for_uberon_id("UBERON:0001162”))

-----------------------------------------------------
Stephen Ramsey
Assistant Professor, Oregon State University
* School of Electrical Engineering and Computer Science
* Department of Biomedical Sciences
208A Dryden Hall
stephen.ramsey@oregonstate.edu<mailto:stephen.ramsey@oregonstate.edu>
http://lab.saramsey.org







On Mar 21, 2018, at 4:25 PM, David Koslicki <notifications@github.com<mailto:notifications@github.com>> wrote:


@saramsey<https://github.com/saramsey> looks like something is wrong with QueryEBIOLS for some uberon's:

>>>QueryEBIOLS.get_mesh_id_for_uberon_id("UBERON:0001162")
set()

**Comment by dkoslicki** [comment]
Ummm... I don't think that was the issue.
```python
In[223]: import QueryEBIOLS
In[224]: print(QueryEBIOLS.get_mesh_id_for_uberon_id("UBERON:0001162"))
Traceback (most recent call last):
  File "/home/dkoslicki/Desktop/RTX/VE3/lib/python3.5/site-packages/IPython/core/interactiveshell.py", line 2910, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-224-d8034d4a5d80>", line 1, in <module>
    print(QueryEBIOLS.get_mesh_id_for_uberon_id("UBERON:0001162"))
AttributeError: module 'QueryEBIOLS' has no attribute 'get_mesh_id_for_uberon_id'
```

The issue was the fact that the MeSH ID is nonstandard. EBIOLS returns `` MESH:A03.492.766.163`` instead of a ``MESH:DXXX``.

**Comment by dkoslicki** [comment]
@saramsey Let me know if commenting on this issue is sufficient (as I just did above), or if I should @ mention you each time so it shows up in your email.

**Comment by saramsey** [comment]
That is in fact what is in the EBI OLS database, for UBERON:0001162

[cid:5498FE9D-D067-43EF-ABCB-7660D4E95B5A@hsd1.or.comcast.net.]
-----------------------------------------------------
Stephen Ramsey
Assistant Professor, Oregon State University
* School of Electrical Engineering and Computer Science
* Department of Biomedical Sciences
208A Dryden Hall
stephen.ramsey@oregonstate.edu<mailto:stephen.ramsey@oregonstate.edu>
http://lab.saramsey.org







On Mar 21, 2018, at 5:15 PM, David Koslicki <notifications@github.com<mailto:notifications@github.com>> wrote:


Ummm... I don't think that was the issue.

In[223]: import QueryEBIOLS
In[224]: print(QueryEBIOLS.get_mesh_id_for_uberon_id("UBERON:0001162"))
Traceback (most recent call last):
  File "/home/dkoslicki/Desktop/RTX/VE3/lib/python3.5/site-packages/IPython/core/interactiveshell.py", line 2910, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-224-d8034d4a5d80>", line 1, in <module>
    print(QueryEBIOLS.get_mesh_id_for_uberon_id("UBERON:0001162"))
AttributeError: module 'QueryEBIOLS' has no attribute 'get_mesh_id_for_uberon_id'

The issue was the fact that the MeSH ID is nonstandard. EBIOLS returns MESH:A03.492.766.163 instead of a MESH:DXXX.

**Comment by dkoslicki** [comment]
@saramsey  Frustrating thing is that MeSH doesn't seem to know that ``MESH:A03.492.766.163`` is a MeSH ID:
```python
QueryNCBIeUtils.get_mesh_terms_for_mesh_uid(QueryEBIOLS.get_mesh_id_for_uberon_id("UBERON:0001162").pop())
Out[309]: []
QueryNCBIeUtils.get_mesh_terms_for_mesh_uid(QueryEBIOLS.get_mesh_id_for_uberon_id("UBERON:0001162").pop().split(':')[1])
Out[310]: []
```

**Comment by dkoslicki** [comment]
So I guess the only approach now is to figure out how to map between MeSH tree numbers and MeSH ID's? EBIOLS gives UMLS cuids, so maybe after @arnabdotorg gets the UMLS up and running, we'd be able to convert them.

**Comment by saramsey** [comment]
I'm creating a new issue "need a method to convert MeSH tree number to MeSH UID" that will reference this issue

**Comment by dkoslicki** [comment]
Close in light of #63
