### ISSUE TITLE
Still collecting incorrect synonymizations?

### ISSUE THREAD

**Issue by dkoslicki** [RTXteam/RTX#2233]
I can't recall if we have a central location to report incorrect synonymizations. Are we just opening issues and labeling them? Tagging @amykglen as she likely knows.

In any case: https://arax.ncats.io/?term=HP:0000938 conflates Osteopenia with Marchiafava-Bignami Disease.

**Comment by amykglen** [comment]
thanks! yeah, I think creating an issue and tagging it with the 'conflation' and 'node synonymizer' tags is a good approach.

taking a look at this one, it looks like this is an issue in the SRI NodeNormalizer: https://nodenormalization-sri.renci.org/get_normalized_nodes?curie=HP:0000938

I just created an issue in their repo: https://github.com/TranslatorSRI/NodeNormalization/issues/249

so I guess maybe we can close this issue here, since we're supposed to align with whatever the SRI NN says?

**Comment by dkoslicki** [comment]
Thanks! I'll continue to open tickets and label them then
