### ISSUE TITLE
QueryNCBIeUtils.get_mesh_terms_for_mesh_uid always returns empty 

### ISSUE THREAD

**Issue by dkoslicki** [RTXteam/RTX#23]
Hi @saramsey, it looks like ``QueryNCBIeUtils.get_mesh_terms_for_mesh_uid`` is always returning an empty answer:
```python
>>>QueryNCBIeUtils.get_medgen_uid_for_omim_id('614332')
{482154, 814824}
>>>QueryNCBIeUtils.get_mesh_terms_for_mesh_uid({482154, 814824})
[]
```
and
```python
>>>QueryNCBIeUtils.get_medgen_uid_for_omim_id('600320')
{325371}
>>>QueryNCBIeUtils.get_mesh_terms_for_mesh_uid({325371})
[]
```
and a bunch of other similar examples.

**Comment by dkoslicki** [comment]
From Steve:
Try this:  (see the “get_mesh_uid_for_medgen_uid” which is a required intermediate step):

    print(QueryNCBIeUtils.get_medgen_uid_for_omim_id('603903')) print(QueryNCBIeUtils.get_mesh_uid_for_medgen_uid(287)) print(QueryNCBIeUtils.get_mesh_terms_for_mesh_uid(68000755))

**Comment by saramsey** [comment]
Hi Steve,

I'm still having issues with the following:
QueryEBIOLS.get_mesh_id_for_uberon_id("UBERON:0001723")  # The "tongue", which has a perfectly good entry on MeSH
{'MESH:D014059'}
which is a perfectly good looking mesh term, and yet
QueryNCBIeUtils.get_mesh_terms_for_mesh_uid('MESH:D014059')
Out[311]: []
QueryNCBIeUtils.get_mesh_terms_for_mesh_uid('D014059')
Out[312]: []
QueryNCBIeUtils.get_mesh_terms_for_mesh_uid('014059')
Out[313]: []
QueryNCBIeUtils.get_mesh_terms_for_mesh_uid(14059)
Out[314]: []
QueryNCBIeUtils.get_mesh_terms_for_mesh_uid(014059) # throws an error

Is this perhaps an issue with the leading 0?

It also concerns me that QueryEBIOLS returns "MESH:XXX" strings instead of actual mesh id's (which are treated as ints in the QueryNCBIeUtils code).

Thanks,

~David

**Comment by saramsey** [comment]
David,

Instead of doing this:

QueryNCBIeUtils.get_mesh_terms_for_mesh_uid(14059)

add 68,000,000 to the integer MeSH UID:

QueryNCBIeUtils.get_mesh_terms_for_mesh_uid(68014059)

now it works:
![screen shot 2018-03-23 at 9 33 29 pm](https://user-images.githubusercontent.com/5562107/37860461-b33e49e2-2ee2-11e8-8980-36d977bfc705.png)


So for any integer UID in “D” form, remove the “D”, convert to an integer, and add 68,000,000.

Yes it took me a long time to figure this out.  And no, I have no idea where the magic number 68,000,000 comes from.

Sigh.

Steve

**Comment by dkoslicki** [comment]
I [incorporated this fix](https://github.com/RTXteam/RTX/blob/master/code/reasoningtool/QuestionAnswering/ReasoningUtilities.py#L656) so am closing the issue.
