### ISSUE TITLE
Major Ranker refactor did not move the needle on testing??

### ISSUE THREAD

**Issue by edeutsch** [RTXteam/RTX#2324]
I have not had a chance to look into this more, but I've remembered and forgotten this twice this week, so here's a vague report:

Last week @chunyuma committed what appeared to be a major advance in our ranking algorithm. However, the testing results appeared not to move the needle at all!

Before (July 6):
https://arax.ci.transltr.io/?systest=78
(44 passing)

After (July 13):
https://arax.ci.transltr.io/?systest=79
(44 passing)

I do believe we made a big advance. But why is it not reflected in the test results?
Has any noticed/investigated this?

**Comment by dkoslicki** [comment]
I think this is due to the top N vs. top 10% issue which according to Shervin, Max, and Chris, should be deployed "soon"

**Comment by chunyuma** [comment]
Hi @edeutsch, 

Thanks for pointing out this potential issue.

I have two questions:

1. What was changed between https://arax.ci.transltr.io/?systest=78 and https://arax.ci.transltr.io/?systest=79? And what was changed between https://arax.ci.transltr.io/?systest=78 and https://arax.ncats.io/?r=248142 (the result we used in [this](https://docs.google.com/document/d/1HCVaLtyHHpbAwqfQZpz_mY8yxlGC9rerYkI1pEXaboc/edit) document)?

I found that ('TestCase_11', 'Asset_387'), ('TestCase_13', 'Asset_311'), ('TestCase_13', 'Asset_361'), ('TestCase_21', 'Asset_338'), ('TestCase_25', 'Asset_399'), ('TestCase_30', 'Asset_599'), ('TestCase_4', 'Asset_66'), ('TestCase_9', 'Asset_622') failed in https://arax.ci.transltr.io/?systest=78 but passed in https://arax.ci.transltr.io/?systest=79

I found that ('TestCase_0', 'Asset_9'), ('TestCase_12', 'Asset_309'), ('TestCase_16', 'Asset_324'), ('TestCase_22', 'Asset_363'), ('TestCase_22', 'Asset_365'), ('TestCase_22', 'Asset_366'), ('TestCase_28', 'Asset_493'), ('TestCase_28', 'Asset_494'), ('TestCase_28', 'Asset_495'), ('TestCase_28', 'Asset_496'), ('TestCase_7', 'Asset_78') passed in https://arax.ci.transltr.io/?systest=78 but failed in https://arax.ci.transltr.io/?systest=79

2. Any reason why the arax.ncats.io ranking results are different from that of the local run?

For TestCase_22 Asset_365, `Quinidine` ranks 69 but the local run (`master`) ranks 96. Although I did find a problem in the new algorithm that will be fixed later and improve its ranking. But I am wondering if the `arax.ncats.io` and local run both run the same pipeline and new algorithm, why are they dfferent?


After careful investigation, the new algorithm indeed has improved the results and fixed some previous failed tests (e.g., see [this](https://docs.google.com/document/d/1HCVaLtyHHpbAwqfQZpz_mY8yxlGC9rerYkI1pEXaboc/edit) document, e.g., `test1_asset12`, `test5_asset70`, `test5_asset72`), but I found the following two main reasons:

### 1. Number of returned results has changed after the new deployment.
For example, test9 asset614: "famotidine treats Gastroesophageal Reflux Disease"
The [previous version](https://arax.ncats.io/?r=248142) has 188 results, the target `famotidine` ranks 58.
The [new deployment](https://arax.ncats.io/?r=7fb53b61-161f-487a-82e3-1d704d3cc79e) has only 78, `famotidine` ranks 13.

This is partly related to the issue #2327. It should be fixed after the full build of xDTD for KG2.10.0. But since the KG is different, the number of results should also change after xDTD v2.10.0 is deployed. But the rank generated by the new algorithm is indeed improved. As @dkoslicki said, if we fixed top 10% issue, most of related tests should pass.

### 2. Number of edges has changed after the new deployment.
Also, we use test9 asset614: "famotidine treats Gastroesophageal Reflux Disease"
The `famotidine` result in the [previous version](https://arax.ncats.io/?r=248142) has 10 edges:
infores:rtx-kg2:PUBCHEM.COMPOUND:3325--biolink:treats--None--None--None--MONDO:0007186--infores:drugcentral
`infores:spoke:PUBCHEM.COMPOUND:3325--biolink:treats--None--None--None--MONDO:0007186--infores:spoke`
infores:rtx-kg2:PUBCHEM.COMPOUND:3325--biolink:treats--None--None--None--MONDO:0007186--infores:repodb
creative_DTD_prediction_6
infores:service-provider-trapi:CHEBI:4975--biolink:treats--None--None--None--MONDO:0007186--infores:chembl
infores:rtx-kg2:PUBCHEM.COMPOUND:3325--biolink:treats--None--None--None--MONDO:0007186--infores:chembl
infores:rtx-kg2:PUBCHEM.COMPOUND:3325--biolink:treats--None--None--None--MONDO:0007186--infores:semmeddb
infores:service-provider-trapi:CHEBI:4975--biolink:treats--None--None--None--MONDO:0007186--infores:drugcentral
`infores:openpredict:DRUGBANK:DB00927--biolink:treats--None--None--None--OMIM:109350--infores:openpredict`
infores:service-provider-trapi:CHEBI:4975--biolink:treats--None--None--None--MONDO:0007186--infores:aeolus

The `famotidine` result in the [[new deployment](https://arax.ncats.io/?r=7fb53b61-161f-487a-82e3-1d704d3cc79e) has only 7 edges:
`infores:openpredict:DRUGBANK:DB00927--biolink:treats--None--None--None--OMIM:109350--infores:openpredict`
infores:molepro:CHEBI:4975--biolink:treats--None--None--None--MONDO:0007186--infores:drug-repurposing-hub
infores:molepro:CHEBI:4975--biolink:treats--None--None--None--MONDO:0007186--infores:chembl
infores:molepro:CHEBI:4975--biolink:treats--None--None--None--MONDO:0007186--infores:sider
infores:molepro:CHEBI:4975--biolink:treats--None--None--None--MONDO:0007186--infores:drugcentral
`infores:spoke:PUBCHEM.COMPOUND:3325--biolink:treats--None--None--None--MONDO:0007186--infores:spoke`
infores:molepro:CHEBI:4975--biolink:treats--None--None--None--MONDO:0007186--infores:ctd

I have highlighted those are the same between two versions. As you see, only two are the same. I am not sure if the change is mainly because of KG2 update, or node synonymizer, or potential updates from provider APIs. @amykglen, do you have any idea?

Also, you can see that the `creative_DTD_prediction_6` edge is gone in the new deployment. It further confirm the refreshed version of xDTD cannot fully recover all edges due to the mapping issue. However, this also makes me concern that the reason 1 is not fully due to the xDTD refresh. The KG2 update, or API update, which might affect the lookup, might also affects the number of returned results.

###

**Comment by edeutsch** [comment]
Hi @chunyuma thank you for your analysis. Unfortunately a lot of things things changed and this is probably responsible for the why the performance did not increase like I expected. Also, we had another major problem with the deployment this past weekend, so the latest test results are not good. Separately, we were still suffering from the "top 10% might be a very small number" problem.

All that to say, I think we should just wait and see. I expect that the next test run this coming Saturday should be MUCH better because of multiple fixes. Let's wait until then and see where we stand and then do the kind of analysis you did above again to see what still needs to be done.

thanks!

**Comment by chunyuma** [comment]
Thank you @edeutsch. I will wait and see its performance in the next run, and then discuss what we should fix.

**Comment by chunyuma** [comment]
> Any reason why the arax.ncats.io ranking results are different from that of the local run?
For TestCase_22 Asset_365, Quinidine ranks 69 but the local run (master) ranks 96. Although I did find a problem in the new algorithm that will be fixed later and improve its ranking. But I am wondering if the arax.ncats.io and local run both run the same pipeline and new algorithm, why are they dfferent?

By the way, team, can anybody help me figure out the reason for this issue. I have spent much time yesterday for this issue but cannot figure it out.

I basically used the following code to extract the results with its response id from `arax.ncats.io` and then perform the new algorithm locally:
```
def _extract_ARAX_online_results(response_id: str, api_link: str = 'https://arax.ncats.io/api/arax/v1.4/response/') -> List[Union[ARAXResponse, Message]]:
    # Extracts the ARAXResponse objects from the ARAX online results
    
    # generate an ARAX response object
    response = ARAXResponse()
    #### Create an empty envelope
    messenger = ARAXMessenger()
    messenger.create_envelope(response)
    response.envelope.submitter = '?'

    # extract results based on response_id
    message = messenger.fetch_message(f'{api_link}{response_id}')
    response.envelope.message = message
    return [response, response.envelope.message]

def _do_arax_query(query: dict) -> List[Union[ARAXResponse, Message]]:
    # Perform the ARAX query
    
    araxq = ARAXQuery()
    response = araxq.query(query)
    if response.status != 'OK':
        print(response.show(level=response.DEBUG))
    #return [response, araxq.message]
    return [response, response.envelope.message]

def _do_arax_rank(response: ARAXResponse) -> Message:
    # Rank the ARAX results
    
    ranker = ARAXRanker()
    ranker.aggregate_scores_dmk(response)
    if response.status != 'OK':
        print(response.show(level=response.DEBUG))
    return response.envelope.message

def _ranker_tester(query: dict = None, response_id: str = None) -> Message:
    # Test the ARAX ranker
    
    if response_id is not None:
        response, _ = _extract_ARAX_online_results(response_id)
    else:
        response, _ = _do_arax_query(query)
    message = _do_arax_rank(response)
    return message

returned_message = _ranker_tester(response_id='250930')
for index, result in enumerate(returned_message.results):
    print([index, result.essence.lower()])
```

**Comment by edeutsch** [comment]
Note that there are different versions of code running on arax.ncats.io. https://arax.ncats.io/test is running on the `master` branch, but https://arax.ncats.io/ is running from the `production` branch, which is substantially different code. I don't know if that is perhaps part of the problem? but I don't know.

**Comment by chunyuma** [comment]
Thanks @edeutsch. I think this should be the reason.

**Comment by edeutsch** [comment]
Latest test results seem excellent, so I think the various contributors to this problem have been solved. closing.
