### ISSUE TITLE
Un-refactor xDTD `treats`

### ISSUE THREAD

**Issue by dkoslicki** [RTXteam/RTX#2329]
Our previous understanding of the `treats` refactor was to replace `treats` in xDTD with `treats_or_applied_or_studied_to_treat`. Subsequently, it [appears](https://github.com/NCATSTranslator/Feedback/issues/865#issuecomment-2240049256) that we _must_ return the top level `treats` in the result, and can use things like `treats_or_applied_or_studied_to_treat` only in the support graph.

Related to #2328 as lookups might not be returning the predicate `treats`

**Comment by chunyuma** [comment]
Hi @dkoslicki, I un-refactor it via [this PR](https://github.com/RTXteam/RTX/pull/2330). Based on my understanding, the `treats_or_applied_or_studied_to_treat` in the support graph should only be fixed in KG2 build itself, right?

**Comment by dkoslicki** [comment]
It appears that support graphs can use whatever predicates they want, so we should be good on that front. Looks like this PR fixes that for the top-level xDTD results, so I've approved that PR

**Comment by chunyuma** [comment]
@dkoslicki, since this fix has been merged into the `master` branch, can we close this issue now?

**Comment by dkoslicki** [comment]
I've tagged it to verify in the next deployment. Let's confirm in there and then close

**Comment by saramsey** [comment]
@dkoslicki is this a TRAPI requirement?  i.e., because the query graph is specifying `biolink:treats`, then the result graph also needs to have `biolink:treats`?  

I guess I'm asking if this changes things for RTX-KG2, where we can (and do) use the predicate `biolink:treats_or_applied_or_studied_to_treat` where that is the most appropriate predicate given the source and source relationship type, for the specific knowledge triple.
