### ISSUE TITLE
Has NodeSynonymizer become very slow?

### ISSUE THREAD

**Issue by edeutsch** [RTXteam/RTX#2336]
I have not investigated this much, but I have on two occasions noted a big lag time from what appears to be the NodeSynonmizer. Could there be a glitch that is causing it to be slow (where it has historically been very fast)?

https://arax.test.transltr.io/?r=253216
```
2024-07-30T23:27:37.886327 DEBUG: Looking up names for 1 input curies using NodeSynonymizer
2024-07-30T23:27:43.801596 INFO: After Expand, the KG has 107 nodes and 181 edges (e00: 181, n00: 1, n01: 106)
```
(6 seconds to look up 1 curie?)

Even running the "Example 1" query on https://kg2.test.transltr.io/ shows:
```
2024-07-30T23:31:18.714806 DEBUG: Looking up names for 1 input curies using NodeSynonymizer
2024-07-30T23:31:23.921815 INFO: 186 Semmeddb Edges with low publication count successfully removed
```
(5 seconds to look up 1 curie?)

Could there be some missing indexes perhaps?

**Comment by amykglen** [comment]
I suspect this might actually be related to the fact that the Acetaminophen cluster now includes over 600 nodes (due to the SRI NN's inclusion of things like `acetaminophen 325 MG Oral Tablet`, `acetaminophen 16 MG/ML Oral Solution`)... the general-purpose `get_normalizer_results()` method is used for that "Looking up names for 1 input curies using NodeSynonymizer" step... maybe it's just a big enough answer that it's a bit slow? my browser also appears to crash now when trying to view the Acetaminophen cluster: https://kg2.test.transltr.io/?term=CHEMBL.COMPOUND:CHEMBL112. not surprising since the cluster includes over 90,000 edges..

supporting that theory, when I plug in naproxen instead of Acetaminophen (which has a smaller, though still large, cluster - 330 nodes), that slowdown is 1.5 seconds vs. 5 seconds:
```
   2024-07-31T17:18:44.356996 DEBUG:    Looking up names for 1 input curies using NodeSynonymizer 0.296 s
   2024-07-31T17:18:45.870246 INFO:    52 Semmeddb Edges with low publication count successfully removed 1.81 s
   2024-07-31T17:18:45.870349 INFO:    After Expand, the KG has 13 nodes and 20 edges (e00: 20, n00: 1, n01: 12)
```
worth noting that this lookup step is really only used to do something that isn't required (it's an extra step to sort of override the synonymizer's canonical curies in the answer and use the CHEMBL curie for acetaminophen instead of the canonical CHEBI one, since the user input a CHEMBL curie)...

**Comment by edeutsch** [comment]
great, thanks for looking into it! I wonder if there could be another method that is faster and nimbler and just returns some basic information like what is the normalized CURIE, which is probably all that's needed here? So instead of returning a 90,000 edge graph and all the fancy stuff, just the CURIE or whatever is really necessary? I think there is/was something like that that we use in the list management tool in the UI? I can't remember, but I wonder if a little optimization could turn this from 5 seconds to 0.05 seconds?

**Comment by amykglen** [comment]
yes, we can certainly add a streamlined method for getting the necessary info... I imagine that will fix this.

this will also go away if we're switching to the 'new' standalone Plover service for KG2 hosting in the near future, though it may be worth still fixing this in the meantime..

**Comment by amykglen** [comment]
ok, this is fixed in `master`! I added a new streamlined synonymizer method and verified that it looks way better on ARAX CI: https://arax.ci.transltr.io/?r=257096
```
 2024-08-22T21:20:27.539727 DEBUG: Looking up names for 1 input curies using NodeSynonymizer.get_curie_names()
 2024-08-22T21:20:27.540235 INFO: After Expand, the KG has 107 nodes and 184 edges (e00: 184, n00: 1, n01: 106)
```
0.001 seconds for this step vs. 6 seconds before.

**Comment by edeutsch** [comment]
Brilliant, thanks!
