### ISSUE TITLE
Prod KG2 not returning interacts_with edges

### ISSUE THREAD

**Issue by edeutsch** [RTXteam/RTX#2368]
Since we deployed to PROD, my watchdog has been barking constantly. The reason seems to be that the RTX-KG2 is not returning expected **intereracts_with** edges and thus the watchdog checks that good results are coming back fail.

For example, running "Example 1" query in CI yields:
![image](https://github.com/user-attachments/assets/8c555f10-fa0f-46a1-8d24-a45ae9fca0b5)

Running "Example 1" query in TEST yields the same.

But running "Example 1" query in PROD yields
![image](https://github.com/user-attachments/assets/283e08b0-f659-4f04-bee3-f7c46b710621)

I don't understand why this is the case, if it is an indication of a deployment problem, or if KG2 just didn't have those edges in that release?

Does anyone know? It might come up at the relay.

**Comment by amykglen** [comment]
hmm, so, I think that the ITRB production KG2 doesn't have the latest databases - the production Plover is running KG2.10.0c as it should be, but the production KG2 appears to have the KG2.9.0c sqlite (for node/edge decoration), instead of the KG2.10.0c sqlite. I'm figuring that it must also have the KG2.9.0 synonymizer, which means that it is likely querying Plover with the wrong canonical curies for KG2.10.0, which means we don't get any results.

I can tell because the name on this node (which comes from Plover) says KG2.10.0, but the attributes (whcih come from KG2's sqlite), are from KG2.9.0:

<img width="798" alt="Screenshot 2024-09-07 at 8 43 17 PM" src="https://github.com/user-attachments/assets/514daba1-0c93-4c65-b96c-a0166451f0ee">

odd, since the production ARAX _does_ appear to have the correct KG2.10.0 databases. not sure why the KG2 database downloads seem to have failed?

**Comment by amykglen** [comment]
I suppose it’s most likely the entire KG2 Prod deployment didn’t go through - seems unlikely it somehow downloaded the wrong databases, since it’s deployed from the same branch as Prod ARAX, which is fine
________________________________
From: Eric Deutsch ***@***.***>
Sent: Saturday, September 7, 2024 4:30:38 PM
To: RTXteam/RTX ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [RTXteam/RTX] Prod KG2 not returning interacts_with edges (Issue #2368)


[This email originated from outside of OSU. Use caution with links and attachments.]

Since we deployed to PROD, my watchdog has been barking constantly. The reason seems to be that the RTX-KG2 is not returning expected intereracts_with edges and thus the watchdog checks that good results are coming back fail.

For example, running "Example 1" query in CI yields:
image.png (view on web)<https://github.com/user-attachments/assets/8c555f10-fa0f-46a1-8d24-a45ae9fca0b5>

Running "Example 1" query in TEST yields the same.

But running "Example 1" query in PROD yields
image.png (view on web)<https://github.com/user-attachments/assets/283e08b0-f659-4f04-bee3-f7c46b710621>

I don't understand why this is the case, if it is an indication of a deployment problem, or if KG2 just didn't have those edges in that release?

Does anyone know? It might come up at the relay.

**Comment by edeutsch** [comment]
yeah, I came to the same conclusion. I will pester ITRB, thanks.

**Comment by edeutsch** [comment]
Although they asked me to verify TEST, they never actually asked me to verify PROD. So it may be that they didn't finish. Maybe they got half way through at Friday quitting time and will finish Monday morning. I pinged them about it and we'll see what they say.

**Comment by amykglen** [comment]
looks like the ITRB Prod KG2 is fixed now! https://arax.transltr.io/?r=292988

**Comment by edeutsch** [comment]
great, thanks! I have informed ITRB. closing.
