### ISSUE TITLE
SynonymMapper.py mangled

### ISSUE THREAD

**Issue by edeutsch** [RTXteam/RTX#241]
@finnagin @dkoslicki 
Hi Finn, I had to mangle SynonymMapper.py to get it to work on rtx.ncats.io. These are actually some changes that we made together  at the hackathon to get it to compile. But now that I merged NewFmt to master, I have to include these hacks. 

Can you help figure out how to get SynonymMapper.py to state where it works for everyone? Here's the diff on what I just checked in:

https://github.com/RTXteam/RTX/commit/ebb11a24debaaee93d1c2521a26d67e61b3b2e93#diff-42d97058e5c7204e34a9e1ab180703ee

Most of it is commenting out things that weren't working on rtx. But there may also be reversions of previous fixes. Help!

thanks,
Eric

**Comment by finnagin** [comment]
@edeutsch No Worries! I'll take a look later and try to unmangle it.

**Comment by finnagin** [comment]
@edeutsch If I remember correctly the reason we had to comment out all of the cui mapping stuff because it used SemMedInterfce.py which depends on a package called mysqlclient which wasn't installed when we tried to run it. While this was previously added to requirements.txt on the master branch my guess is the reason it wasn't working is because the docker container we ran it on was initialized on an older requirements.txt file and has not been updated to include new python modules that have since been added to requirements.txt. If we want to uncomment these lines I think it will probably be as simple as just installing mysqlclient on whichever docker container is going to run SynonymMapper.py.

**Comment by edeutsch** [comment]
ah, okay, that might be easy then. @saramsey, do you want to manage the sync'ing to the requirements.txt in the various containers? Or shall I try to bumble my way through it? I'm not really certain what the best way to do that is, but I can try to figure it out.

**Comment by saramsey** [comment]
Uh sorry, I just noticed this issue from 20 days ago.  I don't see a requirements.txt anywhere in our source code repo.  Am I missing something?

**Comment by dkoslicki** [comment]
It’s at the very top level:
https://github.com/RTXteam/RTX/blob/master/requirements.txt

**Comment by edeutsch** [comment]
If anyone knows the best way to apply these requirements to rtx.ncats.io container rtx1, that would be most helpful, thanks!
