### ISSUE TITLE
need a method for mapping between a drug and human phenotypes (corresponding to side effects)

### ISSUE THREAD

**Issue by saramsey** [RTXteam/RTX#244]
We will use Mychem to map between a drug and its side effects (the drug<->side-effect relationships come from the SIDER database but are provided by Mychem).

You can use Mychem to map between a drug (specified by its CHEMBL compound ID) and its side effects (which are identified by UMLS IDs), see here:
http://mychem.info/v1/chem/KWHRDNMACVLHCE-UHFFFAOYSA-N

then perhaps you can use the EBI OXO to map between a UMLS ID for a "side effect" and a Human Phenotype Ontology (HPO) term ID.
https://www.ebi.ac.uk/chembl/index.php/compound/results

**Comment by saramsey** [comment]
method's input:  a drug identified by a CHEMBL compound ID
method's output:  a set of Human Phenotype Ontology (HPO) IDs of the phenotypes that are the "side effects" of the drug 

(side effects are things like headache, nausea, etc.).

**Comment by finnagin** [comment]
#### This is from an email chain with Steve:

Essentially you can use a get request on url like this: https://uts-ws.nlm.nih.gov/rest/search/2018AA?string=HP:0001947&sabs=HPO&searchType=exact&inputType=sourceUi&ticket=ST-3586050-hBeaugdLoO3UdBK4aade-cas

which results in:
```
{
  "pageSize": 25,
  "pageNumber": 1,
  "result": {
    "classType": "searchResults",
    "results": [
      {
        "ui": "C0001126",
        "rootSource": "MTH",
        "uri": "https://uts-ws.nlm.nih.gov/rest/content/2018AA/CUI/C0001126",
        "name": "Renal tubular acidosis"
      }
    ]
  }
}
```
(`res['result']['resuts'][0]['ui']` is the cui you want)

Where the id in the string field is replaced with the HP id you want to convert and the ticket is generated using this process: https://documentation.uts.nlm.nih.gov/rest/authentication.html

Essentially to get the result you have to first find your api key from your umls account. Then, use that api key to request a ticket generating ticket (which is good for 8 hours). Then you can use that TGT to request a single use ticket which you can then use to send the request.

#### But I realized I was doing the opposite of what he asked so I also said:

You want UMLS -> HPO correct? You can just use oxo to do this as well using a url like this: https://www.ebi.ac.uk/spot/oxo/api/mappings?fromId=UMLS:C0001126

Essentially, you just look at the responses and look for ids starting with HP: in 'fromterm' and 'toterm' in all of the elements in res['_embedded']['mappings'] and you will get your results.

#### I added functionality to SynonymMapper.py that does the second part.

You can run it using the following code:
```
from SynonymMapper import SynonymMapper
sm = SynonymMapper()
hp_id = sm.get_all_from_oxo('UMLS:C0001126', 'HP')
```
`hp_id` will then be `['HP:0001947']`

**Comment by DeqingQu** [comment]
Thank you, @finnagin! Your function makes my work much easier :)

**Comment by finnagin** [comment]
You're welcome!

**Comment by DeqingQu** [comment]
@saramsey 
I found there are many objects have the same umls_id in the 'sider' filed of the response data. 
For example:
```
{
      "_license": "https://goo.gl/8b7ZCQ",
      "meddra": {
        "type": "PT",
        "umls_id": "C0042029"
      },
      "side_effect": {
        "frequency": "3.64%",
        "name": "Urinary tract infection",
        "placebo": false
      },
      "stitch": {
        "flat": "CID116156130",
        "stereo": "CID016157882"
      }
    },
{
      "_license": "https://goo.gl/8b7ZCQ",
      "meddra": {
        "type": "PT",
        "umls_id": "C0042029"
      },
      "side_effect": {
        "frequency": "0.448%",
        "name": "Urinary tract infection",
        "placebo": false
      },
      "stitch": {
        "flat": "CID116156130",
        "stereo": "CID016157882"
      }
    },
    {
      "_license": "https://goo.gl/8b7ZCQ",
      "meddra": {
        "type": "LLT",
        "umls_id": "C0042029"
      },
      "side_effect": {
        "frequency": "8.28%",
        "name": "Urinary tract infection",
        "placebo": false
      },
      "stitch": {
        "flat": "CID116156130",
        "stereo": "CID016157882"
      }
    },
```
I dropped the duplicated umls_id and used Finn's function to query the HP id according to the umls_id. Is it fine?

One more questision. When I try to use 'CHEMBL521' (ibuprofen) to query the side effects, I got nothing. http://mychem.info/v1/chem/CHEMBL521?fields=sider Is this because I used the wrong parameter or because the 'SIDER' database does not have the appropriate data?

**Comment by dkoslicki** [comment]
@DeqingQu I think this is because the mychem API wants the inchi key instead of a ChEMBL ID. For example, the ibuprofen inchi key is ``HEFNNWSXXWATRW-UHFFFAOYSA-N`` and the following gives expected results: http://mychem.info/v1/chem/HEFNNWSXXWATRW-UHFFFAOYSA-N. See also: http://mychem.info/v1/chem/KWHRDNMACVLHCE-UHFFFAOYSA-N?fields=sider

**Comment by dkoslicki** [comment]
That is odd... maybe just make a note of those drugs that don’t have sider side effects and we can figure out what to do with them (if anything) later.

**Comment by DeqingQu** [comment]
I tried some drugs I known. None of the response data from MyChem contains the 'sider' field.

It is very weird. Is this possible because I used the wrong CHEMBL ID?

Penicillin V
https://www.ebi.ac.uk/chembldb/compound/inspect/CHEMBL615
http://mychem.info/v1/chem/CHEMBL615?fields=sider
http://mychem.info/v1/chem/BPLBGHOLXOTWMN-MBNYWOFBSA-N?fields=sider

Cetirizine
https://www.ebi.ac.uk/chembldb/compound/inspect/CHEMBL1000
http://mychem.info/v1/chem/CHEMBL1000?fields=sider
http://mychem.info/v1/chem/ZKLPARSLTMPFCP-UHFFFAOYSA-N?fields=sider

Amoxicillin
https://www.ebi.ac.uk/chembldb/compound/inspect/CHEMBL1082
http://mychem.info/v1/chem/CHEMBL1082?fields=sider
http://mychem.info/v1/chem/LSQZJLSUYDQPKJ-NJBDSQKTSA-N?fields=sider

Domperidone
https://www.ebi.ac.uk/chembldb/compound/inspect/CHEMBL219916
http://mychem.info/v1/chem/CHEMBL219916?fields=sider
http://mychem.info/v1/chem/FGXWKSZFVQUSTL-UHFFFAOYSA-N?fields=sider

**Comment by dkoslicki** [comment]
@saramsey, @jaredroach, or @edeutsch any of you have experience with ``mychem`` and/or ``sider``? It appears that the side effects info for drugs is somewhat sparse...

**Comment by edeutsch** [comment]
I do not have any

**Comment by jaredroach** [comment]
I do not have any.

**Comment by saramsey** [comment]
@DeqingQu note that @flashkicker is working this issue under issue #90; we somehow ended up with two issues for the same thing, but there is a lot of information recorded under #244 so we will keep this issue around for reference purposes.
