### ISSUE TITLE
Neo4j Bloom

### ISSUE THREAD

**Issue by dkoslicki** [RTXteam/RTX#256]
[Neo4j bloom](https://neo4j.com/bloom/) a really cool neo4j visualization package a lot better than the default neo4j browser. Shall we pursue installing? Similar gains to be had as installing APOC. We will need a hardware GPU though...
@finnagin can you:

- [x] Check if any of our AWS instances have a GPU attached
- [ ] inquire about a (free) academic license (see link above)
- [ ] Find out what would be involved with installing it

**Comment by finnagin** [comment]
@dkoslicki Sure! I'll look into this.

**Comment by finnagin** [comment]
@dkoslicki  So, I know that we are using the memory optimized aws instances (r4.4xlarge and r4.8xlarge) but looking on line amazon doesn't seem to [mention anything about GPUs.](https://aws.amazon.com/blogs/aws/new-next-generation-r4-memory-optimized-ec2-instances/) So, I logged into rtxdev.saramsey.org (which is a r4.4xlarge instance) and ran `sudo lshw -C display` which told me that it uses a Cirrus Logic GD 5446 and looking at the [specs](https://www.cnet.com/products/cirrus-logic-5440-graphics-card-cl-gd5440-1-mb/specs/) I don't think it would cut it. I'm guessing that the r4.8xlarge instance has something similar but I cant log into that one to confirm.

**Comment by dkoslicki** [comment]
Ok, I see. How about you find out the other bits of information while we figure out the GPU issue (also, it would be good to know if the GPU needs to be server-side or client-side).

**Comment by finnagin** [comment]
@dkoslicki So, it looks like we also need to an enterprise edition neo4j instance (we are currently running community) but it looks like they offer an [educational licence](https://neo4j.com/licensing/) for the enterprise edition. I'm sending them an email asking about educational licences for both the enterprise editions as well as bloom and I'm also asking to clarify if it runs locally or on the server.(Since I couldn't find much clarification searching online) I'll let you know what they say when they respond.

**Comment by dkoslicki** [comment]
Excellent, thanks @finnagin!

**Comment by finnagin** [comment]
I haven't heard back yet but I did get an email stating that they received my email and telling me who was going to follow up with me. Might be a bit before they actually respond.

**Comment by finnagin** [comment]
Ok, I'll do that. Should I close this issue for now and reopen if they get back to me about bloom educational licences?

**Comment by dkoslicki** [comment]
Works for me!
