### ISSUE TITLE
MyChem API doesn't return side effects

### ISSUE THREAD

**Issue by flashkicker** [RTXteam/RTX#269]
Implement mapping of drugs to side effects after Kevin Xin fixes the issue in their API as mentioned in #90

**Comment by saramsey** [comment]
Hi Ujjval,

Thanks for sending the PR review request.

I have pushed a few code changes to DrugMapper.py, in the issue269 branch. These code changes vastly speed up the code. The issue was that the code in was calling make_meddra_to_hp_map() inside a map_meddra_to_hp(), but the latter method is called many many times.

So I modified the class to call make_meddra_to_hp_map() once during module initialization and cache the map as a class static member variable.

I think we are now ready to merge.  

@Deqing, can you please work on merging the code from the issue269 branch into the trunk?
If you have questions, feel free to ask Ujjval.  Ujjval's GRA is over as of two weeks ago (he is now on a GTA) so that is why I am thinking we should have you do the merge.

Cheers,
Steve

**Comment by deqing** [comment]
@DeqingQu

**Comment by saramsey** [comment]
Sorry, @deqing

**Comment by DeqingQu** [comment]
@flashkicker @saramsey 
I have reviewed and tested the code in the issue269 branch. The branch has been merged into our master branch.

**Comment by saramsey** [comment]
fixed

![screen shot 2018-11-05 at 12 50 41 pm](https://user-images.githubusercontent.com/5562107/48026425-e7c9ad80-e0fa-11e8-9704-bbb90c58ed74.png)

**Comment by saramsey** [comment]
![screen shot 2018-11-05 at 12 50 37 pm](https://user-images.githubusercontent.com/5562107/48026434-edbf8e80-e0fa-11e8-92e8-994d17388e90.png)
