### ISSUE TITLE
Can't query on UniProtKB identifier any more?

### ISSUE THREAD

**Issue by edeutsch** [RTXteam/RTX#271]
It seems like in the past one could query on UniProtKB identifiers, but now not:

What happened to P06865?
 
==== Testing for finding curies by name ====
APS2 = ['OMIM:269200']
phenylketonuria = ['OMIM:261600', 'DOID:9281', 'REACT:R-HSA-2160456', 'REACT:R-HSA-2160456']
Gaucher's disease = ['DOID:1926']
Gauchers disease = ['DOID:1926']
Gaucher disease = ['DOID:1926']
Alzheimer Disease = ['OMIM:104300', 'DOID:10652', 'HP:0002511']
Alzheimers disease = ['DOID:10652', 'HP:0002511']
Alzheimer's Disease = ['DOID:10652', 'HP:0002511']
kidney = ['UBERON:0002113']
Kidney = ['UBERON:0002113']
P06865 = []
HEXA = ['UniProtKB:P06865']
rickets = ['DOID:10609', 'HP:0002748']
fanconi anemia = ['DOID:13636']
retina = ['UBERON:0000966']
is = []
Elapsed time: 0.017115913331508636

**Comment by dkoslicki** [comment]
This may be due to the ``KGNodeIndex`` using the second column of ``NodeNamesDescriptions.tsv`` file. If this doesn't have the identifier in it, the index can't see it. Maybe ``KGNodeIndex`` can be updated to also pull off the protein symbols? Otherwise, I can change ``dumpdata.py`` so that it adds rows in ``NodeNamesDescriptions.tsv`` with column 1 = node id, column 1 = UniProtKB symbol. Do you have a preference?

**Comment by edeutsch** [comment]
Yes, I think this is just due to a change in the identifier form. I think before there were't CURIE prefixes UniProtKB: but now there are, so the parsing code is not working correctly around line 193 of KGNodeIndex.py. I'll fix sometime soon. Assigned to me.

**Comment by dkoslicki** [comment]
@edeutsch iirc, you fixed this at the hackathon, right? Shall we close this issue?

**Comment by edeutsch** [comment]
yes, correct, fixed at hackathon. Thanks for the reminder!
