### ISSUE TITLE
Node type a list?

### ISSUE THREAD

**Issue by edeutsch** [RTXteam/RTX#293]
At the lack hackathon Vlado and Mathias let me know that in the Standard API format Node.type needed to be a list. I said that the KG standard didn't support that, but they said that it was decided that it would. The example they gave was insulin, which was both a drug and a protein. I was a bit skeptical, but they seemed certain.

I'm now addressing all pent up issues with a plan to create a new rev of the API Standard soon. What do you think of Node.type is an Array[string] instead of a string?

Do you know what the latest location of the KG Standard is?

**Comment by edeutsch** [comment]
This was the latest I found:
https://docs.google.com/document/d/1TrvqJPe_HwmRJ5HCwZ7fsi9_mwGcwLOZ53Fnjo8Sh4E

**Comment by saramsey** [comment]
AFAIK, the latest location of the KG standard is:
https://docs.google.com/document/d/1TrvqJPe_HwmRJ5HCwZ7fsi9_mwGcwLOZ53Fnjo8Sh4E/edit

but it hasn't been edited since July 9, so I don't know for sure. I will ask Chris M. and Matt B.

-----------------------------------------------------
Stephen Ramsey
Assistant Professor, Oregon State University
* School of Electrical Engineering and Computer Science
* Department of Biomedical Sciences
208A Dryden Hall
stephen.ramsey@oregonstate.edu<mailto:stephen.ramsey@oregonstate.edu>
http://lab.saramsey.org







On Oct 12, 2018, at 7:34 AM, Eric Deutsch <notifications@github.com<mailto:notifications@github.com>> wrote:


At the lack hackathon Vlado and Mathias let me know that in the Standard API format Node.type needed to be a list. I said that the KG standard didn't support that, but they said that it was decided that it would. The example they gave was insulin, which was both a drug and a protein. I was a bit skeptical, but they seemed certain.

I'm now addressing all pent up issues with a plan to create a new rev of the API Standard soon. What do you think of Node.type is an Array[string] instead of a string?

Do you know what the latest location of the KG Standard is?

**Comment by dkoslicki** [comment]
I don't particularly mind if it's a list of strings: for us, it will just mean the list will contain a single element. As for the status of the standard, I was assuming that the [github repo](https://github.com/NCATS-Tangerine/NCATS-ReasonerStdAPI) contained the latest spec.

**Comment by edeutsch** [comment]
@dkoslicki - there are TWO standards here. You link to the API standard, which I am managing. However, the KG standard is a separate thing, and is the Google doc as linked by me and Steve above.

I am trying to keep the API standard in sync mostly with the KG standard to make our lives easier, but the KG Standard seems a bit vague and subject to unwritten and stealthily written changes. I will try to encourage that it become more formal. Steve, you may wish to participate in that formalization. It is a source of frustration that I was told in September that it changed yet no one edited the document since July. And of course, eventual edits will likely happen quietly.

This thread is mostly to discern what you @dkoslicki and @saramsey think about making the node types a list, since I imagine this could impact your code quite substantially.

**Comment by dkoslicki** [comment]
Ah, whoops! Read the last line too quickly. I have no idea about the KG standard.

If we change the KG itself, that will definitely result in me needing to change reasoning code. Shall we discuss this in more detail on the Monday meeting?

**Comment by edeutsch** [comment]
Ah, okay, Chris reports that the KG standard is now this:
https://biolink.github.io/biolink-model/
and maybe more specifically this:
https://biolink.github.io/biolink-model/about/mapping-neo4j.html
I don't see anything about multiple types.

Discussion at Monday meeting sounds good to me, with the only exception that this may come to a head at the 11am meeting, so I wanted to get your read on this before I go into that thicket.

**Comment by dkoslicki** [comment]
Node type has been a list for a while now (API std 0.9.X?). Closing since appears to be a settled issue.
