### ISSUE TITLE
Hypoglycemic coma is a parent of Coma

### ISSUE THREAD

**Issue by jaredroach** [RTXteam/RTX#305]
When I query, "What are the drugs that target coma"? I get

_Your question has been interpreted and is restated as follows:
   What drugs target proteins associated with Coma?
Please ensure that this is an accurate restatement of the intended question.

No chemical_substance were found with similarity crossing the threshold of 0.000200. Note that Hypoglycemic coma is a parent of Coma, so you might try that instead._

Are you sure it is not the other way around? Shouldn't 'coma' be the parent of any subsets of 'coma'?

**Comment by jaredroach** [comment]
As of now, it is very hard to type a query into the user interface at https://rtx.ncats.io
The autocorrect makes it next to impossible to submit a query that is not canonical.
For example, I have a hard time typing in "What is the clinical outcome pathway of glucose for the treatment of hypoglycemia" without it getting auto changed to something like "What is the clinical outcome pathway of $chemical_substance for the treatment of hypoglycemia"

**Comment by jaredroach** [comment]
More interface problems:

how is insulin connected to surfactant




Status
The most similar question I can answer is: What proteins involve similar biological processes as $protein But I found: "Multiple terms found for protein: ['UniProtKB:P01308', 'UniProtKB:I3WAC9']"

______

what proteins interact with insulin?

The most similar question I can answer is: What proteins interact with $protein But I found: "Multiple terms found for protein: ['UniProtKB:P01308', 'UniProtKB:I3WAC9']"

___

What drugs target proteins in the atelectasis pathway?

Your question has been interpreted and is restated as follows:
   What drugs target proteins associated with BLOOD GROUP, INDIAN SYSTEM; IN?
Please ensure that this is an accurate restatement of the intended question.

No chemical_substance were found with similarity crossing the threshold of 0.000200.

-----

What conditions are commonly treated by insulin, in any form?  

Status
The most similar question I can answer is: Which cellular component is $protein expressed in But I found: "Multiple terms found for protein: ['UniProtKB:P01308', 'UniProtKB:I3WAC9']"


What conditions are commonly treated by METFORMIN, in any form?  


Error parsing the response from the reasoner. This is an internal bug that needs to be fixed. Unable to respond to this question at this time. The unparsable response was: 25505 { "context": null, "datetime": null, "id": null, "known_query_type_id": null, "message": "20 results found", "n_results": null, "original_question_text": null, "query_type_id": null, "reasoner_id": null, "response_code": "OK", "restated_question_text": null, "result_code": null, "result_list": [ { "confidence": 0.02658467981449232, "description": null, "essence": null, "id": null, "reasoner_id": null, "result_graph": { "edge_list": [], "node_list": [ { "description": "A member of the class of guanidines that is biguanide the carrying two methyl substituents at position 1.", "id": "CHEMBL.COMPOUND:CHEMBL1431", "name": "metformin", "node_attributes": null, "symbol": null, "type": "chemical_substance", "uri": "https://www.ebi.ac.uk/chembl/compound/inspect/CHEMBL1431" } ] }, "result_group": null, "result_group_similarity_score": null, "result_type": null, "row_data": null, "score": null, "score_direction": null, "score_name": null, "text": "According to the Columbia Open Health Data, metformin is used to treat patients with the condition Essential hypertension with frequency 0.026585 out of all patients treated with metformin (count=65612). This condition is not in our Knowledge graph, so no graph is shown." }, { "confidence": 0.024425879990502577, "description": null, "essence": null, "id": null, "reasoner_id": null, "result_graph": { "edge_list": [], "node_list": [ { "description": "A member of the class of guanidines that is biguanide the carrying two methyl substituents at position 1.", "id": "CHEMBL.COMPOUND:CHEMBL1431", "name": "metformin", "node_attributes": null, "symbol": null, "type": "chemical_substance", "uri": "https://www.ebi.ac.uk/chembl/compound/inspect/CHEMBL1431" } ] }, "result_group": null, "result_group_similarity_score": null, "result_type": null, "row_data": null, "score": null, "score_direction": null, "score_name": null, "text": "According to the Columbia Open Health Data, metformin is used to treat patients with the condition Type 2 diabetes mellitus without complication with frequency 0.024426 out of all patients treated [...]

**Comment by edeutsch** [comment]
Regarding the Insulin duality, I3WAC9 is an UNREVIEWED entry:
https://www.uniprot.org/uniprot/I3WAC9
i.e. it comes from TrEMBL, not Swiss-Prot.
I would opine that this a knowledge graph issue to be fixed. Maybe the best way to handle this is to have a KG cleaner that does some tidying. For example, if there are any nodes that are UNREVIEWED UniProtKB entries, the likely-available REVIEWED entry should be found, and all edges reassigned to the REVIEWED node, and finally the UNREVIEWED node removed.

I suppose there might possibly be a reason to preserve some knowledge about the unreviewed entry, but I am doubtful. I suspect some KS just linked to the wrong entry.

**Comment by dkoslicki** [comment]
@jaredroach Also, it looks like our knowledge graph doesn't have "atelectasis pathway" in it. Maybe there's a different synonym for this?

**Comment by dkoslicki** [comment]
And it looks like the issue with "What conditions are commonly treated by METFORMIN, in any form?" is the UI not being able to render it for some reason. Perhaps @isbluis could take a look to see what went wrong?

**Comment by jaredroach** [comment]
Atelectasis in the KG is here:

<id>:88065UUID: b62f0b62-96e5-11e8-b6f4-0242ac110002 accession: 0100750 category: phenotypic_feature

**Comment by jaredroach** [comment]
These queries got me close enough to where I wanted to go:

match (n:phenotypic_feature {name : "Atelectasis"})-[r]-(x)-[s]-(y)-[t]-(m:chemical_substance {name:"insulin human"})  return n.name, type(r), x.name, type(s), y.name, type(t), m.name

match p=(n:phenotypic_feature {name : "Atelectasis"})-[r]-(x)-[s]-(y)-[t]-(m:chemical_substance {name:"insulin human"}) where y.name = 'insulin receptor'  return p

**Comment by DeqingQu** [comment]
According to the data from UniProt, the protein nodes could be identified as 'unreviewed' and 'reviewed'. For the 'unreviewed' nodes, they are possibly not related to human, so we migtht drop these nodes.

As discussed with @edeutsch , I wrote a script to find all unreviewed nodes in our KG and also tried to find the related reviewed node which has the same name with the unreviewed node.  Finally,  there are 401 unreviewed nodes in our KG. For 95 of these unreviewed nodes, I can't find the related reviewed nodes in our KG.

I listed parts of the results. The whole results can be found here: https://docs.google.com/spreadsheets/d/1nkElNUgX99AmGVqo9S6rWZyVkc_pD-zd45yLw9uSWkA/edit#gid=909480321

If there is no related reviewed nodes for the unreviewed node, the right column will be blank. 
You may notice that some names of the unreviewed and reviewed nodes may be not same. The reason is that the name of the protein nodes in our KG is queried from MyGene, not from UniProt. 

  | Unreviewed Nodes | Reviewed Nodes
-- | -- | --
id | UniProtKB:A0A087WWP8 | UniProtKB:Q5VWQ0
name | Lysine-specific demethylase 9 | Lysine-specific demethylase 9
organism | Homo sapiens(Human) | Homo sapiens(Human)
url | https://www.uniprot.org/uniprot/A0A087WWP8 | https://www.uniprot.org/uniprot/Q5VWQ0
  |   |  
id | UniProtKB:O40239 |  
name | Transmembrane glycoprotein gp41 |  
organism | Human immunodeficiency virus |  
url | https://www.uniprot.org/uniprot/O40239 |  
  |   |  
id | UniProtKB:Q1KLZ0 | UniProtKB:P60709
name | HCG15971, isoform CRA_a | Actin, cytoplasmic 1
organism | Homo sapiens(Human) | Homo sapiens(Human)
url | https://www.uniprot.org/uniprot/Q1KLZ0 | https://www.uniprot.org/uniprot/P60709
  |   |  
id | UniProtKB:Q25634 |  
name | Glutamate-gated chloride channel |  
organism | Onchocerca volvulus |  
url | https://www.uniprot.org/uniprot/Q25634 |  
  |   |  
id | UniProtKB:Q08AT0 | UniProtKB:Q96LD1
name | SGCZ protein | Zeta-sarcoglycan
organism | Homo sapiens(Human) | Homo sapiens(Human)
url | https://www.uniprot.org/uniprot/Q08AT0 | https://www.uniprot.org/uniprot/Q96LD1
  |   |  
id | UniProtKB:H9U2V9 |  
name | GABA-gated chloride channel 1 |  
organism | Tetranychus urticae(Two-spotted spider mite) |  
url | https://www.uniprot.org/uniprot/H9U2V9 |  
  |   |  
id | UniProtKB:Q6FGU7 | UniProtKB:O14966
name | RAB7, member RAS oncogene family-like 1 | Ras-related protein Rab-7L1
organism | Homo sapiens(Human) | Homo sapiens(Human)
url | https://www.uniprot.org/uniprot/Q6FGU7 | https://www.uniprot.org/uniprot/O14966
  |   |  
id | UniProtKB:A0A0D2X7Z3 | UniProtKB:Q49AN0
name | Cryptochrome-2 | Cryptochrome-2
organism | Homo sapiens(Human) | Homo sapiens(Human)
url | https://www.uniprot.org/uniprot/A0A0D2X7Z3 | https://www.uniprot.org/uniprot/Q49AN0

**Comment by jaredroach** [comment]
I have been trying to use the KG to distinguish between forms of coma, and to suggest drugs specific to particular forms of coma. But there appears to be a knowledge deficit fundamental to the graph.
Do the following Cypher:
match (m) where toLOWER(m.name) contains toLOWER("hypoglycemic coma") return m

You will get two nodes for hypoglycemic coma. One is a "disease" and the other is a "phenotype".
I have been considering it as a disease. but whatever. If someone wants to call it a phenotype, I cannot argue.
Regardless of whether we call it a disease or phenotype, I want to know what phenotypes are associated with it.

So using the result in the Neo4J browser above, click on expand node to neighbors in the graph.

If you expand the "disease" node, you get nothing, other than two generic 'subclass' edges to 'brain disease' and 'endocrine'. So the KG thinks there are NO phenotypes associated with hypoglycemic coma" other than (wait for it - surprise!): "hypoglycemic coma".

If you expand the phenotype node, you get about 100 _diseases_ that have this phenotype, but no other phenotypes.  Whereas from DOID (http://disease-ontology.org/term/DOID%3A1607/), you might at least expect

has_symptom decreased cognition, has_symptom aberrant behavior, has_symptom seizure, and has_symptom coma. And maybe add to that symptoms like hypoglycemia.

The only non-disease nodes connected to the "hypoglycemic coma" phenotype node are:
is a subclass of coma
& that the protein UniProtKB:Q09428name: ATP binding cassette subfamily C member 8 "has the phenotype of hypoglycemic coma"
Neither of these is very useful for the problem at hand. And of all the proteins to assign hypoglycemic coma to, ABCC8 would not be anywhere near the top (insulin might be a good choice for the top, fwiw). Coma is not mentioned in ABCC8's OMIM entry, for example.

**Comment by saramsey** [comment]
I think this issue will be resolved in KG2 as we will have a rich set of relationships between MONDO and HPO
