### ISSUE TITLE
Implement query_graph fulfillment using Cypher

### ISSUE THREAD

**Issue by dkoslicki** [RTXteam/RTX#312]
Add functionality to query RTX using 0.9.0 format API spec input. E.g. allows arbitrary subgraph queries. Borrow liberally from [Robokop/gamma](https://github.com/NCATS-Gamma/robokop-rank/blob/master/ranker/message.py). See ``cypher_``.

**Comment by DeqingQu** [comment]
In the outputs in [TestSimpleQueries06](https://github.com/RTXteam/RTX/blob/NewFmt/code/UI/ClientExamples/Python/TestSimpleQueries06.py
), the 'source_id' and 'target_id' in the edges of 'knowledge_graph' sometimes are flipped.
"knowledge_graph": {
        "edges": [
            {
                "confidence": null,
                "defined_datetime": null,
                "edge_attributes": null,
                "evidence_type": null,
                "id": "0",
                "is_defined_by": "RTX",
                "negated": null,
                "provided_by": "ChEMBL",
                "publications": null,
                "qualifiers": null,
                "relation": null,
                **"source_id": "UniProtKB:P00918",**
                **"target_id": "CHEMBL.COMPOUND:CHEMBL112",**
                "type": "physically_interacts_with",
                "weight": null
            },

In the previous version, Q3Solution is used for query_graph. Because the 'physically_interacts_with' edges are bidirected, the cypher query will return all the edges (chemical_substance -> protein and protein -> chemical_substance). When we convert the Cypher query into a NetworkX graph, some of the edges will be ignored when the graph is set to be bidirectional. Sometimes, only the protein -> chemical_substance edges are stored in the NetworkX graph and the chemical_substance -> protein edges are ignored (because the graph is set to be a bidirectional graph, it makes sense), so the source_id and target_id are flipped.

When I tried to set the parameter of Q3Solution to be 'directed', only the chemical_substance -> protein edges will be queried from KG and the testcase will be fine. But for [TestSimpleQueries07](https://github.com/RTXteam/RTX/blob/NewFmt/code/UI/ClientExamples/Python/TestSimpleQueries07.py), it will return nothing. The reason is that the 'gene_associated_with_condition' relationship in our KG is directed (only protein -> disease). If we simply set the 'directed' parameter of Q3Solution to be True, it will not solve the problem.

@dkoslicki If we switch to use the new QueryGraphReasoner module for query_graph, should we still care about this bug?

**Comment by dkoslicki** [comment]
Current plan per the discussion with @saramsey and @edeutsch today: have @finnagin take a look at Gamma's code:
```
Here's the Gamma code:
Kenny Morton [10:43 AM]
http://robokop.renci.org:6011/apidocs/#/cypher
https://github.com/NCATS-Gamma/robokop-rank/blob/master/ranker/message.py
ranker/message.py
```
There are three methods that start with cypher_
And here's an example of input output: http://robokop.renci.org:6011/apidocs/#/cypher/post_api_cypher_knowledge_graph_
use the "try it out"

We'll try to get this to work in the NewFmt branch.
@edeutsch Can you point us to the location where your current "one hop" solution script is at so @finnagin and/or @DeqingQu can see where to drop in the new code? I recall you showing it to me at the hackathon, but I can't seem to find it atm.

**Comment by dkoslicki** [comment]
As for division of labor, my first estimate is that it would be easier for @finnagin to get the "query graph to cypher query" part implemented, and easier for @DeqingQu to package this into a robust system that interacts with @edeutsch API. Does that sound reasonable to you all?

**Comment by edeutsch** [comment]
As far as I'm concerned, that division of labor sounds fine to me. I will follow up with details of current code that will be of use.

**Comment by edeutsch** [comment]
So here's a quick summary of what you need to know for implementing QueryGraph further:
1. Everything is in the NewFmt branch

2. The first decision about having a query_graph is acted on here: https://github.com/RTXteam/RTX/blob/NewFmt/code/UI/OpenAPI/python-flask-server/RTXQuery.py around lines 60-76. Basically what this does is call the self.interpretQueryGraph(query) method and if that can be translated into a canned query_type_id, then go ahead and do that. I think we should replace this bit with the creation of a new object of type QueryGraphReasoner (that you write) and a handoff to that invoking the answer() method of that and getting the returned Message object back.

3. Then in the same file, you'll want to examine the interpretQueryGraph() method lines 270-377. Currently what this is doing is trying to map the incoming QueryGraph object to something that either Q0 or Q3Solution can answer, and if it can't return a lame error message. This is a toy model of what you will need to implement in QueryGraphReasoner. Except, instead of trying to map the incoming QueryGraph to a "solution script", you're going to want to *be* the solution: checking the QueryGraph to make sure it is legal/interpretable and then build some cypher and execute, and then perhaps do some post processing to try to create a useful response.

4. A good model for a 1-hop query is the NewFmt Q3Solution.py: https://github.com/RTXteam/RTX/blob/NewFmt/code/reasoningtool/QuestionAnswering/Q3Solution.py. It might be instructive to diff this with the trunk version to see how things change in the 0.9.1 world. There were also changes to the FormatOutput.py module in the same directory. You'll need to use that, but maybe not make too many changes.

5. And then there's the stub of the QueryGraphReasoner class that I cobbled together. This is the class that I recommend that you embrace and extend to do great things with. It is a mere toy compared to what it needs to do. But maybe there's enough there for you to get the idea and start extending it. It's not hooked up the the API/UI at all. But I think it runs to do some very simple stuff from the command line. Try running it from the command line and understanding it, and then see if you can extend it to run on far more complex QueryGraphs (as embedded tests).

That's what I have to offer to get started. My lack of Cypher knowledge prevents me from taking this easily forward. I hope you all can! What do you think?

**Comment by finnagin** [comment]
@dkoslicki So I just got the code from gamma working locally and it takes dicts as an input like the following:
```
{
  "answers": [
    {
      "edge_bindings": {
        "e00": "636"
      },
      "node_bindings": {
        "n00": "DOID:12365"
      }
    }
  ],
  "knowledge_graph": {
    "edges": [
      
    ],
    "nodes": [
      {
        "id": "DOID:12365",
        "name": "Ebola hemorrhagic fever",
        "type": "disease"
      }
    ]
  },
  "question_graph": {
    "edges": [
      {
        "id": "e00",
        "source_id": "n00",
        "target_id": "n01"
      },
      {
        "id": "e01",
        "source_id": "n01",
        "target_id": "n02"
      }
    ],
    "nodes": [
      {
        "curie": "DOID:12365",
        "id": "n00",
        "type": "disease"
      },
      {
        "id": "n01",
        "type": "protein"
      },
      {
        "id": "n02",
        "type": "pathway"
      }
    ]
  }
}
```
All it really needs from this example is the `question_graph` field as the other two are not used for the cypher generation. Then there are a couple methods that can produce cypher commands (both of which work on our knowledge graph provided the curie ids and node types that are used are in our knowledge graph):

1. The first, `cypher_query_answer_map` produces the following cypher query:
```
MATCH (n00:disease {`id`: 'DOID:12365'})-[e00]-(n01:protein {}) MATCH (n01)-[e01]-(n02:pathway {}) WITH n00.id as n00, n01.id as n01, n02.id as n02, collect(distinct toString(id(e00))) as e00, collect(distinct toString(id(e01))) as e01 RETURN {n00:n00, n01:n01, n02:n02} as nodes, {e00:e00, e01:e01} as edges
```

In neo4j this returns answer graphs each in the form of a dict of nodes and a dict of edges.
e.g.
nodes:
```
{
  "n00": "DOID:12365",
  "n01": "UniProtKB:P02741",
  "n02": "REACT:R-HSA-6802949"
}
```
edges:
```
{
  "e00": [
    "1341143"
  ],
  "e01": [
    "2606719"
  ]
}
```

2. The second method is `cypher_query_knowledge_graph` which produces a cypher query like the following:
```
MATCH (n00:disease {`id`: 'DOID:12365'})-[e00]-(n01:protein {}) MATCH (n01)-[e01]-(n02:pathway {})
WITH collect(distinct n00) + collect(distinct n01) + collect(distinct n02) as nodes, collect(distinct e00) + collect(distinct e01) as edges
UNWIND nodes as n WITH collect(distinct n) as nodes, edges
UNWIND edges as e WITH nodes, collect(distinct e) as edges
WITH
            [r in edges | r{.*, source_id:startNode(r).id, target_id:endNode(r).id, type:type(r), id:toString(id(r))}] as edges,
            [n in nodes | n{.*, type:labels(n)}] as nodes
RETURN nodes, edges
```

In Neo4j this returns a list of nodes and a list of edges making up the slice of the knowledge graph used for the answers.
 e.g.
An example of a node looks like:
```
{
  "name": "malaria",
  "description": "A parasitic protozoa infectious disease characterized as a vector-borne infectious disease caused by the presence of protozoan parasites of the genus Plasmodium in the red blood cells, transmitted from an infected to an uninfected individual by the bite of anopheline mosquitoes, and characterized by periodic attacks of chills and fever that coincide with mass destruction of blood cells and the release of toxic substances by the parasite at the end of each reproductive cycle.",
  "expanded": true,
  "uri": "http://purl.obolibrary.org/obo/DOID_12365",
  "UUID": "15d25a16-96e0-11e8-b6f4-0242ac110002",
  "seed_node_uuid": "14aa4450-96e0-11e8-b6f4-0242ac110002",
  "accession": "12365",
  "id": "DOID:12365",
  "rtx_name": "DOID:12365",
  "category": "disease",
  "type": [
    "Base",
    "disease"
  ]
}
```
an example of an edge looks like:
```
{
  "predicate": "gene_associated_with_condition",
  "relation": "gene_associated_with_condition",
  "target_id": "DOID:12365",
  "provided_by": "DisGeNet",
  "source_node_uuid": "59b4a2de-96e0-11e8-b6f4-0242ac110002",
  "target_node_uuid": "15d25a16-96e0-11e8-b6f4-0242ac110002",
  "seed_node_uuid": "14aa4450-96e0-11e8-b6f4-0242ac110002",
  "id": "1342761",
  "is_defined_by": "RTX",
  "source_id": "UniProtKB:P16671",
  "type": "gene_associated_with_condition"
}
```

**Comment by edeutsch** [comment]
Looks very promising! So this system performs two queries to get the output in two different forms?

**Comment by finnagin** [comment]
@edeutsch Yeah. The first query has each answer separated and in a graph format but just has identifiers for each node and edge. The second query has all of the node and edge properties but is just one set containing all nodes and edges from all answers.

**Comment by dkoslicki** [comment]
Closing due to #788 and Amy’s `expand` combined with Finn’s implementation/modification of this
