### ISSUE TITLE
QueryNCBIeUtils error handline

### ISSUE THREAD

**Issue by dkoslicki** [RTXteam/RTX#33]
Apparently QueryNCBIeUtils doesn't have sufficient error handling:

```python
>>>python3 Q2Solution.py -r mupirocin -d 'DOID:1563'
HTTP timeout in QueryNCBIeUtils.py; URL: https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi?db=pubmed&term=%28CASP1_HUMAN%7CCaspase-1%20%5BMeSH%20Terms%5D%7CCASP-1%5BMeSH%20Terms%5D%7CEC%203.4.22.36%5BMeSH%20Terms%5D%7CInterleukin-1%20beta%20convertase%5BMeSH%20Terms%5D%7CIL-1BC%5BMeSH%20Terms%5D%7CInterleukin-1%20beta-converting%20enzyme%5BMeSH%20Terms%5D%7CICE%5BMeSH%20Terms%5D%7CIL-1%20beta-converting%20enzyme%5BMeSH%20Terms%5D%7Cp45%7C%20%5BCleaved%20into%3A%20Caspase-1%20subunit%20p20%3B%20Caspase-1%20subunit%20p10%5D%7CCASP1%5BMeSH%20Terms%5D%7CIL1BC%5BMeSH%20Terms%5D%7CIL1BCE%5BMeSH%20Terms%5D%29%20AND%20%28Deubiquitination%29&retmode=json&retmax=1000
Traceback (most recent call last):
  File "Q2Solution.py", line 223, in <module>
    main()
  File "Q2Solution.py", line 218, in main
    res = answerQ2(drug, disease, k)
  File "Q2Solution.py", line 128, in answerQ2
    mesh1=False, mesh2=False)
  File "/home/dkoslicki/Dropbox/Repositories/RTX/code/reasoningtool/QueryNCBIeUtils.py", line 243, in normalized_google_distance
    numerator = max(math.log(ni), math.log(nj)) - math.log(nij)
TypeError: a float is required
```
I assume the way to go is either:
1. Try again if an error is encountered
2. or throw an exception (so downstream code doesn't try to operate on garbage, which is what happened above).

**Comment by dkoslicki** [comment]
Hmmm... a MWE might be hard to come by since entres/eutils only periodically returns an HTTP timeout error. I ran the command (``python3 Q2Solution.py -r mupirocin -d 'DOID:1563'``) a second time and it completed without error. Seems to be an issue on ncbi's end.

**Comment by saramsey** [comment]
If there is a HTTP timeout, what do you want the function to return?  None or math.nan?

-----------------------------------------------------
Stephen Ramsey
Assistant Professor, Oregon State University
* School of Electrical Engineering and Computer Science
* Department of Biomedical Sciences
208A Dryden Hall
stephen.ramsey@oregonstate.edu<mailto:stephen.ramsey@oregonstate.edu>
http://lab.saramsey.org







On Mar 26, 2018, at 11:11 AM, David Koslicki <notifications@github.com<mailto:notifications@github.com>> wrote:


Hmmm... a MWE might be hard to come by since entres/eutils only periodically returns an HTTP timeout error. I ran the command (python3 Q2Solution.py -r mupirocin -d 'DOID:1563') a second time and it completed without error. Seems to be an issue on ncbi's end.

**Comment by saramsey** [comment]
OK, can you do a git pull and try now?  Function normalized_google_distance should return None in the event of a timeout, now

**Comment by saramsey** [comment]
tested (by shortening the timeout to 1 ms); it works now (does not throw an exception but instead returns None if there is a HTTP timeout)

**Comment by dkoslicki** [comment]
Thanks @saramsey , but let's do math.nan instead, since this already represents a kind of error(ish) state (and all the reasoning code has checks for math.nan instead of None).

**Comment by saramsey** [comment]
ok done

-----------------------------------------------------
Stephen Ramsey
Assistant Professor, Oregon State University
* School of Electrical Engineering and Computer Science
* Department of Biomedical Sciences
208A Dryden Hall
stephen.ramsey@oregonstate.edu<mailto:stephen.ramsey@oregonstate.edu>
http://lab.saramsey.org







On Mar 26, 2018, at 11:30 AM, David Koslicki <notifications@github.com<mailto:notifications@github.com>> wrote:


Thanks @saramsey<https://github.com/saramsey> , but let's do math.nan instead, since this already represents a kind of error(ish) state (and all the reasoning code has checks for math.nan instead of None).
