### ISSUE TITLE
Automated Build System For Generating KG2, that is parallel capable

### ISSUE THREAD

**Issue by power10dan** [RTXteam/RTX#338]
As the title suggests, we want to also have an automated system to be able to automatically pull / search for new updates on our data source, and update the KG graph based on the new data. We may be able to achieve this using existing tools, such as Travis CI. However, the feasbility of doing so would need to be investigated. This issue therefore contains two parts: Investigate whether existing CI / CD tools are good enough for this issue, and depending on the answer to the question, either integrate or custom built a continuous integration tool.

**Comment by saramsey** [comment]
I propose to start with something simple. How about we create a `bash` script `check-build-kg2.sh` defined with the following pseudocode: If the file `/tmp/building-kg2` already exists and is less than 48h old, the `check-build-kg2.sh` will exit (if more than 48h old, a warning email will be sent to `stephen.ramsey@oregonstate.edu`). Else, the `check-build-kg2.sh` script will create a zero-length file `/tmp/building-kg2` and then `fork` and `exec` the script `build-kg2.sh` (which should be backgrounded so that the original script `check-build-kg2.sh` will not wait on completion of `build-kg2.sh`). Then we can run the `check-build-kg2.sh` script out of cron on the build server `kg2dev.rtx.ai`, every 1 hour.

**Comment by saramsey** [comment]
We can discuss; I need to think over the above pseudocode to make sure it makes sense.

**Comment by saramsey** [comment]
I think we should look at `snakemake` as a possible replacement for `build-kg2.sh`
