### ISSUE TITLE
switch KG to using MONDO instead of Disease Ontology

### ISSUE THREAD

**Issue by saramsey** [RTXteam/RTX#37]
do this in the same branch where the rest of the KG development work will be done

**Comment by saramsey** [comment]
planning to do this work in branch "newkg"

**Comment by edeutsch** [comment]
@saramsey @dkoslicki FWIW, I found it to be rather a pain in the butt to work with various branches. In my opinion it makes sense to use a branch when we think the development of a major new feature will occur in parallel with the need to continue to roll out fixes or minor updates to the production web site. In practice, production still hasn't changed since before the NewStdAPI and Q4 work, so there really was no substantial advantage to using the branches in this case. We could have all done it in master. But I thought we might continue to tweak production, so it made sense. But we didn't.

If I understand what you're planning, you're going to make major changes to the KG which will break the reasoner and lots of other code, so the changing of the KG and the reasoner needs to happen as simultaneously as possible. As soon as the KG changes, production will break. So I'm going to suggest a coordinated hackathon approach. Let's get all extant code smoothed out and running in production. Then you and David can start doing the prep work for the change. Then as soon as you drop the KG and start the reload, we're down, and just all need to work like mad to get back up with the new node types and code.

Alternatively, Maybe we can have KG1 and KG2, where KG1 is the current production. You can drop and reload KG2. David can recode to KG2. While production continues to run happily on KG1. When All code is ready on KG2, we roll that out to production and KG1 becomes the dev. Would that be a good idea? That way there is no downtime (ideally). This can all be done in master.

**Comment by saramsey** [comment]
Eric,

Development work on issue #34 is almost done, sorry.

Steve

-----------------------------------------------------
Stephen Ramsey
Assistant Professor, Oregon State University
* School of Electrical Engineering and Computer Science
* Department of Biomedical Sciences
208A Dryden Hall
stephen.ramsey@oregonstate.edu<mailto:stephen.ramsey@oregonstate.edu>
http://lab.saramsey.org







On Mar 31, 2018, at 11:11 AM, Eric Deutsch <notifications@github.com<mailto:notifications@github.com>> wrote:


@saramsey<https://github.com/saramsey> @dkoslicki<https://github.com/dkoslicki> FWIW, I found it to be rather a pain in the butt to work with various branches. In my opinion it makes sense to use a branch when we think the development of a major new feature will occur in parallel with the need to continue to roll out fixes or minor updates to the production web site. In practice, production still hasn't changed since before the NewStdAPI and Q4 work, so there really was no substantial advantage to using the branches in this case. We could have all done it in master. But I thought we might continue to tweak production, so it made sense. But we didn't.

If I understand what you're planning, you're going to make major changes to the KG which will break the reasoner and lots of other code, so the changing of the KG and the reasoner needs to happen as simultaneously as possible. As soon as the KG changes, production will break. So I'm going to suggest a coordinated hackathon approach. Let's get all extant code smoothed out and running in production. Then you and David can start doing the prep work for the change. Then as soon as you drop the KG and start the reload, we're down, and just all need to work like mad to get back up with the new node types and code.

Alternatively, Maybe we can have KG1 and KG2, where KG1 is the current production. You can drop and reload KG2. David can recode to KG2. While production continues to run happily on KG1. When All code is ready on KG2, we roll that out to production and KG1 becomes the dev. Would that be a good idea? That way there is no downtime (ideally). This can all be done in master.

**Comment by saramsey** [comment]
Let's get all extant code smoothed out and running in production. Then you and David can start doing the prep work for the change. Then as soon as you drop the KG and start the reload, we're down, and just all need to work like mad to get back up with the new node types and code.

One issue is timing — I am trying to get issue #34 done *before* classes start.

-----------------------------------------------------
Stephen Ramsey
Assistant Professor, Oregon State University
* School of Electrical Engineering and Computer Science
* Department of Biomedical Sciences
208A Dryden Hall
stephen.ramsey@oregonstate.edu<mailto:stephen.ramsey@oregonstate.edu>
http://lab.saramsey.org







On Mar 31, 2018, at 11:11 AM, Eric Deutsch <notifications@github.com<mailto:notifications@github.com>> wrote:


@saramsey<https://github.com/saramsey> @dkoslicki<https://github.com/dkoslicki> FWIW, I found it to be rather a pain in the butt to work with various branches. In my opinion it makes sense to use a branch when we think the development of a major new feature will occur in parallel with the need to continue to roll out fixes or minor updates to the production web site. In practice, production still hasn't changed since before the NewStdAPI and Q4 work, so there really was no substantial advantage to using the branches in this case. We could have all done it in master. But I thought we might continue to tweak production, so it made sense. But we didn't.

If I understand what you're planning, you're going to make major changes to the KG which will break the reasoner and lots of other code, so the changing of the KG and the reasoner needs to happen as simultaneously as possible. As soon as the KG changes, production will break. So I'm going to suggest a coordinated hackathon approach. Let's get all extant code smoothed out and running in production. Then you and David can start doing the prep work for the change. Then as soon as you drop the KG and start the reload, we're down, and just all need to work like mad to get back up with the new node types and code.

Alternatively, Maybe we can have KG1 and KG2, where KG1 is the current production. You can drop and reload KG2. David can recode to KG2. While production continues to run happily on KG1. When All code is ready on KG2, we roll that out to production and KG1 becomes the dev. Would that be a good idea? That way there is no downtime (ideally). This can all be done in master.

**Comment by saramsey** [comment]
I think we should do this work in a "MONDO" branch, as it will touch all kinds of different parts of the code base. @DeqingQu what do you think?

**Comment by saramsey** [comment]
Here is a rough plan: in the branch MONDO, we should start with QueryBioLink.py, and we should add *new* methods to the module, not edit or delete old methods.  Obviously, almost any method in that module that references "disease" (meaning a DOID) will need a new version created (maybe a "_MONDO" method suffix??), which will reference  a MONDO ID. Once we have QueryBioLink.py done, we are going to have to fix QuerySciGraph.py which is where we get the ontology relationships for diseases (probably QueryDisont.py can be deprecated at that point).

**Comment by saramsey** [comment]
Am thinking this is most likely to happen as a part of KG2. Thoughts?

**Comment by dkoslicki** [comment]
Closing due to #788 and the forthcoming normalization API from the SRI group
