### ISSUE TITLE
one strange camelCase edge label showing up

### ISSUE THREAD

**Issue by saramsey** [RTXteam/RTX#384]
edge label is:  `isDemonymOf`

**Comment by saramsey** [comment]
also these:

"hasAncestryStatus": 2,
"hasCountryOfOrigin": 9,
"hasMajorityEthnicity": 127,

also there is a predicate label containing "wild-type" (with a hyphen); should be changed to underscore:

"allele_absent_from_wild-type_chromosomal_location": 1,

**Comment by BluePiggy49** [comment]
I have found two ways to solve the camel case issue, #384, (both are tested with the foodon and efo ontologies, only the first method was tested with NCI, because those were the ones that contained the offending camelCase edge labels and NCI had the "wild-type" edge label).

Method 1: (in multi_owl_to_json_kg.py)

def remove_camel_case(predicate: str):
    if predicate.find("_") < 0:
        for letter in predicate:
            if letter.isupper():
                index = predicate.find(letter)
                toreplace_with = "_" + letter.lower()
                predicate = predicate.replace(letter, toreplace_with, 1)
    for letter in predicate:
        if letter == "-":
            predicate = predicate.replace(letter, "_", 1)

    return predicate

with

predicate_label = remove_camel_case(predicate_label)

after the line currently numbered 381. This solution also fixes the "wild-type" error under number_of_edges_by_predicate_type (but not under number_of_edges_by_predicate_curie) for some reason.

Method 2: (in multi_owl_to_json_kg.py)

predicate_label = kg2_util.convert_camel_case_to_snake_case(predicate_label)

after line 381 instead. This solution is cleaner and fits in with the code better, but I don't think it will fix the "wild-type" issue (please correct me if I am wrong).

Please me know what you think.

**Comment by saramsey** [comment]
let's go with Method 2, thanks

(forget about the hyphen issue; that's now logged under a separate issue:  #473)
