### ISSUE TITLE
RTXQuery checks only for drugs for Q3

### ISSUE THREAD

**Issue by dkoslicki** [RTXteam/RTX#39]
@edeutsch 
Hi Eric,

I noticed in RTXQuery.py, line 88 and onwards, there is the following code:
```python
if id == 'Q3':
  targets = qph.query_drug_name_to_targets(terms[0])
  if targets:
    list = '<UL>\n'
    for target in targets:
      list += "<LI> "+target["name"]+"\n"
    list += "</UL>\n"
    codeString = "OK"
    result = [ { "id": 537, "code": 1, "codeString": codeString, "message": "AnswerFound", "result": targets, "text": [ terms[0]+" is known to target: "+list ] } ]
    self.logQuery(id,codeString,terms)
  else:
    codeString = "DrugNotFound"
    result = [ { "id": 537, "code": 11, "codeString": codeString, "message": "DrugNotFound", "text": [ "Unable to find drug '"+terms[0]+"'." ] } ]
    self.logQuery(id,codeString,terms)
  return(result);
```

Q3 as it stands now can allow for all different node types, so checking query_drug_name_to_targets isn't the best idea here. For example:
```python
QT.find_question_parameters("what phenotype is phenotype associated with malaria")
Out[649]:
{'corpus_index': 3,
 'error_code': None,
 'error_message': None,
 'input_text': 'what phenotype is phenotype associated with malaria',
 'terms': {'relationship_type': 'phenotype_assoc_with',
  'source_name': 'DOID:12365',
  'target_label': 'phenont_phenotype'}}
```

And the node DOID:12365 has been found by QuestionTranslator.py (it checks if nodes exist in the knowledge graph). So the Q3Solution.py would run on these input terms, but the RTXQuery isn't letting it since it thinks it's just looking for drugs. Perhaps an error message like "Unknown term" or, more specifically, "entity not in knowledge graph" is better here, along with removing the check for query_drug_names_to_targets.

**Comment by edeutsch** [comment]
Hi David, you're right that this a problem. This was fine with the original Q3, but is no longer appropriate. You are welcome to fix it, or if you'd like me to, I can.  But I'm mildly concerned for a couple reasons:

1) the reason this is a problem is because you're changing the intent of Q3 from something very specific to something very broad. I am uneasy with the idea of changing the intent of a query_type in general. Yes, it's early days prototype, so it's all probably fine, but this seems like a bad practice. I suppose it's backwards compatible so that's okayish.

2) I'm also a bit concerned that we're combining a whole group of query types into one. I've gotten into my head that a query_type implies a fixed set of input types (i.e. 1 disease+1 compound, or 1 compound, etc.) and that the output type is pretty specific. 1..n proteins or 1..n paths from a drug to a disease. Yet, you're redefining Q3 to be any 1 hop question. And I'm uneasy about that. It might be fine. And maybe it's even a good idea. But I'm thinking not. I think I would have implemented those more rigidly as Q4-Q12 or something with fixed input and output types. I have a gut feeling that we're going to regret combining them all into a vague 1 hop question down the road. But I have nothing more concrete to offer than that. Maybe we should consider Team gamma-ray, where they start with a graph template, which would be a strict set of inputs. If we're strict, that would allow us to define strict templates more easily and maybe map 1:1 with their system better. Maybe we should drag in @saramsey to break the tie on this philological question? I'm fine to be outvoted.

**Comment by dkoslicki** [comment]
Yeah, let’s go ahead and put it on next Monday’s agenda. If we do decide to split it into a bunch of other questions, at least our question type count goes up ;)

Practically though, we’d just reuse the same code in the current Q3 question in all cases with a thin script to check input types. So at least from my perspective, it’s a small amount of work no matter which way we go.

I think it’d be better if you fixed the RTXQuery since I don’t know the error convention you’re using.

**Comment by dkoslicki** [comment]
Decision was to split the current Q3 to many different questions types (with fixed bioentity types). Closing this issue and will open a new one specifying the changes to be made.
