### ISSUE TITLE
Summary tab in UI not working

### ISSUE THREAD

**Issue by dkoslicki** [RTXteam/RTX#507]
When clicking on the summary tab (apparently only when using the query by graph paradigm, not the canned question), nothing shows up:
![Screenshot 2019-09-16 18 44 02](https://user-images.githubusercontent.com/6362936/65004663-04ee1180-d8b2-11e9-9b83-81eeb481e03e.png)
![Screenshot 2019-09-16 18 44 09](https://user-images.githubusercontent.com/6362936/65004669-0a4b5c00-d8b2-11e9-9f13-6a3ed3338582.png)
![Screenshot 2019-09-16 18 44 12](https://user-images.githubusercontent.com/6362936/65004674-0d464c80-d8b2-11e9-8b65-7a56d27a26af.png)

FYI @saramsey

**Comment by edeutsch** [comment]
yes, this is a known TBD. Has not been implemented yet. This summary table is not required by the API and was just a nice-to-have. I won't be able to implement that from here. Would need someone in Seattle to do that if urgent. It is one of the next things that I plan to work on in general when I get back from Oz. Note that the /beta endpoint is recommended for use at the hackathon since this uses API version 0.9.2.

**Comment by dkoslicki** [comment]
Ok, I'll leave it to @saramsey to determine priority, since he's working with people who are primarily using the UI at the hackathon this week

**Comment by dkoslicki** [comment]
Closing due to #788
