### ISSUE TITLE
Normalized google distance API endpoint not working

### ISSUE THREAD

**Issue by dkoslicki** [RTXteam/RTX#527]
Be aware, this code has been updated by @finnagin , so the endpoint API format might need to be updated as well

**Comment by edeutsch** [comment]
The problem was merely a missing dependency. I have added the new requirement for 'lockfile' and all seems to be well again. Announcement of new dependencies might be helpful. See below:

  File "/mnt/data/orangeboard/devED/RTX/code/reasoningtool/kg-construction/QueryNCBIeUtils.py", line 64, in send_query_get
    requests = CacheControlHelper()
  File "/mnt/data/orangeboard/devED/RTX/code/reasoningtool/kg-construction/cache_control_helper.py", line 32, in __init__
    self.sess = CacheControl(requests.session(), heuristic=CustomHeuristic(days=30), cache=FileCache('.web_cache'))
  File "/mnt/data/python/Python-3.7.3/lib/python3.7/site-packages/cachecontrol/caches/file_cache.py", line 82, in __init__
    raise ImportError(notice)
ImportError: 
NOTE: In order to use the FileCache you must have
lockfile installed.

I see lockfile is now at the bottom of requirements.txt
I suppose there was probably an update to this that I did not notice. I can try to be more vigilant, but it would be helpful to me if people could announce when requirements are added.

Or maybe someone has a suggestion for doing this better? Can I set up a GitHub alert every time a particular file is changed (i.e. requirements.txt)? Although really, this sort of thing affects everyone who has a sandbox somewhere, so maybe a team-wide announcement would be beneficial?

**Comment by finnagin** [comment]
@edeutsch Looks like this might work: https://app.github-file-watcher.com/ is a website that you can use to send you an email when a specific file is updated you just need to specify an email you want it sent to, the repository, and the specific files/directories you want it to update you with.

**Comment by edeutsch** [comment]
okay, thanks, I have subscribed. I hope it works!
