### ISSUE TITLE
Pretty print and graphical display of output

### ISSUE THREAD

**Issue by dkoslicki** [RTXteam/RTX#54]
The UI should parse the NewStdAPI results and return some pretty visualization of it. Desired functionality includes:
1. Display the results as a graph (or set/list of graphs)
2. Clickable hyperlinks
3. Work well with the proposed feeback mechanism #53.

See #16 for previous discussion (may or may not be helpful).

**Comment by dkoslicki** [comment]
@isbluis @edeutsch Any progress on the clickable links or the feedback mechanism?

**Comment by isbluis** [comment]
I just checked in the ability to view previous feedback; the form to provide new feedback will be implemented in the next day or two.

I will check with Eric re: hyperlinks.

**Comment by edeutsch** [comment]
Things seem fairly stable at the moment, so I rolled all current code out to test and production. Seems to work okay thus far. More to do. Go to:
http://rtx.ncats.io/
Try example Q1
Notice the dummy feedback in the lower left.
Click on a node and see data.
@isbluis, as a quick hyperlink, would you take the node.uri field and make it a hyperlink? I suppose I would just display the URI itself and then make it a hyperlink to open the link in a new tab.
So, under malaria, have:
URI: http://purl.obolibrary.org/obo/DOID_12365
and hyperlinkable.
An alternative would be to make the CURIE a hyperlink, but I think for the moment, let's just show it all. No prize for compactness at this point.

@dkoslicki , now that we have kind of a graph and some pretty definitions, maybe it would be a nice touch to start writing something a little nicer and prosier in the text field? So instead of:

The proposed mechanism of action for RHEUMATOID ARTHRITIS; RA (OMIM:180300) is: (OMIM:180300:RHEUMATOID ARTHRITIS; RA)--[associated_with_condition]-->(HLA-DRB1:P01912:protein)--[associated_with_condition]-->(DOID:12365:malaria:disease). Confidence: 0.991089 

Maybe something a little nicer like:

With a confidence score of 0.99, the genetic condition RHEUMATOID ARTHRITIS; RA may confer some protection against malaria in the following way: RHEUMATOID ARTHRITIS; RA is associated with condition HLA-DRB1, which is associated with condition malaria.

Or so. @isbluis, it would then be a nice touch to search this text for the node names from the graph, and make those node names a hover-over to the CURIE (DOID:12365) and a hyperlink to the URI. Or some such nice touch.

What do you think?

**Comment by dkoslicki** [comment]
Closing this issue and opening new one for subsequent issues.
