### ISSUE TITLE
tsv-to-neo4j.sh bug in when read-only Neo4j config status is re-enabled

### ISSUE THREAD

**Issue by saramsey** [RTXteam/RTX#542]
Apparently, at lines 81-83 in `tsv-to-neo4j.sh`, where the read-only database config setting is restored and the Neo4j is restarted, this causes a continuous crash/restart cycle for Neo4j. The problem is that after `create_indexes_constraints.py` is run, you *have* to start up Neo4j in write mode, for the indexes to actually get created. Then (after a suitable period, say having `tsv-to-neo4j.sh` sleep for 5 minutes) you can restart the database in read-only mode.

**Comment by amykglen** [comment]
ah, got it - so the problem is that the indexes are still being created in the background by the time `tsv-to-neo4j.sh` puts the database back into read-only mode. (right?) 

so it seems like this should do the trick? https://github.com/RTXteam/RTX/commit/c3ec14d340a3f15e248f2bfd319f17c96dae09db

(I tried to see if there's a way to check whether indexing has completed through the neo4j driver, so that we could just wait for that rather than having to sleep, but not finding an obvious method.)
