### ISSUE TITLE
warning:  for key: iri, dropping second value: http://purl.obolibrary.org/obo/DOID_0005359; keeping first value: http://purl.obolibrary.org/obo/MONDO_0005359

### ISSUE THREAD

**Issue by amykglen** [RTXteam/RTX#560]
this warning is appearing in `build-kg2.log`:

`warning:  for key: iri, dropping second value: http://purl.obolibrary.org/obo/DOID_0005359; keeping first value: http://purl.obolibrary.org/obo/MONDO_0005359`

(it's generated in the `merge_two_dicts` function in `kg2_util.py`)

**Comment by saramsey** [comment]
This is due to a bad URI value for a specific node in KG1:

![Screen Shot 2019-11-12 at 1 54 22 PM](https://user-images.githubusercontent.com/5562107/68714021-f2abef00-0553-11ea-96e1-0f77bf725d39.png)

I suggest that we ignore it for now, since the correct URI (the MONDO one) is overriding the incorrect URI in this case.

**Comment by saramsey** [comment]
Here is the Cypher I used to find the problem in KG1:
```
match (n {id: 'MONDO:0005359'}) return n;
```

**Comment by amykglen** [comment]
ah, cool - sounds good. thanks!

**Comment by saramsey** [comment]
fixed in KG1 by hand
