### ISSUE TITLE
Harmonize API output format and KG node properties

### ISSUE THREAD

**Issue by dkoslicki** [RTXteam/RTX#59]
API output format asks for the following node properties:
```python
{
            'type': str,
            'id': str,
            'symbol': str,
            'name': str,
            'accession': str,
            'description': str,
            'node_attributes': List[NodeAttribute]
        }
```
While the updated KG has the following properties for nodes:
```
["iri", "curie_id", "accession", "seed_node_uuid", "UUID", "name", "description", "expanded"]
```
It's not clear to me how these map. For example, where do I put the IRI in the output format? What is ``symbol`` and ``accession`` in the output format?

**Comment by saramsey** [comment]
Here is the link to the Google Doc on the proposed API output format:

https://docs.google.com/document/d/1O6_sVSdSjgMmXacyI44JJfEVQLATagal9ydWLBgi-vE/edit

**Comment by saramsey** [comment]
> In general, symbol would be an abbreviation for the concept. Such as HB for ALCAM or ABCG2 for proteins, or perhaps AD or AD/HD for diseases where applicable. good for display as nodes where short is good.

@edeutsch Where is "HB" associated with "ALCAM"?   According to Entrez Gene its only alias is CD166 and according to UniProt its only synonyms are MEMD.

Also in general a given gene or protein will have a whole zoo of synonyms (case in point ABCG2 which has 14 synonyms). If you don't want the HGNC Gene Symbol, by what algorithm would the "representative" alias/symbol be selected?

**Comment by saramsey** [comment]
Why don't we just use the HGNC official gene symbol, in the case of proteins?

**Comment by saramsey** [comment]
OK the Google Doc was very helpful, thanks @dkoslicki . 

Looks like, at first blush:

KG "iri" => reasoner output "id"
KG "accession" => reasoner output "accession"
KG "description" => reasoner output "name" (except for proteins, where it maps to output."symbol")

I'm not sure how to map to:
output."type"
output."description" (we don't have that information in our knowledge graph, *yet* -- but Deqing is getting it, see #49)

as for "node_attributes" in the responses API spec, I'm not sure what that is. @edeutsch ?

@dkoslicki  Does this help?

**Comment by saramsey** [comment]
Are we really calling this an accession?  UNIPROT:P01234

I kinda think Accession should be what the knowledge source *calls* an accession. So for Uniprot it would be P01234. For disease ontology it would be DOID:936, for anatomy ontology it would be UBERON_0002736, and for OMIM it would be 271930. For ClinVar it would be SCVNNNNNNN.

As a general rule, I think the "accession" field's string contents should require no munging in order to use it as a key to retrieve the corresponding record for the authoritative database for that node type.

I think the field that should always contain the "PREFIX:XXXXX" format is the *CURIE* ID field.

**Comment by saramsey** [comment]
Sorry for Uberon I think it would be UBERON:0002736

**Comment by edeutsch** [comment]
There are a lot of open questions here. First, one clarification: "HB for ALCAM" was supposed to be "HB or ALCAM". typo, sorry.

for "type" it is the bioentity type from the standard.

Regarding the accession, I thought it might be good to always follow the notation PREFIX:accession whether or not the resource has the prefix included or not. But that's a decision that I'm happy to debate and refine that.

I don't seem to know what a CURIE ID is..

Regarding using HGNC names, I don't object strenuously, but I don't think that HGNC genes and UniProt proteins have a 1:1 mapping, so that's potentially a little weird. I assume UniProt has an official symbol, so I would suggest going with that, but maybe they don't in all cases. HGNC symbols are probably more well know. It's a problem without a great solution.

Node attributes are other kinds of properties/attributes that you want to associate with a node. Again, we need to work through some examples together to achieve a design we all like.

**Comment by saramsey** [comment]
Note:  I have updated the proposed mapping between KG node properties and node fields in the proposed reasoning results output format.

**Comment by saramsey** [comment]
@edeutsch  says "node_attributes" content is TBD at this stage of the specification development

**Comment by edeutsch** [comment]
Although I would say that this is an opportunity to us to propose the standard as it works well for us, rather than waiting for a standard to appear.

**Comment by saramsey** [comment]
@dkoslicki do you have what you need?  (apart from "node_attributes")

**Comment by dkoslicki** [comment]
@saramsey Yes, I do think I have all that I need to populate the output format. I'll let you know early next week if I run into any problems.

**Comment by saramsey** [comment]
At long last, the draft standard for node and relationship properties is here:
https://docs.google.com/document/d/1TrvqJPe_HwmRJ5HCwZ7fsi9_mwGcwLOZ53Fnjo8Sh4E/edit#

**Comment by saramsey** [comment]
OK, anything else for me to do on this issue?  I see that it is assigned to me, but I'm unclear on what (if anything) remains for me specifically to do.

**Comment by edeutsch** [comment]
I think we're stable for now. Discussions about what should be standard is still ongoing at the KG level and API level. I will close this for now, although it will eventually require more work.
