### ISSUE TITLE
Test sutting down rtx services

### ISSUE THREAD

**Issue by finnagin** [RTXteam/RTX#590]
Test shutting down the containers which are running the following services:
* mysql
* neo4j
* apache
* rtx production

Also,
Email Trung about temporarily shutting down rtx.ncats.io to see if anything breaks.

**Comment by finnagin** [comment]
Looks like there is question answering code running on arax.rtx.ai that is still pointing at the neo4j instance on rtx.ncats.io.

I can turn off rtx_openAPI_production, apache2, and mysql without issues and arax.rtx.ai will pass all behave tests and I don't see any abnormalities in the ui. However, if I turn off neo4j I get internal server errors when asking questions.

**Comment by finnagin** [comment]
I went into the rtx1 container running on arax.rtx.ai and did a grep for "rtx.ncats.io" and found a few lines in WF1.py in reasoning tools that uses rtx.ncats.io as well as one line in QueryGraphReasoner.py and one line in question0.py.

running grep in the ui sub-directory found several lines referencing rtx.ncats.io

**Comment by edeutsch** [comment]
My RTX status monitor has been complaining that rtx.ncats.io is not correctly responding to queries since 2am.

**Comment by finnagin** [comment]
Huh. The services seem to be running in the container and the ui is working for me. 

@edeutsch Is it still giving you issues?

**Comment by edeutsch** [comment]
I Restarted the legacy endpoint and now the server monitor is happy. All fixed. Issue can be closed.

**Comment by edeutsch** [comment]
Status monitor complaining since yesterday because rtx.ncats.io disabled by Finn. I have just switched the status monitor to monitor arax.rtx.ai instead. It was fine except for the legacy endpoint. Looks like /legacy is somehow referring to rtx.ncats.io and unable to connect. Rather than try to fix it, I just think we can retire /legacy since it probably isn't needed any more.

So, current status on arax.rtx.ai is that the status monitor is monitoring it and is happy. Except that /legacy is not monitored, is broken, and is declared obsolete until such a time that someone might complain to reopen the case.

All is well as far as I'm concerned.

**Comment by finnagin** [comment]
I'm going to go ahead and close this issue.

**Comment by saramsey** [comment]
Sorry @edeutsch for the notifications!  But I suppose that it is good that we tested for any unforeseen dependencies on rtx.ncats.io, before NCATS shuts it down.

**Comment by saramsey** [comment]
Thanks @finnagin for doing this work.
