### ISSUE TITLE
Some missing edges in kg1endpoint.rtx.ai:7474 that are in arax.rtx.ai:7474

### ISSUE THREAD

**Issue by finnagin** [RTXteam/RTX#591]
The following cypher command gets results in arax.rtx.ai:7474 but not kg1endpoint.rtx.ai:7474

```
MATCH (qg1:protein {})-[qg2]-(qg0:disease {id: 'DOID:83'}) WITH qg0.id as qg0, qg1.id as qg1, collect(distinct toString(id(qg2))) as qg2 RETURN {qg0:qg0, qg1:qg1} as nodes, {qg2:qg2} as edges
```

Looking at the provided by field by running the following command:
```
MATCH (qg1:protein {})-[qg2]-(qg0:disease {id: 'DOID:83'}) return qg2.provided_by
```
It looks like 8 of the 23 results come from BioLink and 15 are coming from DisGeNet.

**Comment by amykglen** [comment]
noticed another instance of this...  `arax.rtx.ai:7474` returns 39 results for this query (proteins associated with Parkinson's) while `kg1endpoint.rtx.ai:7474` returns only 20:
```
match (d {id:"DOID:14330"})-[r]-(p:protein) return r.predicate, r.provided_by, p.id, p.name limit 50
```
(KG2 also returns only 20 results for this query, since it ingests the KG1 at kg1endpoint..)

**Comment by dkoslicki** [comment]
@amykglen @finnagin any update on this? Or should we close due to #788?

**Comment by amykglen** [comment]
I think this is ok to close because:
1. we understand now that the missing edges were because `kg1endpoint.rtx.ai` and `arax.rtx.ai` contain slightly different versions of KG1 (we decided that `arax.rtx.ai` is likely more up to date and thus we're using that one for ARAX and KG2 #705)
2. #595 covers syncing `kg1endpoint.rtx.ai` and `arax.rtx.ai` up, if we still want to do such a thing
