### ISSUE TITLE
Very slow expand?

### ISSUE THREAD

**Issue by dkoslicki** [RTXteam/RTX#614]
It appears that some expands are taking quite a while. For example, while:
```python
query = {"previous_message_processing_plan": {"processing_actions": [
            "create_message",
            "add_qnode(curie=DOID:14330, id=n00)",  # parkinsons
            "add_qnode(type=protein, is_set=True, id=n01)",
            "add_qnode(type=chemical_substance, is_set=true, id=n02)",
            "add_qedge(source_id=n01, target_id=n00, id=e00)",
            "add_qedge(source_id=n01, target_id=n02, id=e01)",
            "expand(edge_id=[e00,e01])",
            "return(message=true, store=false)",
        ]}}
```
executes in about 7 seconds, the following
```python
query = {"previous_message_processing_plan": {"processing_actions": [
            "create_message",
            "add_qnode(curie=DOID:8398, id=n00)",  # osteoarthritis
            "add_qnode(type=phenotypic_feature, is_set=True, id=n01)",
            "add_qnode(type=disease, is_set=true, id=n02)",
            "add_qedge(source_id=n01, target_id=n00, id=e00)",
            "add_qedge(source_id=n01, target_id=n02, id=e01)",
            "expand(edge_id=[e00,e01])",
            "return(message=true, store=true)",
        ]}}
```
has yet to finish after about ~20min. Note that on http://arax.rtx.ai:7474/browser/ the equivalent cypher commands:
```
match p=(n{id:"DOID:14330"})-[]-(:protein)-[]-(:chemical_substance) return count(p)
```
```
match p=(n{id:"DOID:8398"})-[]-(:phenotypic_feature)-[]-(:disease) return count(p)
```
result in 3,742 and 55,212 paths respectively. So when there's a ton of paths, it appears that expand is slowing down quite a bit. Any chance you could look into this and see what exactly is causing the slowdown? I imagine it's either:
1. Multiple cypher calls that should be batched
2. Some slowdown in `QueryGraphReasoner.py` (which you might want to consult with @finnagin since he helped get that working on our system).

**Comment by amykglen** [comment]
Hmm... yep, I'll look into it!

**Comment by amykglen** [comment]
Ok, so it seems that cypher calls aren't the real culprit here (that part is taking 30 or 40 seconds for me for the slow query) - it's instead the python code that processes the results, mainly at the end of Expand, when it's merging the answer knowledge graph into the overarching knowledge graph (that's taking a huge amount of time... 20+ minutes?).. (though QueryGraphReasoner itself is also a bit slow, when it calls `infer_result_information()` - takes about 3 minutes).

I'll work on fixing this (have several ideas)

**Comment by edeutsch** [comment]
hmm, infer_result_information() sounds a lot like what I was wrestling with and my problem that I talked about today. Could it be that that code is already in place and we just need to copy it?

**Comment by edeutsch** [comment]
Also, separately, it would seem that Expand() doesn't need to perform infer_result_information() at all, so calling QueryGraphReasoner may be overkill? I wonder if you'd be much better off not calling QueryGraphReasoner() from Expand, but rather performing the 1-hop Expand with your own code very efficiently? A 1-hop Expand() should be very easy cipher and not require all the fancy overhead for QueryGraphReasoner?

**Comment by amykglen** [comment]
Yep, that was one of my thoughts as well. I don't think it will be hard to do.

As for `infer_result_information`, I'm not sure it's doing quite what you need (?) I think it's adding information (like edge_bindings) to already existing results (it lives [here](https://github.com/RTXteam/RTX/blob/demo/code/reasoningtool/QuestionAnswering/FormatOutput.py#L358))

**Comment by amykglen** [comment]
Alright, so I just pushed [changes fixing the bulk of the slowdown](https://github.com/RTXteam/RTX/commit/e02de3f2d17b856c746a26010521f5b69d0ab55b) (the part that was in Expand itself) to the expander branch - I opted to convert the knowledge graphs being processed to dictionary format (like was mentioned as a potential eventual change to the API standard on yesterday's AHM) - and that completely resolved the issue. (The function call taking 20+ minutes before now takes less than a second.)

(Currently, I convert the knowledge graphs _back_ to standard API format at the end of Expand, so that other modules aren't affected, but eventually perhaps that won't be necessary, if the dictionary format _becomes_ the standard.)

**Comment by amykglen** [comment]
Now I'll work on addressing the remaining 3-minute slowdown coming from QueryGraphReasoner... (as mentioned above, I'm thinking I will skip using QueryGraphReasoner, and instead write some code more tailored to what we need for Expand..)

**Comment by amykglen** [comment]
So it turns out that [a little tweak](https://github.com/RTXteam/RTX/commit/5ff761920f79a7ede31a8df6e505387c873ac1c4) to `infer_result_information()` (in FormatOutput.py) -- which once again entailed switching a knowledge graph to dictionary (vs. list) format -- resolves the 3-minute slowdown coming from QueryGraphReasoner (that step now takes about 1 second). So the entire expand() for the query that was taking 20+ minutes now takes about 40 seconds (30 of which are waiting for the cypher call to complete).

Given this, I'm kind of thinking that it may not be worth writing new code to use instead of QueryGraphReasoner right now... (especially since it seems we will eventually want to be interacting with KPs largely via their APIs (?), and writing some tailored cypher for Expand kind of seems to take us further from that...)  So I think I will not do that at this point... unless anyone thinks otherwise!

**Comment by edeutsch** [comment]
My only concern is that QueryGraphReasoner is a gnarly black box of borrowed code that could be replaced in this instance by something pretty simple. But I don't feel strongly about it, and if it's working and fast now, then that's fine to leave it, and we can consider whether it is worth having a smaller cleaner version in Expand sometime later. So, no need to do that now if there are more urgent things.

Also, while I think it's true that we want to bring in more complex KPs, I still think using the "core brain" of the neo4j KG or KG2 is something we will keep for a long while. But I am not certain.

**Comment by dkoslicki** [comment]
+1 to keeping the “core brain” of RTX KG1 or KG2 around for a while. And considering the speed ups that @amykglen has been able to make, I agree that it’s not urgent or necessary for the demo to depart from the `QueryGraphReasoner` and roll our own expander to completely replace it. Note, btw, that `QueryGraphReasoner` is not a total black box as Finn and I have been able to somewhat understand it, and at least get it modified for our purposes, so it’s somewhat understood.

**Comment by dkoslicki** [comment]
@amykglen you happy with the speed and state of your expander? If so, shall we close this issue?

**Comment by amykglen** [comment]
yep - closing now (sounds good to roll our own QueryGraphReasoner a bit down the road)
