### ISSUE TITLE
Normalized google distance for sets of nodes

### ISSUE THREAD

**Issue by dkoslicki** [RTXteam/RTX#63]
We need a function in ``QueryNCBIeUtils`` that will take in a list of node names (and any required attributes) and return a normalized google distance based on MeSH terms.

**Comment by saramsey** [comment]
@dkoslicki NGD is (from what I remember) defined as a pairwise semantic distance measure. How would it apply to a *list* of node names?  Please forgive my ignorance.

**Comment by dkoslicki** [comment]
It was originally defined for pairs, but we can extend the definition for an arbitrary number. The rational is that "context is king" and so just because a certain anatomy node and symptom co-occur frequently, doesn't mean it's necessarily relevant for a disease under consideration (hence why our COP's answers struggle with these later parts of the path).
For triples, the extended definition would be:
$\frac{\max\{ \log f(x), \log f(y), \log f(z)\} - \log f(x,y,z)}{log N - \min\{ log f(x), log f(y), log f(z)\}}$

![](http://quicklatex.com/cache3/ff/ql_14f48dbb3336c15e44111935fcfd97ff_l3.png)
where f is the pubmed hits, N total number of articles.

**Comment by saramsey** [comment]
@finnagin  please let me know if you have any questions about how to implement this.  As it is marked high priority, this should probably get fast-tracked.

**Comment by finnagin** [comment]
@saramsey Thanks! I'll let you know if I run into any issues. 

@dkoslicki I've already implemented a method that calculates the normalized google distance for n terms (named `multi_nomalized_google_distance` so that it does not break any code that relies on the original `nomalized_google_distance` method) but, I'm still working on getting the functionality that detects the ontology and converts to mesh terms to then use the expanded normalize google distance function. Since this is high priority do you want me to push the code containing the expanded google distance function now  with the rest pushed later or should I wait until I get all of the functionality we discussed working before pushing any of my code?

**Comment by dkoslicki** [comment]
@finnagin Go ahead and finish the automatic conversion to mesh terms (otherwise I'll be writing a bunch of unnecessary code that will duplicate the work you'll be doing).

**Comment by finnagin** [comment]
@dkoslicki Should we close this issue and open a different one for optimization?

**Comment by dkoslicki** [comment]
Sure! I'll close this one and open another.
