### ISSUE TITLE
Warning instead of info: QueryGraphReasoner found no results for this query graph

### ISSUE THREAD

**Issue by dkoslicki** [RTXteam/RTX#656]
@amykglen If `expand()` finds nothing (i.e. an empty graph) you should probably issue a WARNING, not just an INFO as this is rather important information to have passed down the line.

Maybe discuss with @edeutsch and @saramsey if this should be an ERROR instead....

**Comment by amykglen** [comment]
yeah, good catch - I switched those to 'warnings' for now at least... what do others think about using 'error' for this? do we want execution to stop if a single expand call doesn't find any results?

**Comment by dkoslicki** [comment]
Yeah, don’t know if we should stop if an expand fails... good for an AHM discussion (from which I will probably be absent for the next few weeks). Feel free to put it on the agenda and I will defer to what you, @saramsey and @edeutsch come up with. After that, feel free to close this issue.

**Comment by edeutsch** [comment]
I opined at today's meeting that I thought Expand() should issue an ERROR and thereby cause downstream processing to halt if 0 nodes were returned since it seems fairly unlikely that downstream processing would be successful after Expand() returns 0 nodes. I hedged a little to suggest that there could be a user option continue_if_no_results=true or similar which would then instead issue a WARNING, which allows processing to continue if the user imagines that downstream processing might still be successful after a null result.
But I'm just speculating. Happy to be overridden if you feel differently.

**Comment by dkoslicki** [comment]
I generally agree with @edeutsch’s comment. The only situation that I could foresee happening is if the ARS sends us a QG with a partially/full expanded KG, and then asks us to expand a bit more, then do a bunch of other processing.
At least for `overlay`, I’ve done my best that if there’s nothing to do, there’s nothing to do (eg. If the KG is empty, all my `overlay()`s happily report that they successfully did nothing).

**Comment by edeutsch** [comment]
Interesting idea about "expand a bit more". If we think we might encounter that, would Expand() then be obligated to check for duplicates? i.e. make sure that new nodes/edges that it wants to add don't already exist? I assume yes. Not necessary for the demo, but something to consider for afterwards. I assume current behavior might then lead to two of the same node?

**Comment by amykglen** [comment]
Expand() actually already checks for duplicates when it's adding nodes/edges to the knowledge graph. We already encounter that situation when we use multiple expand calls - as in, `expand(edge_id=e00)` followed by `expand(edge_id=e01)`, rather than `expand(edge_id=[e00,e01])`.

For example, if we use the dual expand method for our Parkinson's example, the first expand produces a bunch of proteins that are added to the knowledge graph, and the second expand returns a bunch of drugs **as well as** those same proteins (or technically those of them that 'physically_interact_with' a drug). So it filters those out to prevent duplicates.

**Comment by edeutsch** [comment]
nice!
Then maybe there should be a distinction between "no results at all" (Error) and "nothing new to add" (but there are already some suitable edges there) (Warning)

**Comment by amykglen** [comment]
I think this can be closed? (addressed in #713)

**Comment by edeutsch** [comment]
okay by me, thanks!
