### ISSUE TITLE
what should resultify do if the input message object already has results?

### ISSUE THREAD

**Issue by saramsey** [RTXteam/RTX#691]

**Comment by edeutsch** [comment]
For the record, in order to make Example 4 work the way I think it should:
https://github.com/RTXteam/RTX/tree/demo/code/ARAX/Examples

I made this change to ARAX_resultify:
https://github.com/RTXteam/RTX/commit/9802bf8f0f3ce6f9166b8af9e38c23d415e1c54e#diff-bba70b25afd5d5d8a714c3957e0d02ca

**Comment by saramsey** [comment]
Per @dkoslicki comment in the 3/24 AHM: we need to consider that the interface between the ARS and ARAX is not yet fully defined and likely to evolve; in handling this issue we need to consider what the needs or likely use-cases of the ARS<->ARAX will be.

**Comment by edeutsch** [comment]
I think the reality is that in the short term they will be sending us plain QueryGraphs, not DSL. So therefore we need an extra layer that looks at an incoming query graph, analyzes it for known patterns and *writes* some DSL that best answers that question (rather than shoving it blindly into the crude QueryGraphReasoner) and then executes that DSL.

For example recognize that (curie=X)--(is_set=true)--(generic node type) means that we should run an example 2 style DSL set of commands, etc.

**Comment by saramsey** [comment]
To @edeutsch's point, see also #708

**Comment by saramsey** [comment]
This (commit 9802bf8) works and may be best from a user experience standpoint. 

From a clean design standpoint, I suppose I favor adding a `clear_results` command to the DSL, and having `resultify` *require* the input `message.results` list to be empty. But I can't deny that 9802bf8 means that there is one fewer DSL command in the lexicon for users to have to learn.

**Comment by saramsey** [comment]
I'm going to close out this issue
