### ISSUE TITLE
Resurrect the Snakefile 

### ISSUE THREAD

**Issue by kvarforl** [RTXteam/RTX#694]

**Comment by ericawood** [comment]
@saramsey After running a build with `./build-kg2-snakemake.sh test`, it was successful (it took about 4 hours, 15 minutes, and 50 seconds). Can I close this issue or would you like me to do a full build?

**Comment by saramsey** [comment]
Thanks for the update.  OK, 4 hours 16 minutes sounds good. Next, we want to know how much faster it is than the sequential build. Can you please run (and time) the functionally equivalent sequential build for comparison purposes?

Once that is done, I think the next step is to diff the two JSON reports generated from the `kg2-simplified.json` files. They should be *identical*, otherwise, the build processes are not functionally equivalent, right?

Really appreciate your help on this issue.

Thanks,
Steve

**Comment by ericawood** [comment]
@saramsey Should I run `./build-kg2-snakemake.sh test` in sequential mode (a quick change) or ./build-kg2.sh (if the latter, the times will be substantially different as build-kg2-snakemake.sh in test still downloads everything)?

**Comment by ericawood** [comment]
I ran the sequential build. My initial note about 4 hours and 16 minutes was incorrect, it was closer to 6 hours and 16 minutes (I should not have tried to do the arithmetic in my head). Below is the time table. Please let me know if you have any questions. Also, note that the full build times will not scale according to the test times shown below, as at the end (after the merge step), the data is managed sequentially as it takes over 70% of the available memory to load in the knowledge graph each time, due to its size, which kills other processes that take more than 30% of the available memory. Those sequential steps in the test build only take about 6 minutes each, in comparison to the 30 minutes to an hour that they take in the full build.

Time | Parallel | Sequential
-- | -- | --
Start | 20:35:40 | 21:37:34
Finish | 02:51:30 | 09:30:38
Total | 06:15:50 hours | 11:53:04 hours

**Comment by ericawood** [comment]
Images for Maintenance File:
![snakemakepipeline](https://user-images.githubusercontent.com/36611732/90065568-5a3cc980-dca1-11ea-87ea-d32f8f6b6bd8.png)
![snakemakepipelineshort](https://user-images.githubusercontent.com/36611732/90065571-5b6df680-dca1-11ea-95fc-25ed1c5f6c4d.png)

**Comment by saramsey** [comment]
I think at this point the main thing left is to update the build instructions in `README.md` since we are planning to transition to using Snakemake as our main build system.

**Comment by saramsey** [comment]
Can confirm, the build of `KG2.3.4` on `kg2steve.rtx.ai` during Sept. 3-4 seemed to work. Produced all of the files that I expect to see, including `kg2-simplified.json.gz` and `kg2-tsv.tar.gz`. I recall being told that the AWS S3 commands in `Snakefile-finish` had been commented out on `kg2steve` (not in GitHub master), and indeed, that seems to be the case; the Snakemake build did not copy anything to S3. So, on `kg2steve`, I prepared a  one-off shell script (`/home/ubuntu/kg2-code/build-kg2-finish.sh`) to complete that part of the build. It is running now....

**Comment by saramsey** [comment]
See #1053

**Comment by kvarforl** [comment]
On kg2lindsey, running  `bash -x ~/kg2-code/build-kg2-snakemake.sh all`  terminates on an error in `validate_curies_to_categories_yaml.py`.
![image](https://user-images.githubusercontent.com/39020520/94755160-67447380-0348-11eb-9ba9-73fdd79a4b80.png)
Documenting here for now: will look into it more tomorrow.

**Comment by ericawood** [comment]
Hi @kvarforl,
This is likely an issue with the TUI mappings that I added to curies-to-categories.yaml. I thought that I had run the validation scripts before committing, so this is interesting. I would recommend checking out biolink_categories_ontology_depths to see if "ontology class" is in it. You might also check the date on the biolink download. :)
