### ISSUE TITLE
Differences between API object model and KG2 schema: name vs full_name

### ISSUE THREAD

**Issue by dkoslicki** [RTXteam/RTX#703]
In investigating #698 (in particular, the normalized google distance), I found that while the API object model has `node.name`, KG2 has properties of both `name` and `full_name`. Which of these should be used to populate the `node.name` field in the API object model in `expand`? This will influence the accuracy/speed/results of ngd as it uses the name as a fallback in case the CURIE to MeSH mapping comes up empty.

**Comment by edeutsch** [comment]
I do not know. @amykglen ?

**Comment by amykglen** [comment]
It's a good question...

What I've currently been doing in `expand` for most nodes is:
KG2 `name` -> API model `name`

But for UniProtKB nodes, I've been doing this:
KG2 `full_name` -> API model `name`
KG2 `name` -> API model `symbol`

(Since the `name` of UniProtKB nodes in KG2 is an abbreviation, like "MAOA".)

This is likely imperfect, but I think it's probably not **too** far off, because:

1. Most KG2 nodes do not have a `full_name` (5.4 million out of 7.5 million)
2. Out of the 2.1 million nodes _with_ a `full_name`, that `full_name` differs from the `name` for only about 52,000
3. Out of those nodes, about 26,000 are UniProtKB nodes (where we're already using the `full_name` as `node.name`)

![Screen Shot 2020-04-09 at 4 26 02 PM](https://user-images.githubusercontent.com/49423686/78945986-d4a0d700-7a7e-11ea-9920-8b1e03c91991.png)

@saramsey would know better than me though. I'm not very familiar with how KG2 node names/full names are populated, and if there are further exceptions we should make (where we should use `full_name` as `node.name`).

**Comment by dkoslicki** [comment]
Your way of going about it @amykglen makes sense to me (and is well-justified). I'll wait to hear from @saramsey if he has any more insight about the remaining cases.

**Comment by saramsey** [comment]
Just an FYI, in KG2, I am striving to have the official gene symbol be the first entry of the "synonym" property list, not the "name" field.

**Comment by saramsey** [comment]
Where are we on this issue? Can I close it out?

**Comment by amykglen** [comment]
I think we're pretty much there, although I should probably incorporate what you said in your last comment:

> Just an FYI, in KG2, I am striving to have the official gene symbol be the first entry of the "synonym" property list, not the "name" field.

So does this mean if a node is from KG2 and it's a `gene`:

- API model `name`: should be KG2 node `name`
- API model `symbol`: should be KG2 node `synonyms[0]`

(And I suppose I could store the KG2 node `full_name` in a `NodeAttribute`.)

**Comment by saramsey** [comment]
> I think we're pretty much there, although I should probably incorporate what you said in your last comment:
> 
> > Just an FYI, in KG2, I am striving to have the official gene symbol be the first entry of the "synonym" property list, not the "name" field.
> 
> So does this mean if a node is from KG2 and it's a `gene`:
> 
> * API model `name`: should be KG2 node `name`
> * API model `symbol`: should be KG2 node `synonym[0]`
> 
> (And I suppose I could store the KG2 node `full_name` in a `NodeAttribute`.)

That is my intention. We should probably do a KG2 build from the latest code and verify.

**Comment by amykglen** [comment]
Ok, cool. I can kick a build off whenever (and test this and #743). Today?

**Comment by saramsey** [comment]
Amy, I am ready for this to be tested against KG2.3.0 (http://kg2endpoint-kg2-3-0.rtx.ai:7474)

**Comment by amykglen** [comment]
closing since this issue is old enough to have become irrelevant (see #1213)
