### ISSUE TITLE
Handling synonym nodes edges and how they map back to the query graph

### ISSUE THREAD

**Issue by dkoslicki** [RTXteam/RTX#707]
Possible approaches:

1. `expand` gets all the synonyms, but then maps back the synonym edges to the original query edge, and then discards the synonym nodes
2. `expand` gets all the synonyms, and returns results back everything as it is. Then subsequent reasoning code needs to handle the issue with edges existing on some synonyms and not others
3. Somehow represent the set of synonyms as an "uber node" so while we still retain the specific information about the synonyms and the provided_by fields, the downstream reasoning code has access to a single node that represents the union of all the synonyms

**Comment by edeutsch** [comment]
Great. I think Amy agreed to code up Expander so that any of these three options can be triggered as an option to Expander. Approach 2 is effectively already done I suspect. Approach 1 is next since this is most friendly to downstream processing. Amy is trying this now. Approach 3 is mostly a twinkle in our eyes at the moment. Cool idea, but how to do this in detail? Seems doable, but needs more planning.

**Comment by amykglen** [comment]
Ok, I added synonym handling approach 1 (in `expander` branch) - you can now control the method used via a new optional parameter on `expand`:

- `synonym_handling=map_back` corresponds to approach 1 (default)
- `synonym_handling=add_all` corresponds to approach 2

(Note that since I haven't (quite) yet implemented synonym functionality for KG1, these don't yet do anything for KG1 expands - only KG2.)

**Comment by isbluis** [comment]
Not sure if this is a valid example, but I notice that this response:
https://arax.rtx.ai/index.html?m=2041

contains a KG with 7 orphan synonym-looking nodes (for "Babesia" -- the example of the day!)

From the debug messages, it does seem to be using KG2 and map_back:
```
2020-05-15 16:41:18.429672 INFO:    Processing action 'expand' with parameters {'edge_id': 'e00', 'kp': 'ARAX/KG2'} 
2020-05-15 16:41:18.429690 DEBUG:    Applying Expand to Message with parameters {'edge_id': 'e00', 'node_id': None, 'kp': 'ARAX/KG2', 'enforce_directionality': False, 'use_synonyms': True, 'synonym_handling': 'map_back', 'continue_if_no_results': False}
````

Just wanted to report it in case it is relevant.
Thanks!

**Comment by edeutsch** [comment]
I think this is the same query as in #748, but it is a stored Message back from a time when the query was able to complete without an error.

**Comment by edeutsch** [comment]
I suppose a relevant question is: when performing "map_back", should the demapped node deleted from the KG. I'm thinking yes. But it's not necessarily the best action.

**Comment by amykglen** [comment]
Yes, running this same query today throws an error due to a known issue (#748) - but I'm thinking that my fix for #748 may resolve these strange orphans. I'll confirm after I finish that. Thanks for reporting, @isbluis!

> I suppose a relevant question is: when performing "map_back", should the demapped nodes be deleted from the KG. I'm thinking yes. But it's not necessarily the best action.

Yes - I agree that seems to make the most sense, and that's what `expand` is supposed to do currently.

**Comment by amykglen** [comment]
Documenting for the record: Those [7 orphan nodes](https://github.com/RTXteam/RTX/issues/707#issuecomment-630425349) in the babesia query results appear to be gone now that I pushed the fix for #748/#742. https://arax.rtx.ai/?m=2073

**Comment by amykglen** [comment]
Question here: In addition to using synonyms for QNodes that have a curie specified, should we use synonyms for non-specific QNodes?

Meaning, right now, for this kind of query, synonyms would be used for n00:
```
(n00: DOID:14330)--(n01: protein)--(n02: chemical_substance)
```

And once we begin expansion, the first edge expanded (n00--n01) will produce a bunch of proteins (e.g., UniProtKB:P08183, UniProtKB:Q01959, etc.). Currently that exact list of proteins is what's fed into the next edge expansion (n01--n02), but should we instead feed in those protein curies as well as their synonyms? (Assuming `use_synonyms=true`, of course.)

**Comment by edeutsch** [comment]
I think yes!

**Comment by amykglen** [comment]
closing since we have our synonym handling strategy sorted out (interestingly, KG2c is kind of the "uber" node idea we came up with way back when..)
