### ISSUE TITLE
Create a bird's eye view of available relationships and sources

### ISSUE THREAD

**Issue by edeutsch** [RTXteam/RTX#724]
I think it would be fantastic if we could organize the universe of available relationships in a simple Google Sheet format of relationships. I started one here:
https://docs.google.com/spreadsheets/d/1TwZIK3K67YgZp2SnVRNZbukpCBGCcAGcOrUX--m0lJk/edit#gid=0
I feel that this structure would provide us a useful way of seeing at a glance and organizing "how can we get from here to there". I feel I don't have a good grasp of what relationships and sources we have available and I think this could help. Maybe there's some way to autogenerate most of this for KG1, KG2, and BTE, and hand-edit the rest? Although I think this is important information that should be carefully thought about by a person, too, not just autogenerated. Or maybe we have something like this already? I don't think we need both forward and reverse, just one direction of each pair seems sufficient.

After discussion, I think Amy volunteered to try to populate this in a semi-automated way for KG1, KG2, and BTE based on queries

**Comment by amykglen** [comment]
Ok, I posted a first take at autogenerating this info for KG1, KG2, and BTE in [tab 2 of your spreadsheet](https://docs.google.com/spreadsheets/d/1TwZIK3K67YgZp2SnVRNZbukpCBGCcAGcOrUX--m0lJk/edit#gid=1467834088), @edeutsch. Let me know if you'd like anything tweaked (it's easy to re-run the script that creates this).

One note: I did include both directions for each pair, since different sources/predicates are used for different directions... (and I think a small number of pairs are only given in one direction). But I can collapse these if you'd like.

**Comment by edeutsch** [comment]
Wow, awesome! This is huge! literally. Much bigger than I expected.

Thank you, this gives me something big to muse over.

**Comment by amykglen** [comment]
Cool! Not sure if I should check the script for this into the repo somewhere? (`ARAX/KnowledgeSources`?)

**Comment by edeutsch** [comment]
Yes, please do! That looks like a good place, yes, thanks.

**Comment by amykglen** [comment]
Guess we can close this issue now?

**Comment by edeutsch** [comment]
Yes, thanks so much for creating this. We still haven't figured our how to properly capitalize on this result, but in the near term it will be repurposed for the /predicates endpoint for for what Chunyu needs and be converted into machine readable files. Where it goes next I'm not sure yet, but we shouldn't forget this.
