### ISSUE TITLE
add biolink model object hierarchy to KG2

### ISSUE THREAD

**Issue by saramsey** [RTXteam/RTX#730]

**Comment by dkoslicki** [comment]
@edeutsch do you think this would help @chunyuma in determining a list of allowable node & edge types? See [this comment](https://github.com/RTXteam/RTX/commit/289dbc4c9a07015d2c70a41b99d1cd18fd054b93#commitcomment-39430845) and the associated thread where there is [hard-coding](https://github.com/RTXteam/RTX/commit/289dbc4c9a07015d2c70a41b99d1cd18fd054b93#diff-320ac0b2459a117e13b78a8b8493f2a0R42-R47) of acceptable node & edge types.

**Comment by edeutsch** [comment]
This might be somewhat orthogonal to the current issue, but posted here as well as in other thread:

The currently official way to get all allowable node and edge types is:
Via the API:
    https://arax.rtx.ai/api/rtx/v1/predicates
Internally:
  import ReasoningUtilities as RU
  RU.get_full_meta_graph()

Important notes:
- This uses `call apoc.meta.graph`
- This *caches* the current metagraph since the above call is slow. Cache expiration is NOT implemented yet.
- This is hardwired for KG1. KG2 is not considered
- Is `call apoc.meta.graph` available for KG2?

**Comment by dkoslicki** [comment]
Given that apoc.meta.graph is **not** available for KG2 (won’t complete even when given unbounded time to finish), I would shy away from using this (especially given our desire to abandon ReasoningUtilities), especially since KG2 predicates/types are so much more rich than KG1.

I was hoping for something along the lines of: the intersection/union of biolink predicates/types with those provided by KP’s used.

Maybe it’s worth (not via apoc.meta.graph), getting all predicates/types of KG2 and storing them somewhere (maybe with a SQL command on KGNodeIndex)? I think @amykglen has some way to get these for BTE and we can continue to add as we connect to more KP’s...

**Comment by edeutsch** [comment]
@amykglen has created nearly this in #724. Instead of a Google sheet, I suppose we need these as data structures like provided by RU.get_full_meta_graph(). Ideally separated by KP.

**Comment by finnagin** [comment]
can use `call db.relationshipTypes` to get relationship types quickly and `call db.labels` to get node labels quickly

**Comment by saramsey** [comment]
OK, the biolink object model should be built into the next full KG2 build

**Comment by saramsey** [comment]
Done.

<img width="818" alt="Screen Shot 2020-07-16 at 11 24 32 AM" src="https://user-images.githubusercontent.com/5562107/87708029-f03f0c00-c756-11ea-8c75-bfc70abae270.png">
