### ISSUE TITLE
allow expand(node_id=n00)?

### ISSUE THREAD

**Issue by edeutsch** [RTXteam/RTX#734]
Hi Amy, would you be willing to update Expander to allow this:

expand(node_id=n00)

The behavior would simply be:
- If there's no curie, return with an ERROR
- If there is a curie, populate the knowledge_graph with the node or nodes that correspond to the provided curie with full name and description and any other relevant attributes.

Maybe it would be most fun with synonym_handling=add_all, but you don't need to change the default. The caller can set that.

We might need to update Resultify() to handle this trivial case, we'll see.

**Comment by amykglen** [comment]
Sure! I can do that.

**Comment by amykglen** [comment]
Ok - this is all done, and I confirmed `resultify` already seems to work for single-node expansions. So no changes needed there I think.

Note: I also made it so that `expand` will default to expanding the entire query graph if no edge/node IDs are provided (as I asked about earlier today). (It was trivial to do while already in there for this issue, so I went ahead and did it.)

**Comment by edeutsch** [comment]
Awesome! Thanks so much, looks great! I have rolled out to test, beta, and production and it seems to be working nicely.

Fun DSL snippet of the day:

add_qnode(curie=DOID:14330, id=n00)
expand(node_id=n00, kp=ARAX/KG2, synonym_handling=add_all)
resultify()
