### ISSUE TITLE
Can we make a change in expand function to allow pulling out all nodes with same type in KG? 

### ISSUE THREAD

**Issue by chunyuma** [RTXteam/RTX#744]
Hello all,

I'm writing the code for issue #623 to perform a fisher exact test in ARAX_overlay. To do this, I need to calculate a contingency tables by using DSL. For example, I need to use DSL to pull out all the protein nodes in KG and know how many proteins in KG. I know this would be easy to do by using cypher query like `match (n:protein) return count(n)`. But we have already had the old code to do this fisher exact test by using cypher query [here](https://github.com/RTXteam/RTX/blob/e9fb371b2b9d66aab588dc3237e4491c69acad70/code/reasoningtool/QuestionAnswering/fisher_exact.py#L135). What David and I want to do in the new code is to compute the fisher exact statistics without cypher, but rather by making calculations using the `message.knowledge_graph` and/or internal calls to `expand` and other DSL functions as necessary.

So can we make a change in expand function to allow pulling out all nodes with same type in KG?

**Comment by amykglen** [comment]
to clarify - by "KG" you mean an entire knowledge provider, like KG1 or KG2, right, @chunyuma?

**Comment by chunyuma** [comment]
Yes, you're right. KG means the entire knowledge graph/provider, like KG1 or KG2.

**Comment by edeutsch** [comment]
Tricky issue. It's not clear to me that there should be DSL for this.
- expand() could compute the total number of relevant data type nodes each time. But store it where?
- Can this even be computed for BTE?
- If we decide that it should be overlay()'s job to compute the total numbers, how will it know to look in KG1 or KG2 or BTE or where?
- I suppose for KG1 and KG2 we can pre-compute these numbers for all types and just store it somewhere in a cache file that needs to be refreshed whever KGs are reloaded.
- Should the totals include all redundant nodes (especially in KG2) or only unique concepts?

I have questions, but no answers.

**Comment by chunyuma** [comment]
@edeutsch, can I know what is BET?

- I think we actually don't need to pull out all relevant data type nodes and store it somewhare if we can pre-compute the total number of all types and use certain parameter in `expand`  to access them. 
- To determine which KG to look at, can we base on the `is_defined_by` label of `overlay.message.knowledge_graph.edges` generated from `expand` function? 
- I think it should only include unique concepts.

**Comment by edeutsch** [comment]
BTE is BioThings Explorer. It is an alternative knowledge provider, like KG1 and KG2. However, it is all API based and I suspect it will be difficult to ask "how many drugs do you know about?" (this is what you need to know of the fisher exact test, right?)

You're right, we can used "is_defined_by" to know which knowledge provider to get the totals from, good idea.

It also just now occurs to me that we can use KGNodeIndex to get the totals without having to go to cipher. There isn't a method for that currently, but it would be easy to add. It would even be pretty easy to compute a distinction between the total number of curies of a certain type vs. a total number of distinct concepts since KGNodeIndex has a concept of a canonical curie for each group of synonyms, although it is imperfect.

**Comment by chunyuma** [comment]
@edeutsch, I think whether we need to know total number of drugs in KG1, KG2 or BTE depends on whether the type of query node list is drug.

The contingency table in fisher exact test should like this:
 |                                                          | in query node list | not in query node list | row total   |
 | connect to certain adjacent node |         a                    |           b                         |   a+b         |
 | not connect to adjacent node       |         c                    |           d                         |   c+d          |
 |         column total                            |        a+c                |          b+d                      |  a+b+c+d  | 

If the type of query node list is protein, then a, b, c, d are all proteins and a+b+c+d is the total number of proteins in KG1, KG2 or BTE. If type of query node list is drug, then they will be drug number.

@edeutsch @amykglen, could you help me add a method in expand to get the total number by utilizing KGNodeIndex information? Thank you!

**Comment by amykglen** [comment]
Update: It turns out BTE cannot provide this info (the total number of nodes of a given type that it knows about), according to Kevin Xin. (Because it doesn't keep any backend database.)

**Comment by edeutsch** [comment]
yup, as expected. But the universe of number of distinct concepts (removing redundancy) of each type is probably well conserved between BTE and KG2, so I still think we can use the answer from KG2 for BTE as well. This is another advantage of ETL into KG2 that we should remember when defending it.

**Comment by edeutsch** [comment]
So I have implemnted basic functionality in KGNodeIndex for counting the total number of entities. But it probably isn't very effective.

Example:
    kg = 'KG1'
    print(kgNodeIndex.get_total_entity_count('chemical_substance', kg_name=kg))
    print(kgNodeIndex.get_total_entity_count('disease', kg_name=kg))
    print(kgNodeIndex.get_total_entity_count('protein', kg_name=kg))
    print(kgNodeIndex.get_total_entity_count('drug', kg_name=kg))
    print(kgNodeIndex.get_total_entity_count('cheesecake', kg_name=kg))
2226
19095
20555
0
0
Elapsed time: 0.169926

That seems fine. But the results for KG2 are quite a bit more displeasing:
1988287
170453
253600
335118
0
Elapsed time: 11.2728329

These numbers are way high, probably because of insufficient synonym mapping. It's a bit slow, but probably that's not a problem.

It seems that the reasonable next step is to use the ARS node normalizer to get a better synonym map (useful anyway) is order to push down the total numbers to something more reasonable.

Maybe in the short term, it would be reasonable to always use the numbers for KG1 irrespective of which KP was used for the expand()?
