### ISSUE TITLE
Figure out how to load non-scalar KG2 node/edge properties into NodeAttributes/EdgeAttributes

### ISSUE THREAD

**Issue by amykglen** [RTXteam/RTX#756]
Forking this issue from #750.

Proposal from @edeutsch for handling the node `publications` property ([here](https://github.com/RTXteam/RTX/issues/750#issuecomment-631149501)):

> hmm, that make it more complicated. Perhaps the better thing to do is instead of making the node_attribute value a list with N items, instead there should be N node_attributes, each one with the appropriate type. EDAM has a type for DOI which is data:1188
> http://bioportal.bioontology.org/ontologies/EDAM/?p=classes&conceptid=http%3A%2F%2Fedamontology.org%2Fdata_1188&jump_to_nav=true
> etc.
> 
> ISBN is data:2634
> http://bioportal.bioontology.org/ontologies/EDAM/?p=classes&conceptid=http%3A%2F%2Fedamontology.org%2Fdata_2634&jump_to_nav=true
> 
> If it's not a PMID or a DOI or a ISBN, maybe just a generic article:
> http://bioportal.bioontology.org/ontologies/EDAM/?p=classes&conceptid=http%3A%2F%2Fedamontology.org%2Fdata_0971&jump_to_nav=true
> 
> It's not clear if such care will be rewarded, but that's probably the right way to do it.

**Comment by amykglen** [comment]
Ok, I can do that for node 'publications', @edeutsch. Though should I actually convert PMIDs to pubmed urls in the back end? (I see that @isbluis seems to have done this conversion in the UI for the 'publications' property on edges.)

**Comment by amykglen** [comment]
And how do you suggest handling node 'synonym' attributes? e.g.:
```
{
   "name":"synonym",
   "type":"None",
   "url":"None",
   "value":[
      "clopidogrel",
      "PUBCHEM_BIOASSAY:49666423",
      "SID49666423",
      "GKTWGGQPFAXNFI-HNNXBMFYSA-N",
      "None",
      "InChI=1S/C16H16ClNO2S/c1-20-16(19)15(12-4-2-3-5-13(12)17)18-8-6-14-11(10-18)7-9-21-14/h2-5,7,9,15H,6,8,10H2,1H3/t15-/m0/s1",
      "ASTRAZENECA:1793",
      "COC(=O)[C@@H](N1CCc2sccc2C1)c3ccccc3Cl",
      "BNF:16755",
      "CLOPIDOGREL",
      "PUBCHEM_BIOASSAY:49666065",
      "ATC:16755",
      "DRUGMATRIX:228",
      "SID49666065",
      "Clopidogrel"
   ]
}
```
Is this property reason to adjust the standard to allow lists?

**Comment by edeutsch** [comment]
Regarding publications: I think it would probably best (and @isbluis would agree?) that it would be better to create the url in the backend, so the presentation layer just displays the url as provided without having to do special interpretation of what a node_property of "publications" means.

**Comment by edeutsch** [comment]
Regarding synonyms: I don't know. They easiest path is probably just to leave it mostly as is but make the type something like data:1001 or something:
http://bioportal.bioontology.org/ontologies/EDAM/?p=classes&conceptid=http%3A%2F%2Fedamontology.org%2Fdata_1001&jump_to_nav=true

Probably a better way to do it is to break up the list into individual node_attribute elements where each type is carefully set to what it is, a compound name or compound accession as found in EDAM or BioLink. 

But one might even step back and wonder: is it even necessary or is it redundant? Maybe best (and easiest!) is just to drop this information, because that information, if it is desired, is available via a separate ws call. i.e. maybe adding the constellation of synonyms for a given concept is not necessary or even desirable here.

Sorry, I'm just adding to the confusion. It's not obvious that there is a right answer.

**Comment by amykglen** [comment]
I think this isn't an issue anymore since `Attribute.value` is now allowed to contain a list (or actually any data type) in TRAPI 1.0? right, @edeutsch?

**Comment by edeutsch** [comment]
It is true. That feature is already being abused by other groups.
