### ISSUE TITLE
create separate DEV and PRODUCTION containers on rtx.ncats.io

### ISSUE THREAD

**Issue by saramsey** [RTXteam/RTX#76]
From @edeutsch:

> I still think it would be easier and allow more seamless switchovers to have two parallel KGs on rtx with just a different port number. The only major risk I see if that someone forgets which is production and which is beta and accidentally stomps on the wrong one. But maybe a carefully laid out process could avoid that. And maybe setting the production one read-only would help, too.

**Comment by saramsey** [comment]
Hi Eric and David,

Following Eric’s suggestion, I have deployed a second Neo4j on rtx.ncats.io.

There are two Docker containers on rtx.ncats.io:

PRODUCTION:  neo4j internally on 7474/7687, externally on 7474/7687; apache2 internally on 80, externally on 80; neo4j database is /mnt/data/orangeboard/databases

DEV:  neo4j internally on 7474/7687, externally on 7574/7787; apache2 internally on 80, externally on 8080; neo4j database is /mnt/data/rtxdev/databases

@David:  this may break some things, but for sanity’s sake, I think we should standardize on 7474 for HTTP access to Neo4j.

Try it out:

PRODUCTION NEO4J:
http://rtx.ncats.io:7474

DEV NEO4J:
http://rtx.ncats.io:7574
(make sure to specify bolt:rtx.ncats.io:7787 in the login screen)

**Comment by edeutsch** [comment]
thank you for this. I am back in Seattle and trying to get this working.
One concern I have is with the names. I had envisioned something more neutral than PRODUCTION and DEV because their roles will flip sometimes: Dev will become production and production will revert to dev. It's fine for the moment, but sometime soon I think we should use more neutral names like RTX1 and RTX2 or something. And then we need a process for labeling which is production and which is DEV. Maybe this is easy with docker tools.
