### ISSUE TITLE
Resultify not returning results[] if not all edges present?

### ISSUE THREAD

**Issue by edeutsch** [RTXteam/RTX#774]
Example DSL:

add_qnode(name=acetaminophen, id=n1)
add_qnode(name=scabies, id=n2)
add_qedge(source_id=n1,target_id=n2, id=e1)
expand(edge_id=e1,kp=ARAX/KG2,continue_if_no_results=True)
overlay(action=compute_ngd, virtual_edge_type=NGD, source_qnode_id=n1, target_qnode_id=n2)
resultify()

Seems like this ought to work.
There is no data for edge e1, true.
But there is data for edge NGD.

Should that be enough for resultify() to create a result[]?
I would argue yes.

**Comment by amykglen** [comment]
This actually surprises me that any nodes are in the knowledge graph after `expand` for this query - I think it's a product of synonym handling (if you run the same DSL, but add `use_synonyms=false` to `expand`, the knowledge graph is empty).

How exactly do we want `continue_if_no_results=true` to work? I thought it should work kind of on an edge-level - so, for each edge, if you don't find any results, don't add anything to the knowledge graph.

**Comment by edeutsch** [comment]
I suppose it seems fair to me that for any nodes that are specified by curie, they should always be placed in the KG (assuming they are found). So I think I'm suggesting that the nodes should appear in the KG even with `use_synonyms=false`. 

Probably a "no_results" situation for an edge expansion is when no edges are found for any one of the requested qedges.

For a node expansion, the "no_results" situation is probably when no node is found for any one of the requested qnodes.

An interesting question is when curies is a list, what happens when only *some* are found. Is that a "no_results" condition (that the user can control on whether to move on or not)? I'm thinking that makes a nice default for now. If the user specifies 5 proteins and only 4 are found: if the user specified `continue_if_no_results=true` then press on with a WARNING. But if the user did not specify or provided `continue_if_no_results=false`, then issue an ERROR?

Could also have a separate option `continue_if_some_curies_missing=true`... Maybe that's better than repurposing an existing option.

FWIW, if any curies in a list is missing, this is currently an ERROR in add_qnode(). But expand() could encounter unfindable curies either with a direct incoming query_graph or if the KP for expand() is not KG2.

**Comment by amykglen** [comment]
> I suppose it seems fair to me that for any nodes that are specified by curie, they should always be placed in the KG (assuming they are found). So I think I'm suggesting that the nodes should appear in the KG even with use_synonyms=false.

Hmm... so I see what you mean here, but one issue I can think of is that I don't think I could do this for BTE. I don't think there's a way to query BTE for a single node.

And just fyi - for KG1/KG2 expands, this would require some additional (or at least greatly modified) cypher calls - because currently, when Expand tries to expand `e1` in your example query, it gets nothing back from neo4j - no edges, and no nodes. Because no such paths were found. So I would likely need to add in an additional cypher query to get only the nodes for QNodes with curies, if nothing was found for that edge.

> An interesting question is when curies is a list, what happens when only some are found. Is that a "no_results" condition (that the user can control on whether to move on or not)?

I definitely think this isn't the same as a 'no results' situation. I think the curie list is like an 'OR' - meaning, find me edges that go to _any_ of these curies. Whereas a query graph where each of those curies in the list were instead added as separate QNodes would be like an 'AND' situation (find me edges that go to _all_ of these curies).

But I see why it would be useful for the user to know if some of the curies they provided don't actually exist in the KP being used. But I'm not sure how we would implement such behavior given that we can't know which curies are 'missing' from BTE.

I guess I would vote that we don't throw an error if some of the curies in the list don't exist in the KP being used - instead, if it's KG1/KG2, we could issue a warning, but for BTE I don't think there's anything we could do.

**Comment by edeutsch** [comment]
> 
> 
> > I suppose it seems fair to me that for any nodes that are specified by curie, they should always be placed in the KG (assuming they are found). So I think I'm suggesting that the nodes should appear in the KG even with use_synonyms=false.
> 
> Hmm... so I see what you mean here, but one issue I can think of is that I don't think I could do this for BTE. I don't think there's a way to query BTE for a single node.
> 
> And just fyi - for KG1/KG2 expands, this would require some additional (or at least greatly modified) cypher calls - because currently, when Expand tries to expand `e1` in your example query, it gets nothing back from neo4j - no edges, and no nodes. Because no such paths were found. So I would likely need to add in an additional cypher query to get only the nodes for QNodes with curies, if nothing was found for that edge.

Maybe there could be code that considers: if the expand failed for an edge, but the user provided the option `continue_if_no_results=true` then another quick query could be performed to add the relevant nodes? Could put in a little hack where if a KP can't do that (like BTE) then substitute in KP2 for this little extra?

> > An interesting question is when curies is a list, what happens when only some are found. Is that a "no_results" condition (that the user can control on whether to move on or not)?
> 
> I definitely think this isn't the same as a 'no results' situation. I think the curie list is like an 'OR' - meaning, find me edges that go to _any_ of these curies. Whereas a query graph where each of those curies in the list were instead added as separate QNodes would be like an 'AND' situation (find me edges that go to _all_ of these curies).
> 
> But I see why it would be useful for the user to know if some of the curies they provided don't actually exist in the KP being used. But I'm not sure how we would implement such behavior given that we can't know which curies are 'missing' from BTE.

ah, I see: in BTE you can't tell the difference between this concept has no edges to where I want to go vs. this concept isn't even recognized? Maybe that's a good question for Kevin et al.: can one ask BTE: do you know about these concepts?

> I guess I would vote that we don't throw an error if some of the curies in the list don't exist in the KP being used - instead, if it's KG1/KG2, we could issue a warning, but for BTE I don't think there's anything we could do.

I'm thinking an error might be good unless the user explictly asks to press ahead. Because if not all curies are found, then the answer received is not really the answer to the question asked. Consider that I want to know which pathways are brought to mind by 5 proteins. If only 2 proteins exist in the KP, then the answer I get is not going to be the answer I asked, really. Maybe I'll just notice that there are only two proteins in my answer? hmm. I don't know.

**Comment by amykglen** [comment]
Ok, I can certainly make these changes (and have asked Kevin to confirm whether we can ask BTE if it knows about certain curies). But I guess I'm not clear on why this is useful... when is it helpful to have a knowledge graph containing only nodes matching query graph nodes that have curies specified, when no qedges were fulfilled?

This is more the kind of situation for which (I thought) we added `continue_if_no_results=true` for - to allow expanding the same edge twice, using different KPs. So that you can get answers from both, and not error out even if one of the KPs doesn't have answers for this edge:
```
add_qnode(id=n00, curie=CHEMBL.COMPOUND:CHEMBL521)
add_qnode(id=n01, type=protein)
add_qedge(id=e00, source_id=n00, target_id=n01)
expand(edge_id=e00, kp=ARAX/KG1, continue_if_no_results=true)
expand(edge_id=e00, kp=ARAX/KG2, continue_if_no_results=true)
```

And going back to the [original issue reported](https://github.com/RTXteam/RTX/issues/774#issue-625230279) - I'm of the opinion that `resultify` is already behaving as it should. I thought that every `result` is supposed to match the structure of the `query_graph`? So if any of the qnodes/qedges are unfulfilled, resultify should return 0 results.

**Comment by edeutsch** [comment]
Well, the issue arose from trying to use DSL to compute the NGD between two entities that aren't otherwise connected. So in the original example, even though the expand to KG1 failed to find any edges, the subsequent overlay() could create an NGD edge in both the KG and the QG. And since there is an NGD edge in the QG (added by overlay), I thought resultify() should be able to create results[]. But perhaps resultify() has special code to ignore the "informational" edges?

I don't know, I don't feel strongly about it. It seemed like interesting possible functionality, but maybe we are trying to twist a simple design beyond where it should be.

**Comment by dkoslicki** [comment]
Note from mini-hackathon:
```
add_qnode(name=acetaminophen, id=n1)
add_qnode(name=scabies, id=n2)
expand(kp=ARAX/KG2,continue_if_no_results=True)
overlay(action=compute_ngd, virtual_edge_type=NGD, source_qnode_id=n1, target_qnode_id=n2)
resultify()
```
works.

**Comment by edeutsch** [comment]
and that makes it seem that the current design is correct. The original DSL was flawed.

**Comment by dkoslicki** [comment]
Design decision: all QG edges must have at least representative in the KG, otherwise, no answers.
