### ISSUE TITLE
ncbitaxon in KG2?  Investigate number and diversity of "organism taxon" nodes in the new KG2 build

### ISSUE THREAD

**Issue by dkoslicki** [RTXteam/RTX#854]
**Motivation**: It would be nice to be able to facilitate the diagnosis of causative pathogens in sick patients via metagenomic data + EHR/symptoms lists. This is a topic that was part of a current [CAMI challenge](https://data.cami-challenge.org/cami2). See the "Clinical pathogen detection" section.

Insider info says that no method can currently automate clinical pathogen detection given a taxonomic profile and a list of symptoms. We have plenty of symptoms in KG2, plus diseases, and other resources (like [PATRIC](https://www.patricbrc.org/)) to connect microorganisms to diseases. All we are missing is microorganisms in KG2 (as reported by @chunyuma).

**Proposal:**
I propose that we ETL the [NCBI taxdump](https://ftp.ncbi.nih.gov/pub/taxonomy/) to incorporate this taxonomy/ontology into KG2 to fill this gap.

**Action items:**
- [ ] @chunyuma to coordinate with @saramsey to see how best to format the NCBI taxdump to ETL into KG2 to create nodes corresponding to taxa.
- [ ] @chunyuma to do the same to create edges that connect between certain taxID's (basically CURIES) and diseases by using PATRIC (and potentially other resources).
- [ ] @chunyuma to explore how to utilize [Metalign](https://github.com/nlapier2/Metalign) to facilitate clinical pathogen detection.

**Comment by chunyuma** [comment]
Thanks @saramsey, I just used NCBI organismal classification and it does help to map the microorganism in KG2 even though it is not straightforward. 

@dkoslicki, KG2 does have microorganism but we just can't use taxon id to map them in KG2. Instead, we need to use the key word of microorganism name to map them. For example, based on the taxon id `643561`, we can map it to `Acidovorax avenae subsp. avenae ATCC 19860` by using [NCBI organismal classification](http://www.ontobee.org/ontology/NCBITaxon?iri=http://purl.obolibrary.org/obo/NCBITaxon_643561). And then we need to use `Acidovorax avenae` as keyword to map it in KG2 by using cypher query `MATCH (n:organism_taxon) where n.name contains 'Acidovorax avenae' RETURN n`. The problem for this is that it might not be quite exact. 

But the good new is that KG2 has already had the connection to disease. It even has more connection information than PATRIC. For example, in PATRIC, `Achromobacter` is only associated with `cystic fibrosis`.

![Screen Shot 2020-07-01 at 6 15 13 PM](https://user-images.githubusercontent.com/20031672/86296530-fe255680-bbc6-11ea-8fe4-6a30e59f7bf7.png)

However, in KG2, this microorganism is associated with multiple diseases which also include `cystic fibrosis`.

![Screen Shot 2020-07-01 at 6 19 03 PM](https://user-images.githubusercontent.com/20031672/86296687-66743800-bbc7-11ea-8321-b96c53cae434.png)

So, this allows us to do clinical pathogen detection. Perhaps we can also use GNN to predict the probability.

**Comment by saramsey** [comment]
Hi @dkoslicki  and @chunyuma thank you for bringing this issue to my attention. 

Based on this page
https://github.com/obophenotype/ncbitaxon/blob/master/subsets/README.md

I think it is reasonable to use the `taxslim` ontology. This avoids the practical issue that the full NCBI taxonomy ontology is absolutely massive (1.6 GB) and would probably take a *long* time to parse using `ontobio` (which in our build system is configured to use `owltools` to parse OWL files).

Some empirical testing suggests that we have a plethora of pathogenic microbe friends in `taxslim.owl`:
```
grep -i salmonella taxslim.owl  | wc -l
244
```
```
grep -i burkholderia taxslim.owl | wc -l
226
```
```
grep -i staphylococcus taxslim.owl | wc -l
192
```
```
grep -i klebsiella taxslim.owl | wc -l
42
```
```
grep -i escherichia taxslim.owl | wc -l
223
```
```
grep -i legionella taxslim.owl | wc -l
59
```
```
grep -i listeria taxslim.owl | wc -l
66
```
```
grep -i haemophilus taxslim.owl | wc -l
78
```
```
grep -i campylobacter taxslim.owl | wc -l
82
```
```
grep -i mycobacterium taxslim.owl | wc -l
257
```
```
grep -i chlamydia taxslim.owl | wc -l
114
```
```
grep -i clostridium taxslim.owl | wc -l
623
```
```
grep -i vibrio taxslim.owl | wc -l
593
```
```
grep -i spirochaetes taxslim.owl | wc -l
3
```
```
grep -i enterococcus taxslim.owl | wc -l
225
```
and so on and so forth.  If you like, you can test a few more taxa from this page:http://textbookofbacteriology.net/medical.html

but speaking for myself, based on the above empirical tests, I am reasonably satisfied that `taxslim` contains the "usual suspects" of human microbial bacterial pathogens (I didn't look into common animal pathogens that do no infect humans).

Can @chunyuma please contact Chris Mungall and Jim Balhoff to inquire about how up-to-date `taxslim.owl` on OBO Foundry is? I can't tell from the OBO Foundry web page for this ontology, and the link to their Jenkins build system seems to be not working. 

For your reference, the link to the `taxslim.owl` file on OBO Foundry is here:
http://www.obofoundry.org/ontology/ncbitaxon.html

If you could please respond here (in this issue) with what you hear back from Chris & Chris, I would appreciate it.  Thanks.

**Comment by saramsey** [comment]
Just to be clear, `taxslim.owl` is currently in the KG2 build system and will remain so unless we can find a more suitable/efficient means to ETL NCBI taxa.

**Comment by chunyuma** [comment]
Thanks @saramsey, sure. I will contact Chris Mungall and Jim Balhoff to inquire about what the up-to-date taxslim.owl on OBO Foundry is.

**Comment by saramsey** [comment]
OK, it seems that your example, `Acidovorax avenae subsp. avenae ATCC 19860`, is not in `taxslim.owl`. You might also ask Chris & Jim what the difference between `taxslim` and `ncbitaxon` is.

**Comment by chunyuma** [comment]
@saramsey, they mentioned this on [here](https://github.com/obophenotype/ncbitaxon/blob/master/subsets/README.md) that the `taxslim` is the NCBITaxon Ontology subsets which is intended to cover:

- Anything used in a taxon constraint in an ontology
- All UniProt Reference Proteomes
- Any taxon that has a non-IEA annotation in GO

But I think we are not necessary to use `ncbitaxon` stored in KG2 because I found that many microorganisms in KG2 with `ncbitaxon` ids also have corresponding `cui` identifiers. 

Under the `organism_taxon` category in KG2, the ids have different prefixes:

prefix | count
-- | --
"CHEMBL.TARGET" | 2137
"CUI" | 69228
"DDANAT" | 1
"EFO" | 416
"EO" | 2
"NCBITaxon" | 17144
"NCIT" | 2991

I found that the microorganisms with `cui` identifiers normally have connection to the diseases in KG2 but `ncbitaxon` ids don't have. For example, 

```
MATCH (n:organism_taxon) where n.name contains 'Rhodococcus' with split(n.id,":")[0] as prefix return distinct prefix, count(*) as count order by prefix
```
prefix | count
-- | --
"CHEMBL.TARGET" | 5
"CUI" | 32
"NCBITaxon" | 14
"NCIT" | 2

```
MATCH (n:organism_taxon)-[]-(n1:disease) where n.name contains 'Rhodococcus' with split(n.id,":")[0] as prefix return distinct prefix, count(*) as count order by prefix
```
prefix | count
-- | --
"CUI" | 125

I also found that we could convert `cui` identifier to taxon id by using this website (http://linkedlifedata.com/). I will see how many overlap is between `cui` and `ncbitaxon`. Perhaps we can directly use `cui` identifier to match microorganisms if there are many overlaps. I will also see how many microorganisms in KG2 can match to [NCBI taxdump](https://ftp.ncbi.nih.gov/pub/taxonomy/)

**Comment by chunyuma** [comment]
@saramsey and @dkoslicki, here is the venn diagram for `cui` identifier in kG2, `ncbitaxon` identifier in KG2, species only taxon ids in NCBI taxdump and all taxon ides in NCBI taxdump.

![venn_result27034](https://user-images.githubusercontent.com/20031672/86425879-4ec6ad80-bcb4-11ea-8b1a-8dc71536d477.png)

There are 23167 `cui` identifiers or `ncbitaxon` identifiers that can map to NCBI taxdump. The reason that some taxon ids which are not in NCBI taxdump is because some taxon ids are merged into other taxon ids in NCBI taxdump. For example, the taxon id `11161` in the overlap area between `cui` and `ncbitaxon` has been merged into taxid `1979165` on April 12, 2017.

**Comment by saramsey** [comment]
OK that sounds good. One thing to note about linkedlifedata -- their last build timestamp was in 2013, so I have some concerns that the mappings may be kind of old. Caution is warranted.

> But I think we are not necessary to use ncbitaxon stored in KG2 because I found that many microorganisms in KG2 with ncbitaxon ids also have corresponding cui identifiers.

This is good, because `ncbitaxon` is so huge that parsing its OWL representation would be extremely slow. I guess I could parse it once and save the object representation as a pickle file, but I suspect it would still probably use a *lot* of RAM.

**Comment by saramsey** [comment]
I think you might be able to do this, at least to a fairly high taxonomic level, using `taxslim` as well as the CUI concepts that we already have in KG2. I will leave this issue open to remind me to compute the number of taxons (nodes with biolink category "organism taxon" or whatever it is supposed to be in biolink) in the new build of KG2.

**Comment by saramsey** [comment]
The taxdump zip file looks *much* smaller than `ncbitaxon.owl`, for whatever reason. So a custom ETL script for `taxdump`, if it comes to that, would probably be preferable over trying to ETL `ncbitaxon.owl`.

**Comment by dkoslicki** [comment]
@saramsey the downside of ETL-ing the NCBI `taxdump` is that it _only_ contains NCBI taxID's (and a tad more node information), while the `ncbitaxon.owl` appears to also have connections to diseases. @chunyuma , correct me if I am wrong, but this is what you found with the current (not new) KG2: using the owl file gives CUI's that allow for connections to other bioentities (like diseases and phenotypes) as it currently stands in KG2, while ETL-ing the NCBI taxdump would require finding yet **another** KS to connect these taxID nodes to diseases and phenotypes

**Comment by saramsey** [comment]
Ah, I see. 

Well, for starters (if DMK agrees): @chunyuma would you be willing to try:
1. downloading `ncbitaxon.owl` into `kg2dev.rtx.ai`
2. see if you can load `ncbitaxon.owl` into python and save as a pickle file, as follows:
```
ssh ubuntu@kg2dev.rtx.ai
cd /home/ubuntu/kg2-build
wget http://purl.obolibrary.org/obo/ncbitaxon.owl
source ~/kg2-venv/bin/activate
python
>> import ontobio, pickle
>> ont_return = ontobio.ontol_factory.OntologyFactory().create("ncbitaxon.owl", ignore_cache=True)
>> pickle.dump(ont_return, open("ncbitaxon.pickle", 'w'))
```
then can you report back in this issue on :
1. the size of the pickle file on disk
2. the amount of RAM used to hold the ontology (`ont_return`) in memory
3. the amount of time required to load the pickle file from disk

Thanks.

**Comment by chunyuma** [comment]
@saramsey, I followed your instruction above but got some errors form `ontobio`

Here is the error message:
```
>>> ont_return = ontobio.ontol_factory.OntologyFactory().create("ncbitaxon.owl", ignore_cache=True)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ubuntu/kg2-venv/lib/python3.6/site-packages/ontobio/ontol_factory.py", line 76, in create
    return create_ontology(handle, **args)
  File "/home/ubuntu/kg2-venv/lib/python3.6/site-packages/cachier/core.py", line 129, in func_wrapper
    return func(*args, **kwds)
  File "/home/ubuntu/kg2-venv/lib/python3.6/site-packages/ontobio/ontol_factory.py", line 93, in create_ontology
    ont = translate_file_to_ontology(handle, **args)
  File "/home/ubuntu/kg2-venv/lib/python3.6/site-packages/ontobio/ontol_factory.py", line 174, in translate_file_to_ontology
    g = obograph_util.convert_json_file(fn, **args)
  File "/home/ubuntu/kg2-venv/lib/python3.6/site-packages/ontobio/obograph_util.py", line 116, in convert_json_file
    return convert_json_object(json.loads(jsonstr), **args)
  File "/usr/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

```

**Comment by chunyuma** [comment]
@saramsey, to answer your questions:

> the size of the pickle file on disk

1.5G
> the amount of RAM used to hold the ontology (ont_return) in memory

around 11 GB
> the amount of time required to load the pickle file from disk

around 96 seconds

**Comment by saramsey** [comment]
> @saramsey, to answer your questions:
> 
> > the size of the pickle file on disk
> 
> 1.5G
> 
> > the amount of RAM used to hold the ontology (ont_return) in memory
> 
> around 11 GB
> 
> > the amount of time required to load the pickle file from disk
> 
> around 96 seconds

OK, thanks @chunyuma . Hmm, this might just be doable as an ETL into KG2, although the 11 GB of RAM consumption is a slightly worrysome (hopefully some edges will get dropped and thus there will not be a net 11 GB of RAM consumption in the most memory-intensive downstream steps in the KG2 build process). You could try doing a KG2 build on `kg2dev` but substituting `ncbitaxon.owl` for `taxslim.owl` in `ont-load-inventory.yaml` (IMPORTANT: make **sure** to use the code in the `kg2-curie-refactoring` branch). Please announce on the team (local) slack channel that you are using `kg2dev` for this purpose, since that instance has sometimes various other people using it.

**Comment by saramsey** [comment]
OK in the new KG2 database, http://kg2endpoint.rtx.ai:7474, here are the statistics that I see:

<img width="554" alt="Screen Shot 2020-07-23 at 4 20 15 PM" src="https://user-images.githubusercontent.com/5562107/88347774-6c5dc480-cd00-11ea-937d-de1a316ab21a.png">

**Comment by saramsey** [comment]
Hi @chunyuma since I have like 25 issues assigned to me, I'm going to deassign myself from this issue in order to declutter my assigned-issues screen. But please feel free to reach out if you need anything.

**Comment by chunyuma** [comment]
> Hi @chunyuma since I have like 25 issues assigned to me, I'm going to deassign myself from this issue in order to declutter my assigned-issues screen. But please feel free to reach out if you need anything.

No problem, Steve! Thanks for your help!

**Comment by saramsey** [comment]
Hi @chunyuma is there anything else actionable in this issue, for KG2 development?

**Comment by chunyuma** [comment]
Hi @saramsey, thanks for your asking. Based on my previous statistics (Please see the screenshot below), it seems like the 'new' kg2 has sufficient curies matching to taxon ids used in NCBI taxonomy database (based on the data updated on 07/30/2020) which directly or indirectly connect to disease. So we can start from data provided by the 'new' kg2 to do some exploration for our research. No more further action is needed for KG2 development. Thank you!

<img width="779" alt="Screen Shot 2020-08-20 at 9 19 05 PM" src="https://user-images.githubusercontent.com/20031672/90841912-f616a700-e32b-11ea-93a2-183e42a54bf9.png">

**Comment by saramsey** [comment]
Thanks @chunyuma
