### ISSUE TITLE
Add faster/more targeted method for getting preferred curie/name/type with NodeSynonymizer

### ISSUE THREAD

**Issue by amykglen** [RTXteam/RTX#911]
Wondering if it'd be possible to add a method to `NodeSynonymizer` that's faster/more targeted for getting the preferred curie/name/type for an input curie? I currently still use `get_normalizer_results()` to achieve this in `expand`, but it runs a bit slow.

Ideally it would accept a curie/list of curies from KG1/KG2 or anywhere, and then return the 'ARAX preferred' curie, name, and type(s). (I think we need an 'ARAX preferred' curie rather than `kg2_best_curie`, `kg1_best_curie`, etc. because otherwise the deduplication doesn't work across KPs. a given curie always needs to 'canonicalize' to the same preferred curie, regardless of source... right now I just always use `kg2_best_curie` which more or less achieves this for us, I think..)

ideally something like the following would be output for each input curie:

* `preferred_curie`: ARAX preferred curie (e.g., `MONDO:0015681`)
* `preferred_name`: ARAX preferred name (e.g., `childhood disintegrative disorder`)
* `types`: all the node types for this 'synonym group' (e.g., `['disease', 'unknown_category', 'phenotypic_feature', 'named_thing']`)
  * note: currently I've been assigning the full type list for the synonym group to each 'canonicalized' node, which seemed to me to make the most sense out of the different options, but could take a different approach if others disagree..

**Comment by edeutsch** [comment]
yes, certainly possible, and I'll do it.

Regarding this:
>Ideally it would accept a curie/list of curies from KG1/KG2 or anywhere, and then return the 'ARAX preferred' curie, name, and type(s). (I think we need an 'ARAX preferred' curie rather than kg2_best_curie, kg1_best_curie, etc. because otherwise the deduplication doesn't work across KPs. a given curie always needs to 'canonicalize' to the same preferred curie, regardless of source... right now I just always use kg2_best_curie which more or less achieves this for us, I think..)

I hesitated to create an "ARAX preferred curie" because I wasn't sure what we wanted to use for this. The logic for providing everything is so that you could choose and guide what we want to do. At the moment, you get:
```
      "SRI_normalizer_curie": "MONDO:0001384",
      "SRI_normalizer_name": "myopia (disease)",
      "SRI_normalizer_type": "disease",
      "identifier": "DOID:11830",
      "kg1_best_curie": "DOID:11830",
      "kg2_best_curie": "MONDO:0001384",
      "label": "myopia",
      "type": "disease"
```
I give you what the SRI normalizer says (it doesn't always have information)
I give you what the kg1_best_curie and kg2_best_curie are. Those are always fixed irrespective of which kg_name you selected. And then identifier and label and type are based on the kg_name that you selected. so in the example above, since KG1 was selected, the identifier is an actual node in KG1. identifier would have been the MONDO id if KG2 were selected.

I think it's true that kg2_best_curie will never be empty and is probably the closest thing to 'ARAX preferred', so I think you're using it right. I'm happy to add an "ARAX preferred curie", but what do you think the logic for selecting that should be? I did not add it because I don't know what would be best here. Can we define what the rules should be?

Note that SRI normalizer always picks a gene in the clique for its "canonical" identifier. But I override that for KG2 with a protein identifier if I can because we are more protein centric.

**Comment by amykglen** [comment]
ok, that's great info, thanks. if `kg2_best_curie` is never blank, then I think that's already what I want.

my thinking for an 'ARAX preferred' curie was mainly for if there was a situation where a curie had an `SRI_normalizer_curie` and not a `kg2_best_curie`, then perhaps the 'ARAX preferred' should be the `SRI_normalizer_curie` in that case. but since you said `kg2_best_curie` should never be empty, that doesn't apply...

other than that I suppose it's just a minor terminology complaint. :) (since it sounds a little bit weird to be using something called the 'kg2_best_curie' for nodes returned from BTE and from KG1.) but that's very minor.

**Comment by edeutsch** [comment]
I just verified that kg2_best_curie is never blank or NULL. But it's possible that could change in the future.
I could add a column 'preferred_curie' or 'canonical_curie' that we can apply some rules to on how it is set.
I won't do it yet, but will plan on it for the next rebuild?

**Comment by amykglen** [comment]
ok, great. sounds good to me!

**Comment by amykglen** [comment]
closing - this was implemented quite a while ago and works well
