### ISSUE TITLE
update KG2 to UMLS 2020AA

### ISSUE THREAD

**Issue by saramsey** [RTXteam/RTX#931]

**Comment by saramsey** [comment]
see also #908

**Comment by saramsey** [comment]
Latest version looks to be 2020AA:
https://www.nlm.nih.gov/research/umls/licensedcontent/umlsknowledgesources.html

Maybe just download the Metathesaurus files, and skip running MetamorphoSys?
<img width="1287" alt="Screen Shot 2020-07-16 at 1 21 40 PM" src="https://user-images.githubusercontent.com/5562107/87718821-4caa2780-c767-11ea-9920-d3a42bb7e9ea.png">

**Comment by saramsey** [comment]
@ericawood see reply in slack

**Comment by ericawood** [comment]
Hi @saramsey, commits 9f6a78f and 1a5bef0 address this issue according to my testing. 1a5bef0 adds a dependency into `setup-kg2-build.sh` that will need to be installed on kg2dev and kg2steve. 9f6a78f adds all of the changes to `extract-umls.sh`. A couple notes:
1. Almost all of this code is tested with the exception of the `umls_dir` being `umls2020`. In my testing, I had `extract-umls.sh` use a different `master-config.shinc` that was identical with the exception of the line regarding `umls_dir`.
2. The other piece of this code that has changed since testing is that between lines 74 and 75, there used to be a `pwd`. I doubt this will cause problems, but I thought that it would be best to report it anyway.
3. This version of UMLS adds approximately 1.5 million edges and 900,000 nodes to `kg2-ont.json` in comparison to the version on `kg2dev`.

**Comment by saramsey** [comment]
Nice, shall we do a full build including UMLS 2020AA?  I guess that build version will be KG2.3.2.

**Comment by kvarforl** [comment]
@saramsey  I'm unsure how to verify this fix for KG2.3.5. Could you document steps for me to follow here?

**Comment by ericawood** [comment]
@kvarforl 
To verify this fix, please check that the UMLS directory on the build instance is labeled UMLS2020AA (or something similar with 2020AA in it). If so, this issue is fixed!

**Comment by saramsey** [comment]
Thank you, @ericawood.  Hope you are doing well.
