### ISSUE TITLE
Use COHD as an expand-er

### ISSUE THREAD

**Issue by dkoslicki** [RTXteam/RTX#974]
Pulling this out from #942 so it's easier to track (see #942 for more details).

**Comment by chunyuma** [comment]
@dkoslicki, what is difference between this issue and #875? They seems like a same issue for me.

**Comment by dkoslicki** [comment]
#875 is to get the local COHD database up and running. This issue is to incorporate it into `expand(...,kp=COHD)` as some extra work will need to be done to the `expand` code to know to hit the local COHD database, create the edges, populate the KG, etc.

**Comment by dkoslicki** [comment]
Basic idea:
`expand(qedge_id=xyz, kp=COHD, method=A)` where `A` is one of paired_concept_freq, observed_expected_ratio, chi_square.

Then decide on a thresholding method based on statistics of the distributions of these values to then decide which ones we want to make a new edge for.

**Comment by amykglen** [comment]
@chunyuma - for adding this to `expand`, you could create a new class called something like `COHDQuerier` modeled after [this one](https://github.com/RTXteam/RTX/blob/master/code/ARAX/ARAXQuery/Expand/kg_querier.py). the important part is just that it has a method called `answer_one_hop_query()` that has the same kind of input/output as seen [here](https://github.com/RTXteam/RTX/blob/master/code/ARAX/ARAXQuery/Expand/kg_querier.py#L31-L40).

then some relatively minor additions to the [main Expander file](https://github.com/RTXteam/RTX/blob/master/code/ARAX/ARAXQuery/ARAX_expander.py) will be needed to plug in your new class/file ([here](https://github.com/RTXteam/RTX/blob/master/code/ARAX/ARAXQuery/ARAX_expander.py#L177-L189)). and you'll of course need to adjust the allowed/default parameters in [this area](https://github.com/RTXteam/RTX/blob/master/code/ARAX/ARAXQuery/ARAX_expander.py#L25-L73) in order to add the new `method` parameter.

let me know if you have any questions!

**Comment by chunyuma** [comment]
Thanks @amykglen, I will take a look.

**Comment by chunyuma** [comment]
I have three questions regarding `expand(qedge_id=xyz, kp=COHD, method=A)`

1. How to define the node properties?  e.g.
{'description': 'A monocarboxylic acid that is a propionic acid derivative '
                'having a 4,5-diphenyl-1,3-oxazol-2-yl substituent at position '
                '3. It is  non-steroidal anti-inflammatory drug commonly used '
                'to relieve the pain and inflammatory responses associated '
                'with osteoarthritis and rheumatoid arthritis.',
 'id': 'CHEMBL.COMPOUND:CHEMBL1071',
 'name': 'oxaprozin',
 'node_attributes': [],
 'qnode_ids': None,
 'symbol': None,
 'type': ['chemical_substance'],
 'uri': 'https://www.ebi.ac.uk/chembl/compound/inspect/CHEMBL1071'}

2. How to define the edge properties? e.g.
{'confidence': None,
 'defined_datetime': None,
 'edge_attributes': None,
 'evidence_type': None,
 'id': 'KG1:3036175',
 'is_defined_by': 'ARAX/KG1',
 'negated': None,
 'provided_by': 'MyChem.info',
 'publications': None,
 'qedge_ids': None,
 'qualifiers': None,
 'relation': 'contraindicated_for',
 'source_id': 'CHEMBL.COMPOUND:CHEMBL896',
 'target_id': 'HP:0001658',
 'type': 'contraindicated_for',
 'weight': None}

3. For the pair which has multiple OMOP id pairs, do we only consider the `best` one for `chi_square` and `observed_expected_ratio` and the accumulative frequency for `paired_concept_frequency` like what we did in `overlay_clinical_info.py`?

**Comment by amykglen** [comment]
re: 1, I think that just the `id`, `name`, and `type` need to be filled out on nodes `COHDQuerier` adds to the KG.
* for `name`, you could use the `preferred_name`, as provided by `NodeSynonymizer.get_canonical_curies()`
* for `type` - do you know a type for each curie based on your lookup database? (not sure if curies in there are organized by whether they're a drug vs. disease or whatever) if not, one idea is to use the `preferred_type`, as provided by `NodeSynonymizer.get_canonical_curies()`

note that the main `ARAX_expander.py` may override some of these values (it will override the `id` with the canonicalized curie as long as `synonym_handling` is not set to `add_all`, and it will override the `type` to make it match the QG where possible.) but if you use the above values in `COHDQuerier`, all should work fine.

re: 2, I think that just the `id`, `source_id`, `target_id`, `type`, `provided_by`, and `is_defined_by` need to be filled out on edges COHDQuerier adds to the KG.
* for `type`, maybe you could use the same kinds of types that are used for virtual COHD edges already?
* for `provided_by` and `is_defined_by`, I think a decision will have to be made about what values to use. maybe `provided_by` should be `COHD`, and `is_defined_by` should be `ARAX`?

also note that because `COHDQuerier` builds and outputs a knowledge graph that's organized by qnode/qedge IDs (of [this class](https://github.com/RTXteam/RTX/blob/master/code/ARAX/ARAXQuery/Expand/expand_utilities.py#L24-#L37)), you don't need to fill out the `qnode_ids` and `qedge_ids` properties on nodes/edges. the main `ARAX_expander.py` takes care of that at the very end.

**Comment by chunyuma** [comment]
To determine what thresholds we could use to get the reliable edges expanded by COHD, I did the following investigation.

For each curie, I pulled out all OMOP concept id pairs associated with this curie in the 5-year hierarchical dataset in COHD database. Then I used the `paired_concept_freq`, `observed_expected_ratio`, `chi_square` of all these OMOP id pairs to draw the diagrams of their distribution.

First of all, I randomly picked 10 curies from each of 4 curie type (`disease`, `phenotypic_feature`, `chemical_substance` and `drug`) to draw the distribution diagram and 0.99 quantile threshold lines for each of three methods.

__Note__: The curies used to draw the below distribution should have >3 OMOP concept id pairs after excluding the extreme values (e.g. 0 for `paired_concept_freq`, `observed_expected_ratio` and `chi_square p-value`)

 #### paired_concept_freq
<img width="952" alt="Screen Shot 2020-08-04 at 1 36 22 PM" src="https://user-images.githubusercontent.com/20031672/89325932-83cd7380-d657-11ea-8f4a-8bb20d17d017.png">

 #### observed_expected_ratio
<img width="961" alt="Screen Shot 2020-08-04 at 1 43 31 PM" src="https://user-images.githubusercontent.com/20031672/89326594-88465c00-d658-11ea-9d76-8248fd96809b.png">

 #### chi_square
<img width="959" alt="Screen Shot 2020-08-04 at 1 46 29 PM" src="https://user-images.githubusercontent.com/20031672/89326820-eecb7a00-d658-11ea-9c9e-e9e1400472f6.png">

Then we expect to use 0.99 quantiles as thresholds, so I tried to check the distribution of 0.99 quantile and also calculate their median and standard deviation.

 #### paired_concept_freq
<img width="944" alt="Screen Shot 2020-08-04 at 1 51 08 PM" src="https://user-images.githubusercontent.com/20031672/89327219-934dbc00-d659-11ea-8a3f-9e8e34d98f45.png">

#### observed_expected_ratio
<img width="937" alt="Screen Shot 2020-08-04 at 1 51 42 PM" src="https://user-images.githubusercontent.com/20031672/89327275-aeb8c700-d659-11ea-8c51-081fcfba4a00.png">

#### chi_square
<img width="947" alt="Screen Shot 2020-08-04 at 1 52 01 PM" src="https://user-images.githubusercontent.com/20031672/89327357-d0b24980-d659-11ea-90e7-1946ac6bdb05.png">

**Comment by chunyuma** [comment]
Update: COHD was added as one of kps into `Expander`. It is ready to be tested in `issue974` branch.

Two new parameters `COHD_method` and `COHD_method_threshold` were added to `Expander`.

As a brief tutorial, here are some example DSLs:
```
 add_qnode(id=n00, curie=DOID:5844, type=disease)
 add_qnode(id=n01, type=chemical_substance, is_set=true)
 add_qedge(id=e00, source_id=n00, target_id=n01)
 expand(edge_id=e00, kp=COHD, COHD_method=observed_expected_ratio, COHD_method_threshold=3.5)",
 return(message=true, store=false)
```

```
 add_qnode(id=n00, curie=DOID:5844, type=disease)
 add_qnode(id=n01, type=chemical_substance, is_set=true)
 add_qedge(id=e00, source_id=n00, target_id=n01)
 expand(edge_id=e00, kp=COHD, COHD_method=paired_concept_freq)",
 return(message=true, store=false)
```

```
 add_qnode(id=n00, curie=DOID:5844, type=disease)
 add_qnode(id=n01, type=chemical_substance, is_set=true)
 add_qedge(id=e00, source_id=n00, target_id=n01)
 expand(edge_id=e00, kp=COHD, COHD_method=chi_square)",
 return(message=true, store=false)
```

**Comment by dkoslicki** [comment]
That's great @chunyuma! Looking forward to trying it our tomorrow. 

For the defaults (eg. ` expand(edge_id=e00, kp=COHD, COHD_method=chi_square)`) did you decide to go with the median of the 99-quantile distribution, or the min?

**Comment by chunyuma** [comment]
@dkoslicki, it goes with median of 0.99 quantile of distribution. 

__paired_concept_freq__: 0.000431
__ln(observed expected ratio)__:4.44
__chi square pvalue__: 1.6311e-271

The message info contains the threshold information. You can depend on that to adjust an appropriate threshold if no path is returned.

**Comment by chunyuma** [comment]
Update: Instead of using the fixed threshold for expanding all edges, the updated version allows to set the percentile of distribution of a curie as threshold for each preferred curie. The default is 99 which means 99 percentile of distribution of a curie with certain method (`paired_concept_freq `, `ln_ratio`, `chi square pvalue`). 

The calculation of percentile excludes the extreme value eg. 0 for `paired_concept_freq ` and `chi square pvalue`; -inf for `ln_ratio`. And three conditions were considered:

1. if `(n: CUI:xxxx)-[]-(m:DID:xxx)`, the percentile was calculated from the `maximum` (pvalue) or `minimum ` (frequency or ln_ratio) of the curies in the two ends of edge.
2. if `(n: CUI:xxxx)-[]-(m: chemical_substance)`, the percentile was calculated from the distribution of `CUI:xxxx`.
3. if `(n: drug)-[]-(m:DID:xxx)`, the percentile was calculated from the distribution of `DID:xxx`.

Example DSL:
```
add_qnode(id=n00, curie=DOID:5844, type=disease
add_qnode(id=n01, type=chemical_substance, is_set=true)
add_qedge(id=e00, source_id=n00, target_id=n01)
expand(edge_id=e00, kp=COHD, COHD_method=chi_square, COHD_method_percentile=99)
return(message=true, store=false)
```

Based on the test I did, the speed is still fast and should be acceptable.

@dkoslicki and @amykglen , if you have time, could you please help do more tests? Thank you!

Also, if there is no problem, I think it should be ready to be merged into `master` branch.

**Comment by amykglen** [comment]
nice! @chunyuma - feel free to add test(s) for this to `test_ARAX_expand.py` (if you follow suit with the other tests in there and use `_run_query_and_do_standard_testing()`, some checks will automatically be run on the nodes/edges in the KG - could catch any potential issues)

**Comment by chunyuma** [comment]
Thanks @amykglen, I will do it later.

**Comment by chunyuma** [comment]
This issue has already been merged to `master` branch. 

One thing might need to be paid attention when someone uses `COHD` in `expand()`. Since COHD database is constructed based on only `drug`, `disease`, `chemical_substance` and `phenotypic_feature` of canonicalized kg2, it might throw a warning or even an error if the query graph tries to expand the edge for a qnode which is not one of the above types.  If a list of curies are queried in a `qnode()` and some of them belong to one of above four types and have omop id, the program might just throw a warning for the curies which can't find a match in `COHD` database. If no curies queried can find a match in `COHD` database, then an error will be threw out. 

@dkoslicki, is it ok to close this issue?

**Comment by dkoslicki** [comment]
Sorry, this slipped through the email cracks. It’s fine to merge to master (as has already been done). Let’s make sure that any errors and/or warnings (warning are preferred as empty graphs are ok, as long as the warnings clearly tell why this is the case), describe that requirement about node type.
