### ISSUE TITLE
FastNGD as an expand-er

### ISSUE THREAD

**Issue by dkoslicki** [RTXteam/RTX#975]
Pulling this out from #942 so it's easier to track (see #942 for more details).

**Comment by amykglen** [comment]
an update on where this issue is at:

- an initial version of `expand(kp=NGD)` is implemented and working in the `ultrafast-ngd` branch
- can test with `pytest -v test_ARAX_expand.py -k test_ngd_expand`
- still to do: determine the threshold to use for ngd values in a more sophisticated way (I just hardcoded it to 0.5 to start so I had something while developing)

**Comment by dkoslicki** [comment]
@amykglen Just tested the following on master, and it appears to be working. Ok to close this issue?
```
add_qnode(key=n00,id=UniProtKB:P14136, category=biolink:Protein)
add_qnode(key=n01)
add_qedge(subject=n00, object=n01, key=e00) 
expand(kp=NGD,continue_if_no_results=false,use_synonyms=true)
resultify()
```

**Comment by amykglen** [comment]
nice - yep, sounds ok to me to close. :) though beware that this isn't a totally "comprehensive" NGD expansion, in that it finds connected nodes using KG2, computes NGD for all of those, and then returns only those above 0.5. (so it's limited to whatever connections are in KG2...)
