### ISSUE TITLE
Antonyms for edge types? 

### ISSUE THREAD

**Issue by dkoslicki** [RTXteam/RTX#979]
Question for @saramsey: Is there a way to identify if two edge types are antonyms in KG2?
eg. I have a result that has a `caused_by` and a `prevented_by` edge connecting them and it would be nice to be able to know these are "antonyms" of each other (or at least, represent some sort of "conflicting information")

![PreventedBy](https://user-images.githubusercontent.com/6362936/88436729-e5c5e780-cdd2-11ea-94a4-c693eea07169.PNG)

![CausedBy](https://user-images.githubusercontent.com/6362936/88436747-f24a4000-cdd2-11ea-9884-2b273417b69d.PNG)

No need to be perfectly accurate: just way way to get a vague indication that "these two edges seem to be presenting conflicting/opposite concepts/types"

**Comment by saramsey** [comment]
It's a good idea. We may need to develop a custom list of these antonym relationships. As there are only 65 biolink predicates that we use, the number of antonym pairs is probably small.

**Comment by saramsey** [comment]
There are now 79 edge types in KG2.3.1:

- subclass_of
- close_match
- related_to
- coexists_with
- physically_interacts_with
- quantifier_qualifier
- has_input
- affects
- produces
- negatively_regulates,_entity_to_entity
- positively_regulates,_entity_to_entity
- derives_into
- part_of
- precedes
- located_in
- occurs_in
- treats
- positively_regulates
- disrupts
- causes
- biomarker_for
- prevents
- interacts_with
- predisposes
- has_attribute
- manifestation_of
- same_as
- has_output
- derives_from
- actively_involved_in
- participates_in
- enables
- regulates,_process_to_process
- positively_regulates,_process_to_process
- negatively_regulates,_process_to_process
- regulates
- negatively_regulates
- expressed_in
- capable_of
- colocalizes_with
- contributes_to
- has_not_completed
- has_completed
- affects_transport_of
- overlaps
- has_part
- lacks_part
- increases_degradation_of
- has_increased_amount
- has_decreased_amount
- affects_localization_of
- has_phenotype
- contraindicated_for
- correlated_with
- has_route
- has_attribute_type
- has_count
- in_taxon
- gene_associated_with_condition
- has_gene_product
- has_molecular_consequence
- increases_metabolic_processing_of
- synonym
- has_unit
- has_quantitative_value
- has_participant
- location_of
- disease_has_basis_in
- model_of
- expresses
- disease_shares_features_of_
- molecularly_interacts_with
- increases_stability_of
- decreases_activity_of
- increases_activity_of
- increases_expression_of
- decreases_expression_of
- directly_interacts_with
- affects_activity_of

We just need someone to audit these to identify antonym pairs.

**Comment by saramsey** [comment]
Hi @kvarforl can you please review these 79 edges to compile a list of antonym pairs?  I think the increase/decrease pairs are arguably listable as antonym pairs. See @dkoslicki if you have questions. Thank you!

**Comment by kvarforl** [comment]
@dkoslicki @saramsey Here is my go at a list of antonym pairs. I tried to err on the side of too many pairs rather than too few, so that you all have the luxury of looking at them and saying "hmmm that doesn't seem quite right" rather than discovering pairs that I missed... hopefully :)

- negatively_regulates,_entity_to_entity, positively_regulates,_entity_to_entity				
- positively_regulates,_process_to_process, negatively_regulates,_process_to_process
- negatively_regulates, positively_regulates				
- has_not_completed, has_completed				
- decreases_activity_of, increases_activity_of				
- increases_expression_of, decreases_expression_of				
- contraindicated_for, treats
- contraindicated_for, prevents				
- predisposes, prevents				
- causes, prevents
- causes, treats				
- has_increased_amount, has_decreased_amount				
- increases_degradation_of, increases_stability_of
- increases_degradation_of, increases_expression_of				
- disrupts, enables				
- negatively_regulates, positively_regulates				
- has_input, has_output
- lacks_part, has_part
- lacks_part, part_of
- subclass_of, derives_into
- derives_from, derives_into
- disrupts, enables

**Comment by saramsey** [comment]
Hi @dkoslicki can we close out this issue?

**Comment by dkoslicki** [comment]
Yes indeed!
