### ISSUE TITLE
Still getting internal server errors

### ISSUE THREAD

**Issue by dkoslicki** [RTXteam/RTX#98]
On http://rtx.ncats.io/:
Q: what drugs target proteins associated with osteoporosis
A: Your question has been interpreted and is restated as follows:
   what drugs target proteins associated with $disease
Please ensure that this is an accurate restatement of the intended question.

{
  "detail": "The server encountered an internal error and was unable to complete your request.  Either the server is overloaded or there is an error in the application.",
  "status": 500,
  "title": "Internal Server Error",
  "type": "about:blank"
}

**Comment by edeutsch** [comment]
Working on it. The reason is that this is coming back from ParseQuestion:
{
  "error_code": "multiple_terms",
  "error_message": "The most similar question I can answer is: what drugs target proteins associated with $disease But I found: \"Multiple terms found for disease: ['OMIM:166710', 'DOID:11476']\"",
  "known_query_type_id": "Q23",
  "original_question": "what drugs target proteins associated with osteoporosis",
  "restated_question": "what drugs target proteins associated with $disease"
}

The output model only allows this:
]Inline Model 1 {
known_query_type_id (string, optional):

RTX identifier for the specific query type ,
message (string, optional):

Response from the translation engine to the user ,
original_question (string, optional):

Original question as it was typed in by the user ,
restated_question (string, optional):

Restatement of the question as understood by the translator ,
terms (Query_terms, optional)
}

So, although I can update my code to be more tolerant of this, I think the best fix is if you return this:

{
  "message": "The most similar question I can answer is: what drugs target proteins associated with $disease But I found: \"Multiple terms found for disease: ['OMIM:166710', 'DOID:11476']\"",
  "original_question": "what drugs target proteins associated with osteoporosis",
  "restated_question": "what drugs target proteins associated with $disease"
}

Current code is thrilled to see a known_query_type_id come back and tries to send that to the reasoner and things go off the rails because there's no terms to go with the known_query_type_id

**Comment by dkoslicki** [comment]
I was under the impression that if there is a non-empty "error_message" then this is treated as an error. I vaguely recall a discussion we had that if I can identify a known_query_type_id, then this should be returned. Is that not the case any more?
Also, I see your suggested fix uses "message" instead of "error_message" and doesn't include "error_code". Was this intentional?

**Comment by edeutsch** [comment]
I also recall a discussion about "if there is a message, then error out". But it appears I failed to implement that. Until now. fixed. oops, wait, I failed again. Current code now checks to make sure there is both a known_query_type_id and a terms element. If there is both, then it continues. If not, it prints message or error_message.

As far as message versus error_message, I don't recall either way. you may be right. But the official API definition has been this for a while:
known_query_type_id (string, optional):RTX identifier for the specific query type ,
message (string, optional):Response from the translation engine to the user ,
original_question (string, optional):Original question as it was typed in by the user ,
restated_question (string, optional):Restatement of the question as understood by the translator ,
terms (Query_terms, optional)

So I would vote for message. There is some notion in my head that it might be useful for return some comments (message) from the QuestionParser even if it succeeded...? So maybe the QuestionParser witholding either of known_query_type_id or terms would be a better indicator of failure. I'm not sure what the best design is.

**Comment by dkoslicki** [comment]
Ok, so how about this for a plan:
No error_code returned (I don't know why we had this to begin with)
"error_message" gets changed to "message"
and your code checks for both known_query_type_id *and* terms to execute.

**Comment by edeutsch** [comment]
perfect. done. and rolled out to production.
I think you need to do a SHIFT+REFRESH at http://rtx.ncats.io/ to make sure you're using the latest JavaScript. Now:

what drugs target proteins associated with osteoporosis

Returns useful response instead of hacking up a hairball.

In this particular case it might be kind to tell the user that they did nothing wrong, that there is some weird duality in the knowledge graph that the reasoner doesn't know what to do with. With bonus points for emailing the developers to fix the KG.

**Comment by dkoslicki** [comment]
Excellent! And yes, the duplicate node issue was noticed in #67. Was there anything I needed to change in [FormatOutput.py](https://github.com/RTXteam/RTX/blob/master/code/reasoningtool/QuestionAnswering/FormatOutput.py) to make the change "error_message"->"message" etc? Or was this handled in ``swagger_server.models.response``?
