### ISSUE TITLE
MESH terms need biolink categories in KG2

### ISSUE THREAD

**Issue by saramsey** [RTXteam/RTX#981]

**Comment by saramsey** [comment]
Fix 8385bd4 may not work until #982 is implemented

**Comment by saramsey** [comment]
Still not fixed. Need #982 

<img width="766" alt="Screen Shot 2020-08-20 at 2 45 04 PM" src="https://user-images.githubusercontent.com/5562107/90828978-cba8f780-e2f3-11ea-83b8-591af9393062.png">

```
match (n) where n.id starts with "MESH:" return n.id, n.category limit 50;
```

**Comment by ericawood** [comment]
Hi @saramsey,
After testing with ce126fd:
```
{
            "category": "biolink:Protein",
            "category_label": "protein",
            "creation_date": null,
            "deprecated": false,
            "description": "UMLS Semantic Type: UMLS_STY:T116",
            "full_name": null,
            "id": "MESH:C000622707",
            "iri": "http://purl.bioontology.org/ontology/MESH/C000622707",
            "name": "peroxin 11A, Arabidopsis",
            "provided_by": "umls_source:MSH",
            "publications": [],
            "replaced_by": null,
            "synonym": [],
            "update_date": "2015"
        }
```

**Comment by kvarforl** [comment]
In KG2.3.5, the issue seems to be fixed.
Some of the results from `match (n) where n.id starts with "MESH:" return n.id, n.category limit 50;`


n.id | n.category
-- | --
"MESH:C000622574" | "biolink:ChemicalSubstance"
"MESH:C575594" | "biolink:ChemicalSubstance"
"MESH:C575595" | "biolink:ChemicalSubstance"
"MESH:C575596" | "biolink:Protein"
"MESH:C575597" | "biolink:ChemicalSubstance"
"MESH:C575598" | "biolink:ChemicalSubstance"
"MESH:C115373" | "biolink:MolecularEntity"
"MESH:C575599" | "biolink:ChemicalSubstance"


Going to go ahead and close this now.

**Comment by saramsey** [comment]
looking good in KG2.5.1 as well:

![Uploading Screen Shot 2021-02-02 at 2.35.15 PM.png…]()
