### ISSUE TITLE
Re-generate training data for drug-treats-disease model

### ISSUE THREAD

**Issue by dkoslicki** [RTXteam/RTX#994]
SemMedDB is where we get a lot of our training data. We should re-generate the training data given we have updated SemMedDB.

**Comment by finnagin** [comment]
@chunyuma I've generated the new semmeddb data for you and you can download it [here.](https://github.com/RTXteam/RTX/files/5035656/new_semmed_data.zip)

**Comment by chunyuma** [comment]
Thanks @finnagin

**Comment by dkoslicki** [comment]
Thanks @finnagin! Does the NDF and mychem training data need to be updated as well? I just want to be sure all the training data is as up-to-date as possible.

NDF probably hasn't changed much, but mychem may have added more "treats/indicated_for/contraindicated_for/etc"...
Perhaps @finnagin sharing those scripts with @chunyuma (and/or putting them in the RTX repo) will help so we can periodically update the training data

**Comment by chunyuma** [comment]
Hi @finnagin, if you don't mind, I might also need your help to update the NDF and mychem training data. Although perhaps the NDF and mychem training data don't have too many update, the "old" data is based on the "old" KG2 so it can't match to the canonicalized one. So do you mind helping me update those two datasets as well? Thank you!

**Comment by finnagin** [comment]
@chunyuma sure! I can help with that. I'll have to rewrite some of the code to handle the new curies but it looks like NDF can be downloaded in [csv format now](https://bioportal.bioontology.org/ontologies/NDF-RT) so that will make that part easier.

**Comment by chunyuma** [comment]
Thanks @finnagin!

**Comment by finnagin** [comment]
Hey @chunyuma , I've regenerated the mychem data. you can download it [here.](https://www.dropbox.com/s/f7ve37gs4mibgpu/new_mychem_data.zip?dl=0) I know I also mentioned the NDF data but upon further inspection it has not been updated since 2012 so there will be no difference. It's possible there is a more updated version elsewhere but I don't know where or how to access it.

**Comment by chunyuma** [comment]
Thanks @finnagin

**Comment by dkoslicki** [comment]
@chunyuma I agree: fantastic results (and thanks for your attention to detail on this and continuing to push the pace on this!), but they look a bit _too_ good... Another thing that can be done to test the over-fitting is:

1.  See if the edges that you removed for GraphSage (like `indicated_for` and `contraindicated_for`) are assigned appropriate values by the model when given the source and target nodes (unless you used these node pairs for the training step too).
2. Try doing an “all/most” pairs prediction (I.e. just like with the random pairs in the first figure of [your post](https://github.com/RTXteam/RTX/issues/994#issuecomment-678438924), but with an even larger sample. Then look to see if only the training data is getting a “high probability treats” (I.e. the model isn’t actually generating any new predictions, just recapitulating the training data). This could also be accomplished by taking a small set of drugs and running them against _all_ diseases (might be faster and more to-the-point that just a bunch of random pairs)

**Comment by dkoslicki** [comment]
Also, something fishy is up with the [ROC curve](https://user-images.githubusercontent.com/20031672/90923612-fcecfa80-e3bb-11ea-83b2-d5c31fd39983.png), since the mean AUC doesn’t match up with the individual folds

**Comment by chunyuma** [comment]
@finnagin, I used the 'old' training data and made sure that all `source` nodes are assigned with the type `chemical_substance` or `drug` and all `target` nodes are assigned with `disease` or `phenotypic_feature` in canonicalized kg2.

The results look like normal.

![Figure3](https://user-images.githubusercontent.com/20031672/90995005-92d58080-e588-11ea-82d5-2d90fb08a626.png)

![Figure1](https://user-images.githubusercontent.com/20031672/90995010-979a3480-e588-11ea-9980-4423bb43fc50.png)

So I suspected the problems might come from the the 'new' data. Another thing that makes me feel worried about the data is that I found the `positive` and `negative` relationship from the `new` data makes conflict with the 'positive' and 'negative' relationship in canonicalized kg2.

Here is a few examples:
`source`: CHEBI:100147 (chemical_substance)
`target`: MONDO:0001127 (disease)

Their relationship is `contraindicated_for` in canonicalized kg2. So they should be `negative` relationship. However, they exist in `mychem_tp.txt`.

`source`: CHEBI:68352 (chemical_substance)
`target`: MONDO:0011122 (disease) 

Their relationship is `affects` and `treats` in canonicalized kg2. So they should be `positive` relationship. However, they exist in `mychem_tn.txt`.

> Also, something fishy is up with the ROC curve, since the mean AUC doesn’t match up with the individual folds
 
@dkoslicki, it is normal because the way we used in `LogReg.py` to calculate the mean AUC and the individual folds are different.  For the individual folds, the script used `roc_auc = met.auc(fpr, tpr)` to calculate the AUC score. However, the mean AUC used linear interpolation by `tprs.append(sci.interp(mean_fpr, fpr, tpr)); mean_tpr = np.mean(tprs, axis=0); mean_auc = met.auc(mean_fpr, mean_tpr)` although I don't understand why we need to calculate like this way.

**Comment by chunyuma** [comment]
@finnagin, for relationship-conflict problem, it seems like the 'old' training data also has this problem. So this might not be the reason leading to this suspected 'over-fitting'. But it is good to know that we can't be 100% sure that the relationship between drug and disease in the training data or kg2 is correct.

For some drug-disease pairs, they might have both 'positive' (e.g. `treats`, `disrupts`, `prevents`) and 'negative' (e.g. `contraindicated_for` and `contraindicated_with `)relationship.  For example<

![Screen Shot 2020-08-25 at 4 49 26 PM](https://user-images.githubusercontent.com/20031672/91226547-30e55a00-e6f3-11ea-9857-f015cced82b3.png)

For the overfitting problem, since we used 10-fold cross-validation, the evaluation result of each fold might be able to identify the `over-fitting`. But it seems like the 10-fold cross-validation is not bad, I'm wondering what reason might cause a good 10-fold cross-validation result but the model still has over-fitting problem based on your experience @dkoslicki and @finnagin.

**Comment by dkoslicki** [comment]
@chunyuma That’s what’s making me curious too: you would think the 10-fold cross validation would catch over-fitting. Did you test item 2. from [this post](https://github.com/RTXteam/RTX/issues/994#issuecomment-678812113). Perhaps we can get @saramsey’s and others’ input on this at the AHM (I’ll put it on the schedule).

**Comment by chunyuma** [comment]
Hi @finnagin, I found there are around 1529 drug-disease pairs in the 'new' training data that have both `treat` and `not treat` relationship. In the previous script, I saw we included them as negative training data. But I think we should exclude them, right?

Here are some examples:

1. `CHEBI:57826` and `OMIM:MTHU000443`
In semmed_tp.csv: 66,CHEBI:57826,OMIM:MTHU000443
In semmed_tn.csv: 2,CHEBI:57826,OMIM:MTHU000443

2. 'CHEBI:50667' and 'MONDO:0009960'
In semmed_tp.csv: 138,CHEBI:50667,MONDO:0009960
In semmed_tn.csv: 3,CHEBI:50667,MONDO:0009960

**Comment by chunyuma** [comment]
After discussing with @finnagin, I mark down a few idea here which might help overcome the suspiciously good results for future checking.

1. Remove **all** direction connections between drug/chemical_substance and disease/phenotypic_feature because these connections might reveal certain "indicate_for" or "contraindicate_for" relationship although this action might cause some information loss.

2. Exclude **all** pairs appeared in both `tp` training data and `tn` training data like [this](https://github.com/RTXteam/RTX/issues/994#issuecomment-681177292).

3. Consider the drug class which might reveal the `similar` drug structure information and avoid leaking this information between the folds

**Comment by chunyuma** [comment]
Perhaps we might also need to exclude the edges with the nodes in two side which don't have `preferred_type` belonging to `drug`, `chemical_substance`, `disease ` and `phenotypic_feature` but they are synonyms of these four types.

**Comment by chunyuma** [comment]
@dkoslicki and @finnagin, I might need your suggestion about excluding the edges of which either or both end nodes are not `drug`, `chemical_substance`, `disease` and `phenotypic_feature` based on the preferred_type but they are the synonyms of these four types which means that they have synonyms belong to these four types. Do we need to consider the synonyms of these nodes belong to one of `drug`, `chemical_substance`, `disease` and `phenotypic_feature`? If we need to consider synonyms, how can we define the `type` of these nodes in GraphSage?

The problem seems to be more complicates than I think.

**Comment by dkoslicki** [comment]
Hmmm.. @chunyuma I don’t think I quite understand: are you saying that when training GraphSage, you would exclude _all_ edges between pairs of nodes where either node is a synonym of `drug`, `disease`, etc.? Do you have an example of where the preferred_type is not, say, `drug` but is a synonym of `drug`? It seems to make more sense to exclude the edges when _both_ nodes are either `drug`, `disease`, etc. or synonyms thereof.

I assume gathering all the synonyms of the node types under consideration (`drug`, `disease`, etc.) would be useful here. Is the generation of such a list of synonyms what you had a question about?

**Comment by chunyuma** [comment]
@dkoslicki, Let me explain what I concerned in more detail. 

In canonicalized kg2, for each node, it has the following properties:
`id`, `name`, `preferred_type` and `types`

In the last training, I excluded edges with meaning of `indicate_for` or `contraindicate_for` between the nodes of which the `preferred_type` are either `drug`, `chemical_substance` or `disease`, `phenotypic_feature`.

After discussing with @finnagin, we decided to exclude __all__ connections between drug-disease node pairs. 

However, based on my further investigation, there are some edges connecting to two nodes which don't belong to `drug`, `chemical_substance` or `disease`, `phenotypic_feature` according to `preferred_type` but their `types` property include `drug`, `chemical_substance`, `disease` or `phenotypic_feature`. For example, 

n.id | n.preferred_type | n.types | r.simplified_edge_label | m.id | m.preferred_type
-- | -- | -- | -- | -- | --
"UBERON:0001017" | "anatomical_entity" | ["procedure", "named_thing", "anatomical_entity", "phenotypic_feature"] | "category" | "DRUGBANK:DB09425" | "drug"
"CHEMBL.COMPOUND:CHEMBL191" | "chemical_substance" | ["named_thing", "procedure", "drug", "chemical_substance", "genomic_entity", "gene", "protein", "disease", "phenotypic_feature", "molecular_entity", "metabolite"] | "physically_interacts_with" | "DRUGBANK:DB07402" | "drug"
"UBERON:0002107" | "anatomical_entity" | ["gross_anatomical_structure", "anatomical_entity", "procedure", "named_thing", "phenotypic_feature"] | "located_in" | "DRUGBANK:DB09139" | "drug"
"UMLS:C0175895" | "information_content_entity" | ["information_content_entity", "attribute", "phenotypic_feature"] | "treats" | "DRUGBANK:DB09139" | "drug"
"UMLS:C0451615" | "activity_and_behavior" | ["activity_and_behavior", "named_thing", "phenotypic_feature", "clinical_intervention"] | "has_input" | "DRUGBANK:DB05273" | "drug"
"UMLS:C0162788" | "activity_and_behavior" | ["activity_and_behavior", "gross_anatomical_structure", "anatomical_entity", "information_content_entity", "phenomenon", "individual_organism", "publication", "named_thing", "phenotypic_feature", "disease", "procedure", "provider", "chemical_substance", "disease_or_phenotypic_feature", "genomic_entity", "physiological_process", "occurrent"] | "has_input" | "DRUGBANK:DB05273" | "drug"
"CHEBI:27594" | "chemical_substance" | ["named_thing", "drug", "chemical_substance", "procedure", "disease_or_phenotypic_feature", "phenotypic_feature", "phenomenon", "information_content_entity", "attribute", "metabolite"] | "interacts_with" | "DRUGBANK:DB01574" | "drug"
"CHEBI:27594" | "chemical_substance" | ["named_thing", "drug", "chemical_substance", "procedure", "disease_or_phenotypic_feature", "phenotypic_feature", "phenomenon", "information_content_entity", "attribute", "metabolite"] | "related_to" | "DRUGBANK:DB01574" | "drug"
NCBITaxon:9821" | "organism_taxon" | ["chemical_substance", "procedure", "individual_organism", "named_thing", "organism_taxon"] | "treats" | "UniProtKB:P61278" | "protein" | ["named_thing", "procedure", "drug", "chemical_substance", "anatomical_entity", "genomic_entity", "gene", "protein", "phenotypic_feature", "molecular_entity", "metabolite"]
"NCBITaxon:210" | "organism_taxon" | ["activity_and_behavior", "procedure", "individual_organism", "named_thing", "organism_taxon", "drug"] | "treats" | "UniProtKB:P61278" | "protein" | ["named_thing", "procedure", "drug", "chemical_substance", "anatomical_entity", "genomic_entity", "gene", "protein", "phenotypic_feature", "molecular_entity", "metabolite"]

As you might see, some of these edges still have the meaning of `indicate_for` or `contraindicate_for`. I think it has high probability that this is the main reason leading to that suspiciously good result.

Do they belong to `synonyms`? Do we need to consider these `synonyms`?  Do we treat them as its `preferred_type` or as `types` property including `drug`, `chemical_substance`, `disease` or `phenotypic_feature`. 

Based on the feedback from @edeutsch, the general rule to define `preferred_type` is that it uses the types from the SRI Node Normalizer if possible, and then the KG2 type of the preferred node/curie. So we don't be sure what is the `real` type of these nodes. 

I think we have two choices for these cases:
1. We treats them as the synonyms of `drug` and `disease` although their `preferred_type` are not and remove __all__ edges connecting to these kinds of `drug-disease` pairs. But this might bring in another problem: how should we define their labels in GraphSage training? Do we use their original `preferred_type` which is not  `drug`, `chemical_substance`, `disease` or `phenotypic_feature`? Or we define them as one of these four types? If we choose the latter one, how should we treat some nodes that are both `drug` and `disease` like the following case,

n.id | n.preferred_type | n.types | r.simplified_edge_label | m.id | m.preferred_type
-- | -- | -- | -- | -- | --
"CHEMBL.COMPOUND:CHEMBL191" | "chemical_substance" | ["named_thing", "procedure", "drug", "chemical_substance", "genomic_entity", "gene", "protein", "disease", "phenotypic_feature", "molecular_entity", "metabolite"] | "physically_interacts_with" | "DRUGBANK:DB07402" | "drug"

2. We treats them as what their `preferred_type` are. But this might have risk that the model knows the relationship between `drug` and `disease` which causes that suspiciously good result.

**Comment by dkoslicki** [comment]
Ah, I see now @chunyuma (thank you for the detailed explanation, examples, and “copy-able” tables!).
From how I see it, there are a couple of things going on here:
1. There’s definitely still some work to be done on KG2C. Your example “CHEMBL.COMPOUND:CHEMBL191” is an absolute mess with all the `n.types` in it. Indeed, this node corresponds to Losartan (and antihypertensive drug), so should **not** have `n.types` that include things like “gene”, “protein”, “disease”, etc. Maybe @amykglen can help shed some light on why this node has so many types.
    1.b) In general, I don’t think it should ever (biologically) be the case that a node has `n.types` that include both (drug or chemical_substance) and (disease or phenotypic_feature). So enumerating the occurrences of such nodes would help @amykglen refine KG2C even further. 

As for you suggested choices, I like your option 1: basically override the `preferred_type` if one of the types of interest is in the `n.types` list (eg. `drug`, `disease`), as this is the “conservative” option. You could then overwrite the preferred_type in the GraphSage training to use this label instead of the original `preferred_type`. The issue you pointed out in the last question for your case 1 would be avoided if 1.b) is addressed.

But @amykglen and @edeutsch can comment about if this sounds reasonable (I.e. how much should we “trust” the `preferred_type` over `types`, and does it make sense to take your approach 1)

**Comment by amykglen** [comment]
approach 1) (looking at the `types` field to determine whether something is a chemical_substance/drug or disease/phenotypic_feature) sounds reasonable to me.

@edeutsch  is the expert on `preferred_type`s, but out of curiosity I ran a little query looking at nodes that do _not_ have a `preferred_type` of chemical_substance or drug but that _do_ have chemical_substance in their `types` - it looks like there are about 100,000 such nodes, and most of them have a `preferred_type` of metabolite. which I suppose is fair enough given that metabolite is a child of chemical_substance in the Biolink model.

```
match (n) where "chemical_substance" in n.types and n.preferred_type <> "drug" and n.preferred_type <> "chemical_substance" return n.preferred_type, count(distinct n) order by count(distinct n) desc
```

n.preferred_type | count(distinct n)
-- | --
"metabolite" | 69553
"named_thing" | 36015
"protein" | 720
"gross_anatomical_structure" | 538
"organism_taxon" | 528
"genomic_entity" | 349
"individual_organism" | 227
"procedure" | 123
"information_content_entity" | 119
"anatomical_entity" | 92
"disease" | 34
"activity_and_behavior" | 27
"phenotypic_feature" | 25
"device" | 24
"disease_or_phenotypic_feature" | 18
"publication" | 16
"ontology_class" | 13
"phenomenon" | 12
"occurrent" | 10
"cellular_component" | 10
"gene" | 10
"attribute" | 9
"functional_association" | 3
"abstract_entity" | 2
"material_sample" | 2
"molecular_entity" | 2
"molecular_activity" | 1
"physiological_process" | 1
"gene_family" | 1
"physical_entity" | 1
"gene_product" | 1
"relationship_type" | 1
"cell" | 1

not sure how that might influence your decision to use `preferred_type` or `types`, but just relaying the info..

as for the crazy example of CHEMBL.COMPOUND:CHEMBL191, I'll write that up in a separate issue. I agree it doesn't make much sense that a node should have both (drug or chemical_substance) and (disease or phenotypic_feature) in their `types`. it looks like there are 579 such nodes in kg2canonicalized.

**Comment by chunyuma** [comment]
Thanks for your investigation @amykglen. I think our question is how reliable we reassign chemical_substance/drug or disease/phenotypic_feature to these nodes when their `preferred_type` are not chemical_substance/drug or disease/phenotypic_feature but `types` field has these keywords. 

Actually, we don't need to reassign all of these cases because it doesn't matter if one node of an edge is like these cases but another node is not chemical_substance/drug or disease/phenotypic_feature in both `preferred_type` or `types` fields. For example, it is fine for the edge (n:chemical_substance)-[]-(m:chemical_substance), (n:disease)-[]-(m:disease) or (n:disease)-[]-(m:gene_family). For the nodes in these cases, we can keep their original `preferred_type`.

**Comment by amykglen** [comment]
yeah, that makes sense. so for the nodes for which you need to consider `types`, the analysis above would suggest that at least for the chemical_substance instance, it appears it'd be fairly reliable? (since if a node has a `preferred_type` of metabolite, it seems correct that it might have chemical_substance in its `types`, and thus could be considered a chemical_substance.) but it's hard to comment broadly on how reliable this would be.

this information (`preferred_type` and `types`) is pulled directly from `NodeSynonymizer.get_canonical_curies()`, so perhaps @edeutsch has some comments?

**Comment by edeutsch** [comment]
Sorry for the long silence, folks. Trying to do a bit of vacation.
In general, I would say that the preferred_type is not (yet) very robust. It should generally be the SRI Node Normalizer type if possible, but what to do if there are multiple cliques merged? Unclear.
In general, if you have examples where you think the answer should be different, let me know and we can start to develop some better rules.

**Comment by chunyuma** [comment]
Thanks @edeutsch. OK, it seems like this uncertainty will be always a problem that might bring the bias into the model.

@dkoslicki, do we pause re-training the drug-treats-disease model until we have a good way to solve this uncertainty? Another strategy is to remove __all__ edges of node pairs which are the synonyms of `drug/chemical_substance` or `disease/phenotypic_feature` in either `preferred_type` field or `types` field, and also reassign drug/chemical_substance` or `disease/phenotypic_feature` to these nodes after the issue #1044 is solved.

**Comment by dkoslicki** [comment]
@chunyuma I think your "Another strategy" is a good approach (this is the more conservative approach I had in mind). So I would say, go for that approach

**Comment by chunyuma** [comment]
Update: After excluding the following nodes and edges in the current kg2canonicalized (rebuilt off of the KG2-1-0 @amykglen correct me if I'm wrong) ([Here](https://github.com/RTXteam/RTX/blob/issue994/code/ARAX/ARAXQuery/Overlay/GraphSage_train/py_scripts/pull_canonicalized_KG2.py) is the DSL),

1. the nodes which are both 'drug' and 'disease' (196 nodes)
2. the nodes with type including 'drug' and 'disease' != preferred_type (209,271 nodes)
3. all edges directly connecting 'drug' and 'disease' (around 1,000,000 edges)

I retrained the RF model with considering the drug class (using `QueryMyChem` class) and split the 10-fold cross-validation by group which means that the same drug class will not appear in two different folds ([Here](https://github.com/RTXteam/RTX/blob/issue994/code/ARAX/ARAXQuery/Overlay/GraphSage_train/py_scripts/LogReg_edited.py) is the training script). 

So the final graph used for retraining the model is:

`Number of edges`: 35,504,538
`Number of nodes`: 2,485,322 (70% was used for GraphSage training and 30% for testing)
`Number of drugs in the graph`: 326,992
`Number of diseases in the graph`: 153,857

However, the result is still 'pretty good'.

![Figure1](https://user-images.githubusercontent.com/20031672/92762327-78f5b500-f360-11ea-80c3-237d2112889b.png)

`Number of true positive pairs`: 443,026
`Number of true negative pairs`: 1,508,615
`Number of random pairs`: 100,000

![Figure3](https://user-images.githubusercontent.com/20031672/92762682-d38f1100-f360-11ea-9979-5fbd9954be7b.png)

**Comment by dkoslicki** [comment]
Curious, I thought that would fix the overfitting part...
To confirm that it’s overfitting (or not), do you mind doing the following:

1. Select a subset of diseases
2. Iterate through all drugs
3. Enumerate those drugs that have a prediction probability with your subset of diseases that is above ~0.5
4. Report the number of drugs in 3 that are _not_ part of the training data

This will help us determine if we are overfitting still or not

**Comment by chunyuma** [comment]
>To confirm that it’s overfitting (or not), do you mind doing the following:
>1. Select a subset of diseases
>2. Iterate through all drugs
>3. Enumerate those drugs that have a prediction probability with your subset of diseases that is above ~0.5
>4. Report the number of drugs in 3 that are not part of the training data

@dkoslicki, here is what I did. I randomly selected 100 drugs and calculated the treat probability between them and all other drugs. So there are total 15,385,600 drug-disease pairs, of which 35,711 pairs has prediction probability above 0.5 and none of them are in the training data.

**Comment by dkoslicki** [comment]
Thanks @chunyuma ! A 0.2% positive prediction rate definitely indicates overfitting then (but encouraging that it wasn't even smaller).

This is probably due to the inflation of the TN class like we discussed, so let's continue working with @finnagin to get the training data generation script to investigate why the class bias flipped.

**Comment by chunyuma** [comment]
Update: After re-generating the training data, we now have the new "raw" (i.e. we haven't filtered the data based on the "count" of `semmed` data and we haven't combined the duplicate pairs from different data source) training data showed in below table. 

data | TP class | TN class
-- | -- | --
Mychem | 882 | 3,241
Mychem with UMLS | 258 | 514
Semmedb | 34,6642 | 23,208
NDF | 7,620 | 8,400

I tried two sets of cutoffs for the `count` of true positive data and true negative data in `semmed` data. 

#### First Case
I used 12 for true positive data and 2 for true negative data (which means that at least 12 publications support true positive and 2 publications support true negative). So finally, we have 18,095 numbers of true positive pairs and 11,762 numbers of true negative pairs for training data. The results are showed as follows:

![Figure3](https://user-images.githubusercontent.com/20031672/94372650-710e7280-00cd-11eb-88a9-06ab3fc58d64.png)

![Figure1](https://user-images.githubusercontent.com/20031672/94372655-75d32680-00cd-11eb-881c-fbb025141d26.png)

The model size is 662M. 

#### Second Case
I used 8 for true positive data and 2 for true negative data. Finally, we have 25,889 numbers of true positive pairs and 11,388 numbers of true negative pairs for training data. The results are showed as follows:

![Figure3](https://user-images.githubusercontent.com/20031672/94372625-42909780-00cd-11eb-88e8-06b0f5d108b9.png)

![Figure1](https://user-images.githubusercontent.com/20031672/94372627-44f2f180-00cd-11eb-8110-772faecea0c6.png)

The model size is 715M.

Here we can solve the suspicious "overfitting" problem in the previous results by using the new training data. Also, we can see that using the less stringent cutoff can lead to more training data and higher AUC and F1 score. But there is a trade-off here. Using the less stringent cutoff might also include more false positive training data and increase the size of model which might cause the problem in #1059.

**Comment by dkoslicki** [comment]
Thanks @chunyuma! As a gentle reminder, be sure to reference the issue in any commits you make so we all can know what precipitated the issue being closed

**Comment by chunyuma** [comment]
For supplement: I re-trained the model based on KG2.3.4C(kg2canonicalized2.rtx.ai) because I didn't consider one type of "disease" in the last model which is `disease_or_phenotypic_feature`. In this new model, the nodes with `drug` or `chemical_substance` preferred type are considered as 'drug' while the nodes with `disease`, `phenotypic_feature` or `disease_or_phenotypic_feature` are considered as 'disease'. 

So in the new model, we have 278,687 'disease' nodes and 506,158 'drug' nodes. And I used 8 for true positive data and 2 for true negative data. Finally, we have 26,346 numbers of true positive pairs and 115,52 numbers of true negative pairs for training data. The results are showed as follows:

![Figure3](https://user-images.githubusercontent.com/20031672/95615797-cf751280-0a36-11eb-9b65-973a51a65fd2.png)

![Figure1](https://user-images.githubusercontent.com/20031672/95615804-d1d76c80-0a36-11eb-8005-4d027110d8d8.png)

The model size is 715MB.

I have already updated all model files in `/data/orangeboard/databases/KG2.3.4` for #990

**Comment by chunyuma** [comment]
I've already generated a database named `DTD_probability_database_v1.0.db` for DTD model which stores all drug-treats-disease pairs with probability>0.8. I've also uploaded this database to `arax.ncats.io`:/data/orangeboard/databases/KG2.3.4. @finnagin, if you're making a script for automatically detecting any update of databases and downloading them, could you please help include this database as well? Thank you!

I've also updated the script `predict_drug_treats_diease.py` which is now directly querying `DTD_probability_database_v1.0.db` to get probability instead of calling the DTD model to calculate the probability whenever `predict_drug_treats_disease` is called in `overlay` module. And it passed all the test cases calling `predict_drug_treats_disease` in `test_ARAX_overlay.py` and `test_ARAX_workflows.py`. Calling `predict_drug_treats_disease` in `overlay` is now much faster than before and also doesn't need to cost any memory which should solve the issue mentioned #1059.

**Comment by finnagin** [comment]
@chunyuma Sure! I'll add it to the configv2.json file.
